### ISSUE TITLE
name 'Subset' is not defined

### ISSUE THREAD

**Issue by TM1si** [cubewise-code/tm1py#1003]
I just encountered the TM1PY project. Looks great to me. But I'm just started to TM1 and I have no glue of Python. But I will work on it. :-) 
I managed to install TM1PY and get a connect with the check.py. But every try to do the next step failed.
There is no "Find unused dimensions" anymore, so I skipped to the next theme.
To create a Subset I always get a "name 'Subset' is not defined". But there is no import for other modules. So do you have an idea?
I use te working check.py code and added the code

```
        dimension_name = "}Clients"
        expr = "{TM1SubsetAll([}Clients])}"

        print('Create Subset object: ')
        subset = Subset(
            subset_name="All Clients",
            dimension_name="}Clients",
            hierarchy_name="}Clients",
            expression=expr)
```
        

Best regards
Dirk

**Comment by rkvinoth** [comment]
Hello Dirk,

Thank you for expressing interest in the TM1py project. It's truly captivating with its diverse capabilities. I suggest taking some time to familiarize yourself with the basics of Python before delving into it. Even with support from myself or others, you may end up working with code that feels unfamiliar.

Take a week or two to learn Python, and then return to explore TM1py.

**Comment by MariusWirtz** [comment]
I agree with @rkvinoth. You might want to get more familiar with Python itself first.

Regarding the above problem. This should do the trick:

``` python
from TM1py import TM1Service, Subset

with TM1Service(
        base_url="https://compamy.planning-analytics.ibmcloud.com/tm1/api/tm1",
        user="company01_tm1_automation",
        namespace="LDAP",
        async_requests_mode=True,
        password="YI1b1FrxLTR979") as tm1:

    dimension_name = "}Clients"
    expr = "{TM1SubsetAll([}Clients])}"

    subset = Subset(
        subset_name="All Clients",
        dimension_name="}Clients",
        hierarchy_name="}Clients",
        expression=expr)

    tm1.subsets.create(subset=subset, private=False)

```

**Comment by TM1si** [comment]
Thanks for the hints. I'm developing since the old days of C, so if I have some example code I can examine I will soon be able to change it a little bit the way I need.

And thanks to @MariusWirtz it was just the row

`from TM1py import TM1Service, Subset`

I needed. Thanks a lot. Now I can continue learning and examinig TM1py.
