### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by bakerde-2024** [cubewise-code/tm1py#1007]
**Describe what did you try to do with TM1py**
ran python check.py 

**Describe what's not working the way you expect**
Expected questions for TM1 server information and got the following error
ModuleNotFoundError: No module named 'distutils'

**Version**
- TM1py 
- TM1 Server Version: [e.g. 11.4]

**Additional context**
PS C:\TM1py\tm1py-master\TM1py\tm1py-samples-master> python check.py
Traceback (most recent call last):
  File "C:\TM1py\tm1py-master\TM1py\tm1py-samples-master\check.py", line 6, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
PS C:\TM1py\tm1py-master\TM1py\tm1py-samples-master>

**Comment by 0xWebMilk** [comment]
try: `sudo apt-get install python3-distutils`

**Comment by bakerde-2024** [comment]
In a command prompt or Python? New to the TM1py app and python.

**Comment by 0xWebMilk** [comment]
Enter this command in the command line (command prompt)

**Comment by rkvinoth** [comment]
With that question, I'm gonna believe that you are using a Windows OS.

I think you are using a virtual environment which gets created while using an IDE to open the folder as a project.
To avoid this, you can close the IDE and open the folder in it again. But, this time use the native python interpreter and not a virtual environment.

**Comment by bakerde-2024** [comment]
Yes, running on Windows OS. Downloaded and installed python from Microsoft store and ran the PIP to install  TM1py. Opened a command prompt in the samples directory and ran python check.py. I will try reinstalling Python to see if it can fix the error.

**Comment by TM1si** [comment]
Maybe late, but anyway:

There is a missing module: distutils
Many examples rely on Python before V 3.10. With this version module distutils was depriated, but remained in installation libs. In version 3.12 module distutils was removed. Threfore this results in an error

In most cases you only need function strtobool. For this you have the alternative

pip install str2bool

Then replace distutils by strtobool and str2bool.
Like this:

from str2bool import str2bool
from TM1py.Services import TM1Service
# Parameters for connection
ssl = str2bool("F")
