### ISSUE TITLE
executable file pops up error when called via macro

### ISSUE THREAD

**Issue by vino1493** [cubewise-code/tm1py#101]
Hi,

I have an executable file to fetch all the dimensions in a cube. When I call this file via cmd promp like below it works:

`C:\Users\vino> dim.exe Sales` (Sales is the cube's name)

I wanted this executable to be called from an excel file, so I created an Active X button and use the below VBA:

```
Public Sub CommandButton21_Click()
    Dim strProgramName As String
    Dim strArgument As String
    strArgument = "Sales"
    strProgramName = "C:\Users\vino\dim.exe" + " " + strArgument
    Call Shell("cmd.exe /c" & strProgramName, vbNormalFocus)
End Sub
```

When I run this VBA script, it throws the following error:
**Traceback (most recent call last):
	File "dim.py", line 16 in <module>
	File "configparser.py", line 958, in __getitem__
KeyError: 'SIT'
[8700] Failed to execute script dim**

Here line 16 is `with TM1Service(**config['SIT']) as tm1:`, why doesn't the connection happen when executed via VBA. 

Any suggestions would be greatly helpful!

**Comment by MariusWirtz** [comment]
Hi @vino1493 ,

happy to answer questions about TM1py. When you have questions that are not, at the core, related to TM1py I suggest you try [stackoverflow](https://stackoverflow.com/)

Cheers,

Marius

**Comment by vino1493** [comment]
Thought there could be some integration problem, thanks will Google more!
