### ISSUE TITLE
tm1.cubes.views.get_native_view will fail if in the view there is no dimension in the columns

### ISSUE THREAD

**Issue by TM1si** [cubewise-code/tm1py#1022]
get_native_view will fail if there is no dimension in the columns.

Use example code like this:

```
def ShowMDXOfView(tm1, cube, view):
    # Instantiate TM1py.NativeView object
    nv = tm1.cubes.views.get_native_view(cube, view, private=False)

    # Retrieve MDX from native view. Print it
    print("MDX der View " + cube + "/" + view + ":")
    print(nv.MDX)
```
Error message:
ERROR:
	Column selection must not be empty

BUT, this view is already defined in TM1, by the editor.
I use this to get a flat, row by row output of the cube data. The only column is the value.

I expect, that every existing view can be used to get its MDX.

**Comment by wimgielis** [comment]
Hello,

Where did you use the view ? In TM1 Architect/Perspectives/TM1Web ?
MDX views, the new default type of views, need to have at least 1 dimension
in the columns and 1 dimension in the rows.

------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 12 jan 2024 om 09:07 schreef TM1si ***@***.***>:

**Comment by tomasfelcman** [comment]
Hi,
 I suspect it is used in the TI & having only row dims + implicit Value variable as the column...?

**Comment by TM1si** [comment]
In TM1 Architect.

I simply moved all dimension headers in the rows having no title in the columns, but showing a single column with the values. 

If I can't get the view I already definied, how can I write it in MDX explicitly? If I have a long list of measures, I don't want them all in a condition listed.

Image a simple export view of a cube, only using existing values, and if calculated, only if it is not zero. Result should be a table like output with dimensions as fields and an additional "Value" field.

**Comment by wimgielis** [comment]
As said, you would put a dimension in the columns.
If it's a long list of measures, create a subset and use that one.( using
subsets is often a good idea, be it dynamic or static)


------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 12 jan 2024 om 10:52 schreef TM1si ***@***.***>:

**Comment by TM1si** [comment]
OK, if I do, lets assume measure dimension has elements "A, B, C". I create a subset named "sub" with all 3 element names. So how can I get my outut of the cube "MyCube" with five additional dimensions using MDX without adding each element name in a condition to be compared with IsEmpty?

**Comment by wimgielis** [comment]
Are you familiar with the concept of zero suppression ?

------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 12 jan 2024 om 11:04 schreef TM1si ***@***.***>:

**Comment by TM1si** [comment]
In TM1 views, yes, in MDX I don't think so.

**Comment by rclapp** [comment]
MDX only requires a dimension to be columns to work, rows are optional.

From: tomasfelcman ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Friday, January 12, 2024 at 1:05 AM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [cubewise-code/tm1py] tm1.cubes.views.get_native_view will fail if in the view there is no dimension in the columns (Issue #1022)


Hi,
I suspect it is used in the TI & having only row dims + implicit Value variable as the column...?

**Comment by rclapp** [comment]
Your MDX would look something like this

`
SELECT 
NON EMPTY {[Measures].[A], [Measures].[B],[Measures].[B]} on Columns,
NON EMPTY {[Dim1].Members} * {[Dim2].Members} on Rows
FROM [Cube Name]
WHERE ([Dim3].[Some Element])
`

If you are not comfortable writing MDX by hand, mdxpy is a good library to help.

**Comment by TM1si** [comment]
Yes, I did it that way using Measure Dim as column dimension. Thanks.
