### ISSUE TITLE
URL was not found on server

### ISSUE THREAD

**Issue by richenners** [cubewise-code/tm1py#1034]
I'm new to TM1py (just downloaded it yesterday) and attempting to test connectivity by following the 'get version' example. We use PA on the Cloud (version 2.0.9.18). I am receiving "The requested URL was not found on this server" message (see attached). Here is the url I'm using:   base_url='https://paradiesdev.planning-analytics.ibmcloud.com/tm1/', . I'm also using our non-interactive account and password. I have been successful using the following in Git Bash: curl --location --request GET 'https://paradiesdev.planning-analytics.ibmcloud.com/tm1/api/CPM/api/v1/Dimensions('\''Store%20SAP%20v2'\'')/Hierarchies('\''Store%20SAP%20v2'\'')/Members?select=Name,Ordinal,Weight&$expand=Parent($select=Name),Level($select=Number),Element($select=Name,Type,Attributes)' --header 'Authorization: 
[TM1py Test errors.txt](https://github.com/cubewise-code/tm1py/files/14027383/TM1py.Test.errors.txt)

Any suggestions would be greatly appreciated.

Thanks!

**Comment by MariusWirtz** [comment]
Hi @richenners,

If you initiate TM1Service like in the sample below, it should just work.


``` python
with TM1Service(
        base_url='https://paradiesdev.planning-analytics.ibmcloud.com/tm1/api/CPM/',
        user="non_interactive_user",
        namespace="LDAP",
        password="U3lSn5QLwoQZY2",
        ssl=True,
        verify=True,
        async_requests_mode=True) as tm1:
    print(tm1.server.get_product_version())
```
