### ISSUE TITLE
Clarification needed on Dimension attribute export

### ISSUE THREAD

**Issue by vino1493** [cubewise-code/tm1py#104]
Hi,

Can Only cube module be used for exporting dimension attributes (including their values)?

I checked the dimension module, using this I was only able to fetch the dimension attribute "name" and "attribute type".

Please let me know if I need to elaborate my query.

**Comment by MariusWirtz** [comment]
Hi,

you can not query the element attribute values through the `DimensionService`.
You need to use the `CellService`. Here is a sample:
```

import configparser

from TM1py import TM1Service
from TM1py.Utils.Utils import element_names_from_element_unique_names

config = configparser.ConfigParser()
config.read(r'config.ini')

with TM1Service(**config['tm1srv01']) as tm1:
    mdx = """
    SELECT
    {Tm1SubsetAll([Date])} ON ROWS,
    {Tm1SubsetAll([}ElementAttributes_Date])} ON COLUMNS
    FROM [}ElementAttributes_Date]
    """

    cellset = tm1.cubes.cells.execute_mdx(mdx)

    for coordinates, cell in cellset.items():
        print(*element_names_from_element_unique_names(coordinates), cell["Value"])

```

**Comment by vino1493** [comment]
I'm trying to export the dimension names along with their respective attribute values something like below:

![image](https://user-images.githubusercontent.com/40484319/53517484-bb480000-3af4-11e9-8c16-5d6607e50cca.png)

I used the `DimensionService` with two or more `For` loops and exported the dimension structure like below:

![image](https://user-images.githubusercontent.com/40484319/53517567-f9ddba80-3af4-11e9-8cf7-6ad296580fc2.png)

But how to fetch their corresponding attributes? using the `For` loop you suggested it would only provide me format that would be very difficult to decode (to my python knowledge). Do you have any other suggestion on this?

I sincerely appreciate the support you have provided so far.

> Note: The screenshots were imaginary and used for depicting my expectation

**Comment by MariusWirtz** [comment]
Hi,

you can use the `execute_mdx_dataframe_pivot` method to get the result set from an mdx query in a pivot table. The shape of the pivot table is derived from the MDX query. 


Here is a sample that gives you the elements and the attribute values in an excel like grid:
```

import configparser

from TM1py import TM1Service

config = configparser.ConfigParser()
config.read(r'config.ini')

with TM1Service(**config['tm1srv01']) as tm1:
    mdx = """
    SELECT
    {Tm1SubsetAll([Date])} ON ROWS,
    {Tm1SubsetAll([}ElementAttributes_Date])} ON COLUMNS
    FROM [}ElementAttributes_Date]
    """

    pivot_table = tm1.cubes.cells.execute_mdx_dataframe_pivot(mdx)
    # print into console
    print(pivot_table)
    # save to file
    pivot_table.to_csv("out.csv")

```

I suppose you don't want to manage this information in the same table / file where to manage the parent - child relationships between the elements (contraty to the excel table that you provided) because it does not make sense.

**Comment by vino1493** [comment]
This function provides the correct result (not my expected result). Yes, you are right it doesn't make any sense at all.
I have planned to break up the metadata and attributes files separately.

Thanks for your support!
