### ISSUE TITLE
Getting TM1 Dimensions into PBI

### ISSUE THREAD

**Issue by richenners** [cubewise-code/tm1py#1043]
**Describe what did you try to do with TM1py**
Following the example on the CubeWise website, I have the following code in a py file:
# Run the code:
  version = tm1.power_bi.get_member_properties(
        dimension_name="Version",
        hierarchy_name="Version",
#1        member_selection="{Tm1SubsetAll([Version])}",
        member_selection="{Tm1SubsetToSet([Version],"Act vs WB")}",
        skip_consolidations=False)
#  version
  print(version)

**Describe what's not working the way you expect**
Running this code with line "#1" works.
Running this code with the line under "#1" does not work. It returns "SyntaxError: invalid syntax. Perhaps you forgot a comma?"

**Version**
- TM1py:  3.12.1
- TM1 Server Version: 11.8.02200.2

**Comment by wimgielis** [comment]
Hello,

Please consider using single quotes.

Either:
member_selection='{Tm1SubsetToSet([Version],"Act vs WB")}',

either:
member_selection="{Tm1SubsetToSet([Version],'Act vs WB')}",

------

Best regards / Beste groeten,

Wim Gielis
IBM Champion 2024
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 26 jan 2024 om 19:43 schreef richenners ***@***.***>:

**Comment by richenners** [comment]
Thank you! Both worked. Is it possible to return the consolidated elements and their children?

**Comment by wimgielis** [comment]
Basically, all non-string elements ?

------

Best regards / Beste groeten,

Wim Gielis
IBM Champion 2024
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 26 jan 2024 om 21:37 schreef richenners ***@***.***>:

**Comment by richenners** [comment]
There is a non consolidated element "Working Budget CY" underneath "Current Budget" as an example - see attached snip.
<img width="245" alt="Version Example" src="https://github.com/cubewise-code/tm1py/assets/124631528/242a99da-46aa-4d29-bdb2-e156b19599c0">

Also, I copied a working py script into Power BI but it is unable to connect. Is there a work-around for this?
<img width="235" alt="Version PBI Error" src="https://github.com/cubewise-code/tm1py/assets/124631528/b6818606-dafa-4e9e-87ba-0b1812b79717">

**Comment by wimgielis** [comment]
An MDX like this ?
{[Version].[Act vs. Budget]} + TM1FilterByLevel( Descendants(
{[Version].[Act vs. Budget]} ), 0 )

------

Best regards / Beste groeten,

Wim Gielis
IBM Champion 2024
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 26 jan 2024 om 21:57 schreef richenners ***@***.***>:

**Comment by richenners** [comment]
Yes, that's awesome, thank you very much. I now understand better how this works.

Have you seen the PBI error before?

**Comment by wimgielis** [comment]
No, I haven't used TM1py for the purposes of PBI.
We usually replace PBI with CA.

------

Best regards / Beste groeten,

Wim Gielis
IBM Champion 2024
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 26 jan 2024 om 22:07 schreef richenners ***@***.***>:

**Comment by richenners** [comment]
Got it. Thanks for you help, have a good weekend!
