### ISSUE TITLE
Splitting dimension hierarchy

### ISSUE THREAD

**Issue by vino1493** [cubewise-code/tm1py#105]
Is there a default parameter or function to split the dimension hierarchies (main and alternate hierarchies)?

Would like to export these hierarchies into individual excel or csv files.

**Comment by MariusWirtz** [comment]
The `Dimension `class implements the iterator protocol. That means you can simply loop through it to access all hierarchies. 

```
import configparser

from TM1py import TM1Service

config = configparser.ConfigParser()
config.read(r'config.ini')


with TM1Service(**config['tm1srv01']) as tm1:
    dimension = tm1.dimensions.get('d1')

    for hierarchy in dimension:
        print("Name: {}".format(hierarchy.name))
        print("Number of elements: {}".format(len(hierarchy)))

```

If you explicitly want to access the default-hierarchy / same-named-hierarchy, you can do it like this:
```

import configparser

from TM1py import TM1Service

config = configparser.ConfigParser()
config.read(r'config.ini')

with TM1Service(**config['tm1srv01']) as tm1:
    dimension = tm1.dimensions.get('d1')

    default_hierarchy = dimension.default_hierarchy
    print("Name: {}".format(default_hierarchy.name))
    print("Number of elements: {}".format(len(default_hierarchy)))


```

Does that answer your question?

**Comment by vino1493** [comment]
`hierarchy.name` returns the dimension name itself, it doesn't help.

I'm looking for something that could split the duplicate elements (alternate hierarchy) from dimension and create a new file out of it. If the duplicate element list also has duplicates in it, then go for third file.

I have achieved this using python lists and dictionaries. But is there any inbuilt TM1 py function for this?

If my question is not clear let me know.

**Comment by MariusWirtz** [comment]
`hierarchy.name` returns the name of hierarchy. It just happens to be the name of dimension when you access this property on the default hierarchy.

I am not sure if you understand the concept of alternate hierarchies correctly. Duplicate elements and alternate hierarchies are not the same thing. Please do some more reading on this topics and provide a proper description of the problem at hand at what exactly you need TM1py to do.

**Comment by vino1493** [comment]
I would like to split duplicate elements from the hierarchy. In my case I only have one hierarchy (default hierarchy). I have some duplicate elements in it. 
I looped through the dimension to split the duplicate elements from the hierarchy.

Thanks for the explanation on alternate hierarchies.
