### ISSUE TITLE
After upgrading to 2.0.1, TM1py fails when a URL contains 'api/v1' inside.

### ISSUE THREAD

**Issue by svbtropical** [cubewise-code/tm1py#1056]
**Describe the bug**
TM1py fails to get some data from TM1 (I'm using V11) when the URL contains '/api/v1'.

**To Reproduce**

Establish a connection using TM1Py 2.0.1 to a TM1 instance and retrieve for instance the count of subsets, like this:

```python
	from tm1py import TM1Service
	tm1 = TM1Service(...)
	connection = tm1.connection.GET("/api/v1/Dimensions('Organization')/Hierarchies('Organization')/Subsets('North')/Elements/$count")
```
An error is triggered:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\elias\anaconda3\envs\test-service\lib\site-packages\TM1py\Services\RestService.py", line 500, in GET
    return self.request(
  File "C:\Users\elias\anaconda3\envs\test-service\lib\site-packages\TM1py\Services\RestService.py", line 296, in request
    self.verify_response(response=response)
  File "C:\Users\elias\anaconda3\envs\test-service\lib\site-packages\TM1py\Services\RestService.py", line 888, in verify_response
    raise TM1pyRestException(response.text,
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '{"error":{"code":"278","message":"'api' resource can not be resolved on type 'EntityContainer'."}}' - Status Code: 404 - Reason: 'Not Found' - Headers: {'Content-Length': '106', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}
```

But, after removing the "/api/v1/" part from the URL, like below:

```python
	from tm1py import TM1Service
	tm1 = TM1Service(...)
	connection = tm1.connection.GET("/Dimensions('Organization')/Hierarchies('Organization')/Subsets('North')/Elements/$count")
```
It works! 

**Expected behavior**
TM1py should accept URLs containing '/api/v1' when the TM1 Version accepts them.

**Version**
TM1py 2.0.1
TM1 Server Version: 11.8.01900.10

**Comment by rclapp** [comment]
Is the issue that this worked in prior versions? In v2, this is by design. TM1py figures out the proper URL structure based on the version and environment you are running. The api base url is everything that precedes and includes 'api/v1'.  When using requests directly you only need to specify the entities you want to query.

**Comment by MariusWirtz** [comment]
for backwards compatability we could cut off the leading `/api/v1` of the url in the `_url_and_body` function if it is there.

https://github.com/cubewise-code/tm1py/blob/4785741606330aa4b9a5afc455e01eab8c7a926c/TM1py/Services/RestService.py#L767

**Comment by MariusWirtz** [comment]
@svbtropical please upgrade to branch `issue/1056` with pip and verify if the issue is resolved.

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/issue/1056.zip
```

**Comment by svbtropical** [comment]
Seems to be working fine! 🥳
