### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by gdbanks** [cubewise-code/tm1py#1082]
I am using TM1py 1.11.1, and I am getting the below error message.
Traceback (most recent call last):
  File "D:/Projects/PCC/file_transfer_v2.py", line 139, in copy_to_data_folder
    tm1_inst.file.update_or_create(file, file_content=file_to_transfer.read())
AttributeError: 'TM1Service' object has no attribute 'file'

This is the line of code, which is causing the error

def copy_to_data_folder(file, file_path, target, tm1_inst):
    with open(file_path, "rb") as file_to_transfer:
        tm1_inst.file.update_or_create(file, file_content=file_to_transfer.read())
        logging.info(f"file: {file} has been copied to target instance {target}")

**Comment by MariusWirtz-cubewise** [comment]
I think it should say tm1.files instead of tm1.file

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: gdbanks ***@***.***>
Sent: Thursday, March 28, 2024 5:59:03 PM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cubewise-code/tm1py] Attribute Error (Issue #1082)


CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


I am using TM1py 1.11.1, and I am getting the below error message.
Traceback (most recent call last):
File "D:/Projects/PCC/file_transfer_v2.py", line 139, in copy_to_data_folder
tm1_inst.file.update_or_create(file, file_content=file_to_transfer.read())
AttributeError: 'TM1Service' object has no attribute 'file'

This is the line of code, which is causing the error

def copy_to_data_folder(file, file_path, target, tm1_inst):
with open(file_path, "rb") as file_to_transfer:
tm1_inst.file.update_or_create(file, file_content=file_to_transfer.read())
logging.info(f"file: {file} has been copied to target instance {target}")

**Comment by gdbanks** [comment]
Marius,
I get the same error message when I change it to 'Files'.

Traceback (most recent call last):
  File "D:\Projects\PCC\file_transfer_v2.py", line 158, in <module>
    main()
  File "D:\Projects\PCC\file_transfer_v2.py", line 126, in main
    copy_to_data_folder(file, file_path, target, tar_tm1)
  File "D:\Projects\PCC\file_transfer_v2.py", line 139, in copy_to_data_folder
    tm1_inst.files.update_or_create(file, file_content=file_to_transfer.read())
AttributeError: 'TM1Service' object has no attribute 'files'

Glen Banks
714-255-5447

[cid:fd7e10b8-9c8f-46c7-8f38-35ec55c389a7]
________________________________

**Comment by MariusWirtz-cubewise** [comment]
Please try to upgrade TM1py

pip install TM1py --upgrade

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gdbanks** [comment]
Marius,
I got the following error message when attempting to upgrade TM1py.

C:\Users\GBanks>pip install TM1py --upgrade
Requirement already satisfied: TM1py in d:\python39\lib\site-packages (1.9.1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
Requirement already satisfied: ijson in d:\python39\lib\site-packages (from TM1py) (3.1.4)
Requirement already satisfied: requests in d:\python39\lib\site-packages (from TM1py) (2.28.1)
Requirement already satisfied: pytz in d:\python39\lib\site-packages (from TM1py) (2022.1)
Requirement already satisfied: mdxpy in d:\python39\lib\site-packages (from TM1py) (0.3)
Requirement already satisfied: requests_negotiate_sspi in d:\python39\lib\site-packages (from TM1py) (0.5.2)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\python39\lib\site-packages (from requests->TM1py) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\python39\lib\site-packages (from requests->TM1py) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python39\lib\site-packages (from requests->TM1py) (1.26.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\python39\lib\site-packages (from requests->TM1py) (2022.6.15)
Requirement already satisfied: pypiwin32>=223 in d:\python39\lib\site-packages (from requests_negotiate_sspi->TM1py) (223)
Requirement already satisfied: pywin32>=223 in d:\python39\lib\site-packages (from pypiwin32>=223->requests_negotiate_sspi->TM1py) (304)

Glen Banks
714-255-5447

[cid:66a3e402-a11c-422c-82d3-1d25221fbc88]
________________________________

**Comment by MariusWirtz** [comment]
@gdbanks, were you able to resolve this?

**Comment by gdbanks** [comment]
Marius,
Not yet.  I am working with our IT to resolve the issue with installing the upgrade.

Glen Banks
714-255-5447

[cid:50afaa39-7e49-44e5-965a-5a9a616e84e3]
________________________________

**Comment by gdbanks** [comment]
Marius,
IT has been able to resolve the installation issue.  Also, I do not know why it is looking  at python39 instead of python 311.


C:\Users\GBanks>pip install tm1py --upgrade
Requirement already satisfied: tm1py in d:\python39\lib\site-packages (1.9.1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/tm1py/
Requirement already satisfied: ijson in d:\python39\lib\site-packages (from tm1py) (3.1.4)
Requirement already satisfied: requests in d:\python39\lib\site-packages (from tm1py) (2.28.1)
Requirement already satisfied: pytz in d:\python39\lib\site-packages (from tm1py) (2022.1)
Requirement already satisfied: mdxpy in d:\python39\lib\site-packages (from tm1py) (0.3)
Requirement already satisfied: requests_negotiate_sspi in d:\python39\lib\site-packages (from tm1py) (0.5.2)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\python39\lib\site-packages (from requests->tm1py) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\python39\lib\site-packages (from requests->tm1py) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python39\lib\site-packages (from requests->tm1py) (1.26.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\python39\lib\site-packages (from requests->tm1py) (2022.6.15)
Requirement already satisfied: pypiwin32>=223 in d:\python39\lib\site-packages (from requests_negotiate_sspi->tm1py) (223)
Requirement already satisfied: pywin32>=223 in d:\python39\lib\site-packages (from pypiwin32>=223->requests_negotiate_sspi->tm1py) (304)
Glen Banks
714-255-5447

[cid:ac78e025-9155-41fb-8a03-66f4e1b82da3]
________________________________

**Comment by gdbanks** [comment]
Marius,
I am sorry, I meant to say IT was unable to resolve the issue.  The error message below is what I am seeing now.

How do I install the upgrade without running a pip command?

Glen Banks
714-255-5447

[cid:195c79a2-6af9-4848-bd5b-a462b488baca]
________________________________

**Comment by gdbanks** [comment]
MArius,
I upgraded to tm1py, but I am still seeing the error message below.  I have attached the python script.

D:\Python39\python.exe D:/Projects/PCC/file_transfer_v2.py
Starting File Transfer from Directory...
Connected to the PythonControlCenter instance
Looking for files in ..{('1002',): ['FinancialReporting', 'D:\\Projects\\PCC\\file_transfer\\financialreporting']} directories
 target is FinancialReporting instance
connecting to target instance FinancialReporting
Traceback (most recent call last):
  File "D:\Projects\PCC\file_transfer_v2.py", line 158, in <module>
    main()
  File "D:\Projects\PCC\file_transfer_v2.py", line 126, in main
    copy_to_data_folder(file, file_path, target, tar_tm1)
  File "D:\Projects\PCC\file_transfer_v2.py", line 139, in copy_to_data_folder
    tm1_inst.file.update_or_create(file, file_content=file_to_transfer.read())
AttributeError: 'TM1Service' object has no attribute 'file'

Process finished with exit code 1

Glen Banks
714-255-5447

[cid:601dacae-0316-4fcb-b571-233e97895e0e]
________________________________

**Comment by gdbanks** [comment]
Marius,
The ticket can be closed.  I found out that I was using the wrong Python interpreter, once I changed it from python39 to python311 the code ran without issue.

Glen Banks
714-255-5447

[cid:cf5ecbe2-2450-4f28-9a08-c31e209701ae]
________________________________
