### ISSUE TITLE
Split mdx query dynamically to avoid 'out of memory' error.

### ISSUE THREAD

**Issue by vino1493** [cubewise-code/tm1py#110]
I have created the below `mdx` query dynamically by checking the dimensions in a cube, but getting 'out of memory' error while using `tm1.cubes.cells.execute_mdx`. Is there a way I can dynamically split the query without any hard coding?

hard coding in the sense, I don't want to input any of the dimension members manually.

How to split this mdx dynamically to export the entire cube without getting `out of memory` error?

`SELECT NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim1] )}, 0)} * {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim2] )}, 0)} on ROWS, NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim3] )}, 0)} ON COLUMNS FROM [cube]`

**Comment by MariusWirtz** [comment]
Hi,

instead of creating the cross product of three dimensions in the query, you could pin one dimension.
You could loop through the leaf elements of one dimension and execute one query by element.
Sample:
``` python

import configparser

from TM1py import TM1Service

config = configparser.ConfigParser()
config.read(r'config.ini')

with TM1Service(**config['tm1srv01']) as tm1:
    
    static_dimension = "dim2"
    element_names = tm1.dimensions.hierarchies.elements.get_leaf_element_names(
        dimension_name=static_dimension,
        hierarchy_name=static_dimension)

    for element_name in element_names:
        mdx = """
        SELECT
        NON EMPTY {{ TM1FILTERBYLEVEL( {{ TM1SUBSETALL( [dim1] ) }} , 0) }} * {{ [{static_dimension}].[{element}] }} on ROWS, 
        NON EMPTY {{ TM1FILTERBYLEVEL( {{ TM1SUBSETALL( [dim3] ) }} , 0) }} ON COLUMNS 
        FROM [cube]
        """.format(
            static_dimension=static_dimension, 
            element=element_name)

        data = tm1.cubes.cells.execute_mdx(mdx)
        print(data)
```

**Comment by vino1493** [comment]
Yes that can be done for cubes with less number of dimensions ( 3 or 4).

But what if the source cube has more than 7 dimensions? My `mdx` query would look like this in this scenario:

`SELECT NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim1] )}, 0)} * {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim2] )} * {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim3] )}, 0)} * {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim4] )}, 0)} * {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim5] )}, 0)} * {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim6] )}, 0)} * {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim7] )}, 0)}, 0)} on ROWS, NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL( [dim3] )}, 0)} ON COLUMNS FROM [cube]`

looping through them would be one hell of a task right! is there a way I can loop through every 'n' records from this `mdx` output.

Like export the first '100' rows, then export the second 100 rows and so on!

Apologies if my idea looks stupid.

**Comment by cubewise-tryan** [comment]
Hi @vino1493,

There is no way to do what you are asking as far as I know. You can use the HEAD function on a particular axis but there is no equivalent to SKIP in MDX that would allow you to get the next X number of items.

**Comment by vino1493** [comment]
In that case, what would be the best way export a very big cube data into csv/excel file.

**Comment by cubewise-tryan** [comment]
Hi @vino1493,

A TI process is still the best and most efficient way to export large amounts of data from TM1.

**Comment by vino1493** [comment]
I looped through the dimensions and obtained their leaf elements. Then performed cartesian product over them, such that I get individual combinations. Then passed these combinations one by one to `execute_mdx`
and appended the data frame for every combination.

This process works but, its very slow. It could process only 2000 records in a minute for a cube with 8 dimensions.
Does the count 2000 looks normal to you? or Am I just considering it to be very less.

**Comment by cubewise-tryan** [comment]
Hi @vino1493,

There is an overhead associated with running each query including network latency, MDX parsing, etc. TM1Py is a thin wrapper over the REST API and the problems you are encountered are due to how the REST API works. If you post to the IBM TM1 SDK forum you may be able to get assistance from IBMers that give more details about what the REST API is doing: https://www.ibm.com/developerworks/community/groups/community/TM1SDK
