### ISSUE TITLE
Allow successful transformation of pandas df to spark df in version 2.0 

### ISSUE THREAD

**Issue by ysonali18** [cubewise-code/tm1py#1100]
**Describe the bug**
We are getting typecasting error while transforming pandas df to spark df in version 2.0 whereas in earlier version 1.11.3 it was successfully transforming the dataframes without errors. 

**To Reproduce**
Below is the script, 
![image](https://github.com/cubewise-code/tm1py/assets/166575219/62cfeec5-018f-4754-b67c-4c41361db3f7)

The output with exception error,
![image](https://github.com/cubewise-code/tm1py/assets/166575219/66e822bc-a7fa-4927-8d38-437a953dc2eb)

**Expected behavior**
In Tm1py 1.11.3 doesn't have the typecasting error.
We are expecting it to successfully transform the pandas df to spark df without typecasting error,

![image](https://github.com/cubewise-code/tm1py/assets/166575219/d4a73844-0e3f-41e0-9b5b-89b50b56c59c)

**Version**
TM1py 2.0.2
TM1 Server Version: 11.8.00900.3

**Additional context**

**Comment by rclapp** [comment]
This appears to be an issue with pyspark's support for NumPy's data types. TM1py doesn't make any promises regarding the interoperability of pandas and pyspark as far as I know. However, it seems to be a pretty simple conversion to fix this issue. https://stackoverflow.com/questions/73169054/not-supported-type-class-numpy-float64

**Comment by ysonali18** [comment]
Hi @MariusWirtz,
YearLong, StdAnnualLoad, CreditPointsReq, CourseDuration PT and CourseDuration are the attribute for which it is throwing an infer schema exception. After explicitly excluding this attributes using attribute parameter its successfully transforming the pandas df to spark df.

![image](https://github.com/cubewise-code/tm1py/assets/166575219/d73270ab-e79e-4274-8edf-d8f5e50a8d7a)

Thanks,
Sonali

**Comment by MariusWirtz** [comment]
This issue may be related to the actual data. 

Instead of retrieving all elements, can you please retrieve a couple of elements for which you know the attribute values are consistent and clean?

```
df = tm1.elements.get_elements_dataframe(dimension_name="d1", hierarchy_name="d1", elements=["e001", "e002"])
```

Does it work?

**Comment by MariusWirtz** [comment]
@ysonali18, please execute the below code with 1.11.3 and 2.0.2 and share your findings. 

I would expect to see a difference in types or values between the two runs.

``` python
with TM1Service(**tm1params) as tm1:
    df = tm1.elements.get_elements_dataframe(dimension_name="d1", hierarchy_name="d1", elements=["e001", "e002"])

    print(df.dtypes)
    print(df.isna())
    print(df.to_csv())
```

**Comment by ysonali18** [comment]
@MariusWirtz , as requested please find attached document of code and outputs of 1.11.3 and 2.0 versions.

[1.11.3 and 2.0 Comparison.docx](https://github.com/cubewise-code/tm1py/files/15006819/1.11.3.and.2.0.Comparison.docx)

Thanks,
Sonali

**Comment by MariusWirtz** [comment]
The second table has gaps. please regenerate but make sure that there are no `...` gaps with  `pd.set_option('display.max_colwidth', None)`

It's a bit hard to review in docx. 
Please also confirm that the output from the `to_csv` is actually the same with the exception of the level001 and level000 issue.
