### ISSUE TITLE
Get a Performance Modeler Application

### ISSUE THREAD

**Issue by glaboria** [cubewise-code/tm1py#1109]
Hi! I've been using the TM1py library for over 2 months and I was wondering if it is possible to get an Application created on the IBM Cognos TM1 Performance Modeler.

I created a script to pass multiple objects from one environment to another (develop -> integration), but I wanted to know if it is possible to get an application and pass it to the other environment. I've successfully retrieved an Excel Application with "tm1.applications.get_document", but I don't know if I could retrieve an application with "tm1.applications.get".

If there's a way to do it I would like to know it, please :)

**Version**
- TM1py 2.0.2 
- TM1 Server Version: 11.8.01700.1

**Comment by MariusWirtz** [comment]
Yes. This should just work. You can find examples how to work with applications in the defined tests cases here:

https://github.com/cubewise-code/tm1py/blob/master/Tests/ApplicationService_test.py
