### ISSUE TITLE
Insufficent Right to update the dimension Error using tm1.elements.create( ) in TM1py

### ISSUE THREAD

**Issue by slu18** [cubewise-code/tm1py#1129]
**Describe what did you try to do with TM1py**
tm1.elements.create( )

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. received Insufficient rights to update the dimension
2. A clear and concise description of what you are trying to do: connect to TM1 server from my laptop

**Version**
- TM1py 2.0.3
- TM1 Server Version: window server 2019

**Additional context**
If you encounter an error, please add the error message and the stack trace
I use admin user name and passcode, I am able to add an element to the dimension, when using a user account in a user group which has write access to the cube and dimension, I receive insufficient right to the dimension, run the same python code. User account and pwd have no problem to connect to TM1 instance in the server, only can not write a new element to an ID dimension with 1, 2,3,4,5.

**Comment by MariusWirtz** [comment]
I'm not sure this is a bug.

If user A is not permitted to update dimension D, it would be appropriate for TM1py to raise an error during the attempt.
Isn't that what you expect?
