### ISSUE TITLE
Using tm1.elements.get_elements_dataframe and tm1.hierarchies.update_or_create_hierarchy_from_dataframe together, creates new attribute "type"

### ISSUE THREAD

**Issue by OliverTrupp** [cubewise-code/tm1py#1134]
**Describe the bug**
When deploying a hierarchy with the two methods, we have a new attribute in the destination, which is not in the source called "type".
We use the methods to update different hierarchies in a dimension,  based on a dimension with identical hierarchies. The source dimension contains n-elements, which are missing in the target dimension for importing facts in a cube. 

Source, with new n-elements, and without attribute type. 
![image](https://github.com/user-attachments/assets/af304d65-8e46-4221-ab2f-7c68f6cedfcc)

Target, with new n-elements, and attribute type, with value "Numeric"
![image](https://github.com/user-attachments/assets/0c3e3067-c241-4ecc-b459-2acea96e6f19)

Till now it is not problematic, but if we continuin using the methods for different hierarchies of the same dimension, the method update_or_create_hierarchy_from_dataframe creates the attributes "type_x", "type_y" (My guess is, that they get created because n-Elements share their attribute values of an attribute for different hierarchies. If there are situations, where there would be a situation with varying attribute values for n elements in different hierarchies, the method creates type_x and type_y)

![image](https://github.com/user-attachments/assets/e299a66a-4b25-4cce-8e17-2a7f84ec8de7)

We got pipelines, which make sure our source has the same elements and attributes as our target. So type, type_x and type_y will get created in the source too.

After they got created,  the method  get _elements_dateframe throws an error and only works again, after deleting type_x and type_y :

  File "/opt/airflow2/airflow/dags/dxd_core/operators/dxd_tm1_transfer_dimension_or_subset_operator.py", line 102, in execute
    df = tm1_src.elements.get_elements_dataframe(dimension_name=self.src_dimension_name,
  File "/opt/airflow2/.venv/lib/python3.10/site-packages/TM1py/Utils/Utils.py", line 146, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/airflow2/.venv/lib/python3.10/site-packages/TM1py/Services/ElementService.py", line 427, in get_elements_dataframe
    return pd.merge(df, df_data, on=dimension_name).drop_duplicates()
  File "/opt/airflow2/.venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 183, in merge
    return op.get_result(copy=copy)
  File "/opt/airflow2/.venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 885, in get_result
    result = self._reindex_and_concat(
  File "/opt/airflow2/.venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 837, in _reindex_and_concat
    llabels, rlabels = _items_overlap_with_suffix(
  File "/opt/airflow2/.venv/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 2697, in _items_overlap_with_suffix
    raise MergeError(
pandas.errors.MergeError: Passing 'suffixes' which cause duplicate columns {'Type_y'} is not allowed.

**To Reproduce**
```
df = tm1_src.elements.get_elements_dataframe(dimension_name=src_dimension_name,
                                                         hierarchy_name=src_hierarchy_name,
                                                          elements="{DISTINCT({DESCENDANTS([kostenstelle].[dbd_rahmenkostenstelle].[RKOST_ohne_zuordnung])})}",
                                                         skip_consolidations=True,
                                                         attributes=None,
                                                         attribute_column_prefix="",
                                                         skip_parents=.False,
                                                         level_names=None,
                                                         parent_attribute=None,
                                                         skip_weights=False,
                                                         use_blob=False,
                                                         allow_empty_alias=True)


if not df.empty:
                tm1_dst.hierarchies.update_or_create_hierarchy_from_dataframe(
                    dimension_name=dst_dimension_name,
                    hierarchy_name=dst_hierarchy_name,
                    df=df,
                    element_column=None,
                    verify_unique_elements=False,
                    verify_edges=True,
                    element_type_column="ElementType",
                    unwind=False)
```

**Expected behavior**
I expected the target and source to have the same attributes. Is it maybe possible to set a flag, to decide if the attribut "type" gets created? We have complex workflows for deploying hierarchies, and the new attribute crashes them. 

**Version**
TM1py 2.0.2

**Comment by OliverTrupp** [comment]
Solutions seems to be:            
df = df.rename(columns={"Type": "ElementType"}) 
after using get_elements_dataframe 

the function tm1.hierarchies.update_or_create_hierarchy_from_dataframe is not using type, and expects a column ElementType.
The output of get_elements_dataframe should be ElementType to be usable with update_or_create_hierarchy_from_dataframe

**Comment by MariusWirtz** [comment]
You can specify the name of the `ElementType` column on both functions. It's dynamic and configurable.

We can't change the default values on those arguments in TM1py itself, as this would cause compatibility issues. 

For generic scripts better be explicit and use a column name that is unlikely to clash with real attribute names
