### ISSUE TITLE
optional `update_attribute_types` argument in `update_or_create_hierarchy_from_dataframe` 

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#1139]
By default, TM1py doesn't update attribute types in the `update_or_create_hierarchy_from_dataframe` function.

This is because the attribute would have to be deleted and re-created. 
However we could make this an optional feature of the function

**Comment by Mahimajain25** [comment]
Hi @MariusWirtz ,
When can we use this - update_attribute_types argument. Please let us know.
Thanks,
Mahima Jain

**Comment by MariusWirtz** [comment]
@Mahimajain25 

by default TM1py doesn't update attribute types (e.g. change String Attribute to Alias Attribute).

That is because attribute types can not be changed. They must be deleted and recreated.

If you pass `update_attribute_types=True` TM1py will update an attribute type when it detects a change.

**Comment by Mahimajain25** [comment]
Hi @MariusWirtz ,

Thanks for your reply. 

I understood the functionality. My question is when it is available to use ? 
Currently I have update the library form 2.0.3 to 2.0.4. update_attribute_types argument is not visible.
In which release it will be available for us?

<img width="960" alt="update_or_create_hierarchy_from_dataframe" src="https://github.com/user-attachments/assets/eb251ba4-b71e-4f1e-85ce-84605999dc7a">

Thanks,
Mahima Jain

**Comment by MariusWirtz** [comment]
The feature is currently only available in the master branch on GitHub.

Given all the progress in recent weeks I think we can publish a new release to PyPI soon. I think we can release 2.1 in November.
