### ISSUE TITLE
Issue incorrect DataFrame retrieved from TM1

### ISSUE THREAD

**Issue by MBonotto** [cubewise-code/tm1py#1148]
**Describe the bug**
When retrieving data from TM1, the DataFrame always has the same structure, regardless of the query I use. Specifically, the values (elements) in each column of the DataFrame are always ordered in the same way, which looks like this: 
> **Period, Bedrijf, KostenPlaats, Account, Product, Measure, Scenario**

However, the column names are aligned with the query. For example, if I specify the **Scenario** dimension as the first in the query, the first column in the DataFrame will be named **Scenario**. Yet, the values in this column consistently correspond to the elements of the **Period** dimension, not **Scenario**.
 
This suggests there isn't a correct relationship between the query and the DataFrame's content. The DataFrame structure remains fixed, even though the query changes.
Additionally, I’ve noticed two way in how the query interacts with the DataFrame:
1. **Number of Dimensions**: If the query contains 3 dimensions, the DataFrame will have 3 columns (plus the values column). However, the columns values hold different elements than the ones specified in the query. 

2. **Column** : The names of the columns are determined by the order in which the dimensions are added to the query.

**Code**
`data = tm1.cells.execute_mdx_dataframe(mdx=mdx, skip_zeros=True, use_blob=True)`
![75624a1f-5fd2-4cf7-8576-2d1b9d48191a](https://github.com/user-attachments/assets/928b917f-c0a3-4093-977c-ab71bd9dd74f)

**Example**
![image](https://github.com/user-attachments/assets/5e244e27-e00a-415b-84c9-329f69680b5b)

**Versions**
TM1py 2.0.2
TM1py 1.5.0

**Comment by MariusWirtz** [comment]
Please upgrade TM1 from 11.7 to a more recent version. 
It should be resolved after a TM1 upgrade.

Feel free to re-open if the issue persists.
