### ISSUE TITLE
Potential Bug in "write_dataframe_async" function

### ISSUE THREAD

**Issue by bennybooo22** [cubewise-code/tm1py#1149]
**Describe the bug**
Sadly because of how I was handling errors I did not get the full traceback, I only got the following: "'TM1pyWriteFailureException' object has no attribute 'attempts'"

**To Reproduce**
I wasn't able to reproduce it, but because of the error handling problem, I have a theory.
In CellService.py, `write_dataframe_async` function, lines 970-971, python handles `TM1pyWritePartialFailureException`  and `TM1pyWriteFailureException` in the same way, by adding them to `failures/exceptions`. Then in lines 980-983, a consolidated `TM1pyWritePartialFailureException` is raised, where in line 983, attempts are defined by `attempts=sum([exception.attempts for exception in exceptions]`. This trys to retrieve the attribute `attempts` from `exception`, however in Exceptions.py, `TM1pyWritePartialFailureException` has an attribute `attempts` but `TM1pyWriteFailureException` does not.

So to recreate this issue, I would imagine you would need to use the write_dataframe_async function and have an async executor raise a TM1pyWriteFailureException

**Expected behavior**
Async errors to be consolidated together and raised.

**Version**
TM1py 2.0.4
TM1 Server Version: 11.8.02500.3

**Comment by MariusWirtz** [comment]
I think you are onto something @bennybooo22 

Please confirm that https://github.com/cubewise-code/tm1py/pull/1150 resolves the issue

**Comment by bennybooo22** [comment]
That looks like it will work, Thank you!
