### ISSUE TITLE
TM1py Connection Error to TM1 12 (running in AKS)

### ISSUE THREAD

**Issue by sudarssa** [cubewise-code/tm1py#1154]
**Describe the bug**
Getting unauthorized error on connecting TM1 12 (running in AKS) from TM1py 

**To Reproduce**
Tried below 2 methods to connect

**Method 1:**
from TM1py.Services import TM1Service

with TM1Service(
        address="pa…..net",
        instance="DZK…..N5ZPF",
        database="sampl..ingle",
        application_client_id="4645fc96…..",
        application_client_secret="Lft8………….Tk",
        user="605.....2cd4a0",
        ssl=True) as tm1:

    print(tm1.server.get_product_version())

**Method 2:**
        access_token ="eyJ0eXAiO………………IiNVyAwOHF7A"

headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}
        with TM1Service(
        address="pa…v.net/api/<instancename>/v0/tm1/",
        port="",
        headers=headers,
        ssl=True,
        verify=True) as tm1:

    print(tm1.server.get_product_version())

**Expected behavior**
Getting Unauthorized error

TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '' - Status Code: 401 - Reason: 'Unauthorized' - Headers: {'date': 'Mon, 30 Sep 2024 16:30:40 GMT', 'server': 'istio-envoy', 'content-security-policy': "frame-ancestors 'self'", 'referrer-policy': 'no-referrer', 'strict-transport-security': 'max-age=31536000; includeSubDomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '0', 'www-authenticate': 'Bearer realm="oidc"', 'x-transaction-id':
'0959a691000001490e', 'content-length': '0', 'x-envoy-upstream-service-time': '267'}

**Version**
TM1py 2.0.4
TM1 Server Version: 12.4.1

**Additional context**
Marius advised us to use apikey method, but we are not sure how to get the api key from PA12 running in AKS.

**Comment by MariusWirtz** [comment]
@rclapp 
Are you using this option in your environment? Can you provide any hints on this one?

**Comment by rclapp** [comment]
Let me check. What is AKS

**Comment by wimgielis** [comment]
I guess a typo, AWS maybe ?


------

Best regards / Beste groeten,

Wim Gielis
IBM Champion 2024
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op vr 4 okt 2024 om 00:32 schreef Ryan Clapp ***@***.***>

**Comment by rclapp** [comment]
I think I need some more information to help. @sudarssa where v12 running? Is it one of the SasS offerings or is running in infrastructure that you manage? Is it running in CloudPakForData?

**Comment by sudarssa** [comment]
I am from UBS, due to internal network restriction, I registered from my personal account in Github to raise this case.
TM1 V12 is running in Azure Kubernetes Service (AKS).
If you want to communicate over email, you can send email to my UBS email which Marius aware of it already.

**Comment by rclapp** [comment]
None of our testing was completed using AKS and I am not sure how that works or is installed, sorry.

From: sudarssa ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Friday, October 4, 2024 at 2:34 AM
To: cubewise-code/tm1py ***@***.***>
Cc: "Clapp, Ryan" ***@***.***>, Mention ***@***.***>
Subject: Re: [cubewise-code/tm1py] TM1py Connection Error to TM1 12 (running in AKS) (Issue #1154)


I am from UBS, due to internal network restriction, I registered from my personal account in Github to raise this case.
TM1 V12 is running in Azure Kubernetes Service (AKS).
If you want to communicate over email, you can send email to my UBS email which Marius aware of it already.

**Comment by MariusWirtz** [comment]
I can confirm that there seems to be an issue when using TM1py with TM1 v12 on AKS.

I will look into this

**Comment by rclapp** [comment]
How are you running it on AKS? Is it part of IBM’s cloud offering?

From: sudarssa ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Friday, October 4, 2024 at 2:04 PM
To: cubewise-code/tm1py ***@***.***>
Cc: "Clapp, Ryan" ***@***.***>, Mention ***@***.***>
Subject: Re: [cubewise-code/tm1py] TM1py Connection Error to TM1 12 (running in AKS) (Issue #1154)


Dear Ryan/Marius,
Thanks for the update.
It would be great if you can share your plan for testing TM1PY with AKS and that will really be helpful for us to plan our TM1 12 implementation.

**Comment by MariusWirtz** [comment]
> How are you running it on AKS?

I understand that it's self-hosted in Azure Cloud AKS

**Comment by rclapp** [comment]
Does that mean it is running on CP4D just deployed in Azure?

From: Marius Wirtz ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Wednesday, October 16, 2024 at 10:53 AM
To: cubewise-code/tm1py ***@***.***>
Cc: "Clapp, Ryan" ***@***.***>, Mention ***@***.***>
Subject: Re: [cubewise-code/tm1py] TM1py Connection Error to TM1 12 (running in AKS) (Issue #1154)


How are you running it on AKS?

I understand that it's self-hosted in Azure Cloud AKS
