### ISSUE TITLE
find the number of non zero cells in a cube

### ISSUE THREAD

**Issue by vino1493** [cubewise-code/tm1py#116]
Is there a function to find the number of non zero cells in a cube?

I have used `execute_mdx_cellcount` but is there a better approach? I mean like getting the non zero cell count by just passing the cube name as an argument?

something like: `cellCount = tm1.cubes.cellCount(cube_name)`

**Comment by vino1493** [comment]
We can also obtain the `Number of Populated Numeric Cells` from cube `}StatsByCube`

Please let me know if we have more of a direct approach.

**Comment by MariusWirtz** [comment]
I could not think of a better approach

**Comment by vino1493** [comment]
Thanks for your confirmation as well!
