### ISSUE TITLE
Not able to view element created from update_or_create_hierarchy_from_dataframe function in dimension even after refreshing server.

### ISSUE THREAD

**Issue by Mahimajain25** [cubewise-code/tm1py#1166]
Hi Team,

I'm trying to create a dummy region dimension from Pandas data frame using update_or_create_hierarchy_from_dataframe function. 
issue is -  dimension is created and elements is not visible in architect. But visible in Jupyter notebook.  
Please note using the same user while creating dimension from tm1py and viewing in Architect.

Code: 
1. 
with TM1Service(**config['tm1srv03']) as tm1:
    rest_service = tm1._tm1_rest
    #print(rest_service.version)
    hierarchy_service = HierarchyService(rest_service)
    dimension_name = 'Dummy_Region'
    hierarchy_name = 'RegionHierarchy'

    h1 = hierarchy_service.update_or_create_hierarchy_from_dataframe(dimension_name=dimension_name,hierarchy_name=hierarchy_name,df=df,element_type_column='ElementType',verify_unique_elements=True)
    #Dimension.add_hierarchy(dimension_name,hierarchy_name)

2. 
with TM1Service(**config['tm1srv03']) as tm1:
    a = tm1.hierarchies.exists(dimension_name,hierarchy_name)
    print(a)
    b= tm1.elements.exists(dimension_name,hierarchy_name,'Germany')
    print(b)
    dim_all = tm1.dimensions.get_all_names()
    ele = tm1.elements.get_element_names(dimension_name,hierarchy_name)
    ele1 = tm1.elements.get_element_names(dimension_name,'Dummy_Region')
    att = tm1.elements.get_alias_element_attributes(dimension_name,hierarchy_name)
    print(ele)
    print(att)
    security_service = tm1.security
    element_security = security_service.get_current_user()
    #print(element_security)
    h = tm1.dimensions.hierarchies.get_all_names(dimension_name)
   #tm1.dimensions.hierarchies.delete(dimension_name,'Dummy_Region')
   
    print(h)
    print(ele1)

2. Output :
True
True
['France', 'Belgium', 'Germany', 'Europe', 'World']
['Alias']
['RegionHierarchy', 'Dummy_Region']
['test']

3. Please find screenshot of dataframe and dummy_region dimension attached.
<img width="960" alt="Dummy_Region" src="https://github.com/user-attachments/assets/9d6d2ec7-d96e-4dfe-ba63-b1e5b05d4ff4">
<img width="960" alt="Dataframe" src="https://github.com/user-attachments/assets/a024fc0b-f61a-4409-a5c7-d3e2133bdabc">

**Version**
- TM1py : 2.0.3  
- TM1 Server Version:  11.7.00000.42

**Comment by MariusWirtz** [comment]
You are creating an alternate hierarchy, but the old TM1 front ends (architect/perspectives) can't render alternate hierarchies in the server.

To see the created hierarchy use Arc or PAW
https://code.cubewise.com/software/products/arc/

If you provide the same hierarchy_name as dimension_name you will see your creation in Architect/Perspectives.

**Comment by macsir** [comment]
Yes, agreed. Just about to reply. :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mahimajain25** [comment]
> the same hierarchy_name as dimension_name you will see your creation in Architect/Perspectives.

Thank you @MariusWirtz for your help😊. I really Appreciate it. 👍 I'm able to view Hierarchy in Architect.
