### ISSUE TITLE
Bug: write_dataframe is not case and space insensitive, inconsistent behaviour

### ISSUE THREAD

**Issue by Mr-SabyasachiBose** [cubewise-code/tm1py#1181]
**Describe the bug**
If the dataframe has same element name with different case and space, the `write_dataframe ` is sometime aggregating 
the values, sometime picking one or the other.

**To Reproduce**
Tested on a 2D cube with elements, **Child1** and **Value**. attaching the code in the image. sample data
```

data = {'Sample Dim':['Child1','Child1'],
             'Measure':['Value','Value'],
             'Value':[12,15]
             }

data = {'Sample Dim':['Child1','Child    1'],
             'Measure':['Value','Value'],
             'Value':[12,15]
             }

data = {'Sample Dim':['Child1','child1'],
             'Measure':['Value','Value'],
             'Value':[12,15]
             }
```

![dataframe](https://github.com/user-attachments/assets/8af6252f-f3a0-4e2a-8b3b-4112c3aca8f4)

**Expected behavior**
Every time the cube should have 27 (considering it will always aggregate duplicate entries), or the last record i.e. 15 (if not aggregating)

**Version**
TM1py [2.0]
TM1 Server Version: [e.g. 11.8]

**Additional context**

**Comment by Mr-SabyasachiBose** [comment]
The cube has been manually cleared before each upload attempt.

**Comment by MariusWirtz** [comment]
Good catch! We need to address this
