### ISSUE TITLE
Unexpected behaviour of include_attributes parameter when using Properties clause

### ISSUE THREAD

**Issue by henrys273** [cubewise-code/tm1py#1197]
**Describe what did you try to do with TM1py**
I am trying to load an attribute for a specific dimension into the dataframe using tm1.cubes.cells.execute_mdx_dataframe(mdx, include_attributes=True).

I have defined the attribute for the dimension in the Properties clause in the MDX query. The returned dataframe only restricts the selection of attributes for the addressed dimension and contains all attributes for the other dimensions.

I would have expected that when explicitly specifying a Properties clause, only the referenced attributes would be included, and the attributes of non-addressed dimensions would not be included at all.

Is this the default behavior?

Thx

**Version**
- TM1py 2.0.4 
- TM1 Server Version: 11.8.02301.1

**Comment by MariusWirtz** [comment]
The TM1 REST API returns all attributes if no properties are explicitly requested.

You can explicitly request the member name on each axis as a "dummy" property like below.

Does that solve your problem?

``` python
from TM1py import TM1Service

with TM1Service(address='', port=12354, ssl=True, user='admin', password='apple') as tm1:
    mdx = """
        WITH MEMBER[d2].[e81] AS 2
        SELECT[d1].MEMBERS  PROPERTIES [d1].[Attribute Something] ON ROWS,
        {[d2].[e81]}  PROPERTIES MEMBER_NAME ON COLUMNS
        FROM[c1]
        """

    print(tm1.cells.execute_mdx_dataframe(mdx=mdx, include_attributes=True, top=100))
```

**Comment by henrys273** [comment]
Thank you Marius,

that solves the problem. I did not know about MEMBER_NAME as a Dummy for no attributes.
