### ISSUE TITLE
connectionpool issue

### ISSUE THREAD

**Issue by jmliando** [cubewise-code/tm1py#1200]
Hi Marius

I tried to run samples_setup.py but had an issue with connectionpool.py as you can see in this screenshot.
Can you please help me? Thank you

![connectionpool_py](https://github.com/user-attachments/assets/77730784-399a-4253-b4c8-6851f4d29f3e)

**Version**
- Python 3.9.13
- TM1py 2.0.2 
- TM1 Server Version 2.0.918.3

I also try to use the check.py to check the connection but it is hanging after I put TM1 User.

![check_py](https://github.com/user-attachments/assets/18cf89b3-e3c2-4ffc-aa69-6402a1dcd05b)

**Comment by MariusWirtz** [comment]
Please try to run the simplest possible python script in your pycharm environment. Like this:

``` python
from TM1py import TM1Service

tm1_params = {
    "address": "localhost",
    "port": 12354,
    "user": "admin",
    "password": "apple",
    "ssl": True,
}
with TM1Service(**tm1_params) as tm1:
    print(tm1.server.get_product_version())
    print(tm1.server.get_server_name())

```

Does that work?

**Comment by jmliando** [comment]
It is hang. 
![image](https://github.com/user-attachments/assets/11d2283b-3603-4436-a6d4-fd68f90d1226)
