### ISSUE TITLE
Best way to get leaves of element based on their level

### ISSUE THREAD

**Issue by ScarAnd** [cubewise-code/tm1py#1208]
**Describe what did you try to do with TM1py**
Hey Marius,

Is it possible to get the leaves under a specific member by filtering by a level? I know theres a function called

`get_leaves_under_consolidation` or `get_members_under_consolidation`.

But I think I don't get the results I was looking for.

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. Get the leave element names of a consolidated element based of a level filtering

**Version**
- TM1py (2.0.4)
- TM1 Server Version: [12.4.4]

**Comment by MariusWirtz** [comment]
Have you considered using MDX like this?

> In:

``` python
with TM1Service(**tm1_params) as tm1:
    mdx = "{[Region].[Level000].Members}"
    result = tm1.elements.execute_set_mdx(
        mdx=mdx,
        element_properties=None,
        member_properties=["Name"],
        parent_properties=None)

    df = pd.DataFrame(record[0] for record in result)

    print(df.to_markdown())
```

> Out:

|    | Name        |
|---:|:------------|
|  0 | All Regions |


> In:

``` python
with TM1Service(**tm1_params) as tm1:
    mdx = "{[Region].[Level001].Members}"
    result = tm1.elements.execute_set_mdx(
        mdx=mdx,
        element_properties=None,
        member_properties=["Name"],
        parent_properties=None)

    df = pd.DataFrame(record[0] for record in result)

    print(df.to_markdown())
```

> Out:

|    | Name                 |
|---:|:---------------------|
|  0 | United States        |
|  1 | Canada               |
|  2 | Mexico               |
|  3 | Brazil               |
|  4 | United Kingdom       |
|  5 | Germany              |
|  6 | France               |
|  7 | Italy                |
|  8 | Spain                |
|  9 | Netherlands          |

**Comment by ScarAnd** [comment]
Thanks for your fast answer,

I think that worked, but I don't know if theres a better option. Because I want to get the leaves of a member based of specific parameters which I can get off a view.

**Comment by MariusWirtz** [comment]
So you want all leaf elements that roll into a specific consolidation (e.g. **Europe**). And that specific consolidation comes from a cell in a cube view.

Is that correct?

**Comment by ScarAnd** [comment]
Yes thats correct. I now have a solution to get the children. 

This is what I'm using now in my for loop:

```
    mdx = "{[" + dimension_name + "].[" + row[0] + "].Children}"
    result = tm1.elements.execute_set_mdx(
        mdx=mdx,
        element_properties=None,
        member_properties=["Name"],
        parent_properties=None,
    )
```

I don't know if theres a better way but it works.

**Comment by MariusWirtz** [comment]
OK. 

The `Children` function only returns the immediate children. You might want to use `DESCENDANTS` instead.
Also check out `mdxpy`. It helps build the MDX query dynamically and handles certain edge cases, such as characters that need to be escaped in a member name.
