### ISSUE TITLE
Support HTTPS URL on Cognos Dispatcher for CAM SSO

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#123]
TM1py needs to support SSO through CAM when the Cognos Dispatcher is adressed through HTTPS.

The TM1Service constructor requires a new optional argument like `gateway_verify`. The value can be `false` if no verification is necessary or the path to the appropriate .cer file.

**Comment by rclapp** [comment]
Works like a charm. SSO will make prod deployment's so much easier.

**Comment by MariusWirtz** [comment]
Nice one! Thanks for the fix.
