### ISSUE TITLE
pywin32 dependency breaks Linux build (1.3.0)

### ISSUE THREAD

**Issue by kaylon** [cubewise-code/tm1py#127]
The latest release will not install on Linux. We kindly ask you to keep tm1py platform independend compatible.

`➜  ~ python3 -m pip install "tm1py>=1.3.0"
Collecting tm1py>=1.3.0
  Downloading https://files.pythonhosted.org/packages/c8/06/6f6d51efa0a925c0821f172572a41c250921c7056bfd6d06e0594a6c30e7/TM1py-1.3.0.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 1.8MB/s 
Requirement already satisfied: requests in ./.local/lib/python3.6/site-packages (from tm1py>=1.3.0) (2.21.0)
Requirement already satisfied: pandas in ./.local/lib/python3.6/site-packages (from tm1py>=1.3.0) (0.23.4)
Requirement already satisfied: pytz in ./.local/lib/python3.6/site-packages (from tm1py>=1.3.0) (2018.7)
Collecting requests_negotiate_sspi (from tm1py>=1.3.0)
  Downloading https://files.pythonhosted.org/packages/7c/0b/99220cb4d3c8cf9b667a1cd13650d28b19e689ab7145085897e254d141a3/requests_negotiate_sspi-0.5.2-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python3.6/site-packages (from requests->tm1py>=1.3.0) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./.local/lib/python3.6/site-packages (from requests->tm1py>=1.3.0) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in ./.local/lib/python3.6/site-packages (from requests->tm1py>=1.3.0) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.6/site-packages (from requests->tm1py>=1.3.0) (2018.11.29)
Requirement already satisfied: numpy>=1.9.0 in ./.local/lib/python3.6/site-packages (from pandas->tm1py>=1.3.0) (1.15.4)
Requirement already satisfied: python-dateutil>=2.5.0 in ./.local/lib/python3.6/site-packages (from pandas->tm1py>=1.3.0) (2.7.5)
Collecting pypiwin32>=223 (from requests_negotiate_sspi->tm1py>=1.3.0)
  Using cached https://files.pythonhosted.org/packages/d0/1b/2f292bbd742e369a100c91faa0483172cd91a1a422a6692055ac920946c5/pypiwin32-223-py3-none-any.whl
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas->tm1py>=1.3.0) (1.12.0)
Collecting pywin32>=223 (from pypiwin32>=223->requests_negotiate_sspi->tm1py>=1.3.0)
  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32>=223->requests_negotiate_sspi->tm1py>=1.3.0) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32>=223->requests_negotiate_sspi->tm1py>=1.3.0)`

**Comment by MariusWirtz** [comment]
Hi @kaylon ,

Thanks for the catch!

Just pushed a new version (1.3.1) to PyPI that should fix the issue.
Could you please try to install it again with pip ?

I added a line to the setup.py script, so that `requests_negotiate_sspi` is only installed on windows and made the import in the `RESTService` fail safe.

You can see the changes here:
https://github.com/cubewise-code/tm1py/pull/128

**Comment by kaylon** [comment]
Sorry, took me some time to get to it.
That works for us. Thank you!

**Comment by MariusWirtz** [comment]
Hi @kaylon ,

OK. thanks for the update!
