### ISSUE TITLE
Unable to install TM1py on server with no internet

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#132]
**Describe what did you try to do with TM1py**
I am trying to install TM1py but the server has no internet connection

**Describe what's not working the way you expect**
I receive an error that i am including when running the setup.py after copying the source directory to the site library folder

**Version**
- TM1py 1.3.1 
- TM1 Server Version: 11.4.00003.8

![py error](https://user-images.githubusercontent.com/8358847/59059487-1b291200-886d-11e9-8451-5b07a353d758.png)

![tm1py location](https://user-images.githubusercontent.com/8358847/59059612-64796180-886d-11e9-89f3-8b299ca040b4.png)

Thanks
**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by MariusWirtz** [comment]
It seems you are missing one library: `requests_negotiate_sspi`
You need to download that one manually as well.

**Comment by jbeanz23** [comment]
i only see it as a wheel.  How to i run that?

**Comment by MariusWirtz** [comment]
Just open the command line, go to the folder where you placed the .whl file and run
`pip install some-package.whl`

**Comment by jbeanz23** [comment]
when i try to run that and requests i get the following error about certifi

![error2](https://user-images.githubusercontent.com/8358847/59069246-8d592100-8884-11e9-896c-9a7efccd9d05.png)

**Comment by MariusWirtz** [comment]
It seems `requests_negotiate_sspi` also has dependencies. I don't think it makese sense to install all these packages individually

I think it's easier if you install the Anaconda distribution of python on that machine. Then you already have most of the packages (requests, pandas, numpy, ...) installed.
On top of Anaconda you only need to install `requests_negotiate_sspi` and `TM1py`

**Comment by jbeanz23** [comment]
ok, ill try that.  thanks

**Comment by jbeanz23** [comment]
I am having trouble executing anything within the anaconda prompt.  How do i run tm1py from the anaconda prompt?  I am not familiar with how to use the Anaconda prompt line.  I tried in a pycharm terminal but i get a message that windows cant open the type of file.
![error 3](https://user-images.githubusercontent.com/8358847/59073022-3eff4e80-8893-11e9-85db-c15be7138ecb.png)

**Comment by MariusWirtz** [comment]
Hi, 

you don't necessarily need to run the setup.py script.
You can just paste the TM1py folder into the `Anaconda3/Lib/site-packages/` folder

The Folder structure need to look like this:
```
Anaconda3
- ...
- Lib
- ...
-- site-packages
--- ...
--- TM1py
---- Exceptions
---- Objects
---- Services
---- Utils
...
```

**Comment by MariusWirtz** [comment]
Regarding the execution of py files in the terminal, I think you need to type:

`python setup.py`

or the explicit version:

`C:\Anaconda3\python setup.py`

**Comment by jbeanz23** [comment]
Thanks Marius.  I got everything installed but now when i try to run unused dims i get the error below.  I am also including the config.  Is the issue the https for the gateway?

[tm1srv01]
address= localhost
port= 23999
user=
password=
namespace = TeXXXXX
gateway = https://XXXXXXXX/bi/v1/disp
ssl=True

![error 4](https://user-images.githubusercontent.com/8358847/59123744-019acf80-892c-11e9-8154-925a118efe2f.png)

**Comment by MariusWirtz** [comment]
Hi,

could be related to HTTPS. @rclapp wrote a fix for this yesterday. It's included in the current master branch at GitHub, but not in the latest release (1.3.1) !

If you download the master from github (the green button at the top right in the main page) and place it in the site-packages folder, does that help?

**Comment by jbeanz23** [comment]
I have the fix in and it still does not work...it also does not work for me to leave the gateway blank and use my credentials like below....do you think there is something blocking the connection?

port= 23999
user=nfrigo
password=RmlmaTAwOCQ=
namespace = 
gateway = 
ssl=True

![error 5](https://user-images.githubusercontent.com/8358847/59134116-23a24b00-8948-11e9-9f88-4efccb66b0bc.png)

**Comment by MariusWirtz** [comment]
If the TM1 model is using CAM security and you want access it with user and password, you also need to provide the namespace.

**Comment by jbeanz23** [comment]
i copied it from the branch, the rest service, the RestService.py, correct?

**Comment by jbeanz23** [comment]
I think i tried it that way too, but i will check again and post the error

**Comment by MariusWirtz** [comment]
Yes. All the changes @rclapp made were in the RestService, so if you copy that file you should be alright.

**Comment by MariusWirtz** [comment]
If you password is b64 encoded in the file, you also need to add `decode_b64=True` in the config.ini

**Comment by jbeanz23** [comment]
ya, so i just tried with the namespace.  I have also tried with the full computer name and IP address
[tm1srv01]
address= localhost
port= 23999
user=nfrigo
password=RmlmaTAwOCQ=
namespace = Techdata
gateway = 
ssl=True

![error 6](https://user-images.githubusercontent.com/8358847/59134436-2e111480-8949-11e9-882a-af4b26110cfd.png)

**Comment by jbeanz23** [comment]
oh, i saw that was committed then removed it looked like
i will try that

**Comment by MariusWirtz** [comment]
The 401 Error means that the Authentication failed. It must be either the User, Password or Namespace that is wrong.

Now if you tried it a few times with a wrong password or namespace, it could also be that your user is blocked. 🤔

**Comment by jbeanz23** [comment]
i tried and get the following..do i need to change a line in the Rest Service, it says false in the error for base64 decode

[tm1srv01]
address= localhost
port= 23999
user=nfrigo
password=RmlmaTAwOCQ=
namespace = Techdata
gateway = 
ssl=True
decode_b64=True

![error7](https://user-images.githubusercontent.com/8358847/59134679-0bcbc680-894a-11e9-8f39-d59534ab4678.png)

**Comment by jbeanz23** [comment]
does the username need the domain in front, like us\nfrigo?

**Comment by MariusWirtz** [comment]
No, I believe the domain prefix is not necessary.

The namespace is case-sensitive. Is that perhaps the problem ?

**Comment by jbeanz23** [comment]
I added us\nfrigo and its working now.  Yay!  But for a long term solution for the client, if the RestService script did not fix the issue what can be done?  I don't think they want user info in the config

**Comment by MariusWirtz** [comment]
I close this issue. Please open a new one if you are stuck with setting up SSO.
