### ISSUE TITLE
Unable to execute TM1py script from TI Process

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#139]
**Describe what did you try to do with TM1py**
I created a TI with the following lines to execute my python script:

pyExe = '"D:\Anaconda3\python.exe"' ;

pyFile = '"D:\TM1\GFPMR\Import_Files\EMEA Drivers\scratch_Freight.py"' ;

EXECUTECOMMAND(pyExe |' '| pyFile,1);

It says successful but nothing happened.  I then tried using the command line and received the following:

F:\>D:\Anaconda3\python.exe "D:/TM1/GFPMR/Import_Files/EMEA Drivers/scratch_Freight.py"
Traceback (most recent call last):
  File "D:/TM1/GFPMR/Import_Files/EMEA Drivers/scratch_Freight.py", line 41, in <module>
    with TM1Service(**config["tm1srv01"]) as tm1:
  File "D:\Anaconda3\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'tm1srv01'

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1.The TI to execute the script is not executing the script
2. I should note Anaconda is installed on D drive and there is no internet connection on the server

**Version**
- TM1py 1.3.1
- TM1 Server Version: 11.4

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by MariusWirtz** [comment]
Hi @jbeanz23 ,

you are getting this error because python does not find the `config.ini` file. 
It's due to the relative path to the config.ini in your script.

There are two things you can do now:
- Use an absolute path to the config.ini file
- Set the CurrentDirectory at the start of the script like this:
``` python
def set_current_directory():
    abspath = os.path.abspath(__file__)
    directory = os.path.dirname(abspath)
    os.chdir(directory)
    return directory

CURRENT_DIRECTORY = set_current_directory()
```
