### ISSUE TITLE
Unable to establish Single Sign On using New Parameter "Gateway"

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py#140]
Hi Marius/ Vviau,

 Using latest version TM1py 1.3.1, tried to achieve SSO with new parameter Gateway but im facing an error message SSL : certificate verification failed.
Could you please help me out with this issue ,

FYR attaching error message document please go through it.

Thank You,
Ram
![Error Message_TM1py_SSO_Gateway](https://user-images.githubusercontent.com/49037021/59552236-056cc880-8fa2-11e9-995d-97a22643d2d4.JPG)

**Comment by MariusWirtz** [comment]
Hi @Rnvksm ,

the current release on PyPI is missing a fix that @rclapp wrote a few days ago.
Please download the current master branch from the TM1py github page and try again.

Let us know how it goes!

**Comment by Rnvksm** [comment]
Hi Marius,

I tried New package facing another issue "Actively refusing"
Attaching error message could you please help me out.

![Error Message_TM1py_SSO_Gateway (1) ](https://user-images.githubusercontent.com/49037021/59579275-b8940980-90e9-11e9-963f-a376b452688d.JPG)

**Comment by MariusWirtz** [comment]
it means that the machine exists but that it has no services listening on the specified port, or there is a firewall stopping you.

That's not a TM1py issue. I suggest you try your luck on stackoverflow or with your internal IT department.
