### ISSUE TITLE
cellset to pandas - memory control

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#142]
When I use `pd.read_csv`, I usually save a lot of memory using the arguments: `parse_dates` and `dtypes` to define variables types:

![Dadosaa](https://user-images.githubusercontent.com/51836477/59771058-67b61980-927f-11e9-9d13-b0dfc7b0f06c.jpg)

Is there anything similar using `.build_cellset_from_pandas_dataframe(df)` ?

Thanks

**Comment by MariusWirtz** [comment]
Hi @kaleming,

just wrote a fix for #143, that exposes all arguments from the `pandas.read_csv` method to the `execute_view_dataframe` and `execute_mdx_dataframe` methods. Here is a sample:

``` python
with TM1Service(address='10.77.19.10', port=12354, user='admin', password='apple', ssl=True) as tm1:
    df = tm1.cubes.cells.execute_view_dataframe(
        cube_name="Weather Data",
        view_name="Default",
        private=False,
        parse_dates=[0],
        dtype={'Value': float})
    print(df)

```
Does this work for you?

**Comment by kaleming** [comment]
Sounds Good @MariusWirtz. 
Does it work to specify 'float64',  'float32', 'float16' ?

Thank you

**Comment by MariusWirtz** [comment]
Sure. It would look like this:

``` python
with TM1Service(address='10.77.19.10', port=12354, user='admin', password='apple', ssl=True) as tm1:
    df = tm1.cubes.cells.execute_view_dataframe(
        cube_name="Weather Data",
        view_name="Default",
        private=False,
        parse_dates=[0],
        dtype={'Value': np.float64})
```

**Comment by kaleming** [comment]
Thank you very much
