### ISSUE TITLE
execute_view_dataframe returns dimension elements with datatype int64

### ISSUE THREAD

**Issue by tfisher27** [cubewise-code/tm1py#143]
I'm building a pandas dataframe with the command execute_view_dataframe. I have dimension elements that are strings that "look like" numbers i.e 00354. The data frame values for this dimension are converting the data type to Int64 (354) and I need the datatype to be object in order to retain the leading 0s to be used in dictionary references. Any suggestions?

**Comment by MariusWirtz** [comment]
Hi @tfisher27,

I was able to replicate this behaviour. It's a bug and I will write a fix, so that element names will be treated as strings unless specified otherwise.

**Comment by MariusWirtz** [comment]
Hi @tfisher27,

now when you call the `execute_mdx_dataframe` method, by default all columns will be of type `str` and the Value column will of type `object`. If you want to overrule, this you can pass the `dtype` argument when executing the `execute_mdx_dataframe` method:

``` python
mdx = """
    SELECT
    NON EMPTY { [dim2].[000004124],[dim2].[000004125], [dim2].[000004126]} ON ROWS,
    { Tm1SubsetAll([dim3]) } ON COLUMNS
    FROM [cube1]
    WHERE ([dim1].[elme2])
"""
with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True) as tm1:
    df = tm1.cubes.cells.execute_mdx_dataframe(mdx, dtype={'dim2': str, 'Value': float})
    print(df)
```

**Comment by tfisher27** [comment]
That’s awesome Marius!

This will help a lot! By the way I am really loving TM1py. It’s helping us use TM1 in whole new ways.

Thanks for all you have done.

Tom Fisher
Qualcomm inc.

On Jun 23, 2019, at 6:04 AM, Marius Wirtz <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @tfisher27<https://github.com/tfisher27>,

now when you call the execute_mdx_dataframe method, by default all columns will be of type str and the Value column will of type object. If you want to overrule, this you can pass the dtype argument when executing the execute_mdx_dataframe method:

mdx = """
    SELECT
    NON EMPTY { [dim2].[000004124],[dim2].[000004125], [dim2].[000004126]} ON ROWS,
    { Tm1SubsetAll([dim3]) } ON COLUMNS
    FROM [cube1]
    WHERE ([dim1].[elme2])
"""
with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True) as tm1:
    df = tm1.cubes.cells.execute_mdx_dataframe(mdx, dtype={'dim2': str, 'Value': float})
    print(df)

**Comment by tfisher27** [comment]
Hi Marius,

Does this work for execute_view_dataframe also or only execute_mdx_dataframe? Also, to get the new code I use pip install tm1py –upgrade?

Thanks again,

Tom

**Comment by MariusWirtz** [comment]
Hi @tfisher27 ,

yes. It also works for `execute_view_dataframe`

We haven't pushed the current version to PyPI yet, but you can upgrade to the version on GitHub with pip like this:
`pip install git+https://github.com/cubewise-code/tm1py.git --upgrade"`
