### ISSUE TITLE
Properly escape single quote in object references

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#145]
**Describe the bug**
TM1py fails to update, retrieve or reference objects that contain a single quote in their name.

**To Reproduce**
use the `write_values` method with an element that contains a single quote in it's name.

**Expected behavior**
TM1py should escape single quotes through double single quotes in all references and URLs.

**Version**
TM1py 1.3.1
TM1 Server Version: 11.4

**Comment by lotsaram** [comment]
Thanks for the super quick turnaround on this one. We will try and test this today and let you know if the issue with single quotes in element names is then fixed.
