### ISSUE TITLE
Cannot connect to TM1 Service

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#147]
**Describe what did you try to do with TM1py**
Python and Tm1py has been installed on a separate server then TM1.  When trying to run a script from that server i receive an error the TM1.Service module is not found,

**Describe what's not working the way you expect**
Error occurs at 4th line: 
from TM1py.Services import TM1Service

The service is there but it seems not recognized

**Version**
- TM1py 1.3.1
- TM1 Server Version: 11.4

**Additional context**
Any idea what could be causing this?

**Comment by MariusWirtz** [comment]
Hi @jbeanz23,

sounds like the installation somehow failed.
You check if TM1py is installed with pip:

`pip show TM1py`

**Comment by jbeanz23** [comment]
It did fail, we re-installed today and all is working!

Well, except how we will handle the executing of the scripts when python is on a separate server :)

**Comment by jbeanz23** [comment]
Marius, can the config file take encrypted passwords, besides base64?
