### ISSUE TITLE
Executing Process with Parameters it need to return Boolean

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py#152]
i'm trying to run processes for creating dynamic views .after running the process i need to return something as Boolean. Based on the Boolean expression  i can use dynamic view in the next line to fetch data from cube.
right now i'm using 
            execute(process_name, parameters=None, **kwargs)

can you please help me out i need to get the status of the process based on that i can plan for next event

**Comment by MariusWirtz** [comment]
Hi @Rnvksm ,

if you are on TM1 11 there is a more convenient way to execute a TI process through TM1py.
The `execute_with_return` method is convenient because it provides more information in case the process fails.

Here is how you can use it:

``` python
import configparser

from TM1py.Services import TM1Service

config = configparser.ConfigParser()
config.read(r'..\config.ini')

with TM1Service(**config['tm1srv01']) as tm1:
    success, status, error_log_file = tm1.processes.execute_with_return(
        process_name="Bedrock.Server.wait",
        pWaitSec=2)

    if success:
        print("Process executed successfully")
    else:
        print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)
```
