### ISSUE TITLE
Creating a subset

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#154]
**Describe what did you try to do with TM1py**
Hi - I am having the most difficult time creating a subset.  I have a large list of elements from a filtered view and i want to use them to create a subset.  I have tried using lists, dictionaries but when i run the tm1.dimensions.subsets.create(subset=set1, private=True (or false)) i get the trace back shown below. 

It's many elements so i do not want to type them out.  Is there a way to use a set, list or dictionary and create a subset from them?

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. a newly created subset
2. create a subset within a dimension based on elements return from a suppressed cube view that i have stored in dataframe

**Version**
- TM1py 1.3.1
- TM1 Server Version: 11.4

![subset](https://user-images.githubusercontent.com/8358847/61097693-209bee00-a411-11e9-8b3a-7f196d68de80.png)

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by clappr-zz** [comment]
It returns 401. You don't have permissions to do that. Check you have access to that dimension.

**Comment by jbeanz23** [comment]
I am an admin on the TM1 server.  The python server is on a separate server.  I get the same error message when i try doing this locally on my laptop with both TM1 and python.

**Comment by clappr-zz** [comment]
then your password is wrong maybe? Try requesting something else like a list of cubes.

**Comment by clappr-zz** [comment]
401 only occurs when you can't authenticate

**Comment by jbeanz23** [comment]
I don't understand.  I am a local admin on my PC and in TM1.  How could it not authenticate?  I am attaching my script....i have been changing things around to try and make it work....if you could give me and pointers on why this would return 401?

[Alloc_Subset.zip](https://github.com/cubewise-code/tm1py/files/3384788/Alloc_Subset.zip)

This is my config:
[tm1srv01]
address=localhost
port=8555
user=Nicole
password=MQ==
ssl=True
decode_b64=True
 
You can see i am an admin:
![security](https://user-images.githubusercontent.com/8358847/61099017-d1a48780-a415-11e9-848c-5049df391585.png)

**Comment by vviau** [comment]
Hi @jbeanz23 ,

Just to make sure your configuration is correct, could you please try to run the **check.py** script from the TM1py samples as it is explained here: [Check Connectivity with TM1](https://code.cubewise.com/tm1py-help-content/check-connectivity-with-tm1)

Cheers,

Vincent

**Comment by jbeanz23** [comment]
Sure
Here you go:

![check py result](https://user-images.githubusercontent.com/8358847/61099541-8e4b1880-a417-11e9-9dae-e8800e4f8e2b.png)

**Comment by clappr-zz** [comment]
Looking at your code there are a few things that jump out as a possible issue. You connect to TM1 2x for no reason, you don't need:

 tm1_source = TM1Service(**config['tm1srv01'])

"With" statements in python require an indent. Your subset stament on line 80 is not inside your with statement where you define your tm1 connection. 

I am not sure why you have an "r" in your config reader.

 config.read(r'config.ini')

I have not used that notation for but it shouldnt be needed. 

Hope this helps

**Comment by jbeanz23** [comment]
AH, Thank you  @clappr-zz 
I keep forgetting the indenting part with python.  I am used to using ENDIF's.  Can you tell me if i can use a list to create a subset or does it have to be a dictionary or set?

The config.read(r'config.ini') i got from the TM1py samples, i believe.

Thanks

**Comment by jbeanz23** [comment]
It's working now but only one element is being added to the subset

**Comment by jbeanz23** [comment]
I got it working, Thanks @clappr-zz  for your help!
