### ISSUE TITLE
data using float possibly causing obscure data

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#157]
**Describe what did you try to do with TM1py**
I am not sure of this is related to python and how it is calculating, but I am running data and calculating driver data based on a percentage of Net Gross for a particular material.  I am getting some extreme numbers that are fractions of a penny divided by fractions of a penny resulting in huge numbers that are not being spread or tying out.  In addition, upon completing the spread in python, every time i click recalculate in TM1 multiple months of data change each time it's clicked.  These are not rule driven cells.  They are all written to the month from python.  I am including screenshots of both the extreme large numbers and percentages being used (including a rule trace) and of how the data changes after each time i click re-calc.  I have tried modifying the data load to only use 2 decimal points on the load of NSB data since all % calculations are created using this measure but it has not fixed the problem.

You can see in the 3rd screen shot, after the load completes, i have pressed re-calc 3 times.  Each time months 2018-M04 - 2018-M12 the data changes at the total level.  

I read about how the float picks up so many integers which is why i tried to limit the data load to 2 integers but it's still not totaling out when i do the manipulation from temp feight to freight.  Temp freight is where the initial data is loaded.  In TM1py, we are trying to spread the value down to the material level based on the % of NSB Gross.  For a few months it ties exactly, other months it is off due to these percentages and values are not totaling and then i have these months where every time i click recalculate the value changes.  I have never seen anything like this before and am hoping someone has some insight or recommendations.  Script is also attached.

Thanks

**Version**
- TM1py 1.3.1
- TM1 Server Version: 11.4

![freight 1 shot](https://user-images.githubusercontent.com/8358847/61272372-d93c9700-a75b-11e9-9771-2f189a35b56f.png)

![feight shot 2](https://user-images.githubusercontent.com/8358847/61272428-fbceb000-a75b-11e9-842a-5cd4706f8950.png)

![freight shot 3](https://user-images.githubusercontent.com/8358847/61272392-e5285900-a75b-11e9-801a-b5dcbde0168a.png)

[Freight_EMEA.zip](https://github.com/cubewise-code/tm1py/files/3395725/Freight_EMEA.zip)

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by rclapp** [comment]
TM1 as a limit of 15 digits per number. Sounds like you are running up against TM1 precision.

https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/Wc8dd794ce663_464f_89d9_5472bde75168/page/TM1%20Server%20and%20Floating%20Point

https://www-01.ibm.com/support/docview.wss?uid=swg21515228

**Comment by jbeanz23** [comment]
Yes-  that's what I was reading.  Is there any way around this?  I tried the formatting and RoundP on the rules, and limited the source data on load but nothing is preventing these huge %'s and numbers which are throwing off my totals.  The Freight should be spread based on NSB by Material % and total to the same number showing in Temp Freight.

**Comment by rclapp** [comment]
Data change on refresh is expected and simply due to the order in which TM1 consolidates very large numbers (ie floating point math). [MagnitudeDifferenceToBeZero](https://www.ibm.com/support/knowledgecenter/en/SSD29G_2.0.0/com.ibm.swg.ba.cognos.tm1_inst.2.0.0.doc/c_magnitudedifferencetobezero_tm1.html) only helps with the safe division operator (  A  \  B) . If your division is done in python then it would not help.

You should be able to use rounding and logic to prevent really small (and large percents)

**Comment by jbeanz23** [comment]
The division for the percentages is actually done in the rules.  Only the multiplication is done in python.  With this being the case would the MagnitudeDifferenceToBeZero be a good option?

These are the rules determining the percentages used in python to multiple against the drivers values:
['NSB Gross %']=
                DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,!Profit 
                      Center,!Customer EMEA,!Material EMEA,'NSB Gross') \
               DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,'Total Profit 
                      Center','Total Customer EMEA','Total Material','NSB Gross');


['NSB by Customer %']=
               DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,!Profit Center,!Customer 
                      EMEA,!Material EMEA,'NSB Gross') \
               DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,!Profit Center,'Total 
                      Customer EMEA',!Material EMEA,'NSB Gross');

['NSB By Material %']=
               DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,!Profit Center,!Customer 
                     EMEA,!Material EMEA,'NSB Gross') \
               DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,!Profit Center,!Customer 
                      EMEA,'Total Material','NSB Gross');


['NSB Undefined Customer %']=
               DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,!Profit Center,!Customer 
                    EMEA,!Material EMEA,'NSB Gross') \
               DB('Allocation Assumptions EMEA',!Version,!Time Month,!Region EMEA,!Profit Center,'Total 
                     Customer EMEA','Total Material','NSB Gross');
