### ISSUE TITLE
get/ set _datasource_password

### ISSUE THREAD

**Issue by marfrit** [cubewise-code/tm1py#158]
If I get a _datasource_password from a process (entered in TI before, working), and then proceed to set the string I got (which is different from the actual password), the TI process cannot connect to the database. Any idea how the password is encrypted before it is saved to the .pro file? 

I think this is not an TM1py issue, but maybe someone came accross the same hurdle.

**Comment by MariusWirtz** [comment]
Hi @marfrit ,

I suppose IBM is not going to tell anyone what their encryption algorithm is.
I would say the way to manage it is to use single sign on and have a DB account for whatever system user is running the TM1 service. Or store the password in a TM1 cube and retrieve it on the prolog.

Cheers,

Marius

**Comment by marfrit** [comment]
Yes. For the time being, I just put the plain text password in _datasouce_password on setting and it then works fine.
