### ISSUE TITLE
Implement new load / unload cube methods

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#163]
PA 2.0.8 introduced two new Actions to the TM1 REST API:
- Cube.Load
- Cube.Unload

TM1py needs to wrap them into methods in the CubeService

**Comment by macsir** [comment]
Awesome! What are those and what is the advantages of using that? Thanks.

**Comment by MariusWirtz** [comment]
You can use them to load a cube into memory (like at server startup) or unload it

**Comment by macsir** [comment]
@MariusWirtz  Have you tried to use this method to hot promote a cube? e.g. I unload a cube from the server and replace .cub file with latest data and load it into ram. I am gonna test it to see. Thanks.

**Comment by MariusWirtz** [comment]
@macsir I haven't tried this yet but I would assume that it should just work.
 
Was your test successful?

**Comment by macsir** [comment]
No it doesn’t work. The original cube data was just wiped out and no new data is showing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
