### ISSUE TITLE
Error with CaseandSpaceSensitive Tuple

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#164]
**Describe what did you try to do with TM1py**
Hi - I am using a script you helped with but have modified it for a different cube.  When i go to calculate the exceptions i get an error on the tuple.  I am attaching the script and the log file.

This query only has one dimension where all N levels are used for exceptions.  Error is pointing to line 202.
Thanks

[54000_AMER.zip](https://github.com/cubewise-code/tm1py/files/3488033/54000_AMER.zip)

**Version**
- TM1py e.g. 1.3.1 
- TM1 Server Version: e.g. 11.4

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by MariusWirtz** [comment]
Hi @jbeanz23,

in the error message it essentially says, that in the `file_data` dictionary there is no key called 
`('a3-000000000010445673',)`
You will see that this element is a tuple with one element. Probably what you want to do is to get the value for the key `'a3-000000000010445673'` from the dictionary.

try to change line 199 from 
`for (material,), (cogs, original_value) in data_on_total_customer.items():`
to
`for (material,), (cogs, original_value) in data_on_total_customer.items():`

Cheers,

Marius

**Comment by jbeanz23** [comment]
Thanks.  It's working now.
