### ISSUE TITLE
TM1Py CAM Non-SSO Authentication from Linux

### ISSUE THREAD

**Issue by BigFriendly** [cubewise-code/tm1py#165]
I'm trying to determine if TM1py ought to be able to authenticate via CAM username/password (not NTLM SSO) on Linux?

I understand that TM1py CAM SSO requires HttpNegotiateAuth which requires pypiwin32 and pywin32 which are Windows only packages.  It appears, however, that the entire CAM authorization function in RESTService.py (shown below) is reliant upon the Windows-only HttpNegotiateAuth.  If not using SSO, could the code be written to utilize standard HTTPAdapter calls to setup the authorization?

    def _build_authorization_token_cam(user=None, password=None, namespace=None, gateway=None):
        if gateway:
            if not HttpNegotiateAuth:
                raise RuntimeError(
                    "SSO failed due to missing dependency requests_negotiate_sspi.HttpNegotiateAuth. "
                    "SSO only supported for Windows")
            response = requests.get(gateway, auth=HttpNegotiateAuth())
            if not response.status_code == 200:
                raise RuntimeError(
                    "Failed to authenticate through CAM. Expected status_code 200, received status_code: "
                    + str(response.status_code))
            elif 'cam_passport' not in response.cookies:
                raise RuntimeError(
                    "Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie")
            else:
                return 'CAMPassport ' + response.cookies['cam_passport']
        else:
            return 'CAMNamespace ' + b64encode(str.encode("{}:{}:{}".format(user, password, namespace))).decode("ascii")

Thank you.  -- John

**Comment by MariusWirtz** [comment]
Hi @BigFriendly ,

you can already use TM1py on linux with CAM when authenticating with user and password.
It's implemented here:
https://github.com/cubewise-code/tm1py/blob/51df8e21927119c9b0f8dd20d2ba5f57e0ea8a65/TM1py/Services/RESTService.py#L315

We also adjusted the `setup.py` script (that is used by pip during the install) so that it doesn't try to install windows libraries on Linux.

So you should be good to go

**Comment by BigFriendly** [comment]
Hey Marius, thanks for the response.

It appears (at least in our RHEL environment), that the "if not HttpNegotiateAuth:" test is erroring rather than conditionally testing.  When check.py is run, it produces this error:

  File "/opt/appdata/anaconda3/lib/python3.7/site-packages/TM1py/Services/RESTService.py", line 300, in _build_authorization_token_cam
    if not HttpNegotiateAuth:
NameError: name 'HttpNegotiateAuth' is not defined

If I leave only

return 'CAMNamespace ' + b64encode(str.encode("{}:{}:{}".format(user, password, namespace))).decode("ascii") 

in the _build_authorization_token_cam function, I am able to successfully connect.

-- John

**Comment by MariusWirtz** [comment]
Hi @BigFriendly ,

thank you! You found a bug there. We will fix this!

However, when you authenticate with namespace, user and password you don't need to provide the gateway argument. 
If you don't provide a value for the gateway argument when you instantiate the TM1Service then you shouldn't get an error.

Cheers,

Marius

**Comment by macsir** [comment]
Hi, @MariusWirtz 
I am using TM1py on RHEL too and is there any way to authenticate with CAM rather than using password? That would be convenient and secure. Thanks.

**Comment by MariusWirtz** [comment]
Hi @macsir,

we don't provide SSO with CAM on Linux. 
Feel free to create a Merge Request for this feature.

One alternative for you could be to store the credentials encrypted with the keyring library.
