### ISSUE TITLE
CPU's for Performance

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#167]
**Describe what did you try to do with TM1py**
Hi
We have a Python server on a separate server then TM1.  It currently has 2 CPU's.  Will increasing the CPU's increase the performance of the Python calculations and what is the recommended number of CPU's?

**Version**
- TM1py  1.3.1
- TM1 Server Version:  11.4

Thanks

**Comment by MariusWirtz** [comment]
Hi @jbeanz23 ,

I really depends on your use case. Most of the time we will use python in a single threaded mode I suppose. Here 2 CPUs should suffice. 

However if you are doing really heavy calculations in python, and the calculations are the bottleneck, then parallelization will help. In that case I would argue the more CPUs the better.

Cheers,

Marius
