### ISSUE TITLE
How to retrieve attributes from elements using tm1py ?

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#168]
Hello,

I would like to know how to get elements's attributes from a dimension ?

I am trying to get a dataframe with an additional column with a specific attribute.

I have tried the following:

```
SELECT
{[Dim1].[Subset1]} ON ROWS,
{[Dim2].[Subset2]} ON COLUMNS
DIMENSION PROPERTIES
[Dim2].[Attribute1]
FROM [Cube]
```

However I couldn't get this additional column. Is there some approach using tm1py to get this information ?

Best Regards,

Le ming

**Comment by MariusWirtz** [comment]
Hi,

you can write a query agains the }ElementAttributes_ cube. More details here:
https://github.com/cubewise-code/tm1py/issues/104

**Comment by kaleming** [comment]
It worked fine. 

Thank you very much Marius.
