### ISSUE TITLE
CellSet content method not supported

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/tm1py#172]
Hey Marius, 
We have been playing with the extract_cellset_csv method and noticed some odd behaviors. It auto zero suppresses and automatically enables the first Alias for each element.

I touched base with IBM/Hubert on this and he said that method is not officially supported and was only in place for the Watson analytics connector (now defunct). I think we could replace it with another call and possibly use compact Json. Wanted to get your thoughts.
Thanks

**Comment by scrumthing** [comment]
Sorry to come back to such an old topic. but I am trying to extract data from tm1 to a csv file. I was using execute_view_csv, which afaik utilizes said extract_cellset_csv method and my result is quite the opposite regarding the alias. It seems the activated alias for the rows is not used and I get the principal name. Is there an easy way to extract data from a native view with the proper alias?

**Comment by MariusWirtz** [comment]
Hi @scrumthing,

I can think of two possible solutions to your problem

1. Use the `execute_view_raw` method and specify `elem_properties=Name,Attributes/Alias`. Then you get all the data you need but you have to deal with the raw JSON response of the REST API

2. After you retrieved the data from the cube view, you execute an MDX query against the `}ElementAttributes_` cube and ask explicitly for the Alias values of the elements you retrieved from the view.

**Comment by scrumthing** [comment]
Thanks @MariusWirtz! I did it in a similar fashion as (1). But I think I only went with the „normale“ view function and did the cvs manually. If you are interested I will look for my solution tomorrow.

**Comment by scrumthing** [comment]
I am getting old. I did it **exactly as you** described it in (2). :-D _Great minds always think alike_. 
Thanks for your feedback. :-)

**Comment by rkvinoth** [comment]
@MariusWirtz 

Believe this one can be closed based on #279
