### ISSUE TITLE
If any method to operating Sandboxs?

### ISSUE THREAD

**Issue by Yuschow** [cubewise-code/tm1py#173]
hi
tm1py is very useful to my job,i love to use it.thank a lot.
some questions I want to ask,If any method to operating Sandboxs in tm1py?

hope to get your answers,thank

**Comment by MariusWirtz** [comment]
Hi @Yuschow,

happy to hear that TM1py is useful for you.

We do not have a Service in TM1py that implements dedicated methods to work with Sandboxes  (yet). What functionality do you need TM1py to provide ?

However, if you just want to query data from a Sandbox with MDX, you can reference the `Sandboxes` Dimension in the query like a normal dimension

**Comment by Yuschow** [comment]
@MariusWirtz 
We have a scenario for predictive analytics and need to create a large number of sandboxes to speed up the calculations.

so if TM1py can provide methods to create , delete Sandboxes etc. that will be more wonderful.

**Comment by rclapp** [comment]
@Yuschow. I'm interested in learning more. How will sandboxes help speed up calculations?

On Dec 11, 2019 12:17 AM, Yuschow <notifications@github.com> wrote:

@MariusWirtz<https://github.com/MariusWirtz>
We have a scenario for predictive analytics and need to create a large number of sandboxes to speed up the calculations.

so if TM1py can provide methods to create , delete Sandboxes etc. that will be more wonderful.

-

**Comment by Yuschow** [comment]
hi @rclapp 
Our calculation model will be based on the values of several input variables, and then output 150 versions of analysis results.
we use sandboxes instead of the normal Dimension to parallel computing results, in the sandbox every versions of computing results will not trigger feeder again, so it can reduce calculation time as well as Memory and disk footprint.

**Comment by rclapp** [comment]
@Yuschow very interesting. I have found that sandboxes are quite good for small data set changes, but Large datasets cause considerable RAM and disk space increases, not to mention that sandbox size is governed by a config setting. How do you handle the single user nature of sandboxes?

**Comment by Yuschow** [comment]
@rclapp
these 150 sandbox just use for calculation.we use some specific user to create it. after the result was generate, will push every into the base. so although the normal user can see 150 versions of analysis results, but they can see this 150 sandbox.

**Comment by MariusWirtz** [comment]
@Yuschow ,
that's an interesting use case. 
To be honest, adding functionality for Sandboxes doesn't have highest priority for me at the moment. However TM1py is open source, I would be more than happy to review and merge in your changes if you want to write it yourself.

**Comment by Yuschow** [comment]
@MariusWirtz 
ok, i will try. hope i can contribute something :)

**Comment by MariusWirtz** [comment]
closed in favor of #216
