### ISSUE TITLE
write_values_through_cellset method

### ISSUE THREAD

**Issue by jimnaff** [cubewise-code/tm1py#175]
I am using write_values_through_cellset to move data from a source TM1 server to a target. I am noticing inconsistencies in the data being moved.  I am testing with 2 MDX statements. "MDX1" seems to work but not "MDX2". The code runs without error using either MDX statement. Here is my code:
``` python

import configparser

from TM1py.Services import TM1Service

config = configparser.ConfigParser()
config.read(r'..\config.ini')

with TM1Service(**config['tm1server01']) as tm1source:
    with TM1Service(**config['tm1server02']) as tm1target:

        mdx1 = """
            SELECT non empty {Descendants([plan_version].[plan_version].members,100,LEAVES)} *
            {[plan_business_unit].[plan_business_unit].[10120]} *
            {[plan_department].[plan_department].[415] } *
            {[plan_chart_of_accounts].[plan_chart_of_accounts].[64055] } *
            {[plan_exchange_rates].[plan_exchange_rates].[local] } *
            {[plan_lines].[plan_lines].[line 1] }
            on 0, 
                   {[plan_time].[plan_time].[Dec-2004]} on 1 
                   FROM [plan_BudgetPlanLineItem]
            """

        mdx2 = """
                   SELECT non empty {[plan_version].[plan_version].[FY 2004 Budget]} *
                   {Descendants([plan_business_unit].[plan_business_unit].members,100,LEAVES)} *
                   {Descendants([plan_department].[plan_department].members,100,LEAVES) } *
                   {Descendants([plan_chart_of_accounts]. 
                   [plan_chart_of_accounts].members,100,LEAVES) } *
                   {[plan_exchange_rates].[plan_exchange_rates].[local] } *
                   {Descendants([plan_lines].[plan_lines].members,100,LEAVES) }
                   on 0, 
                   {[plan_time].[plan_time].[Dec-2004]} on 1 
                   FROM [plan_BudgetPlanLineItem]
                   """

        data = tm1source.data.execute_mdx(mdx1, cell_properties=['Value'])

        values = [cell['Value'] for cell in data.values()]

        tm1target.data.write_values_through_cellset(mdx1, values)

       # this for loop returns 1 row when MDX1 is used and that data does move to
       # the target server. Using MDX2 returns 13 rows but the values listed do not appear
       # in the target server
        for x in data.values():
            print(x['Value'])

```
Am I missing something?
Thank you for your help!

**Comment by jbeanz23** [comment]
hi @jimnaff 
Did you try changing your top 2 "with" statements to:
tm1source = TM1Service(**config['tm1srv01'])
tm1target = TM1Service(**config['tm1srv02'])

Then execute against the mdx from the source like:
data = tm1source.data.execute_mdx(mdx)

values = [cell['Value'] for cell in data.values()]

tm1target.data.write_values_through_cellset(mdx, values)

**Comment by jimnaff** [comment]
I tried your suggestion but I am seeing the same results.  
Yes, I am trying to use the cube to cube sample. 
I added a screenshot of the source cube on the left and the target on the right as an attachment.

[planning sample.pdf](https://github.com/cubewise-code/tm1py/files/3644983/planning.sample.pdf)

**Comment by jbeanz23** [comment]
Is the version on top?  You are just wanting FY 2004 Budget?

**Comment by jimnaff** [comment]
They are just 2 different MDX statements I am testing with. They both return data in the for-loop.
Using MDX1 returns just one row of values: 88. MDX2 returns:
3333333
500
3000
750
3000
3000
1500
7000
3000
88
2
350
5000

It must be something I am overlooking. I will keep at it. Thank you for the quick responses!

**Comment by jbeanz23** [comment]
Try this one and see if it gives you the results  you are expecting
[pypal git.zip](https://github.com/cubewise-code/tm1py/files/3645090/pypal.git.zip)

**Comment by jimnaff** [comment]
Thank you, that worked. It looks it's due to your MDX statement using :
{ TM1FILTERBYLEVEL( { Tm1subsetAll( [plan_department] ) } , 0) }
vs mine using:
{Descendants([plan_department].[plan_department].members,100,LEAVES)}

I have another question. I would like to use write_values_through_cellset with data.values() 'RuleDerived' = false only so I avoid 'Rule Applies to Cell' errors. I have been able to filter data.values() with this:
   # mdx5 you see below refers to a MDX statement that included rule based values.
   data = tm1source.data.execute_mdx(mdx5, cell_properties=['Value', 'RuleDerived'])
   values = [cell['Value'] for cell in data.values() if cell['RuleDerived'] == False]
But, then this:
  tm1target.data.write_values_through_cellset(mdx5, values)

will cause this error: CubeCellWriteStatusRuleApplies

I wonder if this is happening because 'mdx5' no longer matches 'values' in since with the rule based values filtered out.
Do you know of a way use write_values_through_cellset and avoid CubeCellWriteStatusRuleApplies error?

**Comment by jbeanz23** [comment]
I would think setting it to 'Rule derived' would pull only rule derived cells.  Could you try removing that from cell_properties but leaving in the if cell['RuleDerived'] == False] to see if you then skip ruled cells?

**Comment by jimnaff** [comment]
Thank you, I tried this:
  data = tm1source.data.execute_mdx(mdx5, cell_properties=['Value'])
  values = [cell['Value'] for cell in data.values() if cell['RuleDerived'] == False] ** this is line 74 

but I see this error:

**Traceback (most recent call last):
  File "C:/Cubewise/tm1py-samples-master/Administration/GetCubeData.py", line 74, in <module>
    values = [cell['Value'] for cell in data.values() if cell['RuleDerived'] == False]
  File "C:/Cubewise/tm1py-samples-master/Administration/GetCubeData.py", line 74, in <listcomp>
    values = [cell['Value'] for cell in data.values() if cell['RuleDerived'] == False]
KeyError: 'RuleDerived'**

It appears that 'RuleDerived' needs to be included for cell_properties?

**Comment by jbeanz23** [comment]
and when you dont use it at all in cell properties or  in the write values portion it writes over rule derived cells?  So the 2 instances are not in sync?

**Comment by jimnaff** [comment]
Based on a comment I see in the definition for 'write_values_through_cellset':

"Cellset gets created according to MDX Expression"

The link for the class is here:
https://github.com/cubewise-code/tm1py/blob/929930d76c63a8dae4eb8bee20cca5738c91ff95/TM1py/Services/CellService.py

I wonder if the cellset size no longer matches to the values size when rule derived values are filtered out?

**Comment by jimnaff** [comment]
Since 'write_values_through_cellset' calls 'self.update_cellset(cellset_id=cellset_id, values=values)',
perhaps I need to create the cellset_id without the rule derived tuples and then call update_cellset?

**Comment by jbeanz23** [comment]
That's something to try. I have not ever had to filter on ruled cells yet so i would be interested to know if that works.

**Comment by jimnaff** [comment]
It will return this when RuleDerived is included in cell_properties:
{'Value': 444, 'RuleDerived': False}
{'Value': 557.7889447236181, 'RuleDerived': True}

I then filter out 'RuleDerived': True with this:
values = [cell['Value'] for cell in data.values() if cell['RuleDerived'] == False]

I will try later today to create a matching cellset_id.

Thanks again for you help, much appreciated!

**Comment by jbeanz23** [comment]
did you try moving the if:
values = [cell['Value'] for cell in data.values()]
 if cell['RuleDerived'] == False:
    tm1target.data.write_values_through_cellset(mdx5, values)

**Comment by jimnaff** [comment]
'cell['RuleDerived'] == False' becomes unresolved when used its own if statement.

**Comment by jbeanz23** [comment]
hmm...I will try looking at this later.  I have planning sample just need to set up another.  If you come across a solution let me know.  I have not used the 'Rule Derived' property before.

**Comment by jimnaff** [comment]
I have this working. Not sure how it would scale.

import configparser

import TM1py
from TM1py.Services import TM1Service

config = configparser.ConfigParser()
config.read(r'..\config.ini')

tm1source = TM1Service(**config['tm1server01'])
tm1target = TM1Service(**config['tm1server02'])

mdx = """
        SELECT 
        NON EMPTY { TM1FILTERBYLEVEL( { Tm1subsetAll( [plan_business_unit] ) } , 0) } *
        { TM1FILTERBYLEVEL( { Tm1subsetAll( [plan_department] ) } , 0) } *
        { TM1FILTERBYLEVEL( { Tm1subsetAll( [plan_Lines] ) } , 0) } *
        { TM1FILTERBYLEVEL( { Tm1subsetAll( [plan_chart_of_accounts] ) } , 0) }  *
        { TM1FILTERBYLEVEL( { Tm1subsetAll( [plan_exchange_rates] ) } , 0) } * 
        {[plan_version].[FY 2004 Budget]} on ROWS, 
        NON EMPTY {[plan_time].[Dec-2004]} on COLUMNS 
        FROM [plan_BudgetPlanLineItem]
        """

data = tm1source.data.execute_mdx(mdx, cell_properties=['Value','RuleDerived'])
mdxdata = {key:value for (key,value) in data.items() if value['RuleDerived'] == False}
tm1sourcedata = {}
for key, value in mdxdata.items():
     tm1sourcedata[TM1py.Utils.element_names_from_element_unique_names(key)] = value['Value']

tm1target.cubes.cells.write_values('plan_BudgetPlanLineItem', tm1sourcedata)

tm1source.logout()
tm1target.logout()

**Comment by jbeanz23** [comment]
Oh that's great.  I was playing around with it last night but could not get it to work.

**Comment by MariusWirtz** [comment]
Hi @jimnaff ,

a problem you had in the inital script was that you were using zero suppression on the source and the target "**grid**".
Thus, it is unlikely that the resulting cellsets from the MDX executions will have the same shape (meaning number of rows and columns). I guess this is why the writing failed (and because of the rule derved cells I suppose).

The code you posted in your last response should be working. However it is using the `write_values` method which is significantly slower than the `write_values_through_cellset` method (due to internals of the API).
If you need to speed it up, you can generate a custom MDX (with tuples on the rows and one dimension on the column) from the `tm1sourcedata` object that you have available. Kinda like this:

``` MDX

SELECT 
([dim1].[elem4], [dim2].[elem8], [dim3].[elem2]), 
([dim1].[elem3], [dim2].[elem1], [dim3].[elem8]), 
([dim1].[elem2], [dim2].[elem9], [dim3].[elem7])
... ON ROWS,
{[dim4].[elem7]} ON COLUMNS
FROM [cube1]

```
With that MDX statement and the values from the `tm1sourcedata` dictionary, you can use the `write_values_through_cellset` method.

Also, parallelizing the write operations allows you to speed up the writing to the TM1 cube.

**Comment by jimnaff** [comment]
Thank you Marius. My goal was to get a dataset of leaves, then write them to another TM1 server avoiding "Rule applies to cell' errors. I don't know of a way for the MDX statement to do that. Is there are way to use write_values_through_cellset and avoid these errors?

**Comment by MariusWirtz** [comment]
Hi @jimnaff ,

Not really. As laid out above, I would suggest to build a new MDX query, after you filtered out the cells, that are not rule derived.

However, I could only think of one rather bold way to write (without pre-checking) and not getting this error.
You could temporarily deactivate the rule before writing. After you are done writing you could reactivate the rule. 
Whether this is a viable approach really depends on your situation and I would not necessarily advice you to do it. If you do it make sure you wrap the write statement into a `try` block and do the reactivation in the `finally` block.

**Comment by jimnaff** [comment]
Thank you Marius. I think writing the MDX statement that only returns data that are not rule derived would be a challenge. Deactivating a rule sounds interesting but not sure if this is feasible.

**Comment by MariusWirtz** [comment]
Hi @jimnaff,

I see. 

It's actually not the first time that a I am asked for a write operation that would skip rule derived cells (or yield minor errors) without aborting the full write operation.
It's up to IBM to provide this kind of write mode through the REST API. 

Another alternative for you case would be to write the cells that you want to update from python into a csv instead of straight to the cube. Then when you are done with this, you can execute a TI process from python that parses the csv file and writes it to the cube. In this TI process you would first do the `CellIsUpdateable `check and then the `CellPutN`
