### ISSUE TITLE
How to reuse thread ID

### ISSUE THREAD

**Issue by user1493** [cubewise-code/tm1py#176]
I have two method to get the cubes and get the  dimensions:

Initially I call **cubes()** and then **dim()**. 

1. Is it possible to reuse the **thread ID** which was created during the call **cubes()**?
2. Calling these methods multiple times creates new threads (with new thread ID).. will this cause any issue?

```
def cubes(self):
    with TM1Service(address=address, port=port, user=user,
                    password=password, namespace=namespace, ssl=ssl, gateway=gateway) as tm1:
        print(tm1.cubes.get_all_names())


def dim(self):
    with TM1Service(address=address, port=port, user=user, password=password,
                    namespace=namespace, ssl=ssl, gateway=gateway) as tm1:
        print(tm1.dimensions.get_all_names())
```

**Comment by user1493** [comment]
Just now saw this thread about using Pickle.... this thread solved my issue with **threads**
https://github.com/cubewise-code/tm1py/issues/176#issue-497637567

**Comment by rclapp** [comment]
I recommend that you explore the tm1py samples. https://github.com/cubewise-code/tm1py-samples
In your case you have too many with statements.




On Sep 25, 2019 9:33 AM, user1493 <notifications@github.com> wrote:

I have two method to get the cubes and get the dimensions:

Initially I call cubes() and then dim().

  1.  Is it possible to reuse the thread ID which was created during the call cubes()?
  2.  Calling these methods multiple times creates new threads (with new thread ID).. will this cause any issue?

def cubes(self):
    with TM1Service(address=address, port=port, user=user,
                    password=password, namespace=namespace, ssl=ssl, gateway=gateway) as tm1:
        print(tm1.cubes.get_all_names())


def dim(self):
    with TM1Service(address=address, port=port, user=user, password=password,
                    namespace=namespace, ssl=ssl, gateway=gateway) as tm1:
        print(tm1.dimensions.get_all_names())

**Comment by cubewise-tryan** [comment]
Hi @user1493,

You need reuse the TM1Service instead of creating a new one in each method.
