### ISSUE TITLE
Using TM1py connection, anyway I can see the Context on Pulse/TM1Top

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/tm1py#178]
**Describe what did you try to do with TM1py**
We may have many TM1py scripts running at the same time on the server, at the moment, they are not able to identify the purpose when reading it from TM1Top or Pulse.

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. Similar to Arc for TM1, we can pass some description to further describe the action when running scripts via TM1py.

![image](https://user-images.githubusercontent.com/43463864/65739264-361edb00-e117-11e9-867c-2531a6c02441.png)

**Version**
- TM1py [1.3.1] 
- TM1 Server Version: [11.7]

**Comment by jbeanz23** [comment]
Hi Tat
I have TM1 server version 11.5 on my laptop and I am able to see TM1Py in the session context when running  a script so maybe it is related to TM1 server version 11.7.  I can also confirm at a client I am working on they are able to see this in the context for TM1 server version 11.4.

![TM1py context](https://user-images.githubusercontent.com/8358847/65740808-dab10680-e09e-11e9-847c-9b6c0d6176db.png)

**Comment by cubewise-tryan** [comment]
Hi @jbeanz23,

I think @tatwong wants a custom context that he can set rather a generic one for all TM1Py connections.

**Comment by jbeanz23** [comment]
Oh, my bad :)

**Comment by MariusWirtz** [comment]
Hi @tatwong,

when you instantiate the `TM1Service`, you can pass the optional argument `session_context` with the value that you would like to see in Pulse, TM1top.

here is a sample:
https://github.com/cubewise-code/tm1py-samples/blob/master/Administration/session_custom_context.py
