### ISSUE TITLE
Login fails when password contains single quote

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#181]
TM1py fails to connect when password contains a single quote.

**Comment by pgrocholacubewise** [comment]
Hi Marius

Customer gave another example of problematic password:

We have a password that was similar as below but didn’t work. Can you look into it? Basically, ?: seems to be an issue. 
d8!?:Y4

**Comment by MariusWirtz** [comment]
Hi @pgrocholacubewise,

I added a test for this case. https://github.com/cubewise-code/tm1py/pull/195
With my local installation of TM1 (11.6.00000.14) I can not replicate this issue.

I suppose it was an issue in TM1 and got solved in a more recent PA release.
