### ISSUE TITLE
Get Application Name

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/tm1py#183]
**Describe what did you try to do with TM1py**
Tried to look for code to get the name of the application or blob name that is displaying on TM1Web, but couldn't find the relevant code.

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. A property to get the name of the application.

**Version**
- TM1py [e.g. 1.3.1] 
- TM1 Server Version: [e.g. 11.4]

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by MariusWirtz** [comment]
Hi @tatwong ,

you can retrieve the elements from }applications dimension. Here is a sample:

``` python
from TM1py import TM1Service

ADDRESS = '14.77.19.11'
PORT = 12354
USER = 'admin'
PASSWORD = 'apple'
SSL = True

with TM1Service(address=ADDRESS, port=PORT, user=USER, password=PASSWORD, ssl=SSL) as tm1:
    apps = tm1.dimensions.hierarchies.elements.get_element_names(
        dimension_name="}ApplicationEntries",
        hierarchy_name="}ApplicationEntries")
    for app in apps:
        print(app)

```
