### ISSUE TITLE
SSLError Bad handshake

### ISSUE THREAD

**Issue by anamariamocanu** [cubewise-code/tm1py#187]
Hi there,

I am running the python script on both a server that I can RDP to the tm1 server and the tm1 server itself. My most recent error is this: 
Max retries exceeded with url: /api/v1/Configuration/ProductVersion/$value (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')")))

Any thoughts into why this is happening?

I got the latest Anaconda Distribution, and use Windows server.

Thanks a lot!
Ana

**Comment by rclapp** [comment]
I have the same issue when using anaconda and SSO.

**Comment by MariusWirtz** [comment]
Hi @anamariamocanu ,

Are you sure the TM1 REST API is accessible from where python runs ? 
Try to access the TM1 REST API from the python machine with postman or chrome. Try this request:
`<<HTTP-OR-HTTPS>>://<<ADDRESS>>/<<HTTPPortNumber>>/api/v1/$metadata`

Does it work?

**Comment by anamariamocanu** [comment]
Hi @MariusWirtz 

It should be accessible, we changed the http port number accordingly, unless there's something else to look into?
If I try the metadata URL it works, I get the xml structure. But I can't access the cubes nor run TM1Service using TM1py :(

Using ssl= False I am now not getting any error - the script tries running and nothing happens. Also checked firewalls and that's not the issue.

Thanks for your help!
Ana

**Comment by MariusWirtz** [comment]
Hi @anamariamocanu ,

I assume, that after you switched the UseSSL paramter on the TM1 side to false, you also made an adjustment in the python code. Correct ?

Perhaps there is an issue with your python installation as @rclapp suggested. Try to uninstall Anaconda and install plain python 3 + TM1py (with pip if possible).

Cheers,

Marius

**Comment by rclapp** [comment]
Chances are this is an anaconda problem. I eventually got it to work, but my notes are a bit incomplete. Some high level points:

1) use a virtual conda environment this seemed to help
2) install what you can from conda forge
3) remove certfi and re-install it (it seems like its broken in the base conda install)
4) (annoying part) remove regular python from your PATH variables



Ryan Clapp
AWS Business Systems
Sr. Manager

Sent from my mobile device

On Nov 24, 2019 12:19 PM, Marius Wirtz <notifications@github.com> wrote:

Hi @anamariamocanu<https://github.com/anamariamocanu> ,

I assume, that after you switched the UseSSL paramter on the TM1 side to false, you also made an adjustment in the python code. Correct ?

Perhaps there is an issue with your python installation as @rclapp<https://github.com/rclapp> suggested. Try to uninstall Anaconda and install plain python 3 + TM1py (with pip if possible).

Cheers,

Marius

-

**Comment by anamariamocanu** [comment]
@MariusWirtz  that is correct, changed SSL=false in the python script

@rclapp  thank you for your notes! I will try to install python and tm1py on top of it. The problem is that conda and pip commands are blocked in our corporate environment. So the only way (that I know) for me to install tm1py is using the whl file.

**Comment by rclapp** [comment]
If you're not using conda for a reason (fbprophet for example) I would avoid it. If you clone tm1py locally you can just run 'python setup.py install'.

I would also double check certifi is installed too. You can test general ssl by using requests to get https://google.com

If your using SSO via cam, be sure requests-negotiate-spin is also installed.


Ryan Clapp
AWS Business Systems
Sr. Manager

Sent from my mobile device

On Nov 24, 2019 4:10 PM, Ana <notifications@github.com> wrote:

@MariusWirtz<https://github.com/MariusWirtz> that is correct, changed SSL=false in the python script

@rclapp<https://github.com/rclapp> thank you for your notes! I will try to install python and tm1py on top of it. The problem is that conda and pip commands are blocked in our corporate environment. So the only way (that I know) for me to install tm1py is using the whl file.

-

**Comment by anamariamocanu** [comment]
Thanks @rclapp  -  I tried your steps and didn't work with the Anaconda install. We use anaconda for the data science capability - the purpose of accessing the data from tm1 is to integrate it with other data sources and do financial modelling, using libraries like pandas and sklearn.

I'll try with basic python - a workaround would be use tm1 APIs on one server and data merging / ML on another, which is not ideal.

**Comment by rclapp** [comment]
Okay, your last message made it seem like conda was blocked. Are you using Cam SSO?

Ryan Clapp
AWS Business Systems
Sr. Manager

**Comment by anamariamocanu** [comment]
Sorry, I can see how I got you confused - yes we use anaconda but packaged as standard, and we install other packages and their dependencies from wheels. I'll check on the Cam SSO and let you know.

**Comment by rclapp** [comment]
Got it. Are you passing a user name and password?

If your trying to connect via cam gateway (kerberos SSO; no user name and password), SSL can be a little bit of a challenge.

Ryan Clapp
AWS Business Systems
Sr. Manager

Sent from my mobile device

On Nov 25, 2019 12:09 AM, Ana <notifications@github.com> wrote:

Sorry, I can see how I got you confused - yes we use anaconda but packaged as standard, and we install other packages and their dependencies from wheels. I'll check on the Cam SSO and let you know.

-

**Comment by anamariamocanu** [comment]
@rclapp I am logging in with a username and password. IntegratedSecurityMode=2 in the cfg file, does that mean I have so set up CAM authentication?

Latest error is 503 Service unavailable or code freeze.

**Comment by anamariamocanu** [comment]
All sorted now, thanks lots for the help @MariusWirtz  and @rclapp . Turns out I was using wrong the port number. Everything is fine with the anaconda install and the package itself.
