### ISSUE TITLE
How to generate TI process with TM1py

### ISSUE THREAD

**Issue by yyucresco** [cubewise-code/tm1py#189]
Hi, there!

I can manually add prolog of TI process, such as: 

EXECUTECOMMAND()

May I know if there exist a function in TM1py to do this?

Thanks!

**Comment by MariusWirtz** [comment]
Hi @yyucresco ,

I understand that you would like to add a line of code to the prolog of an existing ti process. Is that correct?
Yes. That's no problem with TM1py.

**Comment by yyucresco** [comment]
May I know the related command or module?

How about creating a new TI process? 

Thanks for the reply!

**Comment by MariusWirtz** [comment]
Here is a sample how to update a process:
https://github.com/cubewise-code/tm1py-samples/blob/master/Metadata/process_update.py

Here is a sample how to create a new process:
https://github.com/cubewise-code/tm1py-samples/blob/master/Metadata/process_create.py

the `prolog`, `metadata`, `data` and `epilog` properties of the `Process` object are just strings. 
So you can just add a new line to it.

**Comment by yyucresco** [comment]
Thanks a lot!
Will follow the example!
