### ISSUE TITLE
Transaction log query takes longer time

### ISSUE THREAD

**Issue by user1493** [cubewise-code/tm1py#204]
Hi Marius,

I was working with transaction log query. But the response being received takes more time (from  5 - 10 minutes). 
1. Does the response time depend on the no. of days and the volume of logs being queried?
2. Will the server plough through the physical log files in the log folder to create the response? 
     Which means larger log files will take longer time?

**Version**
- TM1py 1.3.1
- TM1 Server Version: 11.4

**Comment by MariusWirtz** [comment]
Hi @user1493 ,

yes. The TM1 server is actually parsing through all log files in the log directory on the server. You can read more about it here:
https://community.ibm.com/community/user/businessanalytics/communities/community-home/digestviewer/viewthread?MessageKey=3ea394b9-19b1-4a46-953f-2368ecfb0dd6&CommunityKey=8fde0600-e22b-4178-acf5-bf4eda43146b&tab=digestviewer#bm3ea394b9-19b1-4a46-953f-2368ecfb0dd6

I think the big driver for query speed on transactionlog queries is the volume of transactions in the tm1s log files in the log directory. I think it is a good practice to move old tm1s log files from the directory.

**Comment by user1493** [comment]
Thanks for your response, then I guess loading the log files directly using the client (python) could be much faster instead of using REST API.

Your thoughts..

**Comment by MariusWirtz** [comment]
Hi @user1493, 

you mean parsing the tm1s log files yourself with python ? 
I don't think that's a viable alternative. I think you can't access the current tm1s file at all when the TM1 Server is still writing to it.

**Comment by user1493** [comment]
Yeah, tm1s file cannot be accessed using Python. I would only be able to access the other files.

Closing this loop, thanks for your comments.
