### ISSUE TITLE
How to properly copy processes between servers?

### ISSUE THREAD

**Issue by luiz-gr** [cubewise-code/tm1py#208]
**Describe what did you try to do with TM1py**
Copied a process from dev server and updated the same process in the prod server.

```
with TM1Service(**config['Server_A']) as tm1:
    p1 = tm1.processes.get('Dim_Info')

with TM1Service(**config['Server_B']) as tm1:
    tm1.processes.update(p1)
```

**Describe what's not working the way you expect**
Everything worked as expected except the DataSource (ODBC)'s password field that was updated to something else not the real password, did I do something wrong?

**Version**
- TM1py 1.3.1
- TM1 Server Version: 11.5.0.23
- DEV: Windows Server 2016
- PROD: WIndows Server 2012 R2

**Comment by MariusWirtz** [comment]
Hello @luiz-gr ,

If you want to do hot deployments you should check out Pulse.
In cubewise, we developed a dedicated solution for hot deployments, change-tracking, and general application monitoring and more!
You can read more about it here: https://code.cubewise.com/pulse-overview/

The problem with TM1py is that the TM1 API does not return the actual password, of the process, to python.

There are two potential solutions to your problem I think.
- You can use integrated login on the SQL side and have the TM1 (windows) Service running with an account that can access the DB.

- Alternatively, you could store credentials in a parameter cube (of course you need to make sure only admin users can access that cube) and update the implicit variables `DatasourceUsername` and `DatasourcePassword` in the prolog tab of the process.
https://www.ibm.com/support/knowledgecenter/SS9RXT_10.1.0/com.ibm.swg.ba.cognos.tm1_ref.10.1.0.doc/c_turbointegratorlocalvariables_n80019.html

It would be good though if we could handle this situation properly in TM1py.
Can you please try the following
- Please comment out 431 in the `Objects/Process.py` file 
- rerun the code that updates a process 
Ideally, the password of the updated process should not have changed.
