### ISSUE TITLE
Value Error while using execute_mdx_ui_array

### ISSUE THREAD

**Issue by wifi1677** [cubewise-code/tm1py#213]
**Describe the bug**
Getting the below error while using all the array functions for mdx. please take a look at the error. 

`    raw_data = _tm1.cubes.cells.execute_mdx_ui_array(mdx)
  File "/var/uber/python/lib64/python3.6/site-packages/TM1py/Services/CellService.py", line 617, in execute_mdx_ui_array
    return Utils.build_ui_arrays_from_cellset(raw_cellset_as_dict=data, value_precision=value_precision)
  File "/var/uber/python/lib64/python3.6/site-packages/TM1py/Utils/Utils.py", line 175, in build_ui_arrays_from_cellset
    row.append(float(value_format_string.format(raw_value)))
ValueError: Unknown format code 'f' for object of type 'str'`

**To Reproduce**
Just any mdx should be fine , i tried multiple different mdx 

**Expected behavior**

**Version**
TM1py [e.g. 1.3.1]
TM1 Server Version: [e.g. 11.4]

**Additional context**

**Comment by MariusWirtz** [comment]
Hi  @wifi1677, 

it was @DJHig who originally added this function to TM1py. The way I see it, it is designed to work with numeric data only.
Are you perhaps using it on string data?
