### ISSUE TITLE
Method to get default member of a hierarchy fails in case the hierarchy is empty

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/tm1py#218]
**Describe the bug**
Method get_default_member() of HierarchyService class will fail with 404 error in case the hierarchy being queried contains no elements. The error contents is as follows:
```
b'{"error":{"code":"278","message":"\'Name\' resource can not be resolved on type \'Member\'."}}'
``` 
**To Reproduce**
Have a hierarchy without any elements in it and issue get_default_member on it.

**Expected behavior**
The method call should succeed but None should be returned as a result.

**Version**
TM1py commit cf1c584
TM1 Server Version: 11.6.00000.14

**Additional context**
NA

**Comment by MariusWirtz** [comment]
Hi @pbuncik ,

thanks for the catch! It should be fixed with the latest commit. Please double check

**Comment by pbuncik** [comment]
Confirming - feature now works as expected. Thank you for a prompt fix.
