### ISSUE TITLE
Create a view with TM1py

### ISSUE THREAD

**Issue by mac0323** [cubewise-code/tm1py#219]
Hi, there!

I am using TM1py to read a csv file and create a view for the cube. 

I am following the Cubike example and have the view code as follows: 

```python
_view_name = 'Default'
_view_rows = [ViewAxisSelection(_row_dim_name, AnonymousSubset(_row_dim_name, _row_hier_name, _row_select_line))]
_view_cols = [ViewAxisSelection(_col_dim_name, AnonymousSubset(_col_dim_name, _col_hier_name, _col_select_line))]
_view_titles = [ViewTitleSelection(_measures_dim_name, AnonymousSubset(_measures_dim_name),'M')]

_view = NativeView(_cube_name, _view_name, rows=_view_rows, columns=_view_cols, titles=_view_titles, format_string="####")
if tm1.cubes.views.exists(_cube_name, _view_name)[1]:
    tm1.cubes.views.update(_view, False)
else:
    tm1.cubes.views.create(_view, private=False) 
```

The cube is created and view is created. But I need to recalculate in the archtecture. 

Is there anything I miss in creating view?

Thanks for the help!

Yang

**Comment by MariusWirtz** [comment]
Hi @mac0323,

I am not sure I understand the question right.
What are you expecting the code to do other than creating a cube view? 
Are you saying that you want the view to be in auto-calc mode?

**Comment by mac0323** [comment]
Hi, 

Thanks for the reply! 

Yes. 

Is there a way to do that?

**Comment by MariusWirtz** [comment]
Hi,

no. Unfortunately not. 
In the TM1 REST API there is no "auto-calc-mode" property on a cube view.
The Architect is using the old C API. Sometimes the two APIs have slightly different features.

**Comment by mac0323** [comment]
I see, thank you!
