### ISSUE TITLE
Multi server administration

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#225]
When you try to administrate multiple tm1 servers it would be great to have a function to just call a list of admin servers and iterate over the registered instances.

**Comment by rclapp** [comment]
You can do that via the Utils module. I have some sample code you can start from here

https://github.com/rclapp/PythonSamplesForTM1/blob/master/Connection_Samples.py

Ryan Clapp
AWS Business Systems
Sr. Manager

Sent from my mobile device

On Apr 23, 2020 2:06 PM, Christoph Hein <notifications@github.com> wrote:

When you try to administrate multiple tm1 servers it would be great to have a function to just call a list of admin servers and iterate over the registered instances.

-

**Comment by scrumthing** [comment]
Thanks for that @rclapp. I will look into that.

**Comment by MariusWirtz** [comment]
@scrumthing if you build something that's applicable generically, please create a MR into TM1py. Perhaps it could go into the `Utils` module 🤔

**Comment by scrumthing** [comment]
@MariusWirtz Will do so but let me first improve it a bit more. :-)

**Comment by scrumthing** [comment]
@rclapp Thanks for your example. Helped me a lot. I will keep on improving my Python. You guys are way more sophisticated.
