### ISSUE TITLE
How to add element Attribute (alias) values

### ISSUE THREAD

**Issue by srinivas1703** [cubewise-code/tm1py#230]
**Describe what did you try to do with TM1py**
Hello Team,
I am starting my journey into tm1py, however I have  been facing difficulties to add element Attribute(alias) values.
Dimension is created and not to update alias values. below is the script.
Can you please provide sample script to add alias values.
I had referred the script with this URL

**https://github.com/cubewise-code/tm1py/blob/master/Tests/Element.py**

DIMENSION_NAME = 'Dummy_Year'
    HIERARCHY_NAME = DIMENSION_NAME
    years = ("1989", "1990", "1991", "1992")
    attributes = ('Previous Year', 'Next Year')
    alias_attributes = ("Financial Year",)
    d = Dimension(DIMENSION_NAME)
    h = Hierarchy(DIMENSION_NAME, HIERARCHY_NAME)
    h.add_element('Total Years', 'Consolidated')
    h.add_element('All Consolidations', 'Consolidated')
    h.add_edge("All Consolidations", "Total Years", 1)
    for year in years:
        h.add_element(year, 'Numeric')
        h.add_edge('Total Years', year, 1)
    for attribute in attributes:
        h.add_element_attribute(attribute, "String")
    for attribute in alias_attributes:
        h.add_element_attribute(attribute, "Alias")
    d.add_hierarchy(h)
    tm1.dimensions.create(d)
tm1.cubes.cells.write_value('1988/89', '}ElementAttributes_' + DIMENSION_NAME, ('1989', 'Financial Year'))
    tm1.cubes.cells.write_value('1989/90', '}ElementAttributes_' + DIMENSION_NAME, ('1990', 'Financial Year'))
   
**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. With the above script i am able to create dimension
2. But alias values are not created.

**Version**
- TM1py  -- 1.3.1] 
- TM1 Server Version: PA 2.0.7

**Additional context**
Error Message:
 tm1.cubes.cells.write_value('1988/89', '}ElementAttributes_' + DIMENSION_NAME, ('1989', 'Financial Year'))

  File "C:\Anaconda3\lib\site-packages\TM1py\Services\CellService.py", line 148, in write_value
    return self._rest.POST(request=request, data=data)

  File "C:\Anaconda3\lib\site-packages\TM1py\Services\RESTService.py", line 40, in wrapper
    self.verify_response(response=response)

  File "C:\Anaconda3\lib\site-packages\TM1py\Services\RESTService.py", line 277, in verify_response
    raise TM1pyException(response.text, status_code=response.status_code, reason=response.reason)

TM1pyException: Text: {"error":{"code":"278","message":"'1989' can not be found in collection of type 'Element'."}} Status Code: 404 Reason: Not Found

Thanks & regards,
Srinivas

**Comment by MariusWirtz** [comment]
Hello @srinivas1703,

I ran the script on my environment and it created and populated the Alias attributes without issues.
I noticed that your TM1py version is a bit outdated. Perhaps just try to upgrade to a more recent version.
You can upgrade to the current master branch:
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`
or to the latest release (1.4.1):
`pip install tm1py --upgrade`

![image](https://user-images.githubusercontent.com/15182131/80461735-03032b00-8936-11ea-9ca7-d592cc02c0dc.png)

**Comment by srinivas1703** [comment]
Hi MariusWirtz,

After update TM1py, its working fine.
Thanks a lot for your support.

Best Regards,
Srinivas.
