### ISSUE TITLE
MdxUtils Deprecation

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#233]
The `MdxUtils` module in TM1py contains code that is not fully thought through. It needs to be refactored or removed.

There are essentially two topics that this module tries to address.
The first topic is to understand the dimensional composition from an MDX query.
Unfortunately, the code is not bug-free and due to exotic MDX functions like `GENERATE`, it is not a feasible approach to parse the MDX, IMO.

The second topic is to construct MDX queries with code.
The approach we choose here is not elegant. I have published a substitution for this topic: [mdxpy](https://github.com/cubewise-code/mdxpy). It is more elegant and way more powerful, IMO.

My suggestion would be to remove the `MdxUtils` module from TM1py. 
Is anybody actually using the `MdxUtils` module? If yes, are you okay to switch to `mdxpy` to generate MDX?

**Comment by cubewise-tryan** [comment]
Hi @MariusWirtz,

I think the best of action would be to mark it as deprecated and give people time to refactor before it is removed.

**Comment by MariusWirtz** [comment]
Hi @cubewise-tryan, 
OK. So we depreciate it with the next release.

**Comment by MariusWirtz** [comment]
Fixed with #238
