### ISSUE TITLE
tm1.dimensions.hierarchies.elements.get_element_names function

### ISSUE THREAD

**Issue by MaaYuu** [cubewise-code/tm1py#242]
Hello,
I am trying to get all leaf elements of a dimension and want to pull the source data for only those elements and skip the data for elements that are not in the element list.

For example, I tried this :
```
 a = tm1.dimensions.hierarchies.elements.get_leaf_element_names(dimension, hierarchy)
print(a)
```
and I am expecting a list but it returns 

`<generator object ElementService.get_element_names.<locals>.<genexpr> at 0x0000017938BDAA48>`

How I can print the element names as a list?

Regards.

**Version**
- TM1py [1.4.1] 
- TM1 Server Version: [PA 2.0.7]

**Comment by MariusWirtz** [comment]
Hi @MaaYuu,

the function returns a generator.
https://wiki.python.org/moin/Generators

If you need a `list` instead just write: 
```
a = list(tm1.dimensions.hierarchies.elements.get_leaf_element_names(dimension, hierarchy))
```
