### ISSUE TITLE
JSONDecodeError while trying to get data

### ISSUE THREAD

**Issue by donny-jo** [cubewise-code/tm1py#249]
Hi, 

I'm facing an issue with execute_view_dataframe_pivot. So i have my TM1 instance running on cloud machine, and i install and do some code using jupyter on the same machine. Here is the code.

ADDRESS = "localhost"
PORT = 5060
USER = "admin"
PWD = "123123"
SSL = False

tm1 = TM1Service(address=ADDRESS, port=PORT, user=USER, password=PWD, ssl=SSL)

cube = 'Source Cube'
view = 'Datasource'

table = tm1.cubes.cells.execute_view_dataframe_pivot(
    cube,
    view,
    private=False)

This code run perfectly. I got the data in pandas format.

But, when i try to run the same code from my laptop also with jupyter, it give JSONDecodeError message. I've change the host to my server ip address. So, the initial setup connection is executed successfully, but when the code run the execute_view_dataframe_pivot part. It gives the error. 

Here is the error trace

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-9-b2bd21299676> in <module>
      7     private=False,
      8     dropna=False,
----> 9     fill_value=None
     10     )

C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Services\CellService.py in execute_view_dataframe_pivot(self, cube_name, view_name, private, dropna, fill_value)
    396         :return:
    397         """
--> 398         cellset_id = self.create_cellset_from_view(cube_name=cube_name, view_name=view_name, private=private)
    399         return self.extract_cellset_dataframe_pivot(
    400             cellset_id=cellset_id,

C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Services\CellService.py in create_cellset_from_view(self, cube_name, view_name, private)
    891             cube_name=cube_name,
    892             views='PrivateViews' if private else 'Views', view_name=view_name)
--> 893         return self._rest.POST(request=request, data='').json()['ID']
    894 
    895     def delete_cellset(self, cellset_id):

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

------------------------ End Stack Trace ---------------------

I'm using TM1py version 1.4.1 and my TM1 version is 11.6. I'm still learning in python, but had few years experience in TM1. Thanks for kind help.

**Comment by MariusWirtz** [comment]
Hi @donny-jo,

could it be that you have different versions of pandas installed in these two setups?
You can find out by executing: `pip show pandas`

We haven't changed anything wrt to that function in the recent versions but it may help to upgrade to the latest version of TM1py (= the master branch here at GitHub).
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip`

One more thing:
From my personal experience, I would not advise to use pandas pivot tables. 
More than once we have monitored bad performance compared to normal data frames.

There are other ways to build data frames with TM1py:
if you upgrade to the latest version of you could use the `execute_view` / `execute_mdx` method from the `PowerBiService`.

``` python
with TM1Service(address=ADDRESS, port=PORT, ssl=SSL, user=USER, password=PASSWORD) as tm1:

mdx = """
SELECT {Tm1SubsetAll([}Clients])} ON 0, {TM1SubsetAll([}Groups])} on 1 FROM [}ClientGroups]
"""

data = tm1.power_bi.execute_mdx(mdx)

print(data)
```

It returns a data frame in the shape of the cube view but ignores the title selections and assumes there is only one dimension on the columns.


You can also use the `execute_view_dataframe` function from the `CellService` or use the `execute_view` method to create a dictionary and then use the `build_pandas_dataframe_from_cellset` method on the result to create a data frame.
Both functions return the data in a flat structure.

**Comment by donny-jo** [comment]
Hi @MariusWirtz ,

Sorry just to get back. 

I think i now why it doesn't work properly. 

tm1 = TM1Service(address=ADDRESS, port=PORT, user=USER, password=PWD, ssl=SSL)

the 'tm1' object above is still empty. Thats why the error said, it expect a value. Then i tried to restart my jupyter (even my laptop), and then try again... Then i got this error connection refuse error... I dont know why at first attempt i didn't get this error. 

Anyway, when i try to telnet the host using specified port for the tm1 instance, the port is listening. So, i don't know why the server is refusing the connection request from jupyter. Tried to run using python console and got same error.. So, right now i still try to figure out why the connection doesn't take place....

Thanks for your input regarding better way to grab the data from TM1. I'll give it a try.

Cheers

**Comment by MariusWirtz** [comment]
Hi @donny-jo,

I don't quite understand. What do you mean by 'empty'?

I would like to take a closer look at this.
Can you post the full code snippet and the error message that you get?

Cheers,

Marius

**Comment by rkvinoth** [comment]
@donny-jo I believe your laptop and the cloud machine are not using the same Network.

So you won't be able to connect to a TM1 instance running in your cloud machine.

Try running the same code via Python IDLE. you will be able to view the `ConnectionError`

**Comment by MariusWirtz** [comment]
@donny-jo did you find a solution to your problem? if yes, please post the solution here for future reference.
