### ISSUE TITLE
TransactionLog

### ISSUE THREAD

**Issue by PiotrRajtar** [cubewise-code/TM1py#25]
Hi,

The description mentions querying TransactionLog, but I cannot seem to find any Service that would provide it.

Am I missing something?

**Comment by MariusWirtz** [comment]
Hi Piotr,

I pushed it to the GitHub today with the release 0.1.3.

```
from TM1py import TM1Service

with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True) as tm1:
    entries = tm1.server.get_transaction_log_entries(reverse=True, user='Admin', scube='plan_BudgetPlan', top=2)
    print(entries)

```
The function get_gettransaction_log_entries now lives in the ServerService.

What excatly do you need it for?
Currently it supports filtering by cube name, user name und topcount. Do you need anything more sophisticated? - Like filtering by one element of a dimension?

User name and cube name are case sensitive in the transactionlog filter. I think this is an issue in the TM1 REST API. 

I push the release to PyPI tonight. You can upgrade through
`pip install TM1py –-upgrade `

**Comment by PiotrRajtar** [comment]
Hi Marius,

Thank you for adding it to the package.

I do not have any specific use case in mind at this moment, I was more intending to assess how it can be utilised for transaction log analytics. So on top of the provided filters, I think that a time stamp filter would be very useful.

However, I think you might be using a deprecated REST API function to query the transaction log judging by this Hubert's post: https://www.ibm.com/developerworks/community/forums/html/topic?id=81df0d11-0296-4a33-92c2-2fb450e9da30

**Comment by cubewise-tryan** [comment]
Just be aware when querying the transaction log, there isn't any "smarts" as yet so when adding a filter TM1 iterates through each line in the transaction log which can be slow.

**Comment by PiotrRajtar** [comment]
@cubewise-tryan, Thanks, that is good to know.

@MariusWirtz, Also, looking at Hubert's post there seems to be a way only to fetch new records since last query:

> This entity set has the added value that it supports deltas, allowing you to retrieve any new entries since the last time you queried.

 I think this might actually be even more useful than the actual time stamp filter - in light of what @cubewise-tryan is saying.

**Comment by MariusWirtz** [comment]
@PiotrRajtar 
thanks for the hint! 
Integration a Transaction log tracker into TM1py is on the roadmap ;)

**Comment by PiotrRajtar** [comment]
@MariusWirtz, 
Sounds great, is the road map available anywhere?

**Comment by MariusWirtz** [comment]
For the moment only in my head. Maybe we should make this more transparent. Anyways, if you have any feature requests feel free to open an issue.
