### ISSUE TITLE
Github vs pip?

### ISSUE THREAD

**Issue by dusherwo57** [cubewise-code/tm1py#257]
I am seeing some functions  eg cancel_all_running_threads which are present here on Github but not in the version which is installed via pip (on windows).  Can you advise how and when you update the latter?
**Version**
- TM1py 1.4.1
- TM1 Server Version: 11.7.00000.42

**Comment by MariusWirtz** [comment]
Hi  @dusherwo57,

you can upgrade to the current master on GitHub with pip like this:
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`

In early July we will publish the 1.5.0 release, then GitHub and PyPI will be back in sync.
