### ISSUE TITLE
Thread cancellation

### ISSUE THREAD

**Issue by dusherwo57** [cubewise-code/tm1py#258]
Mariusz, you may be interested in this.
[https://www.tm1forum.com/viewtopic.php?f=3&t=15377]

A TM1Forum user posted to the effect that using the Rest API (not explicitly TM1PY) users could cancel threads, even if they are not in Admin or OperationsAdmin.
From my testing, users _can_ cancel their own threads, even if they are not in either group. 
More a point for IBM, but FYI. I think the behaviour is fine and potentially useful.

**Version**
- TM1py 1.4.1
- TM1 Server Version: 

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by rkvinoth** [comment]
This is not something that is particular to **TM1py**. I have seen cases where we were not able to cancel certain threads from **ARC**, **PULSE** or even **TM1TOP**.

**Comment by rkvinoth** [comment]
> Indeed - but that was not the point I was making. The original forum post asserted that their (non TM1PY) Rest API code could cancel threads whether or not they were in the relevant groups (Admin or OperationsAdmin). I tested and found that not to be the case - but also found that a normal user can cancel their own threads. In fact the IBM reference he quotes is silent on that issue. David Usherwood | Associate | Email: david.usherwood@infocat.co.uk InfoCat, Unit 3.24 Canterbury Court, 1-3 Brixton Road, London, SW9 6DE Office Phone: 020 7735 7711 | Direct: 020 7390 0333 | Web: [www.infocat.co.uk](http://www.infocat.co.uk) Coronavirus Update - InfoCat is committed to supporting our customers during this difficult period. Click here to find out more. This message is private and confidential. If you have received this message in error, please notify us and remove it from your system. InfoCat Ltd. is a limited company registered in England. Registered number: 2843261. Registered office: Unit 3.24 Canterbury Court, 1-3 Brixton Road, London SW9 6DE From: Vinoth Kumar Ravi <notifications@github.com> To: cubewise-code/tm1py <tm1py@noreply.github.com> Cc: dusherwo57 <davidu@infocat.co.uk>, Author <author@noreply.github.com> Date: 25/06/2020 06:30 Subject: Re: [cubewise-code/tm1py] Thread cancellation (#258) This is not something that is particular to TM1py. I have seen cases where we were not able to cancel certain threads from ARC, PULSE or even TM1TOP. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Right, Initially I misunderstood the question. Later realized it and removed my comment. 
Anyway this looks like something IBM should look into.

**Comment by rkvinoth** [comment]
I performed a quick test:

1. User could view his/her threads only
2. User could cancel his/her threads only
3. User does not have access to use `disconnect user` method
