### ISSUE TITLE
'tm1.Update' resource can not be resolved on type 'Cube'

### ISSUE THREAD

**Issue by shallabhkhera** [cubewise-code/TM1py#26]
I'm receiving the error above  at tm1.cubes.cells.write_values(cube, cellset)

Any known pointers?

**Comment by MariusWirtz** [comment]
Which version of TM1 do you run? You need at least 10.2.2 FP 5.

**Comment by shallabhkhera** [comment]
Thanks :) I should have checked - sorry.
