### ISSUE TITLE
tm1py on iPad

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#260]
I tried installing tm1py on my iPad the other day. With the app “Pythonista” and the stash module you can use pip and install pure python modules. 
I tried it with tm1py and got the attached error message. Now I wonder If that is a deal breaker for tm1py on my iPad and if it is maybe a better solution to create a stripped down fork for the iPad or if even that is not a good solution. 

If you wonder about the use cases. It allows you to maintain your tm1 instances from your tablet. :-)

![image](https://user-images.githubusercontent.com/8442014/85939537-b11b5900-b916-11ea-848d-7c879318d425.jpeg)

**Comment by rclapp** [comment]
That specific package supports SSO on windows. You don't really need it unless your trying to use kerberos via CAM

On Jun 27, 2020 11:10 PM, Christoph Hein <notifications@github.com> wrote:

I tried installing tm1py on my iPad the other day. With the app "Pythonista" and the stash module you can use pip and install pure python modules.
I tried it with tm1py and got the attached error message. Now I wonder If that is a deal breaker for tm1py on my iPad and if it is maybe a better solution to create a stripped down fork for the iPad or if even that is not a good solution.

If you wonder about the use cases. It allows you to maintain your tm1 instances from your tablet. :-)

[image]<https://user-images.githubusercontent.com/8442014/85939537-b11b5900-b916-11ea-848d-7c879318d425.jpeg>

-

**Comment by MariusWirtz** [comment]
Hi @scrumthing,

we configured the TM1py setup.py script so that it installs `requests_negotiate_sspi` only on windows.
It seems on your iPad that config doesn't apply it and tries to install all dependencies.

Perhaps you can do this instead:
- install all necessary dependencies explicitly (requests, pandas, pytz)
- install tm1py without any dependencies: `pip install tm1py --no-dependencies`

**Comment by scrumthing** [comment]
Thanks @MariusWirtz, I will try it. :-)

**Comment by MariusWirtz** [comment]
@scrumthing 
did it work?

**Comment by scrumthing** [comment]
Hi @MariusWirtz, I had a quick try but was unsuccessful. So far had no time to investigate that further. Will try to do so during the week. 
Cheers, Christoph

![image](https://user-images.githubusercontent.com/8442014/86542531-b5e39c80-bf16-11ea-98d8-60b0a96274b6.jpeg)

**Comment by MariusWirtz** [comment]
Please try to install from GitHub directly:
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`


If this generally works we can just create a branch without the `requests_negotiate_sspi` dependency.

**Comment by rkvinoth** [comment]
> Hi @MariusWirtz, I had a quick try but was unsuccessful. So far had no time to investigate that further. Will try to do so during the week.
> Cheers, Christoph
> 
> ![image](https://user-images.githubusercontent.com/8442014/86542531-b5e39c80-bf16-11ea-98d8-60b0a96274b6.jpeg)

@scrumthing 

Use `pip install TM1py --no-deps`

**Comment by scrumthing** [comment]
Thanks @rkvinoth. But unfortunately it did not work either. :-(

![image](https://user-images.githubusercontent.com/8442014/86721219-0eee2600-c026-11ea-9d6e-c33534f3ab3a.jpeg)

**Comment by rkvinoth** [comment]
You can call `pip install -h` and check which option is needed for installing packages without dependencies.

if you have difficulties searching in the cmd prompt, copy the result of `pip install -h`  and then do a search in notepad for **dependencies**

**Comment by scrumthing** [comment]
Thanks @rkvinoth but the result was not very helpful to me. 

![image](https://user-images.githubusercontent.com/8442014/87016912-9c20ae80-c1cf-11ea-9589-347a5d87e4d4.jpeg)

**Comment by rkvinoth** [comment]
Wow, looks like a dead end!


As a workaround, download the TM1py package as zip file and then edit `setup.py`.

remove `'requests_negotiate_sspi;platform_system=="Windows"'` from `install_requires` list in `setup.py`

Then run `setup.py install`


![image](https://user-images.githubusercontent.com/60260968/87025106-96d75a00-c1f7-11ea-9206-444a7b0c94c4.png)


If that works, feel free to create a new branch.

**Comment by rkvinoth** [comment]
> Wow, looks like a dead end!
> 
> As a workaround, download the TM1py package as zip file and then edit `setup.py`.
> 
> remove `'requests_negotiate_sspi;platform_system=="Windows"'` from `install_requires` list in `setup.py`
> 
> Then run `setup.py install`
> 
> ![image](https://user-images.githubusercontent.com/60260968/87025106-96d75a00-c1f7-11ea-9206-444a7b0c94c4.png)
> 
> If that works, feel free to create a new branch.

@scrumthing .. any luck with this approach?

**Comment by scrumthing** [comment]
Hi @rkvinoth, sorry over the last couple of days I had no time to test it. Will try to do it during the current week.

**Comment by scrumthing** [comment]
Didn't work either. :-( So I think I am out of options for now.
