### ISSUE TITLE
Function Request - create static subset from mdx expression

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#262]
**Description**
Enhancement request for function to create a 'static' subset from an mdx expression.

Currently it only creates a 'dynamic' subset when an expression is passed as an argument.

**Version**
- TM1py [e.g. 1.5.0]

**Comment by rkvinoth** [comment]
Hello @cubewise-gng ,

Now you can convert `static subset` into a `dynamic subset`. In the back-end it will just save the dynamic subset as static.
Please make sure you clone the repo before testing this feature.

```
from TM1py.Services import TM1Service
from TM1py.Objects import Subset

with TM1Service(address=ADDRESS, port=PORT, ssl=SSL, user=USER, password=PASSWORD) as tm1:
    subset_name, dimension_name, expr = 'All', 'Period', '{TM1SUBSETALL( [Period] )}'
    subset = Subset(subset_name=subset_name, dimension_name=dimension_name, expression=expr)
    tm1.subsets.create(subset)
    tm1.subsets.make_static(subset_name=subset_name, dimension_name=dimension_name)
```

**Comment by cubewise-gng** [comment]
Thanks @rkvinoth , that worked well.
