### ISSUE TITLE
Subset update_or_create error

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#266]
**Describe the bug**
An exception is thrown when using the subset update_or_create function.
TypeError: unsupported operand type(s) for ** or pow(): 'bool' and 'dict'

Looks like it's missing a comma:
  return self.update(subset=subset, private=private ** kwargs)

**Version**
TM1py 1.5.0

**Comment by MariusWirtz** [comment]
Thanks for the catch! It's fixed
