### ISSUE TITLE
Enhancement - Filter message log by datetime

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#268]
**Describe what did you try to do with TM1py**
Please add filtering by since (timestamp) for retrieving message logs. Thanks.

**Version**
- TM1py 1.5.0

**Comment by scrumthing** [comment]
Great idea. Wanted to add the same issue today. Maybe add something like beginning and end to get certain period from the message log.

**Comment by MariusWirtz** [comment]
Fixed with #270

**Comment by scrumthing** [comment]
Love it! :-)
