### ISSUE TITLE
Error while updating TI process in TM1 < 11

### ISSUE THREAD

**Issue by TomaszBr** [cubewise-code/TM1py#27]
Hi,

I'm getting the following error when trying to create/update a process with the following json body.

**Exception:**
_...\TM1py\Services\ProcessService.py", line 121, in create
    del body['Parameters'][p]['Type']
TypeError: list indices must be integers or slices, not dict_

**Process JSON:**
`'{"Name": "Admin - Start GL Forecast1", "PrologProcedure": "\\r\\n#****Begin: Generated Statements***\\r\\n#****End: Generated Statements****\\r\\n\\r\\n", "MetadataProcedure": "\\r\\n#****Begin: Generated Statements***\\r\\n#****End: Generated Statements****\\r\\n", "DataProcedure": "\\r\\n#****Begin: Generated Statements***\\r\\n#****End: Generated Statements****\\r\\n", "EpilogProcedure": "\\r\\n#****Begin: Generated Statements***\\r\\n#****End: Generated Statements****\\r\\n", "HasSecurityAccess": false, "UIData": "CubeAction=1511\\fDataAction=1503\\fCubeLogChanges=0\\f", "DataSource": {"Type": "None"}, "Parameters": [{"Name": "pStartPeriod", "Prompt": "", "Value": ""}], "Variables": [], "VariablesUIData": []}'`

TM1 Version 10.2.2 FP6 IF7

**Comment by MariusWirtz** [comment]
Hi Tomasz,

thanks for the catch!

I think I found it. Could you try to replace 
`for _, p in enumerate(body['Parameters']):`
with 
`for p in range(body['Parameters']):`
in line 120 in the ProcessService? Does it solve the issue?

I curretly don't have TM1 10.2.2 installed.

**Comment by TomaszBr** [comment]
Hi Marius,

I tested and received a 'list' object cannot be interpreted as an integer` exception. Line 104 because I'm updating the TI process. 

`...\TM1py\Services\ProcessService.py", line 104, in update
    for p in range(body['Parameters']):
TypeError: 'list' object cannot be interpreted as an integer`

**Comment by MariusWirtz** [comment]
Hi,

sorry what meant was:
`for p in range(len(body['Parameters'])):
`

**Comment by TomaszBr** [comment]
Hi,
it is better, but as Type was added in TM1 v11 it does not exists in my JSON and the next statement fails.

'..\TM1py\Services\ProcessService.py", line 121, in create
    del body['Parameters'][p]['Type']
KeyError: 'Type' '

**Comment by TomaszBr** [comment]
Hi Marius,
the issue has been fixed by introducing the drop_parameter_types class.
Thanks for that.

BR
Tomasz
