### ISSUE TITLE
Support for PAWAA API

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#276]
Because of a recent discussion over at the [TM1 Forum](https://www.tm1forum.com/viewtopic.php?f=3&t=15404) the idea came up to support the **Planning Analytics Administration Server-side Agent API** with tm1py. I personally think that is a great idea.
It could help greatly to administrate multiple tm1 instances. 
What do you guys think?

Example of available instance information
![PAWAA03](https://user-images.githubusercontent.com/8442014/87072899-d49aa980-c21c-11ea-9035-1de094b81d83.PNG)

Possibility to create and update and delete instances
![PAWAA02](https://user-images.githubusercontent.com/8442014/87072904-d5334000-c21c-11ea-8c31-d9d056ad16fd.PNG)

More information on the [IBM website](https://www.ibm.com/support/knowledgecenter/SSD29G_2.0.0/com.ibm.swg.ba.cognos.tm1_inst.2.0.0.doc/c_tm1_install_paa.html).

**Comment by cubewise-tryan** [comment]
Hi @scrumthing,

I don't think this is something we would add to TM1Py. We really want to focus on the server REST API and I am not sure accessing the PA agent is documented or officially supported.
