### ISSUE TITLE
SystemParameterTypeInvalid when creating process

### ISSUE THREAD

**Issue by TomaszBr** [cubewise-code/TM1py#28]
Hi,

I'm getting a SystemParameterTypeInvalid exception while trying to create a process using the below JSON. The body in getting extracted from a working process. 

**My code**
```
tm1refmodel = TM1Service(address='...', port=8037, user='admin', password='apple', ssl=True)
tm1compmodel = TM1Service(address='...', port=8042, user='admin', password='apple', ssl=True)

ProcDef = tm1refmodel.processes.get("Cons - Import Data Feedback")
logger.info(ProcDef)
tm1compmodel.processes.create(ProcDef)

tm1refmodel.logout()
tm1compmodel.logout()
```

> ...\TM1py\Services\RESTService.py", line 188, in verify_response
>     raise TM1pyException(response.text, status_code=response.status_code, reason
> =response.reason)
> TM1py.Exceptions.Exceptions.TM1pyException: Text: {"error":{"code":"","message":
> "SystemParameterTypeInvalid"}} Status Code: 400 Reason: Bad Request

**JSON (dev code removed):**
```
{
  "Name": "Cons - Import Data Feedback",
  "PrologProcedure": "\r\n#****Begin: Generated Statements***\r\n#****End: Generated Statements****\r\n\r\n\r\n",
  "MetadataProcedure": "\r\n#****Begin: Generated Statements***\r\n#****End: Generated Statements****\r\n\r\n",
  "DataProcedure": "\r\n#****Begin: Generated Statements***\r\n#****End: Generated Statements****\r\n\r\n",
  "EpilogProcedure": "\r\n#****Begin: Generated Statements***\r\n#****End: Generated Statements****\r\n",
  "HasSecurityAccess": false,
  "UIData": "CubeAction=1511\fDataAction=1503\fCubeLogChanges=0\f",
  "DataSource": {
    "Type": "ASCII",
    "asciiDecimalSeparator": ".",
    "asciiDelimiterChar": "",
    "asciiDelimiterType": "FixedWidth",
    "asciiHeaderRecords": 0,
    "asciiQuoteCharacter": "",
    "asciiThousandSeparator": ",",
    "dataSourceNameForClient": "\\\\mlgmuc00app751\\TM1$\\global_deploy\\Log\\_.log",
    "dataSourceNameForServer": "\\\\mlgmuc00app751\\TM1$\\global_deploy\\Log\\_.log"
  },
  "Parameters": [
    {
      "Name": "pInterface",
      "Prompt": "",
      "Value": ""
    },
    {
      "Name": "pModel",
      "Prompt": "",
      "Value": ""
    },
    {
      "Name": "pDCU",
      "Prompt": "",
      "Value": ""
    },
    {
      "Name": "pProcess",
      "Prompt": "",
      "Value": ""
    },
    {
      "Name": "pError",
      "Prompt": "",
      "Value": 0
    }
  ],
  "Variables": [
    {
      "Name": "vLine1",
      "Type": "String",
      "Position": 1,
      "StartByte": 1,
      "EndByte": 100
    },
    {
      "Name": "vLine2",
      "Type": "String",
      "Position": 2,
      "StartByte": 101,
      "EndByte": 200
    },
    {
      "Name": "vLine3",
      "Type": "String",
      "Position": 3,
      "StartByte": 201,
      "EndByte": 300
    }
  ],
  "VariablesUIData": [
    "VarType=32\fColType=827\f",
    "VarType=32\fColType=827\f",
    "VarType=32\fColType=827\f"
  ]
}
```

**Comment by MariusWirtz** [comment]
Hi Tomasz,

the issue was the small inconistency between TM1 11 and TM1 10.2.2.
While TM 11 expects process parameters to have a Type property, TM1 10.2.2 does not accept process parameters that have a Type property.

TM1py didn't properly work arround that issue. Now it does:
Now the Process class has a method `called drop_parameter_types`, which removes the type property from all parameters in the ti process.
And now the process_service calls this function on a process before it sends a process to a TM1 10.2.2 Server.

Does it work for you now?

**Comment by TomaszBr** [comment]
Hi Markus, 
the fix is working very good but he is fixing the  #27, not the #28.
The exception described above is not connected to Ti parameters.
I'm getting it even if the process doesn't contain any parameter.
After playing around I found out that it happens only on process with fixed width delimiter type set.
Can you please check again?

**Comment by MariusWirtz** [comment]
Hi,
I was able to replicate the problem. As you said it's due to the fixed width delimiter type set.
The Process class in TM1py needs to be extended in order to handle this datasource type properly.

**Comment by TomaszBr** [comment]
Hi, 
great to hear that you could reproduce it. 
Hope you will find some time in the future to extend the Process class.
Let me know when it will be ready for testing.

**Comment by MariusWirtz** [comment]
Hi, 
It should be solved now. Please upgrade to TM1py 0.1.5 and check if it works for you.

**Comment by TomaszBr** [comment]
Hi Marius,
it is working now as expected.
Thanks for fixing it.
