### ISSUE TITLE
Check element exists is not correct when element named with " %"

### ISSUE THREAD

**Issue by echangcl** [cubewise-code/tm1py#285]
**Describe the bug**
we have tried to check element exists or not with:
"if tm1.dimensions.hierarchies.elements.exists( dim_name, dim_name, attr_name ):"
when the element name contain " %" (space+percentage), the check result is not correct.
e.g. 
    case1: element named as "Test %"
        tm1.dimensions.hierarchies.elements.exists( dim_name, dim_name, "Test %" ) = false,
        tm1.dimensions.hierarchies.elements.exists( dim_name, dim_name, "Test%" ) = true
    case2: element named as "Test Space"
        tm1.dimensions.hierarchies.elements.exists( dim_name, dim_name, "Test Space" ) = true,
        tm1.dimensions.hierarchies.elements.exists( dim_name, dim_name, "TestSpace" ) = true

**To Reproduce**
1.create an element named as "xxx %"
2.using elements.exists and print the result

**Expected behavior**
Element named with " %" should be able to check exists with " %"

**Version**
TM1py [1.4.1]
TM1 Server Version: [11.5.00000.23]

**Additional context**

**Comment by MariusWirtz** [comment]
solved with #286
