### ISSUE TITLE
add_element check if element exists

### ISSUE THREAD

**Issue by vviau** [cubewise-code/tm1py#288]
Hi,

TM1py v1.4.1

Currently the function hierarchy.add_element will fail if the element already exists in the hierarchy.

Would it be possible to have similar behavior as DimensionElementInsert function in TM1? i.e. if the element already exists just don't add it to the Hierarchy.

Cheers,

Vincent

**Comment by rkvinoth** [comment]
Hi @vviau 

Why don't you handle that within a `try` block and parse the response in the `except` block? 
That way you can actually make sure that the element has been added.

**Comment by MariusWirtz** [comment]
Hi,

from a TM1 perspective, I think you might expect that the operation "fails" silently.

I think as a middle way we could introduce an optional boolean argument to the function that controls if the function throws an error in the case that the element exists already. I just can't think of a good name for this argument 🤔

However, if you add an element as String or Consolidation that already exists as a Numeric it should still throw an Exception in my opinion.

**Comment by rclapp** [comment]
@Marius Wirtz
I think this should be handled in the most pythonic way possible. TM1 handles these types or errors pretty poorly. I recommend that we introduce a new type of exception that lines up with the cases where Turbo Integrator would not throw an error. Then we could write code like that

‘
try:
Tm1.element.create(‘new element’, ‘my hierarchy’, ‘my dimension’)

except TM1pyTISilentException as e:

                print(‘TI would be silent about this’)

except:

                print(‘this is a real problem’)
‘

**Comment by rclapp** [comment]
@MariusWirtz  I think this should be handled in the most pythonic way possible. TM1 handles these types or errors pretty poorly. I recommend that we introduce a new type of exception that lines up with the cases where Turbo Integrator would not throw an error. Then we could write code like that
```Python
try:
   tm1.element.create(‘new element’, ‘my hierarchy’, ‘my dimension’)
except TM1pyTISilentException as e:
   print(‘TI would be silent about this’)
except:
   print(‘this is a real problem’)
```

**Comment by vviau** [comment]
Is it a real problem, trying to insert an element that already exists?

For me, the way DimensionElementInsert function works is quite convenient. It is probably not best practice, you should not try to insert elements if they already exist but it reduces the lines code (being able to avoid adding an if statement each time you are using the DimensionElementInsert function).

As a default, the add_element function should fail silently as TM1 does. If you want to catch this error, we could use a new parameter like error_if_exists=true or debug=INFO.

I think having a similar behavior as TM1 would help TM1 developers to use TM1.

**Comment by rclapp** [comment]
Parameters to control error behavior is not a great practice. It's hard to scale it across code and it interferes with the standard ways of error and log handling. TBH TI is the outlier here, code should error if it can't do what you ask it to do.

I am of the opinion that we should do your best to not carry forward the unpredictable patterns of TI. For example, if an element insert operation does not error when an element already exists, why does an element delete error if an element doesn't exist?

If you want TI like behaviors you could use unbound TI execution?



On Jul 16, 2020 11:02 PM, vviau <notifications@github.com> wrote:

Is it a real problem, trying to insert an element that already exists?

For me, the way DimensionElementInsert function works is quite convenient. It is probably not best practice, you should not try to insert elements if they already exist but it reduces the lines code (being able to avoid adding an if statement each time you are using the DimensionElementInsert function).

As a default, the add_element function should fail silently as TM1 does. If you want to catch this error, we could use a new parameter like error_if_exists=true or debug=INFO.

I think having a similar behavior as TM1 would help TM1 developers to use TM1.

-

**Comment by scrumthing** [comment]
I agree with @rclapp! Hubert and his colleagues trying there best to get rid of tm1 legacy stuff (aka things that should have been implemented the right way from the beginning) in the rest api. That is a lot of learning for all of us but it makes tm1 better in the future. :-)

**Comment by vviau** [comment]
alright! It looks like all TM1py gurus do not think that is a good idea.

I was trying to find ways to improve TM1py's adoption to more TM1 developers but maybe we should spend more time explaining how it should work than trying to change the code.

I withdraw my request!

It is great to see that many people caring about the TM1py project.

Thanks for your feedback! I hope you will all continue doingGoodTM1py!
