### ISSUE TITLE
REST Sessions do not end if script is killed

### ISSUE THREAD

**Issue by kool2zero** [cubewise-code/TM1py#29]
We are testing the code to multithread the execution of processes and we noticed that if the script is ended, it will not disconnect the threads (leaving all the rest threads out there idle).  Is there a way to sense the kill and handle the disconnect in the script?

**Comment by MariusWirtz** [comment]
How do you kill it? You mean killing the running python process through taskkill?
If the scripts ends naturally would it clean up all the sessions?

As a Fallback you could set a low value for HTTPSessionTimeoutMinutes parameter in the tm1s.cfg.

**Comment by kool2zero** [comment]
Correct.  Killing the python process through task kill... If the script ends naturally, it will clean up the sessions.  I will try the HTTPSessionTimeoutMinutes.

**Comment by kool2zero** [comment]
It does not appear to work in 10.2.2 FP7 for this use case.

**Comment by MariusWirtz** [comment]
Strange. I would expect the TM1 Server to handle it and clean up the sessions, that are timed out.

**Comment by ajmyers** [comment]
I've also encountered issues with HTTPSessionTimeoutMinutes not working correctly in 10.2.2 FP6 as well, I think it may be fixed in one of the Planning Analytics releases.

**Comment by MariusWirtz** [comment]
Problem fixed in TM1 11 / PA
