### ISSUE TITLE
Trying to execute MDX query to get all leaf level elements in all dimensions of a  cube 

### ISSUE THREAD

**Issue by vamsi-cloud** [cubewise-code/tm1py#304]
from TM1py.Services import TM1Service
tm1=TM1Service(address='***************', port=*****, user='xyz', password='abcd', ssl=True,namespace='Active Directory')
##create MDX to extract  investment rates at leaf level
mdx="""
    SELECT
    NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL([GL Activity Investment Plan])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Investment Type])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Location])},0)}*{TM1FILTERBYLEVEL({TM1SUBSETALL([Year])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Txn Currency])},0)}
    *{TM1FILTERBYLEVEL({TM1SUBSETALL([Skills])},0)}*
    {TM1FILTERBYLEVEL({TM1SUBSETALL([Department])},0)}
    *{TM1FILTERBYLEVEL({TM1SUBSETALL([Months])}
     ON ROWS,
    NON EMPTY {[Measure Investment].[Derived Cost],[Measure Investment].[Budget Derived Cost]} ON COLUMNS
    FROM [Investment_Plan]
    WHERE ([Version].[Final Version],[Scenario].[OP])"""
data=tm1.cubes.cells.execute_mdx(mdx)
from TM1py.Utils.Utils import build_pandas_dataframe_from_cellset
df=build_pandas_dataframe_from_cellset(data, multiindex= False)
df.to_csv("C:\Vamsi_IMP_Documents\data.csv")
print(df)
#####

while executing this upto six dimensions on rows it is not giving any error but when i am adding two more dimensions in a cube  i am getting length error please help me out on this

**Comment by MariusWirtz** [comment]
please post the error and the stack trace that you get.

**Comment by vamsi-cloud** [comment]
Hi Marius
this is  the error ...

 File "C:\Python38\lib\site-packages\TM1py\Services\RESTService.py", line 326, in verify_response
    raise TM1pyException(response.text,
TM1py.Exceptions.Exceptions.TM1pyException: Text: {"error":{"code":"270","message":"Unable to create/access to a cellset that contains more than 0xFFFFFFFF cells."}} Status Code: 400 Reason: Bad Request Headers: {'Content-Length': '113', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=ut

**Comment by rkvinoth** [comment]
@vamsi-cloud 

You already have everything as leaf level and trying to add two more dimensions to the row will cause out of memory error or in your case the numbers of cells requested is above the threshold.

The best way to work on requirements like these is to split the `MDX` query and send parallel requests to the TM1 server.


```PYTHON
from TM1py.Services import TM1Service
from TM1py.Utils.Utils import build_pandas_dataframe_from_cellset
from concurrent.futures import ThreadPoolExecutor
import re


tm1 = TM1Service(address='******', port=, user='xyz', password='abcd', ssl=True,namespace='Active Directory')


month_elements = list(tm1.dimensions.hierarchies.elements.get_leaf_element_names('Months', 'Months'))
year_elements = list(tm1.dimensions.hierarchies.elements.get_leaf_element_names('Year', 'Year'))


##create MDX to extract investment rates at leaf level
mdx_list = []
for year in year_elements:
    for month in month_elements:
        mdx = f"""
        SELECT
        NON EMPTY {{TM1FILTERBYLEVEL( {{TM1SUBSETALL([GL Activity Investment Plan])}},0)}} *
        {{TM1FILTERBYLEVEL({{TM1SUBSETALL([Investment Type])}},0)}} *
        {{TM1FILTERBYLEVEL({{TM1SUBSETALL([Location])}},0)}} *
        {{TM1FILTERBYLEVEL({{TM1SUBSETALL([Txn Currency])}},0)}} *
        {{TM1FILTERBYLEVEL({{TM1SUBSETALL([Skills])}},0)}} *
        {{TM1FILTERBYLEVEL({{TM1SUBSETALL([Department])}},0 )}} *
        ON ROWS,
        NON EMPTY {{[Measure Investment].[Derived Cost],[Measure Investment].[Budget Derived Cost]}} ON COLUMNS
        FROM [Investment_Plan]
        WHERE ([Months].[{month}],[Year].[{year}],[Version].[Final Version],[Scenario].[OP])"""
        mdx_list.append(mdx)


def export_data(expression):
    data = tm1.cubes.cells.execute_mdx(expression)
    df = build_pandas_dataframe_from_cellset(data, multiindex=False)
    result = re.search('\[Months\].\[(.*)\],\[Year\].\[(.*)\],\[Version\]', mdx)
    year = result.group(1)
    month = result.group(2)
    df.to_csv(f"C:\Vamsi_IMP_Documents\data_{year}_{month}.csv")


thread_count = 10
with ThreadPoolExecutor(max_workers=thread_count) as executor:
    executor.map(export_data, mdx_list)

```

In your code you are trying to convert the data to `Dataframe` and then export it which is pretty expensive. I would suggest you to explore other options.

**Comment by vamsi-cloud** [comment]
Thanks for the reply... vinoth ..i executed the code which you posted but it is not yielding any output . can you help me out on this. 
   my intention of converting into data frame  is to perform some calculations on the data retrived. i am just checking the format of data that i am getting through csv...

**Comment by rkvinoth** [comment]
@vamsi-cloud 

There were a couple of corrections, I have edited the code in my earlier comment. 

Basically comment the below lines and call the export data function explicitly to make sure that the `mdx` is working correctly. Because, part of multi threading you wont get the errors.
```Python
thread_count = 10
with ThreadPoolExecutor(max_workers=thread_count) as executor:
     executor.map(export_data, mdx_list)
```

So, replace the above code with the below line to make sure that the `mdx `has no syntax errors.
```Python
export_data(mdx_list[1]) 
```

Once you see the `data_**_**.csv` file, put back the multi-threading code you removed earlier.

**Comment by vamsi-cloud** [comment]
i Executed the code it is throwing following error :


Traceback (most recent call last):
  File "C:/Python38/Lib/idlelib/Modified_getting_elements.py", line 46, in <module>
    export_data(mdx_list)
  File "C:/Python38/Lib/idlelib/Modified_getting_elements.py", line 34, in export_data
    data = tm1.cubes.cells.execute_mdx(expression)
  File "C:\Python38\lib\site-packages\TM1py\Services\CellService.py", line 247, in execute_mdx
    cellset_id = self.create_cellset(mdx=mdx)
  File "C:\Python38\lib\site-packages\TM1py\Services\CellService.py", line 885, in create_cellset
    response = self._rest.POST(request=request, data=json.dumps(data, ensure_ascii=False))
  File "C:\Python38\lib\site-packages\TM1py\Services\RESTService.py", line 43, in wrapper
    self.verify_response(response=response)
  File "C:\Python38\lib\site-packages\TM1py\Services\RESTService.py", line 326, in verify_response
    raise TM1pyException(response.text,
TM1py.Exceptions.Exceptions.TM1pyException: Text: {"error":{"code":"278","message":"Unexpected value type encountered in the payload while processing \"ExecuteMDX\". Expecting type \"String\" but was \"Array\"."}} Status Code: 400 Reason: Bad Request Headers: {'Content-Length': '153', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

**Comment by rkvinoth** [comment]
Looks like the `mdx[1]` you are passing to the function `export_data` is not in `str` format.

Try printing the mdx and fix it as required.
```python 
print(mdx[1])
```

**Comment by MariusWirtz** [comment]
@vamsi-cloud,
did this solve your problem? Can we close this issue?

**Comment by rpitiyar** [comment]
Hi,
I’m trying retrieve all level attributes (hierarchy elements)of gl account dimension in my gl cube with measures   from a cube view for external reporting but still there is no success. Gl account -ragged hierarchy , has same gl account  listed under multiple hierarchies. To report  it is essential to show all levels of the relevant account  against each measure value.

When extracted  using TM1SUBSETALL it extracts only the lowest  level elements .

**Comment by MariusWirtz** [comment]
Hi @rpitiyar,

For your particular use case, you might want to try the `get_elements_dataframe` function. 

``` python
with TM1Service(**tm1_params) as tm1:
    df = tm1.elements.get_elements_dataframe(
        dimension_name="Account",
        hierarchy_name="Account",
        elements="{Tm1SubsetAll([Account])}",
        skip_consolidations=True)

    print(df.to_string())

    df = tm1.elements.get_elements_dataframe(
        dimension_name="Account",
        hierarchy_name="Account",
        elements="{Tm1SubsetAll([Account])}",
        skip_consolidations=False)

    print(df.to_string())
```

You can find more about the arguments for the function here when your search for "get_elements_dataframe":
https://buildmedia.readthedocs.org/media/pdf/tm1py/latest/tm1py.pdf
