### ISSUE TITLE
No module named TM1pyQueries

### ISSUE THREAD

**Issue by jwk019** [cubewise-code/TM1py#32]
From the code
   import TM1py
   from TM1py import TM1pyQueries as TM1

Result:
  No module named 'TM1pyQueries'

**Comment by MariusWirtz** [comment]
that's not how you import TM1py. Here is a sample how to import and use TM1py:

from TM1py.Services import TM1Service

```
# Connection to TM1 Server
with TM1Service(address='localhost', port=12354, user='admin', password='apple', ssl=True) as tm1:
    # Read chore:
    c = tm1.chores.get('0300 Save Data')
    print(c.start_time)

```

Here are more samples:
https://github.com/cubewise-code/TM1py-samples

**Comment by jwk019** [comment]
Well played.
Thanks for the quick response --
