### ISSUE TITLE
Enhancement Request - Function to unwind consolidation recursively

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#322]
Could I please request a function to unwind a dimension hierarchy consolidation specified, with the option to unwind recursively to its children.

**Version**
- TM1py 1.5.0

**Comment by MariusWirtz** [comment]
solved with #326 

@cubewise-gng 
Unfortunately, the TM1 REST API does not provide the functionality to delete multiple edges from a hierarchy in one batch.  Therefore we must retrieve the full hierarchy to python, update it, and send it back. I imagine that this approach will be slower than calling the `}bedrock.hier.unwind` process in most cases.
