### ISSUE TITLE
Site-Packages install

### ISSUE THREAD

**Issue by abernhardt** [cubewise-code/TM1py#33]
Due to various security settings at my client, I am unable to use pip to install, and have to manually put it in the site-packages folder. How would I go about handling the dependencies?

Btw, it's a 10061 error in pip.

**Comment by MariusWirtz** [comment]
The only dependency that (core) TM1py has is the requests package.
https://github.com/requests/requests

You need to download the folder and place it in the site-packages folder manually.

**Comment by abernhardt** [comment]
Ran pip at home outside of the company internet....fixed the issue.
