### ISSUE TITLE
Login with security code 2/3

### ISSUE THREAD

**Issue by psegal** [cubewise-code/TM1py#34]
Hi Marius,

Is there a way to perform NTLM logon using TM1py? 

Appreciate the work you're doing on this.

Best

Paul

**Comment by MariusWirtz** [comment]
Hi,
No. TM1py doesn't implement it (yet).
Can you use native login or CAM?

Thank you. Cheers,
Marius

**Comment by mikaelene** [comment]
Works like a charm! Didn't know about the namespace-parameter. Thanks!
