### ISSUE TITLE
Error remove_all_edges on new empty dimension

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#348]
**Describe what did you try to do with TM1py**

Removing edges from a new dimension that is empty is throwing an error.
tm1.hierarchies.remove_all_edges(dimension_name='Manufacturer')

**Describe what's not working the way you expect**
It is a new dimension that is empty, and be default the hierarchy with the same name should exist.
So I did not expect an error to occur.

**Version**
- TM1py 1.5.0
- TM1 Server Version: 11.8.00100.13

**Additional context**
Error message and the stack trace
```
  File "C:\ProgramData\Anaconda3\lib\site-packages\TM1py\Services\RestService.py", line 385, in verify_response
    headers=response.headers)
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: {"error":{"code":"278","message":"'Manufacturer' can not be found in collection of type 'Hierarchy'."}} Status Code: 404 Reason: Not Found Headers: {'Content-Length': '115', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}
```

**Comment by MariusWirtz** [comment]
Hi @cubewise-gng,

I think the problem is that TM1 11.8 doesn't create a same-named hierarchy implicitly when a dimension is created through REST/TM1py.

This produces `False` in TM1 11.8
``` python
with TM1Service(address="localhost", port=12354, user="admin", password="apple", ssl=True) as tm1:
    dimension = Dimension(name="Test4")
    tm1.dimensions.create(dimension)
    print(tm1.hierarchies.exists(dimension_name="Test4", hierarchy_name="Test4"))
```


I can not verify it with my current setup, but I think in earlier versions of TM1, the same-named hierarchy would be created implicitly.

If you create the same-named hierarchy explicitly in your script, it should work.
``` python
from TM1py import TM1Service, Dimension, Hierarchy

with TM1Service(address="localhost", port=12354, user="admin", password="apple", ssl=True) as tm1:
    dimension = Dimension(name="Test3")
    dimension.add_hierarchy(Hierarchy(name="Test3",dimension_name="Test3"))
    tm1.dimensions.create(dimension)
    tm1.hierarchies.remove_all_edges("Test3", "Test3")
```

**Comment by cubewise-gng** [comment]
Thanks @MariusWirtz, I'll keep note of that when creating dimensions through TM1py.

**Comment by cubewise-gng** [comment]
Hi @MariusWirtz 

Just thinking about it, can the TM1py function tm1.dimensions.create just build the default hierarchy for me to behave like native TM1?

It helps eliminate extra lines of code needed to check if hierarchy exists and create it before using tm1.hierarchies.remove_all_edges?

**Comment by scrumthing** [comment]
I think it should not be created implicitly. It can create clutter in the server and if it is technically necessary than TM1 should create it itself (again!) or it is not than we shouldn't force the user to have it.

**Comment by cubewise-gng** [comment]
Thanks @scrumthing, that makes sense. Will take the explicit approach.
