### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by mikeponeill1978** [cubewise-code/tm1py#349]
Hi, 

apologies in advance for the rookie question and if it has already been answered on another post (I did try and search for it). 

Off teh back of the excellent TM1py presentations by Marius Wirtz at the Cubewise TM1 horizon event I have downloaded the latest Python (version 3.8), Jupyter and TM1py with pandas. I have succesfully established a connection to a TM1 server using check.py. 

I am now trying to follow the examples from the presentation "Getting from zero to writing your first script in TM1py" by Marius and am stuck on Challenge 1! 

I have entered the following code succesfully:

import pickle 
from datetime  import datetime
import pandas as pd
from TM1py import TM1Service, Hierarchy, Dimension, Element

However the next part:

tm1 = TM1Service(adress="loncgapv08", port=40078, user="", password="", ssl=True)

Gives me the following error:

 ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-9f9a607b0b19> in <module>
----> 1 tm1 = TM1Service(adress="loncgapv08", port=40078, user="", password="", ssl=True)

c:\python\python38\lib\site-packages\TM1py\Services\TM1Service.py in __init__(self, **kwargs)
     11 
     12     def __init__(self, **kwargs):
---> 13         self._tm1_rest = RestService(**kwargs)
     14 
     15         # instantiate all Services

c:\python\python38\lib\site-packages\TM1py\Services\RestService.py in __init__(self, **kwargs)
    148             self._base_url = "http{}://{}:{}".format(
    149                 's' if self._ssl else '',
--> 150                 'localhost' if len(self._address) == 0 else self._address,
    151                 self._port)
    152 

TypeError: object of type 'NoneType' has no len()

Any ideas what I am doing wrong? I have tries fully qualifiying the address eg "https://loncgapv08" but that does not help. I'm using the same credentials/valies etc as I was using for the check.py. 

Cheers
Mike

**Comment by MariusWirtz** [comment]
Hi,

it's just a typo in `adress`. It should be `address`

**Comment by MariusWirtz** [comment]
PS
Thanks. I'm glad you enjoyed my TM1py presentation

**Comment by mikeponeill1978** [comment]
Oh man now I feel stupid! I must have looked at the code 50 times and not noticed that. 

Marius thanks for taking time out to reply, it’s much appreciated. I’m sure that won’t be the last stupid question I come up with as I delve into TM1py!

Cheers
Mike

**Comment by MariusWirtz** [comment]
You are welcome! Feel free to post more questions.
