### ISSUE TITLE
Output a list of attributes in the Model

### ISSUE THREAD

**Issue by harveyca307** [cubewise-code/tm1py#352]
Working on a script to create the "stub" of documentation that I normally provide to clients at the end of a project.  The script below is purely looking at Attributes.  My intention is to use a Pandas writer to output this as a sheet among several sheets.  The idea is to output as much as I can get out of TM1 as possible and the manually fill in the rest.

```
import os
from configparser import ConfigParser

import pandas as pd
from TM1py.Services import TM1Service

cwd = os.getcwd()
config = ConfigParser()
config.read(os.path.join(cwd, 'config.ini'))

with TM1Service(**config['glcs']) as tm1:
    attr = []
    all_dims = tm1.dimensions.get_all_names()
    for dim in all_dims:
        dimension = tm1.dimensions.get(dimension_name=dim)
        if dim.startswith('}ElementAttributes') and not dim.startswith('}ElementAttributes_}'):
            for hier in dimension:
                for element in hier:
                    if element.name[0:1] != '}':
                        attr.append([dim[19:], element.name, element.element_type])
                    # print(dim, element.name[:19], element.element_type)
    df = pd.DataFrame(attr, columns=['Dimension', 'Element Attribute', 'Attribute Type'])
    df.to_excel('Attributes.xlsx', index=False, startcol=1)
    print(df)
```
This is the format of what I would generally give to a client.  We list all attributes, their type, source, how updated, etc.
![image](https://user-images.githubusercontent.com/59240547/91905089-97c2c000-ec6b-11ea-9871-22c8cde441bb.png)

Using the above script, I am able to generate the beginning of the sheet I would need:
![image](https://user-images.githubusercontent.com/59240547/91909028-16226080-ec72-11ea-97fd-e6abda863cd3.png)

You can see that I have highlighted 2 attributes, that are actually Aliases.  Trying to see if there is a better way to determine the attributes, and their respective types.  Please forgive the horrible variable names, I just put together a "quick-an-dirty" idea from a stream of consciousness.

**Comment by rkvinoth** [comment]
@harveyca307  we have methods for these kind of use cases, you don't have to parse through the hierarchy and stuff.

```Python
import os
from configparser import ConfigParser
import pandas as pd
from TM1py.Services import TM1Service


cwd = os.getcwd()
config = ConfigParser()
config.read(os.path.join(cwd, 'config.ini'))
with TM1Service(**config['glcs']) as tm1:
    dimensions = tm1.dimensions.get_all_names()
    attribute_list = []
    for dimension in dimensions:
        attribute_list.extend([[dimension, attribute.name, attribute.attribute_type]
                               for attribute in tm1.elements.get_element_attributes(dimension, dimension)])
    if len(attribute_list) > 1:
        df = pd.DataFrame(attribute_list)
        df.columns = ['Dimension', 'Element Attribute', 'Attribute Type']
        df = df[df['Attribute Type'] != 'Alias'].reset_index(drop=True)
```

**Comment by scrumthing** [comment]
Thanks @rkvinoth! I shamelessly stole your snippet and tried it out. Was always on my to do list to try something like that and now I don't have to come up with it myself. :-)

**Comment by rkvinoth** [comment]
Glad it was of help! Also, try to _multi-thread_ the dimensions and avoid using `DataFrame`.

**Comment by harveyca307** [comment]
That's awesome,  thanks.  I learned something new today!
