### ISSUE TITLE
Getting Error message while using  dimension ceate code tm1py

### ISSUE THREAD

**Issue by kumaranuj12** [cubewise-code/tm1py#357]
TM1pyRestException: Text:  Status Code: 401 Reason: Unauthorized Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'OData-Version': '4.0', 'Set-Cookie': 'TM1SessionId=4AQHD9BTvZgsy9DEny3IBw; Path=/api/; HttpOnly', 'WWW-Authenticate': 'Basic realm="TM1"'}

**Comment by MariusWirtz** [comment]
Hi @kumaranuj12,

either you are providing a wrong password or your user doesn't have enough permissions to do the operation you are intending to do.

**Comment by kumaranuj12** [comment]
Hi @MariusWirtz ,

Thanks for replyed but i am entering default admin id and password but still getting same error.

Regards,
Anuj Kumar

**Comment by MariusWirtz** [comment]
Please post your code

**Comment by MariusWirtz** [comment]
I need to see the code in the create_dim.py file to help you.

Perhaps you just got the indentation of the code wrong. 
It fails in line 41.  Probably the connection to TM1 is already closed once the program gets to that line.

**Comment by kumaranuj12** [comment]
import getpass
from distutils.util import strtobool
import configparser

from TM1py.Services import TM1Service
from TM1py.Objects import Dimension,Element,ElementAttribute,Hierarchy
config=configparser.ConfigParser()

config.read('C:\\Users\\AnujKumar\\Desktop\\HSBC\\Python\\config.ini')
#sername=input('Enter the serevr name:')
#with TM1Service(**config[sername])as tm1:
     #print(tm1.server.get_server_name())
user = input("TM1 User (leave empty if SSO): ")
password = getpass.getpass("Password (leave empty if SSO): ")
namespace = input("CAM Namespace (leave empty if no CAM Security): ")
address = input("Address (leave empty if localhost): ") or "localhost"
gateway = input("ClientCAMURI (leave empty if no SSO): ")
port = input("HTTP Port (Default 5000): ") or "5000"
ssl = strtobool(input("SSL (Default T or F): ") or "T")
with TM1Service(
        address=address,
            port=port,
            user=user,
            password=password,
            namespace=namespace,
            gateway=gateway,
            ssl=ssl) as tm1:
        server_name = tm1.server.get_server_name()
        print("Connection to TM1 established!! your Servername is: {}".format(server_name))
        
currencies = ('RMB', 'EUR', 'JPY', 'CHF', 'USD', 'AUD', 'TWD', 'HKD', 'GBP', 'SGD', 'INR')
elements = [Element(cur, 'Numeric') for cur in currencies]
hierarchy = Hierarchy('TM1py Currency From', 'TM1py Currency From', elements)
dimension = Dimension('TM1py Currency From', [hierarchy])
if not tm1.dimensions.exists(dimension.name):
        tm1.dimensions.create(dimension)

**Comment by MariusWirtz** [comment]
the indentation matters in python. This should work:

``` python
import getpass
from distutils.util import strtobool

from TM1py.Objects import Dimension, Element, Hierarchy
from TM1py.Services import TM1Service

user = input("TM1 User (leave empty if SSO): ")
password = getpass.getpass("Password (leave empty if SSO): ")
namespace = input("CAM Namespace (leave empty if no CAM Security): ")
address = input("Address (leave empty if localhost): ") or "localhost"
gateway = input("ClientCAMURI (leave empty if no SSO): ")
port = input("HTTP Port (Default 5000): ") or "5000"
ssl = strtobool(input("SSL (Default T or F): ") or "T")

with TM1Service(
        address=address,
        port=port,
        user=user,
        password=password,
        namespace=namespace,
        gateway=gateway,
        ssl=ssl) as tm1:
    server_name = tm1.server.get_server_name()
    print("Connection to TM1 established!! your Servername is: {}".format(server_name))

    currencies = ('RMB', 'EUR', 'JPY', 'CHF', 'USD', 'AUD', 'TWD', 'HKD', 'GBP', 'SGD', 'INR')
    elements = [Element(cur, 'Numeric') for cur in currencies]
    hierarchy = Hierarchy('TM1py Currency From', 'TM1py Currency From', elements)
    dimension = Dimension('TM1py Currency From', [hierarchy])
    if not tm1.dimensions.exists(dimension.name):
        tm1.dimensions.create(dimension)

```

**Comment by kumaranuj12** [comment]
Thanks you so much only indentation matters
