### ISSUE TITLE
CompileProcess not exposed?

### ISSUE THREAD

**Issue by marfrit** [cubewise-code/TM1py#36]
Using TM1Services.processes.create(Process) I can create a syntactic incorrect process on my TM1 server. I wanted to use CompileProcess, but the method does not seem to be mapped, right?

**Comment by MariusWirtz** [comment]
Thanks for the catch!
CompileProcess was introduced in 10.2.2 FP7 I believe. We haven't included it into the library yet.
It will come with the next release.

**Comment by MariusWirtz** [comment]
Fixed with the latest commit.
We release a new version to PYPI in a few days.
