### ISSUE TITLE
Connecting SAP Hana with TM1Py

### ISSUE THREAD

**Issue by MaaYuu** [cubewise-code/tm1py#366]
Hello,
Can anyone be experienced to take data from SAP webservice to TM1 with Tm1py?
Could TM1Py be able to do this?

I have a work to take data from SAP.

Regards.

**Comment by rkvinoth** [comment]
You are looking for a way to connect Python with SAP's backend. This has nothing to do with TM1py.

I do not actual experience with connecting to SAP, but the below link has step by step procedure to connect (looks promising):
https://blogs.sap.com/2020/06/09/connecting-python-with-sap-step-by-step-guide/

Once you have got the data out of SAP, use **TM1py** to load it into TM1.
