### ISSUE TITLE
Error when syncing dimension and hierarchies

### ISSUE THREAD

**Issue by nicolasbisurgi** [cubewise-code/tm1py#369]
Hi, 
I'm trying to sync up 2 dimensions between two different TM1 instances. I want the dimension with its hierarchies and attributes to be replicated on target. The dimension already exists in the target so I want to update it to reflect exactly what it is on source.

For that I'm using dimension.get and then pushing it to target using dimensions.update_or_create.
I'm getting an error message saying:
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: {"error":{"code":"272","message":"ElementLeafConsolidationConflict"}}

There could be level mismatches between them, that why I want to sync it up with source. I've been testing this function to see what transformation of the element in the target is causing this, i.e.: it is 'N' in source but 'C' in target, or the other way around, but when I do this in dummy dimensions I don't get the same error.

Could you tell me what validations are behind the ElementLeafConsolidationConflict error? 

**Version**
- TM1py [e.g. 1.5.0] 
- TM1 Server Version: [e.g. PA Cloud 2.0.8]

**Comment by MariusWirtz** [comment]
Hi @nicolasbisurgi,

the `ElementLeafConsolidationConflict` comes from the TM1 server. TM1py just passes it through.

Is it possible, that you are creating a leaf element in a hierarchy that exists as consolidation in a different hierarchy in the same dimension or vice versa?

**Comment by MariusWirtz** [comment]
Maybe that's a bold suggestion, but if your model is not sensitive to C Elements (e.g. string data stored on C Elements or explicit references of C Elements in rules), perhaps you could delete all C elements in all hierarchies in the target dimension before you call the dimension update 🤔

**Comment by nicolasbisurgi** [comment]
HI @MariusWirtz ,
Thanks for the quick response! What you mentioned is possible, the dimension has more than 50k elements with 5 different hierarchies so spotting the differences is a bit hard but I could definitely see that situation as possible.
I will delete all C level elements on target before attempting to refresh, however: if I have a C level on source that is currently an N level on target, would I get the same message?

That's what I was wondering about the error message: what is validating on the back end before prompting this message. I understand this is not coming from Tm1Py, but maybe you knew the answer.

Thanks!

Nico

**Comment by MariusWirtz** [comment]
Hi @nicolasbisurgi,

I don't know currently. I will do more research and get back to you.

**Comment by MariusWirtz** [comment]
Hi,

in both scenarios TM1py will fail with the `ElementLeafConsolidationConflict` error. See below.
I don't think the fact that it fails with an Error is a problem per se. 

With TM1py we can determine the elements that are defined differently in the 2 instances.
Then you can fix them manually or with TM1py. Here is a sample to identify the differences.

> Find element type differences

``` python
from TM1py import TM1Service
from TM1py.Utils import CaseAndSpaceInsensitiveDict

DIMENSION_NAME = "d3"

with TM1Service(address="localhost", port=12354, ssl=True, user="admin", password="apple") as tm1_source:
    with TM1Service(address="localhost", port=12297, ssl=True, user="admin", password="apple") as tm1_target:

        elements_and_types_source = CaseAndSpaceInsensitiveDict()
        for hierarchy_name in tm1_source.hierarchies.get_all_names(dimension_name=DIMENSION_NAME):
            elements_and_types_source.update(tm1_source.elements.get_element_types(
                dimension_name=DIMENSION_NAME,
                hierarchy_name=hierarchy_name))

        elements_and_types_target = CaseAndSpaceInsensitiveDict()
        for hierarchy_name in tm1_target.hierarchies.get_all_names(dimension_name=DIMENSION_NAME):
            elements_and_types_target.update(tm1_target.elements.get_element_types(
                dimension_name=DIMENSION_NAME,
                hierarchy_name=hierarchy_name))

        for element_name in elements_and_types_source:
            element_type_source = elements_and_types_source.get(element_name)
            element_type_target = elements_and_types_source.get(element_name)

            if element_type_target:
                if not elements_and_types_source[element_name] == elements_and_types_target[element_name]:
                    print(f"Type inconsistency for element: '{element_name}'")

```

> case 1

``` python
from TM1py import TM1Service, Dimension, Hierarchy

with TM1Service(address="localhost", port=12354, ssl=True, user="admin", password="apple") as tm1:
    dimension = Dimension(name="d3")
    hierarchy = Hierarchy(name="d3", dimension_name="d3")
    hierarchy.add_element("e1", "Numeric")
    hierarchy.add_element("c1", "Consolidated")
    dimension.add_hierarchy(hierarchy)
    tm1.dimensions.update_or_create(dimension)

    hierarchy = Hierarchy(name="alternative", dimension_name="d3")
    hierarchy.add_element("e1", "Consolidated")
    hierarchy.add_element("c1", "Consolidated")
    dimension.add_hierarchy(hierarchy)
    tm1.dimensions.update_or_create(dimension)

```

> case 2

``` python
from TM1py import TM1Service, Dimension, Hierarchy

with TM1Service(address="localhost", port=12354, ssl=True, user="admin", password="apple") as tm1:
    dimension = Dimension(name="d3")
    hierarchy = Hierarchy(name="d3", dimension_name="d3")
    hierarchy.add_element("e1", "Numeric")
    hierarchy.add_element("c1", "Consolidated")
    dimension.add_hierarchy(hierarchy)
    tm1.dimensions.update_or_create(dimension)

    hierarchy = Hierarchy(name="alternative", dimension_name="d3")
    hierarchy.add_element("e1", "Numeric")
    hierarchy.add_element("c1", "Numeric")
    dimension.add_hierarchy(hierarchy)
    tm1.dimensions.update_or_create(dimension)

```

**Comment by nicolasbisurgi** [comment]
Hi @MariusWirtz 
Thank you very much for this! 
I agree that the error is not a problem within itself. I did a similar test on my end:
Source_dim:
A+B element (type=C)
Target_dim:
A+B element (type=N)

And the error didn't pop up, that's why I wondered about the validation behind this error is.

Thank you very much again for your help!

Nico
