### ISSUE TITLE
Members under Consolidation - duplicates

### ISSUE THREAD

**Issue by sootytm1** [cubewise-code/tm1py#381]
Not sure if I'm interpreting this command correctly or it's an issue:
When I use "get_members_under_consolidation", with a max dept of 1, the returned list includes duplicate leaves:
e.g. this consol_ele2 = tm1.elements.get_members_under_consolidation(tempdim, tempdim, "Total", 1, False)

returns:

['A', 'A1', 'A1', 'A2', 'A2', 'B', 'B1', 'B2', 'B2', 'B3', 'B3', 'C', 'C1', 'C1', 'C2', 'C2', 'D', 'B', 'C']

![Capture](https://user-images.githubusercontent.com/72068307/94752629-25aadb80-03cf-11eb-909d-518403eef1be.PNG)

from the simple dim attached.
Thanks.

**Comment by rkvinoth** [comment]
A quick workaround would be to use `set`
```python
consol_ele2 = set(tm1.elements.get_members_under_consolidation(tempdim, tempdim, "Total", 1, False))
```

**Comment by sootytm1** [comment]
> A quick workaround would be to use `set`
> 
> ```python
> consol_ele2 = set(tm1.elements.get_members_under_consolidation(tempdim, tempdim, "Total", 1, False))
> ```

Thanks - but there will be occasions where duplicates are part of the dimension, as in my example "B" and "C" have 2 parents.

**Comment by rkvinoth** [comment]
yeah, I get that and I have created this PR #382 
Check that out and let me know if things are as expected.
