### ISSUE TITLE
AttributeError: 'TM1Service' object has no attribute 'data'

### ISSUE THREAD

**Issue by narendra006** [cubewise-code/tm1py#385]
Hi Guys,
Trying to execute 'cube_load_data_from_cube.py' sample to copy cube data from one instance to another instance.
Its giving the error: **AttributeError: 'TM1Service' object has no attribute 'data' error.** .
But it is working fine when am using tm1_source.cubes.cells.execute_mdx instead of tm1_source.data.execute_mdx function.

Can anyone tell why i am getting attribute error? 

**Version**
- TM1py 1.5.0
- Python 3.8.3

**Comment by MariusWirtz** [comment]
Hi @narendra006,

this is an error in the samples. Thanks for bringing this to our attention. In the early versions of TM1py you could access the `CellService` through `tm1.data`. We have changed it a long time ago but forgot to update the samples.

I will take care now.
