### ISSUE TITLE
Alternative write function based on unbound process execution

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#386]
Unfortunately writing through TI processes is still the fastest way to write to TM1 cubes.

TM1py should offer an alternative write function with the same signature as the `write` function, which uses 1 to n unbound processes behind the scenes with the max number of `CellPutN` / `CellIncrementN` statements in the prolog.

Additionally, it would be nice to create a `require_admin` decorator, similar to `require_pandas` that can be added to this function and others, that checks first if the current user has admin permissions and raises an exception otherwise.

**Comment by andreyea** [comment]
Hi Marius,

What if a data frame is converted to csv and then uploaded to TM1 applications using applications service. Then unbound TI process can pick it up from }externals directory, load it into a cube and delete csv from TM1 applications.

**Comment by MariusWirtz** [comment]
Hi @andreyea,

Thanks. Yeah, that would work. It would probably be faster as well since the TI prolog accepts a maximum of 16384 statements.
The only downside I can see about this approach is that it is a bit more invasive. Like it may produce leftovers in }externals directory in the case of an error (e.g. server crash during ti execution).
I can see good use cases for both approaches. I think we should implement both ways.

**Comment by scrumthing** [comment]
Was applications not removed in the latest release?
