### ISSUE TITLE
Problems with integrated login

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#387]
After many dreadful hours playing around with various settings and python packages we finally got integrated login via python (currently not tm1py) working. I want to share our solution so we hopefully can integrate it in tm1py (or if that is already possible, please point me in the right direction). 

In our enviroment we have 'constrained delegation' (something which is BTW not supported by tm1web at the moment) I guess it has something to do with that. We have one spn for each port/service on the server. 
Hope my description is understandble. If not, please let me know. 

Any ideas on how to implement that into tm1py?

Here is my sample code (deleted obviously the real names :-P) 

```python
import requests
# differerent package than in tm1py
from requests_negotiate_sspi import HttpNegotiateAuth

servername = 'tm1server' # NEVER localhost
instanceport = '5001'
windowsdomain = 'MyDomain'

servicename = 'HTTP'
spn = servername + ':' + instanceport
ssl = 'https'
url = ssl + '://' + servername + ':' + instanceport + '/api/v1/Configuration/ProductVersion/$value'
r = requests.get(url, auth=HttpNegotiateAuth(domain=windowsdomain, service=servicename, host=spn, delegate=True), verify=False)
print(r.text)
```

**Comment by MariusWirtz** [comment]
Hi @scrumthing,

we need to incorporate this code into TM1py.

For the moment you can use your code to generate a `TM1SessionId` and then instantiate the TM1Service with the `TM1SessionId`.
Kinda like this:

``` python
import requests
from requests_negotiate_sspi import HttpNegotiateAuth

from TM1py import TM1Service

with requests.Session() as session:
    session.verify = False
    session.headers["Content-Type"] = "application/json"
    session.headers["TM1-SessionContext"] = "TM1py"
    session.auth = HttpNegotiateAuth(domain=windowsdomain, service=servicename, host=spn, delegate=True)
    reply = session.get("https://db...:8050/api/v1/Configuration")
    sessioncookies = session.cookies.get_dict()
    session_id = sessioncookies["TM1SessionId"]

    tm1 = TM1Service(session_id=session_id)

```

**Comment by scrumthing** [comment]
Worked like a charm!
