### ISSUE TITLE
TM1pyRestException: Text:  Status Code: 401 Reason: Unauthorized Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'OData-Version': '4.0', 'WWW-Authenticate': 'Basic realm="TM1"'}

### ISSUE THREAD

**Issue by jace112233** [cubewise-code/tm1py#389]
Hi I am suppose to extract data from TM1 using dataframe.
The cube I will be using is Budget Revenue
There are 7 dimensions Month, Profit_Center, Other_Costs_item, Version, Company, m_OtherCost
The elements in the dimensions are simple.

This is the code I used

#Connect to local server
tm1 = TM1Service(**config['tm1srv01']) 
server_name = tm1.server.get_server_name()
print("Connection to TM1 established!! your Servername is: {}".format(server_name))

mdx ="SELECT" \
"NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL( [Month] )}, 0)} ON ROWS, "\
"NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL( [Profit_Center] )}, 0)} ON COLUMNS" \
"NON EMPTY {TM1FILTERBYLEVEL( {TM1SUBSETALL( [Other_Costs_item] )}, 0)} ON COLUMNS" \
"FROM [Budget_Revenue]" \
"WHERE ([m_OtherCost].[Amount],[Version].[Budget],[Company].[8000])"

content = tm1.cubes.cells.execute_mdx(mdx)

This is the error script that I have
TM1pyRestException                        Traceback (most recent call last)
<ipython-input-63-a44581e09bc1> in <module>
----> 1 content = tm1.cubes.cells.execute_mdx(mdx)

~\anaconda3\lib\site-packages\TM1py\Services\CellService.py in execute_mdx(self, mdx, cell_properties, top, skip_contexts, skip, skip_zeros, skip_consolidated_cells, skip_rule_derived_cells, **kwargs)
    368         :return: content in sweet concise structure.
    369         """
--> 370         cellset_id = self.create_cellset(mdx=mdx, **kwargs)
    371         return self.extract_cellset(
    372             cellset_id=cellset_id,

~\anaconda3\lib\site-packages\TM1py\Services\CellService.py in create_cellset(self, mdx, **kwargs)
   1387             'MDX': mdx
   1388         }
-> 1389         response = self._rest.POST(url=url, data=json.dumps(data, ensure_ascii=False), **kwargs)
   1390         cellset_id = response.json()['ID']
   1391         return cellset_id

~\anaconda3\lib\site-packages\TM1py\Services\RestService.py in wrapper(self, url, data, encoding, async_requests_mode, **kwargs)
     74 
     75             # verify
---> 76             self.verify_response(response=response)
     77 
     78             # response encoding

~\anaconda3\lib\site-packages\TM1py\Services\RestService.py in verify_response(response)
    370         """
    371         if not response.ok:
--> 372             raise TM1pyRestException(response.text,
    373                                      status_code=response.status_code,
    374                                      reason=response.reason,

TM1pyRestException: Text:  Status Code: 401 Reason: Unauthorized Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'OData-Version': '4.0', 'WWW-Authenticate': 'Basic realm="TM1"'}

**Comment by rclapp** [comment]
401 indicates that you are unauthorized, so either you were not able to connect to the TM1 server or the user you are using can’t access that cube. Also the format you have for your MDX query likely won’t work, you need to use \ to continue the line, or concatenate all of those strings together

**Comment by rkvinoth** [comment]
Did your code print the below line?

```python
print("Connection to TM1 established!! your Servername is: {}".format(server_name))
```

If YES, then as Ryan pointed out, the user who called the script does not have access to the cube `Budget_Revenue`.

On a separate note, you can use `"""` to add a paragraph in `Python`. A good `MDX` alignment can make the code more readable.

```python
mdx = """SELECT
               NON EMPTY 
                   {
                     TM1FILTERBYLEVEL( {TM1SUBSETALL( [Month] )}, 0)
                   }
               ON ROWS, 
               NON EMPTY
                   {
                     TM1FILTERBYLEVEL( {TM1SUBSETALL( [Profit_Center] )}, 0),
                     TM1FILTERBYLEVEL( {TM1SUBSETALL( [Other_Costs_item] )}, 0)
                   }
               ON COLUMNS
               FROM [Budget_Revenue]
               WHERE ([m_OtherCost].[Amount],[Version].[Budget],[Company].[8000])"""
```

Also, I would advice you to use plain `python` without `Anaconda` (at least for projects with TM1py)

**Comment by jace112233** [comment]
Oh okay will work on it thanks ryan

**Comment by jace112233** [comment]
Yes it did. Okay I will try thanks Vinoth
