### ISSUE TITLE
Access level

### ISSUE THREAD

**Issue by abhijit2813** [cubewise-code/TM1py#39]
We are working with tm1py package rest of the codes are executing perfectly but the code of checking element access is giving error as element attribute.I want to check the access of element level for a particular user how can I do that?
Thanks in advance.

**Comment by MariusWirtz** [comment]
Hi,

so you want to know the particular rights on dimensionelements (READ, WRITE, NONE) for a given user?

I would do the following:

1. Look which groups are mapped to this User

2. Query the content from the }ElementSecurity_ cube for that particular dimension through MDX

3. Map everything into a dictionary


```

from TM1py.Services import TM1Service
from TM1py.Utils import Utils

STATES = {
    "WRITE": 2,
    "READ": 1,
    "NONE": 0
}

user = "Manny"
dimension = "plan_business_unit"


with TM1Service(address="10.77.19.60", port=12354, user="admin", password="apple", ssl=True) as tm1:
    # 1
    groups = tm1.security.get_groups(user)

    # 2
    rows = "{TM1SubsetAll([" + dimension + "])}"
    columns = "{" + ",".join(["[}Groups].[" + group + "]" for group in groups]) + "}"
    cube = "}ElementSecurity_" + dimension

    mdx = "SELECT NON EMPTY {rows} ON ROWS, " \
          "NON EMPTY {columns} ON COLUMNS " \
          "FROM [{cube}]".format(rows=rows, columns=columns, cube=cube)

    raw_cube_data = tm1.cubes.cells.execute_mdx(mdx)

    # 3
    effective_element_permissions = {}
    for coordinates, cell in raw_cube_data.items():
        if cell["Value"]:
            element = Utils.element_names_from_element_unqiue_names(coordinates)[0]
            value = cell["Value"]
            if element not in effective_element_permissions:
                effective_element_permissions[element] = value
            elif STATES[effective_element_permissions[element].upper()] < STATES[value.upper()]:
                effective_element_permissions[element] = value

    print(effective_element_permissions)

```

**Comment by abhijit2813** [comment]
Thanks for prompt reply 👍 will check it and let you know

**Comment by abhijit2813** [comment]
Hey its working too great.
can you tell me
I am not able to read the documentation as its link is not opening for API documentation.
[http://tm1py.readthedocs.io/en/latest/](url)
Can you help plz
Thanks in advance

**Comment by Mukund0007** [comment]
Yes, Markus Wirtz,
Documentation is not opening. It would be a great help from you if you can provide required documentation for TM1py.

Thanks in advance.

Regards,
Mukund

**Comment by MariusWirtz** [comment]
Thanks for the catch.
We will fix the documentation.

**Comment by abhijit2813** [comment]
Hello Marius
While Getting Dimension elements I am facing error.
This function is giving error
dimension = tm1.dimensions.get('Months')
Error:'ElementAttributes'
I want to get the element names how can I do that?
Thanks in advance

**Comment by MariusWirtz** [comment]
Documentation is working again. Link to CellService Documentation:
https://tm1py.readthedocs.io/en/latest/TM1py.Services.html#module-TM1py.Services.CellService

Link to HierarchyService:
https://tm1py.readthedocs.io/en/latest/TM1py.Services.html#module-TM1py.Services.HierarchyService

If you want to understand TM1py, the documentation may not be the ideal place to start though!
Maybe check out the samples on:
https://github.com/cubewise-code/TM1py-samples

and the blog articles and tutorials we publish on:
https://code.cubewise.com/tm1py-overview

@abhijit2813 
For the dimension issue please open a new issue and post the code and the Exception you get.
