### ISSUE TITLE
Mode 3?

### ISSUE THREAD

**Issue by dusherwo57** [cubewise-code/tm1py#390]
We have a client whose IT Security function will not accept Mode 1 or Mode 5. How would you use Mode 3 with TM1PY?

**Comment by MariusWirtz** [comment]
Hi,

if the customer has the "plain vanilla" integrated login setup, you can install the TM1py master branch from GitHub and write this:

``` python
with TM1Service(address="localhost", port=12354, ssl=True, integrated_login=True) as tm1:
    print(tm1.server.get_product_version())
````

If this doesn't work let's continue the discussion here
https://github.com/cubewise-code/tm1py/issues/387

**Comment by scrumthing** [comment]
I think we can close this issue. If integrated security works at my employer, it should work everywhere. :-D

**Comment by MariusWirtz** [comment]
@dusherwo57,
please confirm if it works for you
