### ISSUE TITLE
A Python script using tm1py to count/list users over TM1 servers on 1 admin host

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/tm1py#393]
This is an enhancement to tm1py.

**Describe what did you try to do with TM1py**
I am converting a TI process into Python code using tm1py. Soon after starting, the functionalities in the new script surpass the functionalities of the TI script, with much less lines of coding.

**Describe what's not working the way you expect**
All functionalities in the script are working for now.

**Version**
- TM1py 1.5.0
- TM1 Server Version: 11.6
- Python version 3.8.6

**Additional context**
All programming done on a local machine, but models that are used for testing are real TM1 production models. Only IntegratedSecurityMode = 1 for now. Other extensions include:
- a more optimised way of retrieving the cube access over security groups, see: https://www.tm1forum.com/viewtopic.php?f=3&t=15531&p=77449&sid=01e0c26ff36225defb3e270cafd365ea#p77442
- using an alias like }TM1_DefaultDisplayValue or a custom one to output client names in a different way. Group names as well.
- ...

**Code attached in plain text format**
[List TM1 users.txt](https://github.com/cubewise-code/tm1py/files/5384263/List.TM1.users.txt)

**Comment by MariusWirtz** [comment]
Hi @wimgielis,

thanks for sharing! 
I think it's be best to publish this script as a sample in the tm1py-samples repo.
https://github.com/cubewise-code/tm1py-samples

I think it would fit well into the Administration folder.
https://github.com/cubewise-code/tm1py-samples/tree/master/Administration

Once it's in the samples repo collaboration would be easier.

Perhaps some of the code you added to the script could also be integrated directly into the TM1py library.
Like the functionality you added to retrieve all read-only users, we could outsource into a function in the TM1py `SecurityService` I think.

Cheers,

Marius

**Comment by wimgielis** [comment]
Hi @MariusWirtz,

You're welcome. I just proposed a new file with the same coding, as it seems that uploading files is blocked for me.
As to outsourcing code, sure ! I'll leave it up to you decide, always happy to have a chat or discussion about what is useful. Feel free to brush up the code. It's far from awful but with experience in Python I guess things might be coded differently.

**Comment by MariusWirtz** [comment]
OK. I will brush up the code and upload it as a sample to the tm1py-samples project and outsource the pieces into TM1py that are generic enough.

**Comment by wimgielis** [comment]
Thanks in advance. In half an hour I am done with what I have foreseen for now, and I will look into the enhancements I listed in the coming days.

**Comment by wimgielis** [comment]
Latest code is here, I will not make changes for now:


`import os
import sys

from TM1py.Services import TM1Service
from TM1py.Utils import get_all_servers_from_adminhost
from TM1py.Objects import User
from datetime import datetime


logline = []

def inspect_users():

    ADDRESS = 'localhost'
    USER = 'wim'
    PWD = ''

    # level of detail in the output = 'YYY':
    # - character 1: whether adding a header section with information for each TM1 model (Y/N)
    # - character 2: whether adding a section for an IBM user audit (Y/N)
    # - character 3: whether adding a section to list  the users in each TM1 model by their rights (Y/N)
    # - character 4: whether adding a section to list  the users in each TM1 model by their rights (Y/N)
    output_level = 'YYYY'


    output_level = output_level.replace(' ','').upper()
    if len(output_level) != 4:
        sys.exit('Level of output should contain 4 characters, with only Y or N. You now have: ' + output_level)

    if len(output_level.replace('Y','').replace('N','')) != 0:
        sys.exit('Level of output should contain 4 characters, with only Y or N. You now have: ' + output_level)
    
    header_or_customer = 'UPDATE THE CONSTANT WITH A DESCRIPTIVE HEADER OF YOUR LIKING'

    filehandle = open(r'D:\tm1_users.txt', 'w')

    # =============================================================================================================
    # Get TM1 models registered with the admin server
    # =============================================================================================================

    if len(header_or_customer):
        logline.append('\n{}\n'.format(header_or_customer))

    if output_level[0] == 'Y':
        pa_versions = {
            '11.8.00100.13':['11.8.100.13', '11.8', '2.0.9.2', '27/07/2020'],
            '11.8.00000.33':['11.8.0.33', '11.8', '2.0.9.1', '21/05/2020'],
            '11.7.00000.42':['11.7.0.42', '11.7', '2.0.9', '16/12/2019'],
            '11.6.00000.14':['11.6.0.14', '11.6', '2.0.8', '17/07/2019'],
            '11.5.00000.23':['11.5.0.23', '11.5', '2.0.7', '29/04/2019'],
            '11.4.00003.8':['11.4.3.8', '11.4', '2.0.6 IF3', ''],
            '11.4.00000.21':['11.4.0.21', '11.4', '2.0.6', '11/10/2018'],
            '11.3.00003.1':['11.3.3.1', '11.3', '2.0.5 IF3', ''],
            '11.3.00000.27':['11.3.0.27', '11.3', '2.0.5', '25/06/2018'],
            '11.2.00000.27':['11.2.0.27', '11.2', '2.0.4', '16/02/2018'],
            '11.1.00004.2':['11.1.4.2', '11.1', '2.0.3 (dec 2017)','12/2017'],
            '11.1.00000.30':['11.1.0.30', '11.1', '2.0.3', '19/09/2017'],
            '11.0.00204.1030':['11.0.204.1030', '11.0', '2.0.2 IF4', ''],
            '11.0.00202.1014':['11.0.202.1014', '11.0', '2.0.2 IF2', ''],
            '11.0.00200.998':['11.0.200.998', '11.0', '2.0.2', '01/06/2017'],
            '11.0.00101.931':['11.0.101.931', '11.0', '2.0.1 IF1', ''],
            '11.0.00100.927-0':['11.0.100.927', '11.0', '2.0.1', '07/02/2017'],
            '11.0.00000.918':['11.0.00000.918', '11.0', '2.0.0', '16/12/2016']}

    tm1InstancesOnServer = get_all_servers_from_adminhost(ADDRESS)
    for tm1Instance in tm1InstancesOnServer:

        # get server information
        port = tm1Instance.http_port_number
        SSL = tm1Instance.using_ssl

        tm1 = TM1Service(address=ADDRESS, port=port, user=USER, password=PWD, namespace='', gateway='', ssl=SSL)
        active_configuration = tm1.server.get_active_configuration()

        logline.append('\n=============  ' + tm1Instance.name + '  =============\n')

        if output_level[0] == 'Y':
            logline.append("Current time: " + datetime.now().strftime("%x %X"))

            try:
                v = tm1.server.get_product_version()
                logline.append('PA version information: ' + v + ' (' + (' | '.join(pa_versions[v])).strip(' | ') + ')')
            except KeyError:
                logline.append('Unknown software version: ' + v)

            logline.append('Base URL: ' + 'http' + ('s' if SSL else '') + '://' + ADDRESS + ':' + str(port) + '/api/v1/$metadata')
            logline.append('TM1 data directory: ' + os.path.abspath(tm1.server.get_data_directory()))
            logline.append('TM1 logging directory: ' + os.path.abspath(active_configuration["Administration"]["DebugLog"]["LoggingDirectory"]))
            logline.append('')
            logline.append('')

        if output_level[1] == 'Y' or output_level[2] == 'Y' or output_level[3] == 'Y':
            admin_users = []
            full_admin_users = []
            security_admin_users = []
            data_admin_users = []
            operations_admin_users = []
            non_admin_users = []
            authorized_users = []
            write_users = []
            read_users = []
            read_only_users = []
            disabled_users = []

            # custom security groups in TM1
            custom_groups = tm1.security.get_all_groups()
            try:
                custom_groups.remove('ADMIN')
                custom_groups.remove('DataAdmin')
                custom_groups.remove('SecurityAdmin')
                custom_groups.remove('OperationsAdmin')
                custom_groups.remove('}tp_Everyone')
            except ValueError:
                pass

            # get read-only users
            cubeContent = tm1.cells.execute_mdx_rows_and_values('SELECT {[}ClientProperties].[ReadOnlyUser]} ON COLUMNS, {[}Clients].MEMBERS} ON ROWS FROM [}ClientProperties]')

            for user in cubeContent:
                if str(cubeContent[user][0]) != 'None':
                    username = str(user[0]).replace('[}Clients].[}Clients].[','').replace(']','')
                    read_only_users.append(str(username))

            # get user types
            users = tm1.security.get_all_users()
            cubes = tm1.cubes.get_model_cubes()

            for user in users:
                sUsername = str(user._friendly_name)
                if user._enabled == False:
                    disabled_users.append(sUsername)
                elif str(user._user_type) == 'Admin':
                    admin_users.append(sUsername)
                    full_admin_users.append(sUsername)
                elif str(user._user_type) == 'SecurityAdmin':
                    admin_users.append(sUsername)
                    security_admin_users.append(sUsername)
                elif str(user._user_type) == 'DataAdmin':
                    admin_users.append(sUsername)
                    data_admin_users.append(sUsername)
                elif str(user._user_type) == 'OperationsAdmin':
                    admin_users.append(sUsername)
                    operations_admin_users.append(sUsername)
                else:
                    non_admin_users.append(sUsername)
                    authorized_users.append(sUsername)
                    vClient_Access = ''
                    if str(user._friendly_name) not in read_only_users:
                        # loop over all application cubes
                        groups = tm1.security.get_groups(user._friendly_name)
                        for cube in cubes:
                            for group in groups:
                                sAccess = tm1.cells.get_value('}CubeSecurity', cube.name + ',' + str(group))
                                if not sAccess in ['','None','Read']:
                                    vClient_Access = 'W'
                    if vClient_Access == 'W':
                        write_users.append(str(user._friendly_name))
                    else:
                        read_users.append(str(user._friendly_name))

            # output
            if output_level[1] == 'Y':

                logline.append('User audit:')
                logline.append('----------')
                logline.append('')

                output_count('Users', users, 0)
                output_count('Full admin users (\'Administrator\')', full_admin_users, 1)
                output_count('Read/write users (\'Authorized User\')', authorized_users, 1)
                output_count('Read-only users (\'Explorer\')', read_only_users, 1)
                output_count('Disabled users', disabled_users, 1)
                if len(security_admin_users) > 0:
                    output_count('Security admin users', security_admin_users, 1)
                if len(data_admin_users) > 0:
                    output_count('Data admin users', data_admin_users, 1)
                if len(operations_admin_users) > 0:
                    output_count('Operations admin users', operations_admin_users, 1)
                logline.append('')
                logline.append('')

            if output_level[2] == 'Y':
                logline.append('User count:')
                logline.append('-----------')
                logline.append('')

                output_count('Users', users, 0)
                output_count('Admin users', admin_users, 1)
                output_count('Full admin users', full_admin_users, 2)
                output_count('Security admin users', security_admin_users, 2)
                output_count('Data admin users', data_admin_users, 2)
                output_count('Operations admin users', operations_admin_users, 2)
                logline.append('')
                output_count('Non-admin users', non_admin_users, 1)
                output_count('Read/write users', authorized_users, 2)
                output_count('Write users', write_users, 3)
                output_count('Read users', read_users, 3)
                output_count('Read-only users', read_only_users, 2)
                logline.append('')
                output_count('Disabled users', disabled_users, 1)
                logline.append('')
                output_count('Custom TM1 security groups', custom_groups, 0)
                logline.append('')
                logline.append('')

            if output_level[3] == 'Y':

                logline.append('User lists:')
                logline.append('-----------')
                logline.append('')

                if len(security_admin_users) > 0 or len(data_admin_users) > 0 or len(operations_admin_users) > 0:
                    output_list('Admin users', admin_users)
                output_list('Full admin users', full_admin_users)
                output_list('Security admin users', security_admin_users)
                output_list('Data admin users', data_admin_users)
                output_list('Operations admin users', operations_admin_users)
                output_list('Non-admin users', non_admin_users)
                output_list('Read/write users', authorized_users)
                output_list('Write users', write_users)
                output_list('Read users', read_users)
                output_list('Read-only users', read_only_users)
                output_list('Disabled users', disabled_users)

                output_list('Custom TM1 security groups', custom_groups)

    filehandle.write("\n".join(logline))
    filehandle.close()
    return

def output_count(sText, lList, iIndent):

    sText = convert_text(sText, len(lList) == 1)
    logline.append("\t"*iIndent + str(len(lList)) + " " + sText )
    return

def output_list(sText, lList):

    if lList:
        lList.sort
        
        sText = convert_text(sText, len(lList) == 1)
        
        logline.append(sText + " (" + str(len(lList)) + "):\n\t" + "\n\t".join(lList) + "\n" )
        return

def convert_text(sText, exactly_one):

    if exactly_one:
        sText = sText.replace('Users', 'User')
        sText = sText.replace('users', 'user')
        sText = sText.replace('groups', 'group')

        # remove the last character (it could be an alternative to the replace code above)
        # sText = sText[:-1]

    # convert the first character to lowercase
    return sText[0].lower() + sText[1:] if sText else ''

inspect_users()`

**Comment by wimgielis** [comment]
Latest code is here, I will not make changes for now.

[List TM1 users.txt](https://github.com/cubewise-code/tm1py/files/5384723/List.TM1.users.txt)

**Comment by wimgielis** [comment]
I provided the code to use a descriptive attribute for }Clients element names, like }TM1_DefaultDisplayValue (or any other attribute). Other than that, the possibility to exclude TM1 models related to certain port numbers and various other small changes.

[List TM1 users.txt](https://github.com/cubewise-code/tm1py/files/5389040/List.TM1.users.txt)

**Comment by MariusWirtz** [comment]
Hi @wimgielis,

I just started working on the script. I like the neat and tidy output it produces. Instead of integrating it into the existing tm1py-samples, I think it should be a GitHub project on it's own. It's already doing a lot more than any of the samples available and it has actualy practical value. The samples serve mostly as illustrations of how to do things.

You can create a GitHub repo easily like this: 

![image](https://user-images.githubusercontent.com/15182131/96252619-8848cd80-0fb2-11eb-966c-df29927bfd9a.png)
The most difficult part is to come up with a name actually 🙂

Once you published the script as a repository, I will create a merge request to include my changes.

**Comment by wimgielis** [comment]
Hi @MariusWirtz,

I guess the repository has been created and I added the latest vesion of the code:
https://github.com/wimgielis/Count-and-list-TM1-users/tree/main

Feel free to make changes and adjustments and extensions ! Let me know if I need to do something or you might want to discuss.

**Comment by MariusWirtz** [comment]
@wimgielis,

I added two functions to the `SecurityService`: `get_custom_security_groups` and `get_read_only_users` you can find the details here: ab89fe0fab042dbf37deffc43c46c8e1c65a62ff
