### ISSUE TITLE
Error AttributeError: 'TM1Service' object has no attribute 'data'

### ISSUE THREAD

**Issue by genglubo** [cubewise-code/tm1py#397]
I am receiving below error. it looks like data attribute or method is not recognized. I manually checked and data is not listed.
Am I missing something here, is it outdated or do I need to install additional package.

any help would be much appreciated. Thanks!

C:\Users\**\PycharmProjects\HelloWorld\venv\Scripts\python.exe C:/Users/**/PycharmProjects/HelloWorld/TM1/copydata1.py
Traceback (most recent call last):
  File "C:/Users/**/PycharmProjects/HelloWorld/TM1/copydata1.py", line 30, in <module>
    data = tm1_source.data.execute_mdx(mdx)
AttributeError: 'TM1Service' object has no attribute 'data'

Process finished with exit code 1

Exact code I am running is attached below. mdx is just a ref.

`import configparser

from TM1py.Services import TM1Service

config = configparser.ConfigParser()

config.read(r'..\config.ini')

# Setup Connections
tm1_source = TM1Service(**config['tm1srv01'])
tm1_target = TM1Service(**config['tm1srv02'])

# Query data from source TM1 model through MDX
mdx = "SELECT " \
      "{[plan_chart_of_accounts].[41101],[plan_chart_of_accounts].[42201]} on ROWS, " \
      "{[plan_time].[Oct-2004],[plan_time].[Nov-2004],[plan_time].[Dec-2004]} on COLUMNS  " \
      "FROM [Plan_BudgetPlan] " \
      "WHERE " \
      "([plan_version].[FY 2004 Budget],[plan_business_unit].[10110],[plan_department].[410]," \
      "[plan_exchange_rates].[local],[plan_source].[input])"
data = tm1_source.data.execute_mdx(mdx)
# Rearrange data
values = [cell['Value'] for cell in data.values()]
# Send data to target TM1 instance
tm1_target.data.write_values_through_cellset(mdx, values)

# Explicit Logout
tm1_source.logout()
tm1_target.logout()
`

**Comment by MariusWirtz** [comment]
Hi,

this is the same problem as #385 

Here is the solution:
In the early versions of TM1py, you could access the `CellService` through `tm1.data`. Now you have to write `tm1.cells`

**Comment by genglubo** [comment]
Thank you so much.
