### ISSUE TITLE
Writing dataframe error

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#401]
**Describe the bug**
Revtrieving values from TM1 and writing back ignores decimal. Values in cube are now much higher. Dataframe values are with correct decimal. 

Probably something to do with the language setup. Local machine ENG, Server GER. 

**To Reproduce**
```Python

cubeName = "plan_BudgetPlan"

from mdxpy import *
mdx = MdxBuilder.from_cube(cubeName) \
.add_hierarchy_set_to_axis(1, MdxHierarchySet.all_leaves("plan_version")) \
.add_hierarchy_set_to_axis(1, MdxHierarchySet.all_leaves("plan_business_unit")) \
.add_hierarchy_set_to_axis(1, MdxHierarchySet.all_leaves("plan_department")) \
.add_hierarchy_set_to_axis(1, MdxHierarchySet.all_leaves("plan_chart_of_accounts")) \
.add_hierarchy_set_to_axis(1, MdxHierarchySet.member(Member.of("plan_exchange_rates",'local'))) \
.add_hierarchy_set_to_axis(1, MdxHierarchySet.member(Member.of("plan_source",'input'))) \
.add_hierarchy_set_to_axis(0, MdxHierarchySet.all_leaves("plan_time")) \
.to_mdx()

with TM1Service(address=servername, port=instanceport, ssl=True, integrated_login=True, integrated_login_host=spn) as tm1:
      df = tm1.cubes.cells.execute_mdx_dataframe(mdx)

print(df.head(10))

with TM1Service(address=servername, port=instanceport, ssl=True, integrated_login=True, integrated_login_host=spn) as tm1:
  tm1.cells.write_dataframe(cubeName, df)
```

**Expected behavior**

**Version**
TM1py Current GitHub Master
TM1 Server Version: 2.0.9.3

**Comment by MariusWirtz** [comment]
Hi @scrumthing,

thanks for bringing this up.
Are the numbers still alright, when you print them out with `print(df.head(10))` ?

**Comment by scrumthing** [comment]
Hi Marius,
Define alright! They are of type float in the data frame but with a `.` as a decimal separator. But the decimal is ignored when they are written into the cube. Had a similar issue with numeric attributes. That is why I finally dropped them. But maybe that is the same problem.

**Comment by MariusWirtz** [comment]
Hi,

OK.

**Comment by scrumthing** [comment]
After carefully debugging it with @MariusWirtz, we came to the conclusion that it is an error in the rest api. Brought the issue up with IBM. Will close it here. 
![image](https://user-images.githubusercontent.com/8442014/98397948-7366d380-2060-11eb-8ee7-41598b9491f0.png)

**Comment by scrumthing** [comment]
The generated cellset should use numeric value instead of string when dataframe is source.

**Comment by MariusWirtz** [comment]
@scrumthing 
Can please check if #456 solves your issue?

`pip install https://github.com/cubewise-code/tm1py/archive/issue/write-values-numbers-as-str.zip --upgrade`

**Comment by scrumthing** [comment]
Hey @MariusWirtz, problem seems to be solved. Thank you very much!
