### ISSUE TITLE
date_time in set_local_start_time

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#403]
I'm trying to set_local_start_time(chore_name, date_time) but I'm struggling with the date_time parameter.
How should this date_time parameter look like? Can you give me an example?
I used trial & error, but I can't figure it out.

Best, Herman

**Comment by rkvinoth** [comment]
`date_time` parameter requires a `datetime` object. You can create a `datetime` object by passing the required time-stamp to it.
You can check the below example:

```PYthon
from TM1py.Services import TM1Service

tm1 = TM1Service()
chore = 'Save_Data_All'

# import datetime and create an object by providing the required time-stamp
from datetime import datetime
new_date = datetime(year=2020, month=10, day=20, hour=12, minute=25, second=20)

tm1.chores.set_local_start_time(chore_name=chore, date_time=new_date)
```

It was difficult for me as well to grasp these things at first. But once you start coding, things will fall in place.

**Comment by hermie64** [comment]
That worked, thanks a lot!
