### ISSUE TITLE
Creating user does not work

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#404]
**Describe the bug**
Tried creating a user via tm1py. Used the sample. Does not work. Not sure what the problem is. 

**To Reproduce**
```Python
    u = User(name='Hodor Hodor', friendly_name='Hodor', groups=['Admin'], password='apple')
    tm1.security.create_user(u)
```

**Expected behavior**
User should be created as admin. Did not happen. 

**Version**
TM1py - current github master
TM1 Server Version: 2.0.9.3

**Additional context**
Error message:
`TM1py.Exceptions.Exceptions.TM1pyRestException: Text: {"error":{"code":"140","message":"ObjectAttributeSetFailed"}} Status Code: 400 Reason: Bad Request Headers: {'Content-Length': '78', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}`

**Comment by rkvinoth** [comment]
`"ObjectAttributeSetFailed"` occurs when you try to set the duplicate value for an alias attribute. Provide a different `friendly_name`

```python
from TM1py.Services import TM1Service                                                                                                       
from TM1py.Objects import User                                                                                                                                                     
                                                                                                 
tm1 = TM1Service()  
u = User(name='Hodor Hodor', friendly_name='Hold the door', groups=['Admin'], password='apple')
tm1.security.create_user(u)
```

**Comment by scrumthing** [comment]
Thanks for the feedback @rkvinoth. That did the trick. Maybe we can figure out a way to provide better error message.
