### ISSUE TITLE
Execute TM1py script via TI

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#407]
I'm calling a TM1py script via TI as suggested [here](https://code.cubewise.com/tm1py-help-content/run-tm1py-script-from-tm1-process) on Cubewise site.

If I execute it via command line, logged on to the Windows Server with my user credentials, it works.
If I execute it via TI nothing happens. TM1 service account has rights on Python folder. 
In the TM1py script I'm currently testing with my user credentials (normally I do not provide user/password since we're using security mode 5).

creds = {
	'address':'xxxxx.xxx.xxx.xxx',
	'port':'12346',
	'user':'domain\user',
	'password':'MyPassword',
	'namespace':'XXX',
	'gateway':'https://xxxxx.xxx.xxx.xxx/ibmcognos/bi/v1/disp',
	'ssl':'True'
}

Am I missing something?

**Comment by rkvinoth** [comment]
There are few questions here:

1. What is the command you have in TI process?
2. What do you mean when you say **nothing happens**? What's the expectation?
3. Is python added to the environment `PATH`?
4. Do you have python installed in **C** drive?

Try these:
1. Logoutput the command
2. Copy the command written in the tm1server.log and open cmd using the service account credentials in your windows server and run the command.


Also note that security mode 5 doesn't mean `SSO` is turned ON.

**Comment by hermie64** [comment]
Hi @rkvinoth,

1. What is the command you have in TI process?
![2020-11-03_205538 (1)](https://user-images.githubusercontent.com/5301621/98035201-68216700-1e18-11eb-9108-fddcde2f347b.png)

2. What do you mean when you say nothing happens? What's the expectation?
That start time of a chore that is maintained in a helper cube is written to chore
3. Is python added to the environment PATH?
Yes
4. Do you have python installed in C drive?
No, on D-drive

1. Logoutput the command
Done
2. Copy the command written in the tm1server.log and open cmd using the service account credentials in your windows server and run the command.
Then I get this: #TE_Test2 is the name of the chore
![2020-11-03_210249](https://user-images.githubusercontent.com/5301621/98034925-06f99380-1e18-11eb-8aa3-425aa9e8fa65.png)

It's complaining that #TE_Test2 can not be found. Does this mean that I'll have to add this service account to TM1 as admin?

**Comment by rkvinoth** [comment]
@hermie64 
When you call a python script from the TI process, the Python process will log into your TM1 application using the Service account's credentials (this is the service account that is running your TM1 service). So, if you have some ADMIN activity provide ADMIN access to the Service account.

**Comment by hermie64** [comment]
After adding ADMIN access to the service account it works.
Thanks guys!
