### ISSUE TITLE
Overrule Windows Service account

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#408]
This is related to this [question](https://github.com/cubewise-code/tm1py/issues/407).

I learned that when TM1py script is executed via TI, the TM1py script runs with the user of the Windows service.

As per out IT infrastructure guidelines, we have separate service accounts for each environment (DEV/QA/PROD) and I therefore can only make this work if I add all three service accounts as ADMIN in TM1 (currently not the case). This means we would need to get additional licenses from IBM.

Wouldn't it be possible to somehow overrule this Windows service account and define another ADMIN account that TM1py can use instead of Windows service account?

**Comment by rkvinoth** [comment]
You can't use SSO though.

Pass the service account username to `user` parameter and password to the `password` parameter.
`gateway` parameter is not required.

You can also pass a base64 encoded password.

**Comment by hermie64** [comment]
Clear, thanks @rkvinoth
