### ISSUE TITLE
Setup.py file not executing 

### ISSUE THREAD

**Issue by abhijit2813** [cubewise-code/TM1py#41]
Hello 
I am trying to load data in tm1 through tm1py for cubike data.
After executing the file of setup.py, I am getting the following error:
TM1pyException: Text: {"error":{"code":"","message":"PATCH not supported on this resource!"}} Status Code: 400 Reason: Bad Request
Due to this, it's not possible to load data
I have followed all the steps for proper connection
My server is connected.
My rest API is also working.
Kindly tell me solution for this
Thanks in advance.

**Comment by MariusWirtz** [comment]
Hi,

You are probably running an old version of TM1 (pre 10.2.2 FP5) that
doesn’t support all REST Features.

What is your version of TM1?

**Comment by abhijit2813** [comment]
Hello
Rest api is working I checked it.
Version is 10.2.2

**Comment by abhijit2813** [comment]
Which version is compatible?

**Comment by abhijit2813** [comment]
Thanks in advance

**Comment by MariusWirtz** [comment]
You need TM1 10.2.2 FP5 or higher.

If you want to know your exact TM1 version you can just instantiate the TM1Service and execute 

print(tm1.version)

**Comment by abhijit2813** [comment]
Thanks Marius
Does tm1py support IBM planning analytics?

**Comment by MariusWirtz-cubewise** [comment]
Yes.

Sent from my iPhone

On 20 Jun 2018, at 08:53, abhijit2813 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Marius
Does tm1py support IBM planning analytics?
