### ISSUE TITLE
Python 3.5 - incompatible because of f-string usage

### ISSUE THREAD

**Issue by pinkymahoney** [cubewise-code/tm1py#410]
The docs here on GitHub claim 3.5+ compatibility, but The Exceptions class uses f-strings, which are **Python 3.6+** (PEP 498) only:

```
File "C:\Users\<username>\AppData\Roaming\Python\Python35\site-packages\TM1py\Exceptions\Exceptions.py", line 14
return f"Timeout after {self.timeout} seconds for '{self.method}' request with url :'{self.url}'"
SyntaxError: invalid syntax
```

**Comment by pinkymahoney** [comment]
While trying to get it running, I found several other f-strings throughout the project and another one, also 3.6+ i guess: 

```
  File "C:\Users\<username>\AppData\Roaming\Python\Python35\site-packages\TM1py\Objects\Application.py", line 25, in ApplicationTypes
    def _missing_(cls, value: str) -> ApplicationType:
  File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\enum.py", line 61, in __setitem__
    raise ValueError('_names_ are reserved for future Enum use')
ValueError: _names_ are reserved for future Enum use
```

**Comment by MariusWirtz** [comment]
Hi @pinkymahoney,

Thank you for bringing this to our attention. Very much appreciated.
If upgrading to python 3.6+ is not a concern for you, we will simply update the requirements of the project.

**Comment by rkvinoth** [comment]
>   File "C:\Users\<username>\AppData\Roaming\Python\Python35\site-packages\TM1py\Objects\Application.py", line 25, in ApplicationTypes
>     def _missing_(cls, value: str) -> ApplicationType:
>   File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\enum.py", line 61, in __setitem__
>     raise ValueError('_names_ are reserved for future Enum use')
> ValueError: _names_ are reserved for future Enum use

I believe this one is from python 3.7+ or 3.8

**Comment by pinkymahoney** [comment]
Hi @MariusWirtz, 

initially I thought this might be a showstopper for me in deploying my 3.7 jupyter notebook to the server, because I depend on MS SQL Server Python integration, which is still on 3.5.2 natively. 
But luckily, I'm in the position to change this on the server, so I even took a bigger leap and upgraded both to 3.9. 

So I guess it's fine if you just update the docs to whatever min version you might determine (README.md still reads 3.5+).

**Comment by MariusWirtz** [comment]
> > File "C:\Users<username>\AppData\Roaming\Python\Python35\site-packages\TM1py\Objects\Application.py", line 25, in ApplicationTypes
> > def _missing_(cls, value: str) -> ApplicationType:
> > File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\enum.py", line 61, in **setitem**
> > raise ValueError('_names_ are reserved for future Enum use')
> > ValueError: _names_ are reserved for future Enum use
> 
> I believe this one is from python 3.7+ or 3.8

Thanks @rkvinoth 
I can confirm that the` _missing_` function in the Enum class requires python 3.8.
I will adjust the requirements in the readme and the setup.py to 3.8
