### ISSUE TITLE
Transfer data from csv file to cube 

### ISSUE THREAD

**Issue by jace112233** [cubewise-code/tm1py#411]
Hi, 

I am trying to transfer data from a csv file to a cube. But I have encounter an error which is "can not be found in collection of type 'Element'."}}  " . Can you guide on the way I should input the values in the csv file.

This is the data from the csv file
![image](https://user-images.githubusercontent.com/72786892/98342408-570c6c00-204b-11eb-9b49-9a36a5bf839f.png)

The is how my cube view looks like
![image](https://user-images.githubusercontent.com/72786892/98342561-8ae79180-204b-11eb-8d86-b52ff7025aab.png)

This is the code that I have used
![image](https://user-images.githubusercontent.com/72786892/98342611-9f2b8e80-204b-11eb-8b2b-287f1ff38b16.png)

**Comment by rkvinoth** [comment]
Do you follow the **cube dimension order** in the `cellset`? If not correct it.

If you still have issues, provide the code in text format and not as an image.

**Comment by jace112233** [comment]
> Do you follow the **cube dimension order** in the `cellset`? If not correct it.
> 
> If you still have issues, provide the code in text format and not as an image.

Hi , this is the code I encounter

TM1pyRestException: Text: {"error":{"code":"278","message":"'2020,NR-DZ600MB' can not be found in collection of type 'Element'."}} Status Code: 404 Reason: Not Found Headers: {'Content-Length': '120', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

**Comment by scrambldchannel** [comment]
Your file looks messed up. You seem to be expecting it to be semicolon delimited but you seem to have a mix of commas and semicolons, hence you're not splitting  ```2020``` and ```NR-DZ600MB```. Also, you seem to expect all columns to be quoted but your image suggests the first column isn't. 

More generally, I wouldn't rely on Excel to show you what's actually in your csv file. Also, if you find yourself removing quotes manually from column values, you might want to look at the csv library.

**Comment by rkvinoth** [comment]
I think you have a good idea of how to load data into `TM1`. Just make sure you follow the **dimension order of the cube** in each `key` in the `cellset`.
You have to get your csv file sorted at the source or take this question to **stackoverflow**, as we lot of python **gurus** there who can definitely provide you a better solution.
I believe this issue can be closed as it is no way related to `TM1PY`.
