### ISSUE TITLE
Update picklist values in TM1 Templates

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/tm1py#423]
**Describe what did you try to do with TM1py**
I am wondering if there is a way in TM1py to check application folder templates for a specific picklist parameter and possibly update or at least return what it is referencing

**Describe what's not working the way you expect**
We have many templates and some are referencing a year from the time month dim while some may be ,looking at APQ settings.  We need to identify which ones are referencing each so we know what needs to be changed.

Either having an out put would be OK or ability to update better but either is helpful.

**Version**
- TM1py 1.5
- TM1 Server Version: 11.8.00000.33

Thanks

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by MariusWirtz** [comment]
Hi @jbeanz23,

I understand you want to retrieve the excel files from the applications folder in TM1 and understand or manipulate the `SUBNM` formulas. Is that correct?
Technically that's possible. You can retrieve the workbooks and use an excel library to parse/manipulate them.

It should be straightforward to scan through the excel and find the `SUBNM` formulas.
```
SUBNM(Dimension, Subset, IndexOrName, [Alias])
```
However, depending on how complex the calculation tree behind each argument is, it could be challenging to understand the actual value of an argument.
If all arguments are hard in the SUBNM, it would be easy to read and or manipulate it.
