### ISSUE TITLE
Error with extracting of elements using execute mdx

### ISSUE THREAD

**Issue by jace112233** [cubewise-code/tm1py#429]
Hi, I am having trouble extracting the elements using tm1.dimensions.execute_mdx.

This is the code I used
tm1 = TM1Service(**config['tm1srv01']) 
elements = tm1.dimensions.execute_mdx(dimension_name="Department", mdx="{Tm1FilterByLevel({Tm1SubsetAll( [Department] )},0)}")
print(elements)

This is the error I have
Text: {"error":{"code":"501","message":"Syntax error at or near: 'efaultMember } ON COLUMNS  FROM [}Elemen ... ', character position 104"}} Status Code: 400 Reason: Bad Request Headers: {'Content-Length': '139', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

**Comment by rclapp** [comment]
I recommend you try the execute set mdx method in the elements service. The method you are using requires an attributes cube to be present, which could be part of the problem.

On Nov 24, 2020 10:53 PM, jace112233 <notifications@github.com> wrote:

Hi, I am having trouble extracting the elements using tm1.dimensions.execute_mdx.

This is the code I used
tm1 = TM1Service(**config['tm1srv01'])
elements = tm1.dimensions.execute_mdx(dimension_name="Department", mdx="{Tm1FilterByLevel({Tm1SubsetAll( [Department] )},0)}")
print(elements)

This is the error I have
Text: {"error":{"code":"501","message":"Syntax error at or near: 'efaultMember } ON COLUMNS FROM [}Elemen ... ', character position 104"}} Status Code: 400 Reason: Bad Request Headers: {'Content-Length': '139', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

-

**Comment by rkvinoth** [comment]
As Ryan suggested:

```python
from TM1py.Services import TM1Service

tm1 = TM1Service(**config['tm1srv01'])

elements = tm1.elements.execute_set_mdx(dimension_name="Department",
                                        mdx="{Tm1FilterByLevel({Tm1SubsetAll( [Department] )},0)}")
print(elements)
```

I'm not sure about your use case here, but there are other methods available which can provide you **leaf elements**, **consolidated elements**, **elements with weight**, etc,.

**Comment by jace112233** [comment]
> As Ryan suggested:
> 
> ```python
> from TM1py.Services import TM1Service
> 
> tm1 = TM1Service(**config['tm1srv01'])
> 
> elements = tm1.elements.execute_set_mdx(dimension_name="Department",
>                                         mdx="{Tm1FilterByLevel({Tm1SubsetAll( [Department] )},0)}")
> print(elements)
> ```
> 
> I'm not sure about your use case here, but there are other methods available which can provide you **leaf elements**, **consolidated elements**, **elements with weight**, etc,.

Hi, what other methods are there? 
I want to extract only the names of the elements from the dimension

**Comment by rkvinoth** [comment]
If you use any IDE like pycharm, then just type **tm1.elements.** and that will show you the list of methods available for querying.

_some sample methods:_

```python
from TM1py.Services import TM1Service

tm1 = TM1Service(**config['tm1srv01'])

dimension_name = "Department"

# Get all elements in the dimension
all_elements = tm1.elements.get_element_names(dimension_name=dimension_name, hierarchy_name=dimension_name)
print(all_elements)

# Get only the leaf level elements
leaf_elements = tm1.elements.get_leaf_element_names(dimension_name=dimension_name, hierarchy_name=dimension_name)
print(leaf_elements)
```

If you don't use any IDE, then you can use this documentation which has the list of all available methods under `ElementService`
https://tm1py.readthedocs.io/en/latest/TM1py.Services.html#module-TM1py.Services.ElementService
