### ISSUE TITLE
SandboxService - moduel object is not callable

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/tm1py#432]
**Describe the bug**
When trying to connect to the TM1 database in Cloud using IntergatedSecurityMode 1, I got following error:
Traceback (most recent call last):

  File "/Users/tomasfelcman/Documents/Projects/TM1Py/fel_codes/check_tm1.py", line 51, in <module>
    with TM1Service(

  File "/Applications/anaconda3/lib/python3.8/site-packages/TM1py/Services/TM1Service.py", line 33, in __init__
    self.sandboxes = SandboxService(self._tm1_rest)

TypeError: 'module' object is not callable

**To Reproduce**
Connect to TM1 in Cloud with ISM=1

**Expected behavior**
When I commented the line 33, no error appeared and the connection was sucessfully made.

**Version**
TM1py [1.5.0] - I have done upgrade yeasterday
TM1 Server Version: [11.0.00101.931]

**Additional context**
Is there any TM1 Server setup that has to be made in order for SandboxService to work?

**Comment by MariusWirtz** [comment]
Please upgrade to the latest master branch from GitHub. I wonder if this solves the problem.
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`

**Comment by MariusWirtz** [comment]
@tomasfelcman please confirm if the issue still persists after the upgrade
