### ISSUE TITLE
execute_mdx_dataframe_pivot column order is not same as MDX

### ISSUE THREAD

**Issue by yyzz1010** [cubewise-code/tm1py#434]
**Describe the bug**
even i stated "Sales Qty" first, and "Sales Amount (LCY)" second for M Sales dimension as columns, the column order in pivot table is not same as MDX

**To Reproduce**
<img width="684" alt="image" src="https://user-images.githubusercontent.com/45536868/101018490-8b217100-35a6-11eb-8dab-9ccc86d5be4e.png">

**Expected behavior**
pivot table column order is shown according to MDX given

**Version**
TM1py Version: 1.5.0
TM1 Server Version: 11.8.0.33

**Comment by MariusWirtz** [comment]
Hi @yyzz1010,

thanks for reporting the issue. I will look into this.

Pivot tables in pandas are real beasts. Perhaps for the moment, it's easiest if you just use the `execute_mdx_dataframe_shaped` function. Then you get a normal data frame but in the shape of the query/view.

**Comment by yyzz1010** [comment]
Thanks @MariusWirtz, this is exactly what I want!! but this function is not documented [here](https://tm1py.readthedocs.io/en/latest/index.html) so I didn't know about it.

**Comment by MariusWirtz** [comment]
Happy to hear that this is helpful for you.
I will regenerate the docs.

To know what functions are available in the different services I would recommend also using the autocompletion features of tools like Juypter or PyCharm. It can be a good way to discover the functionality in TM1py.

![image](https://user-images.githubusercontent.com/15182131/101022764-1f251580-3572-11eb-8b97-df13fba2663a.png)


![image](https://user-images.githubusercontent.com/15182131/101022853-3cf27a80-3572-11eb-9b1f-d0d5091866e3.png)

![image](https://user-images.githubusercontent.com/15182131/101023070-89d65100-3572-11eb-93f6-2fef8e023b52.png)

![image](https://user-images.githubusercontent.com/15182131/101023194-b38f7800-3572-11eb-9b76-e3d341ec805c.png)
