### ISSUE TITLE
Write Back via Unbound TI does not Format Large Floats; Process Fails

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/tm1py#437]
**Describe the bug**
When using the cells.write method with use_ti set to true, large float values fail and causes a process error. Write back via the API directly does not produce an error on values over 16 digits in length

**To Reproduce**
create a cellset with a write back value of 1.1234567812345678, the process will fail

**Expected behavior**
I think we want to put in some sort of truncation or rounding to protect against this issue. If direct writeback via the API produced an error then I wouldn't think this is an issue. 

**Version**
TM1py 1.5 (HEAD)
TM1 Server Version: [e.g.  11.8]

**Comment by MariusWirtz** [comment]
Thanks for reporting this issue @rclapp

I created a fix in the `write_through_unbound_process` function to make sure number strings don't exceed the float range.
Please install the branch and check if the fix works for you.

`pip install https://github.com/cubewise-code/tm1py/archive/issue/write-with-unbound-ti-digits.zip --upgrade`

**Comment by rclapp** [comment]
I tested this and it doesn't seem to fix the issue. However when I cast the cellset value as a numpy.float16 it works correctly.

**Comment by MariusWirtz** [comment]
Hi @rclapp,

this is strange. For me the below works after the fix. 

Can you share some code that doesn't work after the fix?

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    cells = {
        ("e1", "e1"): "1.123456781234512312321321321321141521678"
    }
    tm1.cells.write("c1", cells, use_ti=True)

```


``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    cells = {
        ("e1", "e1"): 1.123456781234512312321321321321141521678
    }
    tm1.cells.write("c1", cells, use_ti=True)

```

**Comment by MariusWirtz** [comment]
I just added another commit. Please try again with the latest version of the branch.

**Comment by rclapp** [comment]
I tried again and it still fails. After debugging the code I think the problem is related to string conversion and floats. In our case we are dealing with really small numbers and it results in CellPutN methods that are using scientific notation. This entry was in the unbound process:
`CellPutN(1.0495342974719299e-10,'Matrix','Actual');
CellPutN(7.473631240859451e-08,'Matrix','Actual');
CellPutN(1.0638239745436309e-07,'Matrix','Actual');
`

**Comment by MariusWirtz** [comment]
@rclapp thanks for the update. I added another commit and I think we have got it now.

We are now converting scientific notation floats into normal float strings for the TI code.  To control the conversion, I added the optional `precision` argument to the `write_through_unbound_process` function. It defaults to 8.

**Comment by rclapp** [comment]
@MariusWirtz Excellent, this seems to do the trick. Thanks for the solution.

**Comment by MariusWirtz** [comment]
Thanks for the confirmation @rclapp!

**Comment by rkvinoth** [comment]
It seems like Using explicit `CELLPUTN` we can only use numbers up to 21 digits. Wasn't the case when I loaded the data from a flat file.
![image](https://user-images.githubusercontent.com/60260968/107782464-1c634f80-6d6f-11eb-8bc9-c5e47111874f.png)

**Comment by MariusWirtz** [comment]
@rkvinoth 
that's why I added the `precision` argument. If you have very large numbers you can change the precision to 4 or something.
Not an ideal solution of course...
