### ISSUE TITLE
Get updated transaction logs

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#439]
**Describe what did you try to do with TM1py**
I am using the following script to get the transaction logs:

`tm1.server.get_transaction_log_entries(since=datetime.datetime.strptime("2020-10-01", "%Y-%m-%d"))`

**Describe what's not working the way you expect**
It seems the values I get is not up to date. If I compare these logs with the tm1 architect`s logs, there is a 1 month gap. 

Should I run some previous command in order to get the most updated log ?

**Version**
- TM1py [latest] 
- TM1 Server Version: [e.g. 11.1]

**Comment by rkvinoth** [comment]
@kaleming  for me it works perfectly.
Try upgrading to TM1py's latest version.

**Comment by kaleming** [comment]
Hi @rkvinoth, 

I am already using the latest version. I will make some more tests in order to see if I find why this is happening.

I will close this for a while. If I notice this has something to with tm1py, then I reopen.

Thanks
