### ISSUE TITLE
Message log filter does not take list as parameter for msg_contains

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#443]
**Describe the bug**
The function **get_message_log_entries** excepts Iterable as variable. But if the example below is used no entries are returned. If only one of them is used (depending on the language of the server) entries are found. 

**To Reproduce**
```python
with TM1Service(**TM1_PARAMETERS) as tm1:
    messagelog = tm1.server.get_message_log_entries(reverse=False, logger= 'TM1.Server' , msg_contains= ['TM1 Server is ready','TM1 Server ist bereit,'])
```

**Expected behavior**
Entries should show up if only on of the entries in the list is valid

**Version**
Current GitHub Master
TM1 Build Number:  11.8.00200.24

**Comment by rkvinoth** [comment]
The above PR will solve the issue and I believe this is how it should work instead of searching for all the wildcards in a single `Message` row.

**Comment by scrumthing** [comment]
Sounds good for me! :-)
