### ISSUE TITLE
How could I avoid space sensitivity upon hierarchy build?

### ISSUE THREAD

**Issue by nicolasbisurgi** [cubewise-code/tm1py#445]
**Describe what did you try to do with TM1py**
Build a hierarchy from a pandas data frame with Parent/Child/ElementType/Weight columns ~72k unique elements.
The code:
Variant 1:
`# Build hierarchy from file`
`elements = []`
`edges = {}`
`for element in df_hierarchy.itertuples(index=False):`
`elements.append(Element(name=element.Child,element_type=element.ElementType))`
`consolidation = (element.Parent,element.Child)`
 `edges[consolidation] = element.Weight`

Variant 2:
`hierarchy = Hierarchy(hierarchy_name, dimension_name)`
`hierarchy.add_element(element_name=element.Child, element_type=element.ElementType)`
 `hierarchy.add_edge(parent=element.Parent, component=element.Child, weight=element.Weight)`

**Describe what's not working the way you expect**
Within those ~72k elements I have 4 distinct ones (PCKGROUNDSHIP, PCK GROUND SHIP, PCKAIRSHIP, PCK AIR SHIP).
After the code successfully executes I only see PCKAIRSHIP and PCK GROUND SHIP (as they were before the other 2). 
By default TMPy is considering PCKGROUNDSHIP= PCK GROUND SHIP and PCKAIRSHIP = PCK AIRS HIP.

How could I override that behavior?

**Version**
- TM1py 1.5.0 
- TM1 Server Version: 11.6.00004.2

**Comment by rkvinoth** [comment]
That is how TM1 works. TM1 is case and space insensitive.

Since the elements already exists, TM1 isn't building them.

You have got to come up with a logic to remove those unwanted elements from the `DataFrame` or within the `for` loop.

**Comment by nicolasbisurgi** [comment]
Hi Vinoth,
Thanks for the quick reply. I was not aware that TM1 was also space insensitive... after 10 years of working with TM1 I'm glad to see I can still get surprised :)

Thanks again for the quick response.

Nico
