### ISSUE TITLE
Retrieve all applications from tm1 instance

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#458]
I want to get a list with all applications on the server. Neither could I find a function in tm1py nor could I find out to get it directly from the api. Anyone any idea how to achieve that or did I overlook something?

**Comment by rkvinoth** [comment]
Its there under `Utils`

```python
from TM1py.Utils import Utils

# get a list of servers under a particular admin host
servers = Utils.get_all_servers_from_adminhost(adminhost='localhost')
```

**Comment by scrumthing** [comment]
Thanks but I meant applications like Excel files. Stored under applications in a tm1 instance aka tm1 server aka tm1 database. I think wording here is confusing.

**Comment by macsir** [comment]
Use application service. I have just done one recently.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scrumthing** [comment]
The application services unfortunately provides no function to retrieve all files stored there. I am looking for something similar to 'get_all_cubes_name'...

**Comment by macsir** [comment]
get_document function can return the file name with path and you can dump to xls files afterwards

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MariusWirtz** [comment]
> The application services unfortunately provides no function to retrieve all files stored there. I am looking for something similar to 'get_all_cubes_name'...
> 
> After using ARC and tracing the rest calls there I found a way of retrieving it. But I don't like it. :-D
> 
> _https://localhost:5001/api/v1/Contents('Applications')?$select=ID,Name&$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents($select=ID,Name;$expand=tm1.Folder/Contents)))))))))_

It's true, we are lacking a function to return the name and path for every application on the server.

**Comment by scrumthing** [comment]
Something like that would be really useful, I guess. It is rather painful to get the path own your own. Maybe someone could come up with a better approach than the one I mentioned above.

**Comment by MariusWirtz** [comment]
@scrumthing 
you can use this for the moment. Eventually we can make it more robust and integrate it into the ApplicationService.

``` python

from TM1py import TM1Service
from TM1py.Objects.Application import ApplicationTypes

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    application_entries = tm1.elements.get_element_names("}ApplicationEntries", "}ApplicationEntries")

    for application_entry in application_entries:
        *path_parts, application_name = application_entry.split("\\")
        if not application_name.endswith(".blob"):
            continue

        application_name, extension = application_name.rsplit(".", maxsplit=1)

        application = tm1.applications.get(
            path="/".join(path_parts),
            application_type=ApplicationTypes.DOCUMENT,
            name=application_name,
            private=False)

        application.to_xlsx(application.name + ".xlsx")

```

**Comment by scrumthing** [comment]
Hey @MariusWirtz, thanks for that. Works exactly like I need it. Playing around with perspective reports and trying to parse them for their formulas. For all that are curious, please find my work in progress here. 

```python
        wb = load_workbook(filename = application.name)
        sheet_range = wb.sheetnames

        for sheet in sheet_range:
            ws = wb[sheet]
            for col in ws.iter_cols(min_row=1, min_col=1):
                for cell in col:
                    if str(cell.value) != 'None' and cell.data_type == 'f':
                        print(str(cell) + ' - ' + str(cell.value))
```

**Comment by farevian** [comment]
Hello,

Great, but in my case it work fine if application is in 1 level directory. When I try to go like 'application\rep in application\file, it dont work. But I dont know if it's because their is blank caracter in the name, or because it's a sub directory.

**Comment by MariusWirtz** [comment]
Hi @farevian,

do you mean the code that I posted or the code that @scrumthing posted?
When it doesn't work, does it fail silently or does it raise an error? If so please also post the error message and the stack trace.

**Comment by farevian** [comment]
Hello,
The part that faile look the same as your or  @scrumthing
I have a 404 error in RestService for the directory "UIB\\Dimension Update" (the directory where the excel file is). Message is "'UIB\Dimension Update' can not be found in collection of type 'Entry'."
Other excel file in "UIB" directory work find.
Regards

**Comment by MariusWirtz** [comment]
please try this:

``` python
from TM1py import TM1Service
from TM1py.Objects.Application import ApplicationTypes
from openpyxl import load_workbook

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    application_entries = tm1.elements.get_element_names("}ApplicationEntries", "}ApplicationEntries")

    for application_entry in application_entries:
        *path_parts, application_name = application_entry.split("\\")
        if not application_name.endswith(".blob"):
            continue

        application_name, extension = application_name.rsplit(".", maxsplit=1)

        application = tm1.applications.get(
            path="/".join(path_parts).replace('', ' '),
            application_type=ApplicationTypes.DOCUMENT,
            name=application_name,
            private=False)

        application.to_xlsx(application.name)
        wb = load_workbook(filename = application.name)
        sheet_range = wb.sheetnames

        for sheet in sheet_range:
            ws = wb[sheet]
            for col in ws.iter_cols(min_row=1, min_col=1):
                for cell in col:
                    if str(cell.value) != 'None' and cell.data_type == 'f':
                        print(str(cell) + ' - ' + str(cell.value))
```

**Comment by farevian** [comment]
Hello,

After add the * before path_parts, application_name = application_entry.split("\\") that I forgot and change the line 
path="/".join(path_parts).replace(' ', ''), by path="/".join(path_parts),
It's look ok.
Thank you Marius

**Comment by MariusWirtz** [comment]
Thanks! I'm not sure I understand your change though. Please post the working code for future reference.

**Comment by farevian** [comment]
Ok, I will do that.

Le mer. 19 janv. 2022 à 17:09, Marius Wirtz ***@***.***> a
écrit :

**Comment by farevian** [comment]
Hello,

The code I use

vserv = self.getConnexion('Source')



        application_entries =
vserv.elements.get_element_names("}ApplicationEntries",
"}ApplicationEntries")



        for application_entry in application_entries:

            *path_parts, application_name = application_entry.split("\\")

            print(f'repertoire {path_parts} applie {application_name}')

            if not application_name.endswith(".blob"):

                continue



            application_name, extension = application_name.rsplit(".",
maxsplit=1)

            try :

                application =vserv.applications.get(

                   #path="/".join(path_parts).replace(' ', ''),

                   path="/".join(path_parts),

                   application_type=ApplicationTypes.DOCUMENT,

                   name=application_name,

                   private=False)

            except TM1pyException as verreur :

                print(verreur.message)

Le mer. 19 janv. 2022 à 17:09, Marius Wirtz ***@***.***> a
écrit :

**Comment by farevian** [comment]
Hello,
Try to copy the code from Marius, but get an error with ApplicationTypes.DOCUMENT. Get the message : 
 "'tuple' object has no attribute 'suffix'"

It's look like the named tuple is not reconize in ApplicationService.py

Code work forFOLDER (even sending that the FOLDER is not found), but not for DOCUMENT, CUBE. the error is ApplicationService,   when it try to access the namedtuple : name += application_type.suffix

Other than me have this case ?
