### ISSUE TITLE
Copy View

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#461]
I'm copying View A to View B:

view_source = tm1.views.get_native_view(cube_name=cube_name, view_name=view_name_source, private=False)
view_source.name = view_name_target
view_update = tm1.views.update(view=view_source, private=False)

As such the process works fine but in the resulting View B the dimension elements are shown with their technical names instead of attribute-based names in source View A, unless dimension is based on subset, then attribute-based name is also shown in View B?

Not sure if I'm missing something, or if this is a limitation of REST API or maybe an issue with TM1py?

**Comment by scrumthing** [comment]
I think it is a test api issue. If I recall correctly PAW behaves the same when retrieving a view without proper subsets. Have to check when I am back at the office.

**Comment by MariusWirtz** [comment]
@hermie64 
thanks for finding and posting this issue.
I was able to replicate and fix it.

Please upgrade to the below branch and check if it fixes the issue on your end:
`pip install https://github.com/cubewise-code/tm1py/archive/issue/minor-fixes.zip --upgrade`

**Comment by hermie64** [comment]
@MariusWirtz 
Issue is fixed now. 

I do however notice one more thing, the format of the source view is "General" but the format of the target view is "0.#########".
Also when I print the source view with format set to "General", "FormatString": "0.#########" is displayed.

**Comment by hermie64** [comment]
Hi @MariusWirtz,

I tested fix on my own workstation.
I just upgraded TM1Py on one of our servers to 1.6 but I see that the fix is not included because I get technical names again in copied views.

**Comment by MariusWirtz** [comment]
@hermie64 
Yes. It's not included in the release. 
Can you upgrade your servers to the master branch?

We don't normally create minor releases.

**Comment by hermie64** [comment]
OK, will do, thanks.
