### ISSUE TITLE
Not possible to connect Tm1 Instance to TM1py with CAM Security Mode 5

### ISSUE THREAD

**Issue by crittgerott** [cubewise-code/tm1py#465]
Hello,
I have the problem, that I cannot connect to a TM1 Instance with TM1py when I change to SecurityMode 5 to use the CAM Authentication. The Authentication with Securtiy Mode 1 works.
When I test the connection with check.py I just get an Error.
C:\TM1py\tm1py-samples-master>python check.py
TM1 User (leave empty if SSO):
Password (leave empty if SSO):
CAM Namespace (leave empty if no CAM Security): Cognos
Address (leave empty if localhost): ourserver
ClientCAMURI (leave empty if no SSO): http://ourserver:9300/bi/v1/disp
HTTP Port (Default 5000): 8020
SSL (Default T or F): T

ERROR:
        ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Ok, a collegue changed some settings to change from http to https. So the standard settings from me doesn't work. 
Now is all changed back to standard.

After a new check i get this Error message
ERROR:
        Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

Perhaps I just forgot something.
The authentication with SecurityMode 5 on the tm1 instance works.

Thanks for your help
Kind Regards
Christian

**Comment by MariusWirtz** [comment]
Can you sign into Architect or TM1Web without providing credentials?
If Single Sign-On works in other clients like Architect or TM1Web, it should just work for TM1py as well.

**Comment by crittgerott** [comment]
Hello,

sorry for misunderstanding. 
We use on that Server CAM as authentication but no SSO. 
We use it with user and credentials. 
That was my fault, ("if you can read than it helps"). Everywhere stand SSO... so i have to provide User and Password but no ClientCAMURI.

If I provide User and Password without ClientCamuri I get following Error:

C:\TM1py\tm1py-samples-master>check.py
TM1 User (leave empty if SSO): USERNAME
Password (leave empty if SSO): PAssword
CAM Namespace (leave empty if no CAM Security): Cognos
Address (leave empty if localhost): ourserver
ClientCAMURI (leave empty if no SSO):
HTTP Port (Default 5000): 8020
SSL (Default T or F): F

ERROR:
        ('Connection aborted.', BadStatusLine('\x15\x03\x03\x00\x02\x02\n'))

If I select SSL as Default T then i get this Error:
ERROR:
        Text:  Status Code: 401 Reason: Unauthorized Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'Set-Cookie': 'TM1SessionId=dJJQFmMpO4dWr9T353dGCw; Path=/api/; HttpOnly; Secure', 'WWW-Authenticate': 'CAMPassport http://srv-im-capa.intern.infomotion.de:9300/bi/v1/disp, CAMNamespace'}

What can I Do? What is my fault?

**Comment by crittgerott** [comment]
OK, I found my fault. Now it Works. I should use the right Namespace. If I use the Cognos Namespace it don't work but if I use our Namespace which is named in Cognos Configuration, than it works.
Thanks for your help.
