### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by kaleming** [cubewise-code/tm1py#469]
Hi, I would like to know if tm1py provides a way to query auditlogs ? I have found only transaction logs.

There is [this tutorial from ibm ](https://www.ibm.com/support/knowledgecenter/en/SSD29G_2.0.0/com.ibm.swg.ba.cognos.tm1_inst.2.0.0.doc/pa_nf_tm1_audit_logging.html)

**Comment by MariusWirtz** [comment]
TM1py doesn't offer access to audit logs yet.

@kaleming happy to accept a Pull Request
