### ISSUE TITLE
[Enhancement Request] Create/Re-schedule Chore using Quartz cron format

### ISSUE THREAD

**Issue by tatwong** [cubewise-code/tm1py#473]
**Describe what did you try to do with TM1py**
Would like to have a way to create/re-schedule chore using the Quartz cron format or expression, understood chore is not as flexible as normal cron job from other systems, but able to use similar syntax can speed up development if requiring something to be scheduled.

Format can refer to http://www.cronmaker.com/

**Version**
- TM1py [e.g. 1.3.1] 
- TM1 Server Version: [e.g. 11.4]

**Comment by MariusWirtz** [comment]
Thanks for the suggestion @tatwong

**Comment by MariusWirtz** [comment]
Hi @tatwong,

I'm afraid TM1py can not accept a CRON format as a frequency definition. 

The chore's frequency property in TM1 (e.g. `P01DT00H00M00S`) is much less sophisticated than the CRON scheduling format.

![image](https://user-images.githubusercontent.com/15182131/108195717-74f06f00-7118-11eb-8913-96c6bb702719.png)
