### ISSUE TITLE
Use aliases for parent hierarchy nodes

### ISSUE THREAD

**Issue by carltoncheung** [cubewise-code/tm1py#478]
**Describe what did you try to do with TM1py**
We are using `get_member_properties `to get parent hierarchy nodes into Power BI for reporting.

**Describe what's not working the way you expect**
The function is returning the IDs of the hierarchy nodes in the "levelNNN" fields. 
But is it possible to get the "aliases" of these hierarchy nodes in the "levelNNN" fields?

This screenshot shows the hierarchy node IDs that are being returned:
![image](https://user-images.githubusercontent.com/63375086/106679818-82cecc00-6611-11eb-9192-a6392c75ef8e.png)

We would like to see the aliases of those hierarchy node IDs:
![image](https://user-images.githubusercontent.com/63375086/106679873-99752300-6611-11eb-8482-d80cec02d930.png)

The ultimate goal is to use these hierarchy levels in a Power BI slicer that allows the user to choose the level of the hierarchy that they want to report on. So having aliases would make it much more user friendly:
![image](https://user-images.githubusercontent.com/63375086/106680279-726b2100-6612-11eb-8287-2045608d6655.png)

**Version**
- TM1py 1.5.0 
- TM1 Server Version: 11.x

**Comment by MariusWirtz** [comment]
Good point @carltoncheung. Thanks.

I think we could add a new optional argument to the `get_member_properties` function like `parent_attribute` that determines which attribute is retrieved in the level columns. If no attribute is passed we retrieve the element name.

Would that work for you?

**Comment by carltoncheung** [comment]
Hi Marius,

Yes adding an option argument would be great, as long as we can choose which "alias" to use, like in the subset editor:
![image](https://user-images.githubusercontent.com/63375086/106823240-b161ab00-66d4-11eb-806e-bc07861b2996.png)

Thanks again,
Carlton

**Comment by MariusWirtz** [comment]
Hi @carltoncheung,

I added the new `parent_attribute` argument to the `get_member_properties` function.
It resides in the same branch as the fix for #476 

`pip install https://github.com/cubewise-code/tm1py/archive/issue/powerbi-levels.zip --upgrade`

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12297, ssl=True, user="admin", password="apple") as tm1:

    dimAccount = tm1.power_bi.get_member_properties(
        dimension_name="Accounts - AusG One",
        hierarchy_name="Accounts - AusG One",
        skip_consolidations=True,
        parent_attribute="Description")


    print(dimAccount)
```

**Comment by carltoncheung** [comment]
Hi Marius,

Thanks a lot - it works great. Exactly what I wanted. Happy to close this issue now.

Kind regards,
Carlton.

**Comment by carltoncheung** [comment]
Hi Marius, would it be possible to merge this fix into the master tm1py code, so that new users will get it automatically?

**Comment by MariusWirtz** [comment]
OK. Will do it in the next days.

**Comment by MariusWirtz** [comment]
Hi @carltoncheung,

just pushed a new hotfix release to PyPI (1.6.2)
Please verify if it includes all the requested functionality.


`pip install tm1p==1.6.2`
