### ISSUE TITLE
Confusing GIT behaviour

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/tm1py#481]
**Describe what did you try to do with TM1py**
Using the new git functions in tm1py and the ARC plugin by @rclapp. 

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
I did a push via Python. Everything arrived in GIT as expected. Afterwards without changing anything I pushed via the ARC plugin and a couple of processes were changed. If I do two pushes back to back via ARC or via Python no changes in GIT occur. 

Not sure where to place that but I think here is a good way to start asking questions. Anyone encountered something similar? Not sure if that is a rest api issue or a Python issue or an ARC-plugin issue.

**Comment by rclapp** [comment]
Any chance the processes have an odbc data source?

Sent from my mobile phone

On Feb 4, 2021 2:56 AM, Christoph Hein <notifications@github.com> wrote:

Describe what did you try to do with TM1py
Using the new git functions in tm1py and the ARC plugin by @rclapp<https://github.com/rclapp>.

Describe what's not working the way you expect
Didn't get the expected result? Describe:
I did a push via Python. Everything arrived in GIT as expected. Afterwards without changing anything I pushed via the ARC plugin and a couple of processes were changed. If I do two pushes back to back via ARC or via Python no changes in GIT occur.

Not sure where to place that but I think here is a good way to start asking questions. Anyone encountered something similar? Not sure if that is a rest api issue or a Python issue or an ARC-plugin issue.

-

**Comment by scrumthing** [comment]
I have to check. It is a test system with a PlanningSample and some additional stuff. Those PlanningSample ones could have a broken ODBC connections but others which get updated definitely have none. Very confusing. 🤔

**Comment by scrumthing** [comment]
Okay, I looked more and found the following difference between the two commits. The UIData gets changed. Very strange. Isn't that one of those fields which only exists to be compatible with old architect?
![arc_GitIntegration01](https://user-images.githubusercontent.com/8442014/106942347-5f487600-6724-11eb-9894-e7e66e112e8e.PNG)

**Comment by rclapp** [comment]
Seems like the JSON string encoding is different, that is an odd one.

**Comment by scrumthing** [comment]
Yes. It definitely is. Not sure if I should address this with IBM or if it is a frontend thing. Maybe the headers between tm1py and the arc plugin are different. But to be honest I have no clue.

**Comment by MariusWirtz** [comment]
This is definitely related to encoding. I think Arc does something differently than TM1py.

**Comment by scrumthing** [comment]
But how can that be an issue if the processes are untouched. Very confusing and totally annoying because you now have useless changes documented. :-/
Maybe I will open an issue with the other guys and tell them it is their fault because tm1py is the de-facto standard for interacting with the tm1 rest api. :-D

**Comment by cubewise-tryan** [comment]
It looks like the one on the right is not encoded with UTF-8. The separator in the UIData is the "form feed" character which appears on the left.

**Comment by MariusWirtz** [comment]
Hi @scrumthing,

please install the issue branch and see if it resolves the issue
`pip install https://github.com/cubewise-code/tm1py/archive/issue/process-ui-data-encoding.zip --upgrade`

**Comment by scrumthing** [comment]
Hey @MariusWirtz , 
thanks for your help but unfortunately that does not fix the problem. It still does not work properly. 
But I think we are on the right track here. 

![Bug_Git_Python](https://user-images.githubusercontent.com/8442014/110533953-d192e880-811e-11eb-871b-c2d2edf4ce60.PNG)

**Comment by MariusWirtz** [comment]
It should have been resolved in the meantime.

@scrumthing, please reopen if this is still an issue.
