### ISSUE TITLE
Integrated Login from PAW session ?

### ISSUE THREAD

**Issue by Akaori** [cubewise-code/tm1py#482]
Supposing I want to add a external webpage inside PAW.

My objective: I want to avoid an extra login page inside PAW.

If I create a flask app running on docker, is it possible to use PAW (token or user credentials session) with tm1py ? 

Is it possible this scenario ?
1st - The user will sign in on PAW. 
2nd - Inside PAW the user will access an external webapp (using flask and tm1py)
3rd - Tm1py get the PAW token or credential (between tm1 and PAW) and can connect to tm1 without storing user password.

Can I accomplish this using something like this ?

```
with requests.Session() as session:
    session.verify = False
    session.headers["Content-Type"] = "application/json"
    session.headers["TM1-SessionContext"] = "TM1py"
    session.auth = HttpNegotiateAuth(domain=windowsdomain, service=servicename, host=spn, delegate=True)
    reply = session.get("https://db...:8050/api/v1/Configuration")
    sessioncookies = session.cookies.get_dict()
    session_id = sessioncookies["TM1SessionId"]

    tm1 = TM1Service(session_id=session_id, ssl=True, address=servername, port=instanceport)
```

I couldn`t install requests_negotiate_sspi on linux.

**Comment by rkvinoth** [comment]
`requests_negotiate_sspi ` is only for **windows**

**Comment by Akaori** [comment]
Thanks @rkvinoth. 
I will try on windows (without docker).

Do you think is it possible to get PAW section using integrated login in order to avoid an extra login page inside PAW ?

**Comment by Akaori** [comment]
I would like to understand how it works this session id.

If I sign in on PAW, my browser's cookies will generate a TM1SessionId code.

If I try to use it:

`tm1 = TM1Service(session_id="[UmiixxxxxxxxxxxkA].[yygExxxxxx4Ftc=]", ssl=True, address='168.xxx.xxx.xxx', port='1xxxx')`

I get `TM1pyRestException: Text:  Status Code: 401 Reason: Unauthorized Headers`

**Comment by rclapp** [comment]
TM1 session ID is usually just a AlphaNumeric string. I don’t recognize the format of your session ID. You’ll want to check that you have the right cookie.

**Comment by Akaori** [comment]
This is what appears when I sign in on PAW:

![image](https://user-images.githubusercontent.com/45232866/107406348-1a875b00-6ae7-11eb-81c6-7e41915fbf10.png)

On tm1py error, it seems this value is converted to AlphaNumeric:
`
Text:  Status Code: 401 Reason: Unauthorized Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'OData-Version': '4.0', 'Set-Cookie': 'TM1SessionId=E46hMiBVvCUr1vgJEPA;`

**Comment by rclapp** [comment]
Are you signing into multiple TM1 instances via PAW? My guess is that each of those TM1SessionId sections is a session on one of your servers.

**Comment by scrumthing** [comment]
If you have configured tm1 to use integrated login and security mode 3, in general it is possible to avoid passing credentials. But I am not sure if your browser can relay the windows authentication.

**Comment by Akaori** [comment]
Thanks for both answers. 

It seems only what is inside the first brackets is the session_id. 

I will try some tests.
