### ISSUE TITLE
Usage create_element_attributes_through_ti

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#485]
I'm struggling with how to use "create_element_attributes_through_ti".

I see in the code:
            statements = ["AttrInsert('{}', '', '{}', '{}');".format(dimension.name, ea.name, ea.attribute_type[0])
                          for ea
but I fail to understand where these ea values and properties are coming from.

I searched the examples, but alas...
Do you have an example how I could use this?

**Comment by MariusWirtz** [comment]
Hi @hermie64,

it's a list comprehension. The AttrInsert statements are created based on element_attributes property of the hierarchy.

``` python
            statements = ["AttrInsert('{}', '', '{}', '{}');".format(dimension.name, ea.name, ea.attribute_type[0])
                          for ea
                          in h.element_attributes]
```

The function is from 2017. I believe it was created because back then there was an issue in the REST API w.r.t. creating element attributes. The function is essentially obsolete in TM1 11.

**Comment by MariusWirtz** [comment]
So in TM1 11, to add an element attribute to a dimension/hierarchy, you can do it in a more straightforward way like this:

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    hierarchy = tm1.hierarchies.get(dimension_name='d1', hierarchy_name='d1')

    hierarchy.add_element_attribute(name='New Attribute', attribute_type='String')

    tm1.hierarchies.update(hierarchy)
```

**Comment by hermie64** [comment]
Hi @MariusWirtz,

OK, thanks for clarifying!
