### ISSUE TITLE
Check if cell is updateable

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/tm1py#486]
**Describe what did you try to do with TM1py**
I'm loading data through a cellset (as a user, not ADMIN), but some of the cells are not editable.
Which cells are not editable can't be defined upfront as it changes dynamically due to rules and security being dependent on time dimension.

**Describe what's not working the way you expect**
I would like to have an option/argument in write functions to skip noneditable cells similar to what can be achieved using 
CELLISUDATEABLE tm1 function.

**Version**
- TM1py: 1.6.0
- TM1 Server Version: 11.0.8

**Additional context**
N/A

**Comment by MariusWirtz** [comment]
Hi @macmaj,

You have to write custom logic to solve this problem. To know if a cell is editable you can execute an MDX and ask for the `RuleDerived`, `Consolidated` and `Updateable` properties.

So essentially, based on your cellset you create an MDX to find the cells that are not editable in TM1.
Then you remove those cells from your cellset and write the rest of the cells to TM1.

Kinda like this:


``` python
from mdxpy import MdxBuilder

from TM1py import TM1Service
from TM1py.Utils import cell_is_updateable, element_names_from_element_unique_names

cells = {
    ('Total', 'Total'): 1,
    ('e1', 'e1'): 1,
    ('e2', 'e2'): 1,
    ('e3', 'e3'): 1}

query = MdxBuilder.from_cube('c1')
for elements in cells:
    member_tuple = [f"[d1].[{elements[0]}]", f"[d2].[{elements[1]}]"]
    query.add_member_tuple_to_columns(*member_tuple)

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    data = tm1.cells.execute_mdx(
        mdx=query.to_mdx(),
        cell_properties=['Value', 'Updateable', 'RuleDerived', 'Consolidated'])

    for coordinates, cell in data.items():
        if cell['RuleDerived'] or cell['Consolidated'] or not cell_is_updateable(cell):
            del cells[element_names_from_element_unique_names(coordinates)]

    tm1.cells.write(cube_name='c1', cellset_as_dict=cells)

```

![image](https://user-images.githubusercontent.com/15182131/107932851-4ccd0880-6f7e-11eb-9d42-3cba0d714e18.png)

**Comment by macmaj** [comment]
Hi @MariusWirtz 

Thanks a lot, this is exactly what I was looking for.
