### ISSUE TITLE
dimensions.update behavior

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#487]
I’m trying to copy a dimension but I see some unexpected behavior. Not sure whether it’s me or TM1py?

If I copy a dimension from A >> B via dimensions.update, I see that elements of accompanying ElementAttributes dimension are also updated.
I noticed that if I run dimensions.update on the same ElementAttributes dimension afterwards, it then changes the type of all ElementAttributes to Numeric?

Next to that, if I manually add an element to ElementAttributes dimension, this element gets index 1. If I then use dimension.update on the dimension, the new element of ElementAttributes is added, but not with index 1, but with the last available index number?

**Comment by MariusWirtz** [comment]
Hi @hermie64,

are you saying that you use the `tm1.dimensions` functions to work on the `}ElementAttributes_` dimensions directly? 

Why don't you retrieve the full dimension/hierarchy and do the changes on the hierarchy object (like in #485)?

**Comment by hermie64** [comment]
Hi @MariusWirtz,

Re. "are you saying that you use the tm1.dimensions functions to work on the }ElementAttributes_ dimensions directly?"

Yes that's what I did initially, but then I found out that }ElementAttributes dimension is updated automatically when I use tm1.dimensions function on base dimension. So I skipped the }ElementAttributes part.
Then I noticed the issue with index numbers.

**Comment by MariusWirtz** [comment]
@hermie64,

OK. I believe with the REST API (and TM1py) we are not supposed to manipulate the `}ElementAttributes_` dimension directly. So I'm not surprised that the result isn't "satisfying".

Sorry, I'm not sure I fully understand the problem with attribute indexing. Do you perhaps have a small reproducible code sample?

**Comment by hermie64** [comment]
@MariusWirtz,

I manually add new attribute, for example, 'TEST' to GL_account dimension, this element 'TEST' then gets index number 1. 
I then execute following code to sync 'GL_account' with ' GL_account_2' and see that element 'TEST' Is added but not with index number 1 but with the last available index number.

dim_name_SRC = 'GL_account'
dim_name_TAR = 'GL_account_2'

dim_SRC = tm1_SRC.dimensions.get(dimension_name=dim_name_SRC)
dim_SRC.name = dim_name_TAR

tm1_SRC.dimensions.update(dim_SRC)

**Comment by MariusWirtz** [comment]
Hi @hermie64,

I understand. That's an issue in TM1py. Thanks for the catch!
We will write a fix.

**Comment by MariusWirtz** [comment]
Hi @hermie64,

this is actually a limitation of the TM1 REST API. Currently, the REST API doesn't allow to reorder element attributes. I will close this issue for the moment and re-open it once the REST API offers the functionality.
