### ISSUE TITLE
Cancel MDX query when timeout argument is specified in execute_mdx type of functions

### ISSUE THREAD

**Issue by macmaj** [cubewise-code/tm1py#489]
**Describe what did you try to do with TM1py**
I would like the timeout argument for execute_mdx to also cancel the thread on tm1 side.

**Describe what's not working the way you expect**
Currently timeout argument only cancels execute_mdx function and moves on in the python script, but the MDX query is still running in the background

**Version**
- TM1py 1.6.0
- TM1 Server Version: 11.0.8

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by MariusWirtz** [comment]
Hi @macmaj,

I like this idea very much. It will be a useful feature.
I'm a bit hesitant to use the existing `timeout` argument for it though. 

The `timeout` argument is used consistently throughout all TM1py functions. It would be inconsistent in a way, if the timeout argument aborts the MDX execution, but doesn't abort a TI execution. 

Perhaps we could introduce a new argument to the `execute_mdx_` functions, something like `cancellation_timeout`, that triggers a timeout but also aborts the operation on the server.

What do you think? Any other opinions on this one?

**Comment by macmaj** [comment]
Sounds good to me, but what seems more natural to me is a boolean argument cancel_after_timeout (or something similarly named) that would be checked after timeout runs out and if set to True it would not only cancel python script but also MDX query.

**Comment by MariusWirtz** [comment]
I agree with you @macmaj. Let's do it that way.

**Comment by MariusWirtz** [comment]
@macmaj,
the `cancel_at_timeout` argument should now work on all functions in TM1py. Please upgrade to the feature branch and confirm that it works for you.

`pip install https://github.com/cubewise-code/tm1py/archive/feature/cancel-at-timeout.zip --upgrade`

``` python
from TM1py import TM1Service
from TM1py.Exceptions import TM1pyTimeout

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple", async_requests_mode=False) as tm1:
    try:
        data = tm1.cells.execute_view("Big Cube", "Default", timeout=1, cancel_at_timeout=True)

    except TM1pyTimeout:
        pass
```

**Comment by macmaj** [comment]
Hi @MariusWirtz 
I confirm, it works.
Thanks!
