### ISSUE TITLE
Error when passing user: None in kwargs to RestService

### ISSUE THREAD

**Issue by BenStruwe** [cubewise-code/tm1py#490]
This fails if user is present in kwargs but None. 
Maybe enhance the check here.

https://github.com/cubewise-code/tm1py/blob/8bc19d6cfd8e9ced2867d7a9eeaea9423e5ec256/TM1py/Services/RestService.py#L148

**Comment by rclapp** [comment]
Thanks Ben, this and the password check was causing me pain as well.

**Comment by MariusWirtz** [comment]
@BenStruwe thanks for the catch. It is fixed in #492 

@rclapp I don't fully understand which password check you mean.

**Comment by rclapp** [comment]
Maybe it was just the user one then. In our connection wrapper when using SSO we initialize the TM1Service with user and password set to None. I assumed that if user had the issue password would too.

**Comment by BenStruwe** [comment]
Thanks Marius for the quick fix!
