### ISSUE TITLE
The best way to copy data of the same Cube from one TM1 server to another

### ISSUE THREAD

**Issue by kondor20** [cubewise-code/tm1py#491]
The best way which I found is:
1. connect to source tm1_source
2. connect to target tm1_target
3. Create View of Target Cube and zero it
`    mdx_view = MDXView(cube_name='Cube_name', view_name='zero_view', MDX=mdx2)
    tm1_target.cubes.views.create(view=mdx_view)

    ti_statements = [
        "ViewZeroOut('Cube_name', 'zero_view');"
    ]
    tm1_target.processes.execute_ti_code(lines_prolog=ti_statements, lines_epilog=[])`

where mdx2 - mdx view which I want to zero

4. Create panda dataframe from mdx3 view (there all dimensions-1 in rows and last dimension in column
`    cells1 = tm1_source.cubes.cells.execute_mdx_dataframe(mdx3)`

5.  Transform panda dataframe in cellset
   cellset1 = build_cellset_from_pandas_dataframe(cells1)

6. Put cellset in target_cube using async
`results = event_loop.run_until_complete(write_async(tm1_target, cellset1))`
where write_async is
`tm1.cells.write(cube_name="BCube_name", cellset_as_dict=chunk, use_ti=True)`

The narrow place which I see is 4 and 5 steps because transformation from dataframe to cellset takes time. Is it possible to create cellset on step 4 which will be compatible with write function on step 6?

**Version**
- TM1py [e.g. 1.6] 
- TM1 Server Version: [e.g. 2.0.9]

**Comment by MariusWirtz** [comment]
Hi @kondor20,

yes. You don't need to retrieve data as a data frame.

You can retrieve data as a dictionary instead. Actually, I just made a change to the `execute_mdx` function, so that it can return a dictionary that can be passed to the `write` function without any transformations.

You can upgrade to the feature branch
`pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/master.zip --upgrade`

And use the `execute_mdx` function with the new arguments (`element_unique_names` and `values_only`) :

``` python
from TM1py import TM1Service

mdx = """
SELECT
{Tm1SubsetAll([d1])} ON 0,
{Tm1SubsetAll([d2])} ON 1
FROM [c1]
"""

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    data = tm1.cells.execute_mdx(mdx, element_unique_names=False, values_only=True)

    print(data)

```

**Comment by kondor20** [comment]
Thank you Marius
I checked and it works.

Unfortunately  I noticed:
`
cells1 = tm1_source.cubes.cells.execute_mdx_dataframe(mdx3)
+
cellset1 = build_cellset_from_pandas_dataframe(cells1)
`
works faster than 
`
data = tm1.cells.execute_mdx(mdx, element_unique_names=False, values_only=True)
`

May be it is possible to do something with speed of:
`data = tm1.cells.execute_mdx(mdx, element_unique_names=False, values_only=True)`
?

**Comment by MariusWirtz** [comment]
Could it be that `execute_mdx_dataframe` is only faster because it has the `skip_zeros` to `True` by default? 

Please try to run `execute_mdx` with `skip_zeros=True`

**Comment by kondor20** [comment]
Marius, thank you for reply
1. First of all I used `Select NON EMPTY` in MDX. I checked `skip_zeros=True` in `execute_mdx` and results are the same.
In my example I transfer ~ 80000 elements.
it takes ~ 13 sec in case `execute_mdx_dataframe` + `build_cellset_from_pandas_dataframe`
and ~ 21 sec in case `execute_mdx(mdx, element_unique_names=False, values_only=True, skip_zeros=True)`

2. Also I noticed if I use 
`execute_mdx_dataframe` + `build_cellset_from_pandas_dataframe` i have to write MDX with order of dimension like in Cube. If use another order - I receive error in `write`

but if I use
`execute_mdx(mdx, element_unique_names=False, values_only=True, skip_zeros=True)`
it doesn't matter order of dimension in MDX
