### ISSUE TITLE
Issue with authentication in pandas read csv

### ISSUE THREAD

**Issue by ards14** [cubewise-code/tm1py#495]
Hi All,

How do I get URL authentication to work using pandas read csv.

Below is how i am trying to pass the URL, since URL is authenticated i am not sure about the syntax to provide username and password. Could you please suggest.
 df = pd.read_csv("https://sftp.xxxx.com/api/v1.0/files/TM1/SAND/IN/Test.csv")

**Comment by MariusWirtz** [comment]
Hi @ards14,

better to search the answer on StackOverflow. It's not related to TM1py.

Maybe take a look here:
https://stackoverflow.com/questions/51062176/pandas-read-data-from-a-secure-ftp-server-in-python-3
