### ISSUE TITLE
on dimensions.update: "Cannot destroy a Leaves hierarchy"

### ISSUE THREAD

**Issue by JamesDMiller1969** [cubewise-code/tm1py#497]
how do i resolve this issue?
Message=Text: '{"error":{"code":"276","message":"Cannot destroy a Leaves hierarchy"}}' - Status Code: 400 - Reason: 'Bad Request' - Headers: {'Date': 'Thu, 25 Feb 2021 19:45:35 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'Content-Length': '87', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0', 'X-Content-Type-Options': 'nosniff', 'Connection': 'close'}

**Comment by MariusWirtz** [comment]
Please upgrade to the latest version of tm1py on Github

`Pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`

I will push this fix to PyPI tomorrow.

**Comment by JamesDMiller1969** [comment]
> Please upgrade to the latest version of tm1py on Github
> 
> `Pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`
> 
> I will push this fix to PyPI tomorrow.

I am on the latest version 1.6 - are you saying there is a newer version?

**Comment by MariusWirtz** [comment]
1.6 is the latest release on PyPI. The fix is already included in the master branch on GitHub.

Tomorrow I will push the fix to PyPI as 1.6.1.

**Comment by MariusWirtz** [comment]
1.6.1 is now available on PyPI. Please upgrade to the latest version and verify if it resolved the issue.

`pip install tm1py --upgrade`

**Comment by JamesDMiller1969** [comment]
Thank-you. the error is resolved.
