### ISSUE TITLE
How to sort by hierarchy order in Power BI?

### ISSUE THREAD

**Issue by carltoncheung** [cubewise-code/tm1py#500]
**Describe what did you try to do with TM1py**
We are trying to sort dimension members by hierarchy order in Power BI

**Describe what's not working the way you expect**
After bringing dimension members and hierarchy parent nodes into Power BI using `tm1.power_bi.get_member_properties`, we'd like to create a report in Power BI where the children of a parent are displayed in the same order as in TM1 hierarchy.

However since `tm1.power_bi.get_member_properties` doesn't return any sort order column, it's not possible to replicate the same sorting order in Power BI.

Is it possible to extract the hierarchy sort order from TM1 into Power BI?

In the following example, the structure of the hierarchy in Power BI is correct. However the order in which children of a parent are displayed is not the same as the hierarchy in TM1:
 
Hierarchy order in TM1:
![image](https://user-images.githubusercontent.com/63375086/109586155-d7099500-7b58-11eb-87b9-747c59be9a1a.png)

Hierarchy order in Power BI:
![image](https://user-images.githubusercontent.com/63375086/109586189-e1c42a00-7b58-11eb-9348-19e42b282549.png)

Thanks,
Carlton

**Comment by MariusWirtz** [comment]
As Roy suggested, it would easier to add an attribute in the model and populate it with a sort order value, when the dimension is created/updated by a process.
