### ISSUE TITLE
build_headers_from_cellset - support for Calculated Members in MDX Queries

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/TM1py#51]
@DJHig ,
the build_headers_from_cellset function can't consume cellsets that were generated from MDX Queries with calculated members.

When I use it with the following Query:
```
    WITH MEMBER [Date].[First 2 Month] AS AGGREGATE({[Date].[2017-01], [Date].[2017-02]})
    SELECT 
    NON EMPTY {[Date].[First 2 Month], [Date].[2017-01]:[Date].[2017-12]} on ROWS, 
    NON EMPTY {[City].[NYC], [City].[Chicago], [City].[Washington]} on COLUMNS  
    FROM [Bike Shares] 
    WHERE ([Bike Shares Measure].[Count],[Version].[Actual]) 
```
I get this error:
Traceback (most recent call last):
  File "C:/Projects/TM1py-samples/Query Data/mdx_query_different_formats.py", line 80, in <module>
    array = tm1.cubes.cells.execute_mdx_ui_array(mdx, value_precision=1)
  File "C:\Anaconda3\lib\site-packages\TM1py\Services\CellService.py", line 409, in execute_mdx_ui_array
    return Utils.build_ui_arrays_from_cellset(raw_cellset_as_dict=data, value_precision=value_precision)
  File "C:\Anaconda3\lib\site-packages\TM1py\Utils\Utils.py", line 147, in build_ui_arrays_from_cellset
    header_map = build_headers_from_cellset(raw_cellset_as_dict, force_header_dimensionality=3)
  File "C:\Anaconda3\lib\site-packages\TM1py\Utils\Utils.py", line 254, in build_headers_from_cellset
    for member in tuples_as_dict]
  File "C:\Anaconda3\lib\site-packages\TM1py\Utils\Utils.py", line 254, in <listcomp>
    for member in tuples_as_dict]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by MariusWirtz** [comment]
solution probably similar to fix for other execute_mdx functions:
https://github.com/cubewise-code/TM1py/pull/49/files

**Comment by DJHig** [comment]
@MariusWirtz, 
Ok, I will take a look. Probably cannot get to it for a few days.
Also, I noticed you added a member_properties to the parameters; I think this is the same as elem_properties was supposed to be. I have not pulled to code to check yet.

**Comment by MariusWirtz** [comment]
Generally, the relationship between elements and members is 1 to n as an element can be part of n consolidations.
The calculated members don't have an underlying element though! the was the issue with the build_content_from_cellset function. I adapted the function to return the member unique name, if the member does not have a reference to an element

**Comment by DJHig** [comment]
Hi @MariusWirtz ,
I have not used Aggregate in MDX queries. 
I'm trying to test the query from the Planning Sample server with similar changes as you demonstrated above and it crashes the server (PA 2.0.4). When I use it with an aggregate function (like sum, max, count, etc), I get an error (Bad Request) from the server with a syntax error at the function. What am I missing?

```
WITH MEMBER [plan_time].[H1-2004] AS AGGREGATE( { [plan_time].[Q1-2004], [plan_time].[Q2-2004] } )
SELECT
        NON EMPTY { [plan_time].[H1-2004], [plan_time].[Q3-2004], [plan_time].[Q4-2004] } on COLUMNS,
        NON EMPTY { [plan_chart_of_accounts].[Revenue], [plan_chart_of_accounts].[Net Operating Income] } on ROWS
FROM [plan_Report]
WHERE (
            [plan_business_unit].[Total Business Unit], 
            [plan_department].[Total Organization],
            [plan_exchange_rates].[actual],
            [plan_report].[Budget]
            )
```

**Comment by MariusWirtz** [comment]
Hi @DJHig ,
could be an issue in PA 2.0.4. 
Does this one work?

```
	WITH MEMBER [plan_time].[H1-2004] AS [plan_time].[Q1-2004] + [plan_time].[Q2-2004]
	SELECT
	NON EMPTY { [plan_time].[H1-2004], [plan_time].[Q3-2004], [plan_time].[Q4-2004] } on COLUMNS,
	NON EMPTY { [plan_chart_of_accounts].[Revenue], [plan_chart_of_accounts].[Net Operating Income] } on ROWS
FROM [plan_Report]
WHERE (
            [plan_business_unit].[Total Business Unit], 
            [plan_department].[Total Organization],
            [plan_exchange_rates].[actual],
            [plan_report].[Budget]
            )
```

**Comment by DJHig** [comment]
Hi Marius,

Yes, I was able to use the + version to create the aggregate query. I just created a PR with a fix.

**Comment by MariusWirtz** [comment]
Thank you. I will check out the PR.
The server crash is reproducible on 11.3. We reported it to IBM.
