### ISSUE TITLE
Executing a TM1 TI process from TM1py with parameters

### ISSUE THREAD

**Issue by brianknott** [cubewise-code/tm1py#511]
**Describe what did you try to do with TM1py**
I want to execute a process on the TM1 server.  This process required parameters.  

**Additional context**
Some code is pasted below.
I am using execute_process_with_return.  I can execute a process, jus not with paramaters.  How do I add parameter to the Process class below.

```
from TM1py import Process
from TM1py.Services import TM1Service

process = Process(name="dim.Oracle could update - MASTER")
success, status, error_log_file = tm1.processes.execute_process_with_return(process)
if success:
   print("Process executed successfully")
else:
   print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)
```

**Comment by rkvinoth** [comment]
```PYTHON
from TM1py import Process
from TM1py.Services import TM1Service


tm1 = TM1Service()

# Get the existing process
process = tm1.processes.get(name="dim.Oracle could update - MASTER"))

# Define the parameters you want to pass
parameters = {"pYear": "2021", "pModel": "LRP"}

# Pass the parameter by unpacking the dictionary
success, status, error_log_file = tm1.processes.execute_process_with_return(process, **parameters)
if success:
   print("Process executed successfully")
else:
   print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)
```

**Comment by MariusWirtz** [comment]
Hi @brianknott,

there are two functions to execute processes. 

> execute_with_return

`execute_with_return` executes an existing process.

``` python
from TM1py.Services.TM1Service import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    success, status, error_log_file = tm1.processes.execute_with_return(
        process_name="Bedrock.Server.Wait",
        pWaitSec="2")

    print(success)
```

> execute_process_with_return

`execute_process_with_return` executes the passed process as an unbound process. It means the process gets executed without ever being registered.  Thy typical use case for this is if you need to do something that can't be done through REST, like a SecurityRefresh.

``` python
from TM1py import Process
from TM1py.Services.TM1Service import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    process = Process(name="", prolog_procedure="SLEEP(2000);")

    success, status, error_log_file = tm1.processes.execute_process_with_return(process)

    print(success)
```

To pass parameters you can pass them as keyword arguments (case sensitive!)
I hope this helps!

**Comment by brianknott** [comment]
Thanks @MariusWirtz and @rkvinoth.,  

Under normal circumstances I would use the execute_with_return, unless I am doing a lot of data and need speed. 
Is that correct?

**Comment by brianknott** [comment]
Got some new code.  It works in that it calls the procedure but it is not passing the parameters.  If I dump out the parameter in the TI process it is the default value not the passed value

```
    process = tm1.processes.get(name_process="dim.Oracle cloud update - MASTER")
    parameters = {"pFileName":filetosave}
    success, status, error_log_file = tm1.processes.execute_process_with_return(process, **parameters)
    if success:
        print("Process executed successfully")
    else:
        print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)
```

**Comment by MariusWirtz** [comment]
Hi @brianknott,

yes. You can use the `execute_process_with_return` to execute an unbound process that is loaded with `CellPutN` statements.
However, it doesn't really make sense to do it because we offer you the `use_ti=True` option in the `write` method, which does exactly that and takes care of the little things that could go wrong (e.g. formatting of numbers, maximum statements per tab). Sample:

``` python
from TM1py.Services.TM1Service import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    cells = {
        ('e1', 'e2'): 12.4,
        ('e3', 'e1'): 4.5
    }

    tm1.cells.write('c1', cells, use_ti=True)
```

The parameters are case-sensitive. Does your parameter name (`pFileName`) match the casing of the actual parameter?
For your use case, I would advice to use the `execute_with_return` function instead of the `execute_process_with_return`. It is more straightforward since the process already exists and it will create better log entries in the TM1 server log.

**Comment by brianknott** [comment]
Thanks @MariusWirtz .  Got it to work with the code below

```
processname="dim.Oracle cloud update - MASTER"
filename = loadFile + now + ".csv"
    success, status, error_log_file = tm1.processes.execute_with_return(process_name=processname,pFileName=filename)
    #success, status, error_log_file = tm1.processes.execute_proecss_with_return(process, **parameters)
    if success:
        print("Process executed successfully")
        # move the file on the SFTP server to the loaded directory
        filetomove = OracleLoadedDir + loadFile + now + ".csv"
        sftp.rename(filetoload, filetomove)
    else:
        print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)
        # move the file on the SFTP server to the error directory
        filetomove = OracleErrorDir + loadFile + now + ".csv"
        sftp.rename(filetoload, filetomove)
```

**Comment by vamsi-cloud** [comment]
Hi 
I am Trying to Execute TI from TM1py .Below is the TI and Parameters passed

process = tm1.processes.get(name_process="Python_Export_External_FTE")
parameters = {"Scenario": "2EA", "Version": "Final Version","Year": "2021"}
success, status, error_log_file = tm1.processes.execute_process_with_return(process, **parameters)

In this process TI is executing fine but **it is not taking the parameters that i passed in the above script**

please help me out in this

**Comment by rkvinoth** [comment]
It should work. Try `Logoutput`/`asciioutput` and check what parameter it is taking.

**Comment by vamsi-cloud** [comment]
I took export .It is taking Already saved parameters in TI but not the input parameters defined in TM1py

**Comment by rkvinoth** [comment]
1. Which TM1py version are you using?
2. Are you passing all the required parameters?

Hope you don't have any typo in the parameter names.
The same code works for me (with a different TI obviously).

**Comment by vamsi-cloud** [comment]
1.6.2 is the version we are using and the parameters are correct

**Comment by vamsi-cloud** [comment]
1.5.0 & 1.6.2 & 1.7.0 we tried with these three versions of TM1py

**Comment by rkvinoth** [comment]
> With 1.7.0 or above: this will work

```python
    process = tm1.processes.get(name_process=""Python_Export_External_FTE")
    parameters = {"Scenario": "2EA", "Version": "Final Version", "Year": "2021"}
    success, status, error_log_file = tm1.processes.execute_process_with_return(process, **parameters)
```

> with any version: use

```python
    process = tm1.processes.get(name_process=""Python_Export_External_FTE")
    process.remove_parameter(name='Scenario')
    process.add_parameter(name='Scenario', prompt='', value='2EA')
    process.remove_parameter(name='Version')
    process.add_parameter(name='Version', prompt='', value='Final Version')
    process.remove_parameter(name='Year')
    process.add_parameter(name='Year', prompt='', value='2021')
    success, status, error_log_file = tm1.processes.execute_process_with_return(process)
```
or 
```python
    process = tm1.processes.get(name_process=""Python_Export_External_FTE")
    for parameter in process.parameters:
        if parameter['Name'] == 'Scenario':
            parameter['Value'] = '2EA'
        if parameter['Name'] == 'Version':
            parameter['Value'] = 'Final Version'
        if parameter['Name'] == 'Year':
            parameter['Value'] = '2021'
    success, status, error_log_file = tm1.processes.execute_process_with_return(process)
```

**Comment by vamsi-cloud** [comment]
It worked thanks @rkvinoth
