### ISSUE TITLE
Sample code for sandbox manipulation?

### ISSUE THREAD

**Issue by dusherwo57** [cubewise-code/tm1py#513]
**Describe what did you try to do with TM1py**
I'm working with the new sandbox functionality with the aim of identifying sandbox content created by non-admin (using Impersonate) then manipulating it eg by updating the base data (potentially to a different element). I am struggling with the objects returned by the sandbox methods and properties. It would be good to see some samples.
eg:

sbs = tm1a.sandboxes.get_all
            print (sbs)
returns
<bound method SandboxService.get_all of <TM1py.Services.SandboxService.SandboxService object at 0x215E6418>>
with no obvious way to move to picking up sandboxes and identifying content.

**Version**
- TM1py 1.6
- TM1 Server Version: 11.0.95.13-0

**Comment by MariusWirtz** [comment]
For the `SandboxService` you can find samples in the test suite  [here](https://github.com/cubewise-code/tm1py/blob/master/Tests/SandboxService.py)

For the `write`, `execute_mdx...`, `execute_view...` functions you can just pass the additional `sandbox_name` argument

I hope this helps.

**Comment by dusherwo57** [comment]
It does, many thanks. I will check out the test suite more closely in future.
