### ISSUE TITLE
Unable to run a saved TM1py script from Jupyter Notebook

### ISSUE THREAD

**Issue by ards14** [cubewise-code/tm1py#514]
Hi All,

I have saved a TM1py script to move file between 2 SFTP servers, Script works fine when it run from a new notebook.
However when the notebook is saved and reopened in the next session it fails with "NameError: name 'paramiko' is not defined".

Sample Code :

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(hostname = "sftp.xxx-xxx.com",username  = 'xxxx', password = 'xxxxx', port=22)
    sftp_client = ssh.open_sftp()
    sftp_client.get('source','dest')
    sftp_client.close()
    ssh.close()
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(hostname = 'sftp-xx.planning-analytics.xxxx.com',username  = 'xxxx', password = 'xxxxx',port = 22)
    sftp_client = ssh.open_sftp()
    sftp_client.put('source','dest')    
    sftp_client.close()
    ssh.close()

**Comment by MariusWirtz** [comment]
Not a  TM1py question, but are you perhaps missing the `import paramiko` statement at the top of your script?

**Comment by ards14** [comment]
Hi Marius,

I have included the import statement on the top.
import paramiko
from TM1py import TM1Service

I have installed TM1py in 2 different servers and saved the script with same name in both places, will it be the cause?

**Comment by MariusWirtz** [comment]
Please post the error that you receive when you run the script
