### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by JamesDMiller1969** [cubewise-code/tm1py#518]
after successful connection is made and our python script is running, Is seems like at times if a PA server is or becomes busy? We get: “Remote end closed connection without response” and obviously the connection is dropped and our script raises the error and cannot continue.

**Comment by MariusWirtz** [comment]
Hi @JamesDMiller1969,

are you working with TM1 in the IBM cloud?
If yes, the `TM1Service `needs to be created slightly differently to work around the hard 60s timeout on the IBM cloud infrastructure.
https://code.cubewise.com/tm1py-help-content/connecting-to-the-ibm-cloud-remotely-with-tm1py

**Comment by JamesDMiller1969** [comment]
yes we are using the IBM cloud. was missing the "verify=True" so will give that a try. Will requesting the timeout be increase resolve this?

**Comment by MariusWirtz** [comment]
Actually, the key parameter is the `async_requests_mode =True`.

In this mode, TM1py doesn't wait for REST API Operations to complete, but it asks the server to do an operation and then checks every 1 sec if it completed.

**Comment by MariusWirtz** [comment]
Do you have a piece of code that you can post, that reproduces the error?

**Comment by MariusWirtz** [comment]
I understand that not all operations fail. Like the initial connection (`TM1Service(...)`) is established successfully and then further down the road some operation fails. is that correct?

**Comment by JamesDMiller1969** [comment]
Not all operations fail, the initial connection (TM1Service(...)) is established successfully and then further down the road some operation fails. 
Other times it "seems" that if a PA server is busy then the connection attempt fails

**Comment by MariusWirtz** [comment]
It doesn't look like a TM1py issue to me. I think you may need to bring this up with the IBM cloud support. 
This kind of occasional failure of REST operations looks more like an issue on the server/cloud side.

One last thing you can try though is to upgrade to the most recent version of TM1py. We introduced the `async_requests_mode` about 2 years ago. Perhaps your TM1py installation predates that change.

**Comment by JamesDMiller1969** [comment]
so we found that playing with the "timeout" number makes a difference:

with TM1Service(**config[tm1_target_server], timeout=4800) as tm1:

**Comment by MariusWirtz** [comment]
Hi @JamesDMiller1969,

I'm glad it works. I'm surprised the timeout argument makes the difference though.

I will close the ticket for now. Feel free to re-open.
