### ISSUE TITLE
Git Integration & Python

### ISSUE THREAD

**Issue by harveyca307** [cubewise-code/tm1py#519]
**Describe what did you try to do with TM1py**
I have a client wanting to use Git for their SDLC with PA.  I see there is Git integration in TM1PY, but have not implemented this functionality yet.  Are there some samples or documentation that I can use to get up to speed on the Git usage?  I eventually want to write a Python script for the client to use.

**Describe what's not working the way you expect**
There is nothing inherently not working, I just have a knowledge gap on using the Git functionality of TM1PY.  Need guidance

**Version**
- TM1py 1.6.2] 
- TM1 Server Version: 2.0.9.6

**Additional context**
There also seems to be a line missing from the "\_\_init\_\_.py" in the Services namespace.  I added

``` Python
from TM1py.Services.GitService import GitService
```
to my local copy to be able to enable the Git intellisense:

``` Python
from TM1py.Services import TM1Service

with TM1Service(**config[instance_name]) as tm1:
    tm1.git.git_init()
```

**Comment by scrumthing** [comment]
IMHO so far the best description of the git integration comes from @ykud.

https://www.ykud.com/blog/cognos/tm1-cognos/git-integration-for-tm1-part-1/
https://www.ykud.com/blog/cognos/tm1-cognos/git-integration-for-tm1-part-2/

The official ibm documentation is filled with wrong samples and useless descriptions. 
https://www.ibm.com/support/knowledgecenter/SSD29G_2.0.0/com.ibm.swg.ba.cognos.tm1_rest_api.2.0.0.doc/tm1_md/tm1-source-specification.html#tm1-project

**Comment by harveyca307** [comment]
Thanks Christoph, that was what I needed,
