### ISSUE TITLE
float object cannot be interpreted as an integer line 525 in wait_time_generator

### ISSUE THREAD

**Issue by JamesDMiller1969** [cubewise-code/tm1py#527]
When a tm1 server is very busy, we receive this error when trying to connect or cellset put

**Comment by MariusWirtz** [comment]
Could it that you are parsing a float value as the `timeout`?

I will adjust the code to convert the timeout to int before calling the `range` function

**Comment by MariusWirtz** [comment]
Issue should be resolved now. Just pushed a new commit to the master branch on GitHub. 

Please verify.

**Comment by JamesDMiller1969** [comment]
We will update, test and let you know. Thank-you!

**Comment by JamesDMiller1969** [comment]
resolved
