### ISSUE TITLE
Format Execute_mdx

### ISSUE THREAD

**Issue by benzaklb** [cubewise-code/TM1py#53]
Hello , 

I would know if it's possible to have the same rows and columns that a view. 
For example, when i make a view, i define rows and columns ( like a crosstab) but when i want to get data by a dataframe ( or by csv) i have only data by row

this is my code : 
```
mdx = tm1.cubes.views.get_native_view(cube_name, view_name, private=False).as_MDX
content = tm1.cubes.cells.execute_mdx_get_dataframe(mdx)
```

thank you
Laurent

**Comment by MariusWirtz** [comment]
Hi,

no. TM1py does not (yet) give you a dataframe in the shape of the original view / MDX Query.

If you need the arranged data to be in a dataframe, there are different ways to get there.
You could rearrange the data in the dataframe with the pivot method:

```
mdx = """
SELECT 
NON EMPTY {[Date].[2017-01], [Date].[2017-02]} on ROWS, 
NON EMPTY {[City].[NYC], [City].[Chicago], [City].[Washington]} on COLUMNS  
FROM [Bike Shares] 
WHERE ([Bike Shares Measure].[Count],[Version].[Actual]) 
"""

data = tm1.cubes.cells.execute_mdx(mdx)
df = Utils.build_pandas_dataframe_from_cellset(data, multiindex=False)
df.drop(columns=["Version", "Bike Shares Measure"], inplace=True)
pivot = df.pivot(index="Date", columns="City", values="Values")
print(pivot)
```

If you need the data for visualization purposes I suggest you check out the execute_mdx_ui_array and execute_mdx_ui_dygraph functions:
```
pp = pprint.PrettyPrinter(indent=2)

mdx = """
SELECT 
NON EMPTY {[Date].[2017-01], [Date].[2017-02]} on ROWS, 
NON EMPTY {[City].[NYC], [City].[Chicago], [City].[Washington]} on COLUMNS  
FROM [Bike Shares] 
WHERE ([Bike Shares Measure].[Count],[Version].[Actual]) 
"""

data = tm1.cubes.cells.execute_mdx_ui_array(mdx, value_precision=3)
pp.pprint(data)
```
