### ISSUE TITLE
Feedback of the write_values function 

### ISSUE THREAD

**Issue by il66ezov** [cubewise-code/tm1py#530]
**Describe what did you try to do with TM1py**
I have written a script by which the user automatically logs into TM1 and then can write sales numbers for different months into the Sales_Cube.  

**Describe what's not working the way you expect**
There are three months for which the user should enter sales numbers. 
If the user has permissions for all three months, there is no problem with the write_values function. 
If the user does not have authorization for all three months, he will get an error message that there is no authorization to write. 
The problem is, if he has authorization for only one month, the data for the authorized month is written to TM1, but the user does not receive any feedback that he lacks authorization for the two other months. 

How to solve the problem? As I think it makes a lot of sense that the user gets the feedback that not all his data could be written to TM1.

**Version**
- TM1py 1.6.2

**Comment by MariusWirtz** [comment]
Hi @il66ezov,

I agree with you. If the operation is not entirely successful a TM1pyException should be raised.

I can't replicate the described behavior. I'm running TM1 version 11.8.00300.33.
For me the write operation fails with this error: `CubeCellWriteStatusElementNoWriteAccess`

What version are you on?

**Comment by il66ezov** [comment]
Hello @MariusWirtz,

thank you for the quick response. 

I'm running TM1 Version 11.8.00300.34.

**Comment by il66ezov** [comment]
Hello @MariusWirtz,

in the meantime I have solved the problem, I had a programming bug .....
Get now the same error message as you.
