### ISSUE TITLE
RuntimeError: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

### ISSUE THREAD

**Issue by hornyakap1** [cubewise-code/tm1py#533]
Good Afternoon,

We are currently trying to use Python to Pull data from the REST API in two of our Planning Analytics applications. We use IntegratedSecurityMode 5 and have our Active Directory leverage CAM Authentication from our Cognos Analytics environment. All necessary firewalls are open. I tried running two separate scripts and got the same error (below) pointing to the _build_authorization_token_cam in the RestService.py script. Any information would be helpful. I checked with our system engineer and there shouldn't be any security software sitting on our Cognos Analytics servers blocking API calls. Any information would be greatly helpful. I saw there was a prior solution to use Selenium and a Chrome plug-in but was not entirely sure how to go about testing that out.

RuntimeError: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

**Comment by rkvinoth** [comment]
Do you have SSO enabled / Are you able to login to architect or tm1web without passing credentials?

**Comment by hornyakap1** [comment]
we do not. when we log into Architect (TM1) or Workspace (PA) we have to enter our credentials

**Comment by rkvinoth** [comment]
Follow this page to connect using usn and pwd

Look at: https://code.cubewise.com/tm1py-help-content/category/Configuration

**Comment by hornyakap1** [comment]
Thank You! That worked! I was able to utilize the code to successfully connect to the REST API of our environments using Python.

**Comment by dadhichvedant** [comment]
Hey @MariusWirtz and @rkvinoth, I'm getting the same error and not sure why. The link above doesn't work anymore.
Is there an updated link?

I have SSO on and when i run the below script, i get the following error:
RuntimeError: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

Script:
from TM1py import TM1Service
with TM1Service(address="xyz.com", port=8050, user="Adm", password="apple" ,ssl=True, gateway="gateway uri",namespace="LAXD") as tm1:
    print(tm1.server.get_product_version())
