### ISSUE TITLE
Comparison ElementAttribute to list of names of ElementAttributes

### ISSUE THREAD

**Issue by BenStruwe** [cubewise-code/tm1py#536]
This is not an error but caught my eye while debugging.

I think the comparison of the ElementAttribute Object against the list of names could be more explicit by also using the name. I know the __eq__ function within ElementAttribute takes care of this.

https://github.com/cubewise-code/tm1py/blob/c7756f6f3d8ff725c19bfbd854699abd5710a625/TM1py/Services/HierarchyService.py#L144

**Comment by rkvinoth** [comment]
@BenStruwe I bet it is for a clean looking script and perform the check on the backend. The code is not too implicit and I believe it still follows the Zen of Python.

But yes, for someone new to python like myself it looks bugging!

**Comment by BenStruwe** [comment]
Hey @rkvinoth , you are right. It just felt odd to check against the list of names when the list of objects was also present.  The creation of the list of names seems unnecessary for both the following create  and delete loops although there maybe a deeper reason to do so.

Not in any way a functional issue.

**Comment by MariusWirtz** [comment]
Hi @BenStruwe,

thanks for the feedback! I appreciate it.
I agree it would increase the readability if we wrote `if element_attribute.name not in element_attribute_names:` instead. 

Please feel free to create a PR for this or other enhancements that you have in mind
