### ISSUE TITLE
cannot connect to TM1 with IntegratedSecurityMode=2

### ISSUE THREAD

**Issue by crittgerott** [cubewise-code/tm1py#537]
Hello,
**Problem:** After Installation Python 3.9 and TM1Py 1.6.2 I try to connect on the Server direct to our TM1 Systems with check.py. But i get two different Error Messages, first if I try to connect via localhost I get the error incorrect proxy and second if I try to connect via Full Server Name I get the error blocked by firewall.

First Checks with internal IT from the customer: no irregularities on the server.

Do you have an Idea why we cannot connect via TM1Py to the TM1 Server?
![000674-403 Forbidden_ incorrect proxy service was requested](https://user-images.githubusercontent.com/77775399/116090348-101b3d00-a6a4-11eb-92c1-0b7130de89ad.jpg)
![000675-Access Denied](https://user-images.githubusercontent.com/77775399/116090365-127d9700-a6a4-11eb-84e6-438a85e917c2.jpg)

Thank you for your help.

Kind regards
Christian

**Comment by MariusWirtz** [comment]
Both issues proxy configuration and firewall restrictions look like they could be addressed by the local IT.
Maybe the server is fine, but some configuration on the client or network is required.

Don't think it's a TM1py issue.

**Comment by crittgerott** [comment]
Hi Marius,
I also think that is not really a TM1py issue. But if i want to connect on the server direct via tm1py to the PA system, is there something that call outside in the web? It is difficult for me to call the right persons of the local IT, because the last time, I talked to the Server Guys and they said, that everything is fine, but they also say, that something with the proxy could be the problem, but in this case they cannot help me. I hope you could help me, to give the right hints to thel local IT and Cyber Security guys. Thanks for your help.

Kind Regards
