### ISSUE TITLE
Installing tm1py in enterprise environment

### ISSUE THREAD

**Issue by edd1ploiesti** [cubewise-code/tm1py#542]
**Describe what did you try to do with TM1py**
python3.9 -m pip install ./tm1py-1.6.2.tar.gz

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. Install tm1py-1.6.2
2. I am trying to install tm1py on an enterprise environment (private cloud with no internet connection). I can't identify what libraries i'm missing from my python 3.9 based on the error log (see below)

**Version**
- TM1py [1.6.2]
- TM1 Server Version: [2.0.94]
- Python [3.9]
- Linux [RHEL 7]

**Additional context**
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aaf340>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aaff40>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0a47130>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aaf970>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aa4760>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
ERROR: Could not find a version that satisfies the requirement requests (from tm1py) (from versions: none)
ERROR: No matching distribution found for requests

**Comment by macsir** [comment]
Has your IT configured the firewall and opened the ports for you between TM1 server and the cloud?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: edd1ploiesti ***@***.***>
Sent: Friday, May 14, 2021 4:42:39 PM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cubewise-code/tm1py] Installing tm1py in enterprise environment (#542)


Describe what did you try to do with TM1py
python3.9 -m pip install ./tm1py-1.6.2.tar.gz

Describe what's not working the way you expect
Didn't get the expected result? Describe:

  1.  Install tm1py-1.6.2
  2.  I am trying to install tm1py on an enterprise environment (private cloud with no internet connection). I can't identify what libraries i'm missing from my python 3.9 based on the error log (see below)

Version

  *   TM1py [1.6.2]
  *   TM1 Server Version: [2.0.94]
  *   Python [3.9]
  *   Linux [RHEL 7]

Additional context
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aaf340>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aaff40>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0a47130>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aaf970>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f56b0aa4760>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/requests/
ERROR: Could not find a version that satisfies the requirement requests (from tm1py) (from versions: none)
ERROR: No matching distribution found for requests
