### ISSUE TITLE
Unable to connect to TM1 server on IBM PA Cloud

### ISSUE THREAD

**Issue by Saxenaamit15** [cubewise-code/tm1py#544]
Hi Team,

I am trying to test TM1py connection with TM1 server on IBM cloud and have executed below script:
#############################################
from TM1py import TM1Service

with TM1Service(
        base_url='https://compnay_name.planning-analytics.ibmcloud.com/tm1/api/tm1server_name',
        user=Non Interactive User ID,
        namespace="LDAP",
        password=**********,
        ssl=True,
        verify=True,
        async_requests_mode=True) as tm1:
    print(tm1.server.get_product_version())
####################################################

But I am getting below error:
The URL can not be found on server. The URL is also not opening from browser itself. Can you pls suggest what I am missing.

![image](https://user-images.githubusercontent.com/67405659/120093646-44699980-c139-11eb-8d41-049baef9ccd3.png)

**Comment by rkvinoth** [comment]
From my experience, IBM cloud can be accessed from anywhere. and also it is not a `ConnectionError `.
It is not a `ConnectionError` and you are unable to access it from browser. So, I think your `base_url` is incorrect. 

I'm providing some suggestions here:
1. If you are using PAW or PAX. you can get the `base_url` from that URL.
1. **tm1server_name** should be the **database directory name**, please confirm that.
2. **company_name** would be the server name or its alias, confirm that as well.
2.  Raise a ticket with IBM and they should be able to provide you the correct `base_url`

**Comment by Saxenaamit15** [comment]
Hi @rkvinoth,
I am using **_https://company_name.planning-analytics.ibmcloud.com_** as base URL and it is same for what is being used in PAW/PAX.

I am little unclear on your 2nd point about the database directory name. How will it resolve to TM1 server in that case? and what is the format for specifying database directory name in the URL? I saw one of the previous posts here, where the TM1 server name was specified in this place.

I will reach out to IBM for more details as for now I am using the one which they have provided.

**Comment by rkvinoth** [comment]
Data base directory is the parent folder which holds the folder in which all the TM1 objects are placed and you can confirm it in the tm1 config file.

If your config file looks something like below:
`DataBaseDirectory= "E:\Regional_Headcount\data\"`

Then **Regional_Headcount** should be passed as the `tm1server_name` in the `base_url`.

Checkout this configuration guide from Cubewise code: https://code.cubewise.com/tm1py-help-content/category/Configuration

**Comment by Saxenaamit15** [comment]
Yes, this directory folder name generally is always same as the TM1 server name to distinguish between multiple servers. I passed this correct in the first place, but it did not work.

I have reached out to IBM to review the base URL and will see what is missing in the current one. Thanks!

**Comment by rkvinoth** [comment]
Cool... When you find the root cause post it here and will be helpful for others.

**Comment by Saxenaamit15** [comment]
Yeah sure . will do. Thanks for your time in looking into this! I really appreciate this. :)

**Comment by tomasfelcman** [comment]
Hi, could it be that you are missing quotes on user parameter? My second thought is that you cannot connect to pa from outside with non interactive account (just guessing) -> could you try different username?
T.

**Comment by rkvinoth** [comment]
IBM PA cloud can be accessed from anywhere and non-interactive accounts are the only supported accounts for TM1 REST API in IBM cloud (unless things changed over the last couple of months).

**Comment by Saxenaamit15** [comment]
> Hi, could it be that you are missing quotes on tje "user" parameter? My second thought is that you cannot connect to pa from outside with non interactive account (just guessing) -> could you try different username?
> T.

Hi, I am using username under quotes itself, but getting error.

**Comment by Saxenaamit15** [comment]
Hi guys, 

The issue is now fixed. IBM said non interactive account got locked due to some reasons that is why it was not connecting. But the issue is now resolved and connection established successfully.

Also I was missing one '\' at the end of my URL, so that also needs to be updated for anyone who faces the same issue.
base_url='https://compnay_name.planning-analytics.ibmcloud.com/tm1/api/tm1server_name/',


Thanks for your support!

**Comment by rkvinoth** [comment]
That slash is actually not mandatory (possibly depending on the way your system was setup). I have used without slash.

**Comment by Saxenaamit15** [comment]
Then this must be system configuration as IBM suggested to use the slash.

**Comment by wimgielis** [comment]
Hi all,

2 of my customers on IBM cloud have these base URLs:

This one works:
https://CUSTOMERNAME.planning-analytics.cloud.ibm.com/tm1/api/MODELNAME/api/v1/

This one I cannot test due to the fact that I don't have the
non-interactive account (or do you guys have a workaround ?):
https://CUSTOMERNAME.planning-analytics.ibmcloud.com/tm1/MODELNAME/api/v1/

This gives 2 different URL's. Now we have a 3rd flavour, right ?

https://CUSTOMERNAME.planning-analytics.ibmcloud.com/tm1/api/MODELNAME/

Best regards,

Wim


------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op di 1 jun. 2021 om 10:28 schreef Saxenaamit15 ***@***.***>:

**Comment by Saxenaamit15** [comment]
Hi Wim,

The third flavor is suggested by IBM itself on their documentation. Here is the link:
_https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/wsj/analyze-data/add-data-planning-analytics-conn.html_

![image](https://user-images.githubusercontent.com/67405659/120297224-871ca480-c2e6-11eb-86a2-0942f97e5da9.png)

I initially tried with the /api/v1/ suffix, but the URL did not work. It worked for me only with the 3rd flavor.
Any thoughts?

Regards,
Amit

**Comment by wimgielis** [comment]
Yes, I just find it strange why there are different URL's and strange that
we somehow have to guess what the URL could be.
Did you receive an IBM Welcome kit with the Base URL ? And the
non-interactive account ?


------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op di 1 jun. 2021 om 11:06 schreef Saxenaamit15 ***@***.***>:

**Comment by rkvinoth** [comment]
The welcome kit will have the interactive accounts.. not sure about the URL though.
But creating a case with IBM, will definitely get you the URL.

**Comment by wimgielis** [comment]
Thanks.

This is what I see in a recent IBM Cloud hosting for a customer of ours:

[image: image.png]
The non-interactive account should be enabled by IBM and once they do so
(not for this customer), you will receive a new Welcome kit normally.

[image: image.png]


ANOTHER customer, where I have the REST API working:


[image: image.png]

[image: image.png]

------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op di 1 jun. 2021 om 11:17 schreef Vinoth Kumar Ravi <
***@***.***>:
