### ISSUE TITLE
Element Service has no atrribute get_elements_by_level

### ISSUE THREAD

**Issue by pal-16** [cubewise-code/tm1py#548]
result = tm1.dimensions.hierarchies.elements.get_element_by_level(dimension_name="", hierarchy_name="", level=1)
print(result)

Didn't get the expected result? Describe:
I am getting an error described below instead I should have got the elements in the level 1

**Additional context**
Element Service has no atrribute get_elements_by_level

**Comment by MariusWirtz** [comment]
Hi @pal-16,

that's just a typo.

The function is called `get_elements_by_level`.
There is a shortcut to for `dimensions.hierarchies.elements`. You can also write `tm1.elements`

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    result = tm1.elements.get_elements_by_level(
        dimension_name="d1",
        hierarchy_name="d1",
        level=1)
    print(result)

```

**Comment by pal-16** [comment]
Thanks for the reply, Yes I corrected the typo and also used tm1.elements
Now I am getting TM1Service has no attribute elements.

**Comment by pal-16** [comment]
result = tm1.elements.get_elements_by_level(  dimension_name="d1",
        hierarchy_name="d1",
        level=1)

Error: TM1Service has no attribute elements

**Comment by rkvinoth** [comment]
I believe you are not using the latest version of TM1py. 
If you are using your local machine for working with TM1py, please upgrade to the latest version of TM1py using: 
`pip install TM1py --upgrade`

If you working on your organization related machine, I wouldn't suggest an upgrade.
You can try using:
 ```python
tm1.dimensions.hierarchies.elements.get_elements_by_level(dimension_name="d1",
hierarchy_name="d1",
level=1)
```

**Comment by pal-16** [comment]
Thanks @rkvinoth but the syntax you gave is also giving me a similar error

tm1.dimensions.hierarchies.elements.get_elements_by_level => 'ElementService' object has no attribute get_elements_by_level tm1.elements.get_elements_by_level                                      => 'TM1Service' object has no attribute 'elements'

**Comment by rkvinoth** [comment]
What do you get when you run `pip show TM1py`?

**Comment by pal-16** [comment]
I am doing this as a part of my organization so pip does not work but tm1py version is 1.3.1

**Comment by rkvinoth** [comment]
`get_elements_by_level` is not available in **TM1py==1.3.1**

**Comment by pal-16** [comment]
So upgrade is the only option then, thanks I will confirm the upgrade with my organization

**Comment by rkvinoth** [comment]
As a workaround you could replicate the method in your code. But I would still suggest you to talk to your team and get the package upgraded.

```python
from TM1py.Services import TM1Service

dimension = "Scenario"
hierarchy = dimension
lvl = 0
tm1_connection = TM1Service()


def get_elements_by_level(tm1, dimension_name, hierarchy_name, level):
    url = "/api/v1/Dimensions('{}')/Hierarchies('{}')/Elements?$select=Name&$filter=Level eq {}".format(
        dimension_name, hierarchy_name, str(level))
    response = tm1._tm1_rest.GET(url)
    return [e["Name"] for e in response.json()['value']]


print(get_elements_by_level(tm1_connection, dimension, hierarchy, lvl))
```

**Comment by pal-16** [comment]
Yes, this helps. Thank you @rkvinoth  and @MariusWirtz
