### ISSUE TITLE
Change the default subset in TM1 portal

### ISSUE THREAD

**Issue by pal-16** [cubewise-code/tm1py#550]
I have created a subset and it gets updated as well, but the users have to manually go and select the subset. Instead, it should get applied as default i.e override default and show the users automatically

Is there any option of overriding a default public subset with a private subset in TM1?

**Comment by rkvinoth** [comment]
If you have Admin access to the TM1 instance, update the Default subset directly.
You can also update the Default subset with the contents from your private subset.

**Comment by MariusWirtz** [comment]
You can also create private default subsets for users through impersonation. Here is a sample:

``` python
from TM1py import TM1Service
from TM1py.Objects.Subset import Subset

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple", impersonate="Marius") as tm1:
    subset = Subset(subset_name="Default", dimension_name="d1", hierarchy_name="d1", elements=["e1", "e2"])

    tm1.subsets.update_or_create(subset, private=True)

```
