### ISSUE TITLE
Running Remote Scirpt using SSO get "Failed to authenticate through CAM. Expected status_code 200, received status_code: 401"

### ISSUE THREAD

**Issue by vmitsenko** [cubewise-code/tm1py#551]
Hi! 

I have 2 Windows machines:
1. IBM PA 2.0.94 and CA 11.1.6 installed, SSO is enabled 
2. Another server where installed Python and TM1Py

My purpose is to run TM1py script that is located on the 2nd server from TM1 located on the 1st server using SSO. 

I tried to run this script (script is located on the 2nd server): 
 with TM1Service(address="1stServer", port=12354, ssl=True, namespace="XXX", gateway="https://1stServer:443/ibmcognos/bi/v1/disp") as tm1:    print(tm1.server.get_product_version())

When I run this script directly on the 2nd server everything works fine. Script succesfully connects to the 1st server using SSO.

But when I'm trying to run script from 1st server where TM1 is located I'm getting an error. I tried to run script from the 1st server using Powershell command. 

Invoke-Command -Computer 2ndComputerName -Scriptblock {python.exe 'C:\PythonScript\Script.py'}
and get error
File "C:\Python\Python_3_9_5\lib\site-packages\TM1py\Services\RestService.py", line 464, in _build_authorization_toke
n_cam
    raise RuntimeError(
RuntimeError: Failed to authenticate through CAM. Expected status_code 200, received status_code: 401

May be there is something i need to check in server configuration?

**Comment by rkvinoth** [comment]
Not a powershell expert but when you are running the script that is in another machine.. which account triggers that script?
I believe it is not using your account which is causing the problem.

A simple solution to this is build an executable using your script.py in server 2 (where python exists).
Check out a python package named `pyinstaller`. That will convert your script into an executable by packing all the required dependencies (like TM1py).

You can then copy this executable (.exe) file to server 1 and run it there.
