### ISSUE TITLE
Ragged TM1 hierarchy in Power BI 

### ISSUE THREAD

**Issue by mikeponeill1978** [cubewise-code/tm1py#554]
**Describe what did you try to do with TM1py**
I have imported all of the TM1 dimensions of a cube that I want to visualise in Power BI using the tm1.power_bi.get_member_properties function. The hierarchies and attributes have all been imported as expected. I have also then brought in data from a cube view to bring in the facts using tm1.power_bi.execute_view function. Again - this imported as expected. 

**Describe what's not working the way you expect**
I have created a simple cross tab in Power Bi to display the values in the TM1 cube view. One of the dimensions has a ragged hierarchy - this dimension is on the rows. It has all levels in the rows so that you can clearly see the hierarchy. The hierarchy that I see mathes that of TM1. 

However, the values in the cross tab are not present for each level of the hierarchy and do not add up as expected/as they do in TM1. 

I have read the cubewise documenattion here which describes the issue: https://code.cubewise.com/tm1py-help-content/getting-tm1-data-into-power-bi

It has the following text:
"PBI doesn’t deal well with ragged hierarchies, but this can be mitigated by the use/creation of additional attributes"

But I cannot find any details anywhere about how to mitigate the issue with the use/creation of additional attributes. Is this documented anywhere?

**Version**
- TM1py version: 1.6.2
- TM1 Server Version: Planning Analytics 2.0

Thanks in advance - Mike

**Comment by MariusWirtz** [comment]
Hi @mikeponeill1978,

one easy way to deal with ragged hierarchies is to retrieve multiple "slices" or "rollups" of a dimension where each one is in itself "balanced".
I hope you know what I mean.

**Comment by jjcreniers** [comment]
I would also like to import a ragged hierarchy from TM1 to Power BI. The account structure in TM1 is ragged and I would like to be able to drill down in Power BI using this structure. Is there a way to do this? As I understand correctly, what you describe is to create a view for each roll-up level and then combine those in the Power BI model afterwards?

**Comment by MariusWirtz** [comment]
Ragged hierarchies (= hierarchies with leaves on multiple levels) are not a problem. 
Just follow the guide. 
https://code.cubewise.com/tm1py-help-content/getting-tm1-data-into-power-bi

When you query a hierarchy TM1py will give you a dataframe with a column for the element name and a column for each level/parent all the way to root (=total).
Based on that table/dataframe you can create a PBI Hierarchy with drag and drop in PBI.

However, if you have multi-parent relationships in a hierarchy (e.g., product A rolls into Consolidation 1 and also into Consolidation 2) you need to bring those rollups into PBI with separate queries.

**Comment by jjcreniers** [comment]
Thank you for your response Marius! I do have multi-parent relationships, does this mean I would for example create a view for each roll-up?

**Comment by MariusWirtz** [comment]
Please check out the article I posted above above.
You need to bring data and hierarchies in separate queries. 
You query ONE cube **view** for the data (per cube). Then you query as many hierarchies or rollups as you want to aggregate data in PBI.

PBI does your aggregations according to the data and the hierarchies you bring across.
