### ISSUE TITLE
Adding alias values to all elements in a hierarchy

### ISSUE THREAD

**Issue by pal-16** [cubewise-code/tm1py#555]
How to add attribute value to each element. When I click on a button in TM1 architect
with alias off
![image](https://user-images.githubusercontent.com/50794716/123099493-dcfcec00-d44f-11eb-9cc1-bf6195f048b5.png)

with alias on
![image](https://user-images.githubusercontent.com/50794716/123099559-ebe39e80-d44f-11eb-94da-217e9f62566b.png)

How can I achieve the same with TM1 py?

**Comment by MariusWirtz** [comment]
Hi @pal-16,

I am not entirely sure what you are trying to accomplish.

Are you attempting to retrieve elements with their alias values or are you trying to create a hierarchy in TM1 with alias attributes on elements?

**Comment by pal-16** [comment]
I want to create a hierarchy. I am able to do with the help of edges. How do I add alias names to my elements?

**Comment by MariusWirtz** [comment]
To create element attributes, use the `add_element_attribute` function on the `Hierarchy` class.

To write attribute values into the `}ElementAttributes` cube, you can just use the `write` function in `tm1.cells`.

Would you like a sample?

**Comment by pal-16** [comment]
Yes please. I want to give alias names to all the elements in my hierarchy

**Comment by MariusWirtz** [comment]
Here you go

``` python
from TM1py import TM1Service, Hierarchy, Dimension

with TM1Service(address='', port=12354, ssl=True, user='admin', password='apple') as tm1:
    dimension_name = "Region2"

    hierarchy = Hierarchy(name=dimension_name, dimension_name=dimension_name)
    hierarchy.add_element(element_name="Europe", element_type='Consolidated')
    hierarchy.add_element_attribute(name="Name", attribute_type="Alias")

    attribute_cells = dict()

    hierarchy.add_component(parent_name='Europe', component_name='DE', weight=1)
    attribute_cells['DE', 'Name'] = 'Germany'
    hierarchy.add_component(parent_name='Europe', component_name='FR', weight=1)
    attribute_cells['FR', 'Name'] = 'France'
    hierarchy.add_component(parent_name='Europe', component_name='CH', weight=1)
    attribute_cells['CH', 'Name'] = 'Switzerland'

    dimension = Dimension(name=dimension_name, hierarchies=[hierarchy])
    tm1.dimensions.update_or_create(dimension)
    tm1.cells.write(cube_name="}ElementAttributes_" + dimension_name, cellset_as_dict=attribute_cells, use_ti=True)

```

**Comment by pal-16** [comment]
Thanks a lot, this helps. Where can I read more about this?

**Comment by MariusWirtz** [comment]
About what in particular?

**Comment by pal-16** [comment]
attribute_cells = dict()
attribute_cells['DE', 'Name'] = 'Germany'
tm1.cells.write(cube_name="}ElementAttributes_" + dimension_name, cellset_as_dict=attribute_cells, use_ti=True)

About the functionalities and more usage of these lines. I understood what these lines are doing but any further reference or examples where this is used?

**Comment by MariusWirtz** [comment]
the `write` function is the key part of these lines. If you use PyCharm you can `ctrl+click` on the function name and jump to the function definition. There you should find a docstring that explains all arguments and optional arguments.
