### ISSUE TITLE
Issue with updating static subset

### ISSUE THREAD

**Issue by tmonty12** [cubewise-code/tm1py#557]
**Describe the bug**
When trying to update a named static subset on a target server based off the same named subset from a source server, there is a 400 http request error.

**To Reproduce**
Configure two copies of the Planning Sample database on your local environment and try to update the same named static subset from one server to another.

```python
from configparser import ConfigParser
from TM1py.Services import TM1Service

config = ConfigParser()
config.read('config.ini')

source_tm1 = TM1Service(**config['ps1'], password="apple")
target_tm1 = TM1Service(**config['ps2'], password="apple")

dimension_name = 'plan_department'
subset_name = 'n level departments'

source_subset = source_tm1.dimensions.subsets.get(subset_name=subset_name, dimension_name=dimension_name)

target_tm1.dimensions.subsets.update(subset=source_subset)
```

**Expected behavior**
I expected for the subset on the target server to be updated so that it matched the subset on the source server.

**Version**
TM1py [1.6.2]
TM1 Server Version: [11.1]

**Additional context**
Stack Trace
```
Traceback (most recent call last):
  File "c:\Users\tmontfort\Documents\TM1py\Migrations\issue.py", line 15, in <module>
    target_tm1.dimensions.subsets.update(subset=source_subset)
  File "C:\Users\tmontfort\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Services\SubsetService.py", line 87, in update
    self.delete_elements_from_static_subset(
  File "C:\Users\tmontfort\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Services\SubsetService.py", line 178, in delete_elements_from_static_subset
    return self._rest.DELETE(url=url, **kwargs)
  File "C:\Users\tmontfort\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Services\RestService.py", line 77, in wrapper
    self.verify_response(response=response)
  File "C:\Users\tmontfort\AppData\Local\Programs\Python\Python39\lib\site-packages\TM1py\Services\RestService.py", line 436, in verify_response
    raise TM1pyRestException(response.text,
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '{"error":{"code":"278","message":"No $id query option specified in DELETE on a collection valued navigation property."}}' - Status Code: 400 - Reason: 'Bad Request' - Headers: {'Content-Length': '125', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}
```

My intuition:
I believe the error has to do with the SubsetService method delete_elements_from_static_subset() that gets called on the SubsetService update method if the subset is static. It seems that my TM1 server does not support deleting all elements of an entity.

**Comment by MariusWirtz** [comment]
Hi @tmonty12,

You are running an old version of the TM1 Server. This version doesn't support the delete request against a collection and that breaks the TM1py code.

Can you upgrade to a more recent version e.g. 11.8.

I understand you are using 11.1, which is already quite old. There are lots of good reasons to upgrade. Especially if you are using the REST API (TM1py), you will benefit from better performance and more stability.

**Comment by tmonty12** [comment]
Hey @MariusWirtz,

Thanks for the response. I have upgraded to version 11.8 and I no longer encounter this issue.
