### ISSUE TITLE
Update attribute values into the Element Attributes Cube

### ISSUE THREAD

**Issue by pal-16** [cubewise-code/tm1py#560]
Hello @MariusWirtz, I can create an element attribute and write values to it based on our previous discussion. 

 To create element attributes, we use the add_element_attribute function on the Hierarchy class.
 To write attribute values into the }ElementAttributes cube, we the write function in tm1.cells.
```
attribute_cells = dict()
attribute_cells['DE', 'Name'] = 'Germany'
tm1.cells.write(cube_name="}ElementAttributes_" + dimension_name, cellset_as_dict=attribute_cells, use_ti=True)
```

Now I wish to update these values in the same attribute. I want to keep few values the same and update few values.
Any suggestions for the same. Thank you for your time.

**Comment by pal-16** [comment]
For updating if I use the same function ```tm1.cells.write``` , it gives me a dataspread error

**Comment by pal-16** [comment]
@MariusWirtz sorry to disturb but any suggestions on this issue?

**Comment by rclapp** [comment]
@pal-16 just update less values. It will only update the attribute cells that you include.

**Comment by pal-16** [comment]
But how do I update? Any function for that?
or just the same function again,  ```tm1.cells.write```

**Comment by rkvinoth** [comment]
Yup, to the `cellset_as_dict` pass the elements for which you need the update.

**Comment by rkvinoth** [comment]
For example consider you have a dimension **Product** with elements A, B, C and an attribute **Color**.

The current cube data:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rkvinoth/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rkvinoth/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Product | Color
-- | --
A | Yellow
B | White
C | Grey



</body>

</html>


To update only **A** pass `{('A', 'Color') : 'Green'}` to  `cellset_as_dict`

**Comment by pal-16** [comment]
I get data spread error when I do this

**Comment by rclapp** [comment]
That means you are trying to write a string to a numeric cell. I would check your attribute type

From: pal-16 ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Wednesday, June 30, 2021 at 10:19 AM
To: cubewise-code/tm1py ***@***.***>
Cc: "Clapp, Ryan" ***@***.***>, Comment ***@***.***>
Subject: Re: [cubewise-code/tm1py] Update attribute values into the Element Attributes Cube (#560)


I get data spread error when I do this

**Comment by pal-16** [comment]
But initially when I created the alias values of elements, I added them to the cell as string. It worked properly

**Comment by MariusWirtz** [comment]
@pal-16, try to narrow down the problem to one attribute. Try to replicate it with the simplest possible script. You will see that the error message comes either because of a typing mismatch or perhaps you are trying to write to a rule-derived cell or trying to set an invalid alias.

You are for sure attempting to write an illegal value into that attribute cube. If you narrow it down to the cell, you will see what exactly is wrong.
