### ISSUE TITLE
Connecting to a TM1 server , without password for a particular user

### ISSUE THREAD

**Issue by pal-16** [cubewise-code/tm1py#561]
I want to access user-specific private subsets. For that, I will require every user's credentials to connect to the TM1 server. 

Password is unfortunately not available for connecting. For testing, passing the password explicitly is working

But in an integrated environment, I will be calling a TM1 subset from another website and that website authentication is the same as my TM1 authentication. So any suggestions  to connect from my website to a TM1 server(eventually accessing the private subset on that server for a dimension) with the credentials of the website

Note: The website is using Kerberos authentication.

**Comment by MariusWirtz** [comment]
You can use impersonation to access user-specific private subsets. Impersonation means you login as admin, but you perceive the TM1 model as if you were a specific user. 

I posted a sample to your previous question. Here https://github.com/cubewise-code/tm1py/issues/550

**Comment by pal-16** [comment]
Any other way? This does not seem to work. I also want to create/update the private subset

**Comment by MariusWirtz** [comment]
Impersonation is the way to go. It is the only way to update private objects and it works reliably.
Try to make this code work in your environment:

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple", impersonate="Marius") as tm1:
    print(tm1.whoami.name)
```

For the `impersonate`  argument you have to provide a valid user name.
What error message do you get?

**Comment by pal-16** [comment]
![image](https://user-images.githubusercontent.com/50794716/123908801-aebe6580-d995-11eb-86d1-1329938e4512.png)

When I specify the password, I get this for ```tm1.whoami.name```
I am unable to understand what to enter in name while impersonating this username as an admin

**Comment by pal-16** [comment]
For impersonation, will the user Marius have admin rights?
Also for my organization if just pass impersonate="user_name_in_IBM_TM1" does not work, I have to pass CAM ID

**Comment by MariusWirtz** [comment]
Thanks that's correct! You do need to pass the CAM ID.

No. If you impersonate `Marius` then in your TM1py session you don't have admin permissions. In your TM1py session, you have the permissions that `Marius` has.

You can read more general stuff about impersonation in TM1 [here](https://code.cubewise.com/blog/save-time-testing-tm1-security-with-impersonation).

**Comment by pal-16** [comment]
Hello @MariusWirtz the problem is I don't have access to all CAMID of users.

Basically there is website#1 where users are logged in and now based on the user logged in website#1 I want to authenticate the same user in TM1 as well. We have their username but not the CAMID so impersonation won't work here.

**Comment by MariusWirtz** [comment]
Hi @pal-16,

I suggest you maintain a mapping between the user name in instance 1 and the CAM ID in instance 2 in a cube in instance 1.
With that mapping, the tm1py script can impersonate user A in instance 2.

**Comment by pal-16** [comment]
But again @MariusWirtz  to access the cube I will require credentials to connect?

**Comment by MariusWirtz** [comment]
You can store the mapping in a file if you want to do.

I understood that user A is already authenticated at instance 1. If this is not the case then store the mapping somewhere else. Your script needs a mapping of the user name of instance 1 and the CAM ID of instance 2.

I will close this issue. We are getting into implementation details and it's no longer related to TM1py.
