### ISSUE TITLE
cellset iteration

### ISSUE THREAD

**Issue by VY109** [cubewise-code/tm1py#565]
cells = tm1.cubes.cells.execute_view( )

hi everyone,

does anyone have a python code snippet that reads through the cells and puts it to variables so it can be embedded in html ?

thanks!

**Version**
- TM1py: 1.6.2
- TM1 Server Version: 2.0.65

**Comment by MariusWirtz** [comment]
Hi @VY109,

I haven't done this myself. @DJHig added some functions a while ago to retrieve data in a UI-friendly shape.
Check out the `execute_mdx_ui_dygraph`, `execute_view_ui_dygraph` functions. Perhaps that helps you

**Comment by VY109** [comment]
thanks Marius 👍
