### ISSUE TITLE
TM1pyException: Text: Status Code: 401 Reason: Unauthorized after 100+ successful process executins

### ISSUE THREAD

**Issue by izachorn** [cubewise-code/tm1py#575]
** What are we trying to do **
We have a script that migrates TM1 data objects between two TM1 environments. It does this by calling a process on the source instance, then calling a process on the target instance for each object. The script is running as a production ID with admin credentials.

**Describe what's not working the way you expect**
Sometimes our script fails midway through with a 401 error after having successfully executed the same two processes many times, other time it completes fully. The process entitlements do not change in between.

**Version**
- TM1py 1.3.1

**Additional context**
We use CAM authentication are creating a TM1Service object for each process call.

Exception is:

with TM1Service (**self.config) as tm1:  File "/ms/dist/python/PROJ/TM1py/1.3.1/lib/TM1py/Services/TM1Service.py", line 12, in __init__ 
self._tm1_rest = RESTService(**kwargs) 
File "/ms/dist/python/PROJ/TM1py/1.3.1/lib/TM1py/Services/RESTService.py", line 123, in __init__ 
decode_b64=self.translate_to_boolean(kwargs.get("decode_b64", False))) 
File "/ms/dist/python/PROJ/TM1py/1.3.1/lib/TM1py/Services/RESTService.py", line 208, in _start_session 
response = self.GET(request=request) 
File "/ms/dist/python/PROJ/TM1py/1.3.1/lib/TM1py/Services/RESTService.py", line 40, in wrapper 
self.verify_response(response=response) 
 File "/ms/dist/python/PROJ/TM1py/1.3.1/lib/TM1py/Services/RESTService.py", line 277, in verify_response 
raise TM1pyException(response.text, status_code=response.status_code, reason=response.reason) 
TM1py.Exceptions.Exceptions.TM1pyException: Text:  Status Code: 401 Reason: Unauthorized

**Comment by rkvinoth** [comment]
So to which instance the connection fails?

Is it the source or the target?

Without the code, its hard to say anything.

**Comment by izachorn** [comment]
We loop over a list of objects, calling a process on the source server and target server for each. The method that executes the process is below. This failed when calling the process on the source, but it was the 65th object in the list, the previous 64 had all completed fine, which leads me to believe a transient network issue or something with our CAM server. The process permissions and prodid permissions are not changing in between execution.

```
  def execute_process(self, object_name, params):
        process_parameters = {"Parameters" : params}
        with TM1Service (**self.config) as tm1: 
            tm1.processes.execute(object_name, process_parameters)
```
Our config is pretty standard, we update with a password retrieved from a vault prior to calling the execute.
[config]
address=server.com
port=30916
user=prodId
namespace=camnamespace
ssl=False
scv_namespace=scv_namespacepath
ti_proid=scv_key

**Comment by rkvinoth** [comment]
1. Why are you trying to establish a new session for every TM1 object? Refactor the code to use the same session.
2. At which TM1 object the script fails?

**Comment by rclapp** [comment]
You are likely hitting some kind of connection limit. Move the TM1Service declaration elsewhere so it is only done once. In addition if it is a network issue as you suspect, you can change to an async model by passing

async_requests_mode=true



From: izachorn ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Saturday, July 24, 2021 at 10:29 AM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [cubewise-code/tm1py] TM1pyException: Text: Status Code: 401 Reason: Unauthorized after 100+ successful process executins (#575)


We loop over a list of objects, calling a process on the source server and target server for each. The method that executes the process is below. This failed when calling the process on the source, but it was the 65th object in the list, the previous 64 had all completed fine, which leads me to believe a transient network issue or something with our CAM server. The process permissions and prodid permissions are not changing in between execution.

  def execute_process(self, object_name, params):

        process_parameters = {"Parameters" : params}

        with TM1Service (**self.config) as tm1:

            tm1.processes.execute(object_name, process_parameters)

Our config is pretty standard, we update with a password retrieved from a vault prior to calling the execute.
[config]
address=server.com
port=30916
user=prodId
namespace=camnamespace
ssl=False
scv_namespace=scv_namespacepath
ti_proid=scv_key

**Comment by MariusWirtz** [comment]
@izachorn did the suggestions above resolve your issue?

**Comment by izachorn** [comment]
@MariusWirtz I have refactored as suggested, as its intermittent its hard to tell but our first release using the updated logic was fine.
