### ISSUE TITLE
Creating cube json with Cube._construct_body() method wrong json format is generated

### ISSUE THREAD

**Issue by tomasfelcman** [cubewise-code/tm1py#577]
**Describe the bug**
When trying to create a cube from json representation, I have created the cube.json file using Cube._construct_body() method and got json string with Dimensions part:
{"Name": "Cube123", "Dimensions": ["Dimensions('organization')", "Dimensions('product')", "Dimensions('Year')", "Dimensions('Month')"]

but method Cube.from_dict() expects something like this:
{"Name": "Cube123", "Dimensions": [{"Name":"organization"}, {"Name":"product"}, {"Name":"Year"}, {"Name":"Month"}]
e.g. the Cube.from_dict() expects there to be a dictionary of Dimensions used, not list of Dimension("dim_name") strings.
referring to Cube.py line dimensions=**[dimension['Name']** for dimension in cube_as_dict['Dimensions']],

The question is , is the Cube._construct_body() output wrong or the creator Cube.from_dict() wrong, or am I missing something?

**To Reproduce**
Take existing cube and apply Cube._construct_body(), then try to use this json string by Cube.from_json() to get Cube object.

Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.8/site-packages/TM1py_custom/fel_create_cube_test.py", line 27, in <module>
    cube_instance = Cube.from_json(cube_json_string)
  File "/Applications/anaconda3/lib/python3.8/site-packages/TM1py_custom/venv/lib/python3.8/site-packages/TM1py/Objects/Cube.py", line 80, in from_json
    return cls.from_dict(cube_as_dict)
  File "/Applications/anaconda3/lib/python3.8/site-packages/TM1py_custom/venv/lib/python3.8/site-packages/TM1py/Objects/Cube.py", line 91, in from_dict
    dimensions=[dimension['Name'] for dimension in cube_as_dict['Dimensions']],
KeyError: 'Dimensions'

**Expected behavior**
Consistent json structure of Cube object representation

**Version**
TM1py  1.5.0
TM1 Server Version: 11.6.00000.14

**Additional context**
I would sugget to modify the Cube._construct_body() 
body_as_dict['Dimensions'] = [format_url("{'Name':'{}'}", dimension)
                                                 for dimension
                                                 in self.dimensions]
instead of 
body_as_dict['Dimensions@odata.bind'] = [format_url("Dimensions('{}')", dimension)
                                                 for dimension
                                                 in self.dimensions]

but that would relust in different json representation of Cube object... Any suggestions? I am happy to create a pull request.

**Comment by MariusWirtz** [comment]
Hi @tomasfelcman,

I'm not sure this is a bug. 

The `from_json` function consumes the JSON that the REST API provides and builds an instance of the `Cube` class
the `_construct_body` build the JSON that the REST API requires when creating or updating a cube.

Like the below code fails. I would argue though that this is by design and not a problem in itself.


``` python
from TM1py import TM1Service, Cube

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:
    cube = tm1.cubes.get('c1')

    json = cube._construct_body()

    Cube.from_json(json)

```

Why do you need the two JSON to be equal?
If you need to persist an instance of the `Cube` class into a file, perhaps you can use pickle.

**Comment by tomasfelcman** [comment]
Hi @MariusWirtz,
 I do not need those two JSONs to be the same, I was just expecting them to be equal as a common thing.
Is there somewhere documented how Cube.from_json(json) json should look like? That was actually the trigger how I got to the _construct_body() method...
Thank you,

**Comment by MariusWirtz** [comment]
No not documented. You can kinda derive it from here:
https://github.com/cubewise-code/tm1py/blob/01eb4a7bbeddb3b00b5f82ac90ddff09a090cfde/TM1py/Objects/Cube.py#L89
