### ISSUE TITLE
Hierarchy 

### ISSUE THREAD

**Issue by an5ir** [cubewise-code/TM1py#58]
When extracting a view from tm1 using tm1py, Is there a way to extract what level on a hierarchy a particular element of a dimension is?

**Comment by MariusWirtz** [comment]
Hi,

when you use the `execute_mdx_raw` method you can explicitly ask for certain element properties, such as the Level.
This method gives you more flexibility, however it returns you data in the raw format that the TM1 REST API returns to python.
Here is a sample:
```

with TM1Service(address='localhost', port=9699, user='admin', password='apple', ssl=True) as tm1:
    mdx = """
    SELECT 
    NON EMPTY {[Date].[2017-01]:[Date].[2017-12]} on ROWS, 
    NON EMPTY {[City].[NYC], [City].[Chicago], [City].[Washington]} on COLUMNS  
    FROM [Bike Shares] 
    WHERE ([Bike Shares Measure].[Count],[Version].[Actual]) 
    """

    data = tm1.cubes.cells.execute_mdx_raw(mdx, elem_properties=["Level"])
    print(data)
```
