### ISSUE TITLE
Utils "get_all_servers_from_adminhost" does not support another PORT nor SSL

### ISSUE THREAD

**Issue by cwffonseca** [cubewise-code/tm1py#583]
**Describe the bug**
The function **TM1py.Utils.get_all_servers_from_adminhost()** does not support selecting a different port nor an SSL connection to the adminhost.

**To Reproduce**
Scenario: Adminhost accepting only connections with **SSL** on port **5898**
When I run the function **get_all_servers_from_adminhost(adminhost='localhost')**, I receive the following error:
_ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it_

**Expected behavior**
A successful execution without error, and a list of the TM1 instances connected to that adminhost.

**Version**
TM1py 1.6.2
TM1 Server Version: 2.0.9.9

**Additional context**

**Comment by MariusWirtz** [comment]
Hi @cwffonseca,

thanks for reporting the issue.
I would suggest enhancing the function and add an additional optional argument: `ssl`.
If it is `True`, it could aim for 5898 with HTTPS otherwise it can look for 5895 as it does now.

Please feel free to fork this project and create a Pull Request.
