### ISSUE TITLE
Can not get elements from a dimension without attribute cube by MDX

### ISSUE THREAD

**Issue by Cubewise-Ronan** [cubewise-code/tm1py#585]
**Describe the bug**
Can not get elements from a dimension without attribute cube by MDX, e.g. }ApplicationEntries 

I query the mdx with below code,
`with TM1Service(**config["Instance"]) as tm1:
            elements = tm1.dimensions.execute_mdx(dimension_name="}ApplicationEntries", mdx="{TM1FILTERBYLEVEL({[}ApplicationEntries].[}ApplicationEntries].Members}, 0)}")
            print(elements)`

And then I got the following error,
`
elements = tm1.dimensions.execute_mdx(dimension_name="}ApplicationEntries", mdx="{TM1FILTERBYLEVEL({[}ApplicationEntries].[}ApplicationEntries].Members}, 0)}")
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\TM1py\Services\DimensionService.py", line 154, in execute_mdx
    response = self._rest.POST(request, json.dumps(payload, ensure_ascii=False), **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\TM1py\Services\RestService.py", line 77, in wrapper
    self.verify_response(response=response)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\TM1py\Services\RestService.py", line 439, in verify_response
    headers=response.headers)
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '{"error":{"code":"501","message":"Syntax error at or near: 'efaultMember } ON COLUMNS  FROM [}Elemen ... ', character position 137"}}' - Status Code: 400 - Reason: 'Bad Request' - Headers: {'Content-Length': '139', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}
`

**Expected behavior**
`with TM1Service(**config["Instance"]) as tm1:
            elements = tm1.dimensions.execute_mdx(dimension_name="Currency", mdx="{TM1FILTERBYLEVEL({[Currency].[Currency].Members}, 0)}")
            print(elements)`
 I can get the correct result while there is the dimension's attribute's cube 

**Version**
TM1py 1.6.0

**Comment by rkvinoth** [comment]
Use the `ElementService`

```python
with TM1Service(**config['Instance']) as tm1:
    elements = tm1.elements.execute_set_mdx(
        mdx="{TM1FILTERBYLEVEL({[}ApplicationEntries].[}ApplicationEntries].Members}, 0)}")
    print(elements)
```

**Comment by Cubewise-Ronan** [comment]
Hi @rkvinoth 

Got this error 
`
elements = tm1.elements.execute_mdx(dimension_name="}ApplicationEntries", mdx="{TM1FILTERBYLEVEL({[}ApplicationEntries].[}ApplicationEntries].Members}, 0)}")
AttributeError: 'ElementService' object has no attribute 'execute_mdx'
`

**Comment by rkvinoth** [comment]
`execute_mdx` does not exist in `ElementService`, use `execute_set_mdx`.

You can copy paste my code.

**Comment by Cubewise-Ronan** [comment]
@rkvinoth 

It works, thanks.
