### ISSUE TITLE
Unable to kill TM1py sessions running in backend using TM1 top? Please suggest if we have any python code to kill active sessions

### ISSUE THREAD

**Issue by sjadha22** [cubewise-code/tm1py#594]
![Capture](https://user-images.githubusercontent.com/85240045/129763873-4cd81bfc-ba38-4460-af54-ff2c530c31a9.PNG)

**Comment by rkvinoth** [comment]
If you are unable to cancel it via TM1py or TM1 Top, then there is nothing else that can be done.
Server restart is the final option.

Next time fix that mdx query.. try to shorten it if it's a big query.

**Comment by rkvinoth** [comment]
If it's your prod server, then wait for some more time and see if it is getting done automatically.
I dont see any locks as of now.. so I would wait.

**Comment by MariusWirtz** [comment]
Not sure if I understand the question correctly, but did you try to kill the thread with TM1py / REST ?

```  python
tm1.monitoring.cancel_all_running_threads()
```

**Comment by sjadha22** [comment]
> If you are unable to cancel it via TM1py or TM1 Top, then there is nothing else that can be done.
> Server restart is the final option.
> 
> Next time fix that mdx query.. try to shorten it if it's a big query.

Hi Vinoth,

Thanks for your quick response.
Yes there were no lock on any other thread IDs but we concerned because we haven't run anything Power BI refresh but still it was showing ID is running. We checked in Power BI Service as well and we thought in future if have to kill TM1 PY ID's, how we can kill from TM1 top? Because we are doing TM1 data refresh using Power Automate in Power Bi. So when power automate triggers python script, we will see that thread ID with TM1 py naming convention. We thought through TM1 top we can kill TM1 py but I think we can't kill from TM1 Top. Please correct me If I am wrong. But we have found other workaround as Data Gateway Restart and automatically that thread got killed.

**Comment by rkvinoth** [comment]
Doesn't matter what is creating a thread, you can kill it using TM1top or TM1py or other UI (pulse/paw).
You just need Admin access to do so. 

Some threads cannot be killed (doesn't matter from where it got triggered or from where you are trying to kill it)

**Comment by sjadha22** [comment]
> Not sure if I understand the question correctly, but did you try to kill the thread with TM1py / REST ?
> 
> ```python
> tm1.monitoring.cancel_all_running_threads()
> ```
Hi Vinoth,

Yes, we have tried to create same scenario and from TOP we killed TM1 PY related threads.
Thanks once again for your help and support.

**Comment by sjadha22** [comment]
> Not sure if I understand the question correctly, but did you try to kill the thread with TM1py / REST ?
> 
> ```python
> tm1.monitoring.cancel_all_running_threads()
> ```

Hi Marius,

Thanks for your response! Yesterday I tried to kill threads form TM1 py using below command tm1.monitoring.cancel_thread(thread['']). But it was not killing from TOP as well TM1 py. May be some bug. We tried to to run same report in Dev environment and even I tried to kill TM1 py threads from TOP.

**Comment by sjadha22** [comment]
> Doesn't matter what is creating a thread, you can kill it using TM1top or TM1py or other UI (pulse/paw).
> You just need Admin access to do so.
> 
> Some threads cannot be killed (doesn't matter from where it got triggered or from where you are trying to kill it)

Hi Vinoth,

Yes, we have tried to create same scenario and from TOP we killed TM1 PY related threads.
Thanks once again for your help and support.

**Comment by sjadha22** [comment]
As this issue has been addressed I am closing it from my end.
