### ISSUE TITLE
Sandboxes dimension returned by cubes.get

### ISSUE THREAD

**Issue by grandryjn** [cubewise-code/tm1py#595]
**Describe the bug**
The cubes.get function is returning the Sandboxes dimension and it is not consistent with the cubes.create dimension (not expecting the sandboxes dimension).

**To Reproduce**

I wanted to clone a cube between TM1 instances.
I was hoping to do the following.

```
# Create cube
cubesrc = tm1_source.cubes.get(cube_name=CUBE_TO_REPLICATE)

if not tm1_target.cubes.exists(CUBE_TO_REPLICATE):
    tm1_target.cubes.create(cubesrc)
```

But the problem with this is approach is the function cubes.get is returning the **Sandboxes** dimension.
When passing the cube object to the other instance for the cube creation, it is trying to create a cube with a "Sandboxes" dimension.

So to actually clone the cube I had to update to the following (remove the first dimension from the list).

```
# Create cube
cubesrc = tm1_source.cubes.get(cube_name=CUBE_TO_REPLICATE)

if not tm1_target.cubes.exists(CUBE_TO_REPLICATE):
    new_cube = Cube(cubesrc.name, cubesrc.dimensions[1:], cubesrc.rules)
    tm1_target.cubes.create(new_cube)

```

**Expected behavior**

Ideally the first piece of code should allow to create the cube directly.

For reference, the dimension clone can be done this way.
```
dimension_master = tm1_source.dimensions.get(dimension_name=dimension_name)
if not tm1_target.dimensions.exists(dimension_name):
    tm1_target.dimensions.create(dimension_master)

```

**Version**
TM1py 1.6.2

**Comment by MariusWirtz** [comment]
Fixed with #597
