### ISSUE TITLE
execute_view_dataframe returns error 'could not convert string to float'

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/tm1py#601]
**Describe the bug**
Trying to get a cube view into a data frame.  The cube view contains fields that are dates.  This function returns the error...

could not convert string to float: 'Apr 20 2021  1:45PM'

**To Reproduce**
Create a cube view that contains string measures that have date formatted strings in them.

**Expected behavior**
Expected the date to be returned as a string field.

**Version**
TM1py 1.4.1
TM1 Server Version: 11.8.00200.24

**Additional context**

**Comment by MariusWirtz** [comment]
duplicate of #248

Please also upgrade to TM1py 1.7

**Comment by raeldor** [comment]
Updated to 1.7.0, same error.

**Comment by MariusWirtz** [comment]
Pease check #248

**Comment by rkvinoth** [comment]
When you explicitly pass the `dtype`, python will be faster. So it's a win-win.

**Comment by raeldor** [comment]
Got it.  Appreciate the quick response, thank you.
