### ISSUE TITLE
execute_view_dataframe blowing up memory even with top=1000

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/tm1py#604]
Getting data from a (large) view is blowing up the memory usage, even if I specify top=1000.  Eventually it just hangs Visual Studio Code and I have to shut it down.  How can I prevent this and/or how can I get the records in batch?

**Comment by raeldor** [comment]
Looks like it may have also crashed the server with memory usage too, lol.  Which is odd, because we have an SPSS job pulling from the same view that runs every hour without a problem.

**Comment by MariusWirtz** [comment]
Hi @raeldor,

You need to know a bit about the internals of TM1py and the REST API to make sense of this.

TM1 creates a "cellset" based on your cube view / MDX query. This can be a time and memory-intensive operation.
The top parameter only applies *after* the cellset is created, when python retrieves the cells from the cellset.

We must avoid creating extremely large views when working with TM1 through the REST API.
There are different things you can do. Here are a few thoughts.
- Make sure you always use zero suppressed views and MDX queries
- When using MDX queries, try to use HEAD and TAIL to avoid mega queries
- You can pass the `timeout` (int: seconds) and `cancel_at_timeout` (boolean) keyword arguments to all functions in TM1py

**Comment by raeldor** [comment]
Thanks for the reply.  SPSS seems to be able to push data from this view into our data mart seemingly without a huge memory impact.  Is SPSS doing some kind of streaming?  Is there any way to stream/batch the data instead?  I already have suppress zeros on in both the view and the parameter.

**Comment by raeldor** [comment]
Looking at the memory usage it seems to creep up slowly to what looks like a reasonable level (800MB) like as if it's retrieving the data, and then BANG, it suddenly goes into the multiple gigabytes.  Is it possible the conversion to a pandas data frame is what's killing it?

**Comment by MariusWirtz** [comment]
> Looking at the memory usage it seems to creep up slowly to what looks like a reasonable level (800MB) like as if it's retrieving the data, and then BANG, it suddenly goes into the multiple gigabytes. Is it possible the conversion to a pandas data frame is what's killing it?

Please check which process is causing the memory spike on the machine. Python or TM1?

Sounds very likely. The obvious solution would be to process the data in chunks. Retrieve and process 100k cells at a time or so.

**Comment by raeldor** [comment]
It's Python, TM1 is running on a remote server.  Is it possible to process in chunks?  How would I do that?  Thank you.

**Comment by raeldor** [comment]
When I return ALL the data and write it out to a CSV, it's only 343MB (4M rows).  So I'm a little confused why my memory is getting hammered past 16GB.

**Comment by MariusWirtz** [comment]
I'm not sure I understand.

TM1 server is now fine, and it doesn't have a problem dealing with the query. Correct?
Python is running on a separate server and it fails during runtime because it uses too much memory. Is that correct too?

**Comment by MariusWirtz** [comment]
please post your code

**Comment by raeldor** [comment]
Well, let's put the server issue aside for now since I can't 100% confirm at this point it's related.  The Python code is running on VS Code on my laptop and yes, memory usage goes from 5GB to well over 16GB during the call.  

Digging into your code, it seems it gets down to executing a extract_cellset_raw (execute_view_dataframe->extract_cellset_dataframe->extract_cellset_csv->extract_cellset_raw) and memory usage goes from 65MB to over 9GB.  It seems the code line...

response = self._rest.GET(url=url, **kwargs)

causes memory to go from 65MB to about 900MB, which is fine since the CSV is 343MB and I know JSON isn't great on space.  However the next line...

return response.json()

causes the memory to blow up to over 9GB.  What is going on in this call?  I imagined the 'response' would already contain the JSON, so I don't understand.

**Comment by raeldor** [comment]
Digging into this further, it indeed seems that the JSON dict representation does indeed take a ton of memory, probably because of object overhead.  Since it's an intermediary to get to the pandas data frame it seems grossly inefficient from a memory perspective when dealing with large data sets.  I'm going to see if I can code something to go straight from JSON to either CSV (which seems to be the second intermediary source) or straight to the data frame.

**Comment by raeldor** [comment]
Using response.content worked great without impacting memory.  Really appreciate your fast assistance, thank you.

**Comment by raeldor** [comment]
Closed wrong issue, sorry.

I have created a new version of CellService.py that makes the CSV directly from response.content using IJSON streaming rather than reading the entire document into a DICT.  Memory usage has gone down from about 9GB+ to around 1GB total.  Performance seems to be about the same.  I'm not sure my code is as elegant as yours, but do you have any interest in reviewing it for inclusion?

**Comment by MariusWirtz** [comment]
Hi @raeldor,

thank you for analyzing this in depths! I would be very interested in including your fix. Please open a Pull Request.

**Comment by raeldor** [comment]
Created pull request #606.  I'm not a python expert, so though this works for us it probably requires a more expert hand.

**Comment by MariusWirtz** [comment]
Closed with https://github.com/cubewise-code/tm1py/pull/612
