### ISSUE TITLE
PyPi Release Schedule

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/tm1py#605]
Hey @MariusWirtz can you provide some clarity on the PyPi release schedule? Corporate security prefers that external packages are imported from PyPi, but the lack of PyPi releases makes it hard when we require a newer commit/fix.

**Comment by jpbonard** [comment]
+1

**Comment by jpbonard** [comment]
I just noticed the new PyPi release 1.7.0, but it has now the wheel file instead of the package source. Our import tool for third party packages only works with package source. @MariusWirtz , Can you distribute both files in PyPi?

**Comment by MariusWirtz** [comment]
Currently, there is no fixed schedule. We had a soft rule to do a release every few months, but we didn't stick to it consequently.
Perhaps we can schedule a release for the end of every quarter. What do you think?
Any other suggestions?

We haven't advertised the 1.7 release publicly yet. I do agree that we could provide both: package source and wheel.
We will do a 1.7.1 release soon and I will make sure we include both.

**Comment by jpbonard** [comment]
My view is that for regular releases is OK a quarterly schedule but for important bug fixes on existing features you may want to consider a hot fix branch with a faster release schedule.  Thanks @MariusWirtz  for considering our suggestions.

**Comment by MariusWirtz** [comment]
Hi @jpbonard, @rclapp,

we just released version 1.8 to PyPI. As `.tar` and `.wheel`.
Going forward we will attempt to release a version every 3 months.

Thanks again for the feedback. It's important for us to understand the challenges that real people in organizations have with TM1py. Please keep it coming.
