### ISSUE TITLE
Why TM1py threads holding other users Read only activity on wait on TM1?

### ISSUE THREAD

**Issue by sjadha22** [cubewise-code/tm1py#608]
Hi Everyone,

We are using Python to get TM1 cubes data in Power Bi. When we refesh Power BI dataset, it will trigger python script using TM1 API and it will fetch data in Power BI.
During this time TM1py threads starts runinng in backend and holding other threads on wait?
Can anyone please suggest why TM1Py tasks waiting other activities on wait?
![Tm1 top](https://user-images.githubusercontent.com/85240045/133489563-fecaede2-9baa-4450-9e2a-bf96d7bf87c1.png)

**Comment by rclapp** [comment]
This is pretty common in the TM1 locking model. Your best bet is to follow this playbook to find the issue. https://www.ibm.com/support/pages/how-troubleshoot-tm1-server-lock-contention

Those are intent exclusive locks so there is code in those TIs that need exclusive access to an object that the query has a read lock on.

Just some high level suggestions
1) Avoid using TM1SubsetToSet in your MDX queries and can lock that subset and block other things that trying to update it
2) Make sure you are using temporary and unique objects in your TIs, like views and subsets
3) Don't update dimensions when you expect to be running queries you will end up on wait
4) Don't use CUBESETLOGCHANGES in your TIs it tiggers a cube wide lock. Instead use CELLPUTS('No/Yes', }CubeProperties)

**Comment by rkvinoth** [comment]
It doesn't matter if the request is from TM1py.
If a thread is holding **Read** lock on an object, during that time other threads can also acquire **Read** lock but not a **Write** lock **IXC**

You can avoid **Read** locks by following Ryan's suggestions. Tweak your TM1py code to avoid the **Read** lock.

_On a totally unrelated note to the question_: Try to hide the customer info while posting screenshots.

**Comment by MariusWirtz** [comment]
Good points already made by @rclapp  and @rkvinoth!

Here is another thought: if the query takes almost 2000sec, perhaps it can be optimized to execute faster.
Make sure you use zero suppression in the view / MDX. Can you share your code?

How many cells are you retrieving? Perhaps there are inefficient rules in the cube?

Perhaps you can break down the query into ~ 200 smaller ones that each take 10sec and execute sequentially. While this would likely increase the overall retrieval time, it would cause the locks to be much less dramatic.

Upgrading to a recent version of TM1 could also help. IBM has done a good job reducing (b)locks in recent versions of TM1.

**Comment by sjadha22** [comment]
> This is pretty common in the TM1 locking model. Your best bet is to follow this playbook to find the issue. https://www.ibm.com/support/pages/how-troubleshoot-tm1-server-lock-contention
> 
> Those are intent exclusive locks so there is code in those TIs that need exclusive access to an object that the query has a read lock on.
> 
> Just some high level suggestions
> 
> 1. Avoid using TM1SubsetToSet in your MDX queries it can lock that subset and block other things that trying to update it
> 2. Make sure you are using temporary and unique objects in your TIs, like views and subsets
> 3. Don't update dimensions when you expect to be running queries you will end up on wait
> 4. Don't use CUBESETLOGCHANGES in your TIs it tiggers a cube wide lock. Instead use CELLPUTS('No/Yes', }CubeProperties)

HI 

> It doesn't matter if the request is from TM1py.
> If a thread is holding **Read** lock on an object, during that time other threads can also acquire **Read** lock but not a **Write** lock **IXC**
> 
> You can avoid **Read** locks by following Ryan's suggestions. Tweak your TM1py code to avoid the **Read** lock.
> 
> _On a totally unrelated note to the question_: Try to hide the customer info while posting screenshots.



> This is pretty common in the TM1 locking model. Your best bet is to follow this playbook to find the issue. https://www.ibm.com/support/pages/how-troubleshoot-tm1-server-lock-contention
> 
> Those are intent exclusive locks so there is code in those TIs that need exclusive access to an object that the query has a read lock on.
> 
> Just some high level suggestions
> 
> 1. Avoid using TM1SubsetToSet in your MDX queries it can lock that subset and block other things that trying to update it
> 2. Make sure you are using temporary and unique objects in your TIs, like views and subsets
> 3. Don't update dimensions when you expect to be running queries you will end up on wait
> 4. Don't use CUBESETLOGCHANGES in your TIs it tiggers a cube wide lock. Instead use CELLPUTS('No/Yes', }CubeProperties)

HI

> This is pretty common in the TM1 locking model. Your best bet is to follow this playbook to find the issue. https://www.ibm.com/support/pages/how-troubleshoot-tm1-server-lock-contention
> 
> Those are intent exclusive locks so there is code in those TIs that need exclusive access to an object that the query has a read lock on.
> 
> Just some high level suggestions
> 
> 1. Avoid using TM1SubsetToSet in your MDX queries it can lock that subset and block other things that trying to update it
> 2. Make sure you are using temporary and unique objects in your TIs, like views and subsets
> 3. Don't update dimensions when you expect to be running queries you will end up on wait
> 4. Don't use CUBESETLOGCHANGES in your TIs it tiggers a cube wide lock. Instead use CELLPUTS('No/Yes', }CubeProperties)

H Everyone,

Thanks for your quick response. We would like to undestand more on 1st point.
1. When we will use TM1 subsettoset, it will lock only that subset or all other activities?
2. In SubsettoSet function we have to use with MDX subsets or without MDX subsets(static)?
3. Is there any Alternative for TM1 SubsettoSet? Because as per out knowledge if will not use Subsettoset then MDX willl have static list of element names. Then how to get dynamic elements?

**Comment by rkvinoth** [comment]
1. A `Read` lock will be on that subset and other threads that is trying to update that subset/dimension (expecting `IXC`) will create contention.
2. You can add all the elements as a set within the `MDX`.
3. If the subset you are using in `TM1SUBSETTOSET` is a static subset, then hardcode then elements as a set within the `MDX`. If its dynamic, add the mdx set you used for the dynamic subset directly in the main `MDX`.

**Comment by MariusWirtz** [comment]
@sjadha22 
please re-open if the issue hasn't been resolved.
