### ISSUE TITLE
Update Applications

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#609]
**Describe what did you try to do with TM1py**
Would like to update existing Application document (workbooks). But cannot find any update functions currently to support this. Does IBM support it yet?

**Describe what's not working the way you expect**
There is the create and create_document_from_file function but would fail if the application document already exist.

**Version**
- TM1py 1.7.0

**Comment by jrobinsonAG** [comment]
Hi,

There is no update_or_create method for applications currently from what I can see. 

You could check if the application exists and then remove it, before adding it again?

``` python
with TM1Service(config) as tm1:
    application_path = "Finance"
    application_type = "Document"
    file_path = "C:\\Users\\User\\Reconciliation.xlsx"
    application_name = "Reconciliation.xlsx"
    private = False
    # Check if already exists
    if tm1.applications.exists(path=application_path,
                               application_type=application_type,
                               name=application_name,
                               private=private):
        # Remove Existing application
        tm1.applications.delete(path=application_path,
                                application_type=application_type,
                                name=application_name,
                                private=private)
    # Add Application
    tm1.applications.create_document_from_file(path_to_file=file_path,
                                               application_path=application_path,
                                               application_name=application_name,
                                               private=private)
```

**Comment by MariusWirtz** [comment]
@jrobinsonAG 
perhaps we should offer a `update_or_create_document_from_file` function, based on your code sample.
Could you post it as a Pull Request?

**Comment by jrobinsonAG** [comment]
@MariusWirtz  sorry been a bit busy lately. PR submitted with basic implementation.
