### ISSUE TITLE
'[WinError 10022] An invalid argument was supplied' when trying to connect to TM1 via network drive

### ISSUE THREAD

**Issue by elBurg0** [cubewise-code/tm1py#610]
Hi everyone,
I got an error i can't solve by myself so i'm here to search for help. 

**Describe what did you try to do with TM1py**
I wrote a script that connects to TM1 with TM1py and downloads / uploads data. The TM1 server is using 
```
UseSSL=T
IntegratedSecurityMode=1
```
as their security settings.
On my local laptop the connection works great with a vpn. I'm using these settings for connecting to TM1:
```
server_ssl = True
server_namespace = None
server_gateway = None
```

**Describe what's not working the way you expect**
Now I'm trying to publish that software as an .exe file on a mounted network drive. When executing the .exe file on my local laptop everthing still works great. But when trying to run the software from the drive i get an OS WinError 10022. 
The fileshare is in the same IP-range as the VPN so that shouldn't cause the problem. 

1. The result you expected.
I expected the script to run the same on the network drive as on my local laptop.

2. A clear and concise description of what you are trying to do.
I'm trying to connect to TM1 from that server (mounted as network drive) with TM1py via the RestAPI. 

Maybe you know more about sockets and what is happening there but this is out of my scope. If you need more information please tell me.
Thanks a lot for your help.

**Version**
- TM1py: 1.6.2
- TM1 Server Version: 10.2.2 FP5

**Additional context**
Detailed error:
```
Error: Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 77, in create_connection
  File "socket.py", line 231, in __init__
OSError: [WinError 10022] An invalid argument was supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 353, in connect
  File "urllib3\connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000224B36B6820>: Failed to establish a new connection: [WinError 10022] An invalid argument was supplied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='...', port=...): Max retries exceeded with url: /api/v1/Configuration/ProductVersion/$value (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000224B36B6820>: Failed to establish a new connection: [WinError 10022] An invalid argument was supplied'))
```

**Comment by elBurg0** [comment]
I also tried to connect to the RestAPI via a curl http request but curl isn't installed on that drive. 
And i tried to connect to TM1 via the http request in browser on the server and there i can only make requests that i don't need a authentication for (e.g. $metadata)

**Comment by rkvinoth** [comment]
Hello


First of all this question is out of TM1py community's support scope. So, I'm not sure if you will get a direct answer.

Secondly, what's your use case here?

**Comment by elBurg0** [comment]
Hi @rkvinoth,

thank you for your answer. 
That is unfortunate, i had the hope that somebody could tell me further details about that error and what could be the reason for it. It seems really strange to me that the tool is working fine locally but on the server it doesn't.

I'm developing an ETL tool for a company that is working with TM1 and the tool should not run local on a laptop instead on a network drive on a server for accessibility purposes.

Maybe someone also tried to do that and ran into a similar problem. I'm very grateful for every answer! :)

**Comment by rkvinoth** [comment]
I have created exe files myself integrating TM1py. It works perfectly both on local and server.

1. Let's forget the concept of network drive here. Let's say you have copied your exe file into server A's `D:\files\TM1py_usecase.exe`. Have you tried connecting to the server via remote desktop and trigger it there?
2. Posting the code you use to connect would also help figure out the issue.
3. Have you tried connecting from this server to TM1 via Architect/perspectives?

Just to confirm - Does the server not have python installed?

**Comment by elBurg0** [comment]
1. I have tried opening the .exe via a different environment where i do have access to TM1 via architect / perspectives. But when i try to connect with the browser in that environment to TM1 via Rest HTTP-Requests, i only can access sites where i don't need authentication for.

2. Here is the code i use to connect:
```
tm1 = TM1py.Services.TM1Service(
address = server_ip,
port = server_port,
user = server_user,
password = server_password,
namespace = server_namespace,
gateway = server_gateway,
ssl = server_ssl,
session_context = 'RestAPI-ETL',
)
```
I'm using this TM1 instance in some methods in a context manager.

3. I'm not sure on how to test that as but when I can connect to TM1 perspectives when accessing that share drive from another environment. I can't connect to the server (drive) right now from a remote desktop but i will try when I can.

Yes, there is no python installation on the Server.

**Comment by rkvinoth** [comment]
1. I hope you are using the `server_ip` of the server where the database directory exists and not the admin host. If they are both the same then it should be fine.
2. Try removing the `gateway` parameter, as it will try to connect using SSO.
3. Is this the exact stack trace or did you modify it?`HTTPSConnectionPool(host='...', port=...):`

**Comment by elBurg0** [comment]
1. This is the IP that I also can see in the TM1 architect when displaying the properties window. I hope that is correct, I don't know what you mean with admin host.
2. Gateway is actually None so that should not cause a problem. But I will try it too.
3. I only removed the IP and the Port in the exception.

**Comment by rkvinoth** [comment]
Definitely out of TM1py's scope. Sorry, but I'm not a network guy. If only I could replicate the error.

my last suggestion - Try with stable python version in a virtual environment (with latest TM1py version) and create the executable again.

**Comment by elBurg0** [comment]
Thank you for your advice.
I will try to test it under different circumstances.
