### ISSUE TITLE
AttributeError: 'TM1Service' object has no attribute 'views'

### ISSUE THREAD

**Issue by elcinsayin** [cubewise-code/tm1py#613]
I created a code which extracts the view from TM1 to GoogleSheets. I can run it in PyCharm and Command Prompt on my computer, however I cannot run it from a TI process. Also, the main computer that's logged in to TM1 throws an error saying that TM1Service has no attribute views. This is the piece of code:

``` python
CUBE = "Account Budget"
VIEW_NAME = "newGoogleSheetView"
DIMENSION_NAME = "Year Month"
SUBSET_NAME = sys.argv[1] + " Months"
with TM1Service(address="localhost", port=PORTNUMBER, ssl=True, user=USER, password=PASSWORD) as tm1:
    view = tm1.views.get(cube_name=CUBE, view_name=VIEW_NAME, private=False)
    if isinstance(view, NativeView):
        ti_lines = f"""
        ViewSubsetAssign('{CUBE}', '{VIEW_NAME}', '{DIMENSION_NAME}', '{SUBSET_NAME}');
        """
        tm1.processes.execute_ti_code(lines_prolog=ti_lines)
    else:
        pass
```

See the error below:

`view = tm1.views.get(cube_name=CUBE, view_name=VIEW_NAME, private=False)`
`AttributeError: 'TM1Service' object has no attribute 'views'`

**Comment by MariusWirtz** [comment]
Please upgrade to a more recent version of TM1py.

`pip install tm1py --upgrade`

**Comment by elcinsayin** [comment]
> Please upgrade to a more recent version of TM1py.
> 
> `pip install tm1py --upgrade`

It's up-to-date. When I try to update it, it says "... already satisfied."

**Comment by MariusWirtz** [comment]
Does it work if you change it if you change it to `tm1.cubes.views.get` ?

**Comment by MariusWirtz** [comment]
If you use PyCharm, please go to `file -> settings -> Project: ProjectName -> Project Interpreter`.

There you should see a list of all packages, including TM1py. Which version does it show for you?

![image](https://user-images.githubusercontent.com/15182131/134481261-2a21cdf7-72c3-4007-b99f-1be72582ef60.png)

**Comment by rkvinoth** [comment]
Try `pip uninstall tm1py`
Then `pip install tm1py`

**Comment by elcinsayin** [comment]
> > Please upgrade to a more recent version of TM1py.
> > `pip install tm1py --upgrade`
> 
> It's up-to-date. When I try to update it, it says "... already satisfied."

It runs now. I didn't think it would run since it was already there but now it works somehow. Thank you.
