### ISSUE TITLE
Check if a control cube exists

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/tm1py#614]
**Describe what did you try to do with TM1py**
I need to check whether a given cube exists or not. It is a control cube though.

control_cubes = tm1.cubes.get_control_cubes()
if '}CubeSecurity' not in control_cubes:
    ........

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. The result you expected: True or False. In a given TM1 model, that cube does not exist so I want to test it.
2. A clear and concise description of what you are trying to do: reading out user access to cubes

**Version**
- latest

Error:
'str' object has no attribute 'body'
  File "D:\OneDrive\Script_00.py", line 93, in inspect_users
    if '}CubeSecurity' not in control_cubes:
  File "D:\OneDrive\Script_00.py", line 154, in <module>
    inspect_users()

    return self.body == other.body
AttributeError: 'str' object has no attribute 'body'

**Comment by MariusWirtz** [comment]
I think you can use the `exists` function. TM1py offers an `exists` functions on all services

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user='admin', password='apple') as tm1:
    exists = tm1.cubes.exists("}CubeSecurity")
    print(exists)

    exists = tm1.cubes.exists("}Cube SECURITY")
    print(exists)
```

It is case and space insensitive as it should be :)

**Comment by MariusWirtz** [comment]
``` python
control_cubes = tm1.cubes.get_control_cubes()
print('}CubeSecurity' in control_cubes)
```

This code fails, because the `get_control_cubes` function returns `Cube` objects instead of strings.
It is also not case and space insensitive.

If you wanted to compare against a list of cube names you could do this.

``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user='admin', password='apple') as tm1:
    cube_names = tm1.cubes.get_all_names()
    print("}CubeSecurity" in cube_names)
```

Or this if you want the comparison to be case and space insensitive

``` python
from TM1py import TM1Service
from TM1py.Utils import CaseAndSpaceInsensitiveSet

with TM1Service(address="", port=12354, ssl=True, user='admin', password='apple') as tm1:
    cube_names = tm1.cubes.get_all_names()
    print("}Cube Security" in CaseAndSpaceInsensitiveSet(*cube_names))
```

**Comment by wimgielis** [comment]
Thanks Marius, it works now.

I used:
cube_security_exists = ("}CubeSecurity" in tm1.cubes.get_all_names())
if not cube_security_exists:
    vClient_Access = 'Write'

Case can be closed.


Op do 23 sep. 2021 om 11:26 schreef Marius Wirtz ***@***.***>:
