### ISSUE TITLE
Python code not sending the parameters to the process it triggers when the code is triggered by another process

### ISSUE THREAD

**Issue by elcinsayin** [cubewise-code/tm1py#640]
I have a Python code that triggers a TM1 process. When I run the Python code from PyCharm and Command Prompt, the code works as intended. However, when I trigger the Python code from an another process, the process that is triggered by the Python code does not receive the parameters that are sent by the code. I don't get any kind of error. I am not sure what is the problem.

**Comment by MariusWirtz** [comment]
Hi @elcinsayin,
please post a script that reproduces the error

**Comment by elcinsayin** [comment]
The code below is the Python code that triggers the process:  
  with TM1Service(address="localhost", port=PORT, ssl=True, user=USER, password=PASSWORD) as tm1:
        process = tm1.processes.get(name_process="Sys.GoogleSheetExport")
        parameters = {"pYear": year, "pClient": client}
        # Pass the parameter by unpacking the dictionary
        success, status, error_log_file = tm1.processes.execute_process_with_return(process, **parameters)
        if success:
            print("Process " + "Sys.GoogleSheetExport " + "executed successfully for Client" + " " +client)
        else:
            print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)

We added an ASCIIOutput in the begginning of the sys.GoogleSheetExport so that we can print the parameters given. 
Below is what is written in the log file:
"",""

**Comment by MariusWirtz** [comment]
where are the `year` and `client` variables coming from?

What does it output if you do this:

``` python
client = 'A'
year = 'B'

with TM1Service(address="localhost", port=PORT, ssl=True, user=USER, password=PASSWORD) as tm1:
    process = tm1.processes.get(name_process="Sys.GoogleSheetExport")
    parameters = {"pYear": year, "pClient": client}
    # Pass the parameter by unpacking the dictionary
    success, status, error_log_file = tm1.processes.execute_process_with_return(process, **parameters)
    if success:
        print("Process " + "Sys.GoogleSheetExport " + "executed successfully for Client" + " " +client)
    else:
        print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)


```

**Comment by elcinsayin** [comment]
Client and Year parameteres are passed from the process that triggers the code, I also printed those parameters out to check whether the Python code receives them or not. It looks like it receives them but it does not properly send them to the process it triggers.

**Comment by MariusWirtz** [comment]
Try to debug the code the see step by step where the values get lost.
The python code itself looks good.

What version of TM1 are you using?
Some early versions of TM1 11 would not accept numeric parameter values. To work around it you need to explicitly convert the parameter value with the `str` function: `parameters = {"pYear": str(year), "pClient": str(client)}`

**Comment by elcinsayin** [comment]
Wouldn't that also be a problem while I was running the code in PyCharm as well it that was the case, though? While running the code directly from PyCharm, I also trigger the same process with same parameters, however it works just fine. Also, pYear is a string parameter.

**Comment by MariusWirtz** [comment]
How do you execute the python script? Can you post the command line statement there?
Something like:

`C:/python3/python.exe C:/projects/my-project/main.py "2021" "Germany"
`

**Comment by elcinsayin** [comment]
"C:\Program Files\Python39\python.exe" "C:\Program Files\Cubewise\TM1Models\Provectus_Test\SourceData\TA.py" 2021 "Client Name"

I printed the type of the year parameter, it says it's a string.

**Comment by MariusWirtz** [comment]
How do you consume the arguments that are passed through the cmd to python?

If you execute this at the top of the script. does it print out the 2021 and Client name?

``` python
import sys

args = sys.argv[1:]
print(args)
```

**Comment by elcinsayin** [comment]
I use these parameters to trigger the process sys.GoogleSheetExport from the python code, the process updates a few views with these parameters, then I retrieve data from these views. Then I write them into Google Sheets.

Yes, it does.

**Comment by MariusWirtz** [comment]
Are you saying that if this is executed from the command line it works fine

`C:/python3/python.exe C:/projects/my-project/main.py "2021" "Germany"`

But when execute from a TI through ExecuteCommand the 2021 and Germany is not passed through?

**Comment by elcinsayin** [comment]
Yes, from the command line, it works. But when I execute it from the TI, python code receives the parameters, however it does not pass them to the process it triggers.

**Comment by elcinsayin** [comment]
We've changed the log-on user from our user name to local system and it worked. However, we need it to be our user name since some other stuff does not work when it is the local system.

**Comment by MariusWirtz** [comment]
It sounds very odd. If your user has READ permission to a process, your user must be able to execute it with custom parameters.

It's very odd that the process gets executed but the parameters are not "accepted".

I wonder if maybe something else is wrong in the code or if the wrong script gets executed or something.

**Comment by elcinsayin** [comment]
But it something was wrong in the code, it shouldn't worked at all. There is only one script called TA.py in the SourceData and it is the one triggered by the TI.

**Comment by elcinsayin** [comment]
if something was wrong*

**Comment by MariusWirtz** [comment]
@elcinsayin 
is this problem solved?

**Comment by elcinsayin** [comment]
No, but I figured out another way to do the same thing.

**Comment by GaliNithin** [comment]
Can you tell us the other way

**Comment by GaliNithin** [comment]
i am also facing the same issue my process is executed where as the parameters are not being passed on

**Comment by elcinsayin** [comment]
> i am also facing the same issue my process is executed where as the parameters are not being passed on

I looked up the parameters from a cube.
