### ISSUE TITLE
can not use write_to_message_log

### ISSUE THREAD

**Issue by Cubewise-Ronan** [cubewise-code/tm1py#641]
Hi, 

I am tring to use write_to_message_log to log information into tm1,
but 
![image](https://user-images.githubusercontent.com/65941927/140696600-cadfb0a4-bb9c-4279-9ce5-76244f5240ef.png)
the code I am using is like below,
![image](https://user-images.githubusercontent.com/65941927/140696655-f0028c44-1fcd-46e5-9699-5852823f194b.png)

How can I use it?

**Comment by rkvinoth** [comment]
I don't think there is an official release on this feature yet.

You will have to use the `master` branch from github. Install the master branch using the below command and then execute your code:
`pip install https://github.com/cubewise-code/tm1py/archive/master.zip --upgrade`

**Comment by MariusWirtz** [comment]
I can confirm. It's not officially released to PyPI yet. We are aiming for a release at the end of Q4. 
Hopefully with some other good features like #612.

For the moment, to use this feature you need to upgrade to the master branch as @rkvinoth suggested.
