### ISSUE TITLE
TM1Service.cells.write_value() not working 

### ISSUE THREAD

**Issue by elcinsayin** [cubewise-code/tm1py#642]
I was trying to set a value in the cube that has two dimensions, say A and B. I have two elements in A, Client and Year, and one in B, which is called Value. In the code, I write this to be able to update the value:

with TM1Service(address="localhost", port=PORT, ssl=True, user="USER", password="PASSWORD") as tm1:
        tm1.cells.write_value(value=client, cube_name="CUBE NAME", element_tuple = {"Client", "Value"})

client being a string value, and the order of the element tuple is correct. Both "Client" and "Year" are of type string.

I got the following error:
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: {"error":{"code":"278","message":"'Value' can not be found in collection of type 'Element'."}} Status Code: 404 Reason: Not Found Headers: {'Content-Length': '106', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

The interesting thing is, it works sometimes, and sometimes throws this error even though I don't change anything.

**Comment by elcinsayin** [comment]
Value is type string. I have the Value element in my Measure dimension. Can you explain what do you mean by not being available?

**Comment by rkvinoth** [comment]
Are you creating this dimension on the fly using python script?
If yes, are you sure the dimension and the element got created before updating the cube?
If no, how can I replicate this issue of yours (can you share your code and cube's metadata)?

**Comment by elcinsayin** [comment]
I created the dimensions and the cube manually before I write the code. 

It is difficult to replicate the exact same situation since it is a very model-spesific code in which I retrieve and write data in different cubes. But I believe you can replicate the issue by having the following:

I have a cube called Google Sheet, in which I created a view which is also called Google Sheet. I have two dimensions, one of them (Google Sheet) has Year and Client elements, the other (Google Sheet m) has the Value element. All of them are of type string.

 Then I used this piece of code to write to Google Sheet cube:

with TM1Service(address="localhost", port=PORT, ssl=True, user="USER", password="PASSWORD") as tm1:
    tm1.cells.write_value(value=client, cube_name="CUBE NAME", element_tuple = {"Client", "Value"})

client being a string value. 

Then I got the error I mentioned earlier.

**Comment by rkvinoth** [comment]
ahhh man how did I miss this!
Python `set` is unordered, use a `list` instead.
`tm1.cells.write_value(value=client, cube_name="CUBE NAME", element_tuple = ["Client", "Value"])`

**Comment by elcinsayin** [comment]
Thank you so much for your help, it works now.
