### ISSUE TITLE
execute_set_mdx member_properties

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#648]
**Describe what did you try to do with TM1py**

Getting attribute values using the following function
tm1.elements.execute_set_mdx(mdx=mdx, member_properties=['Name', 'Attributes/Short Name'])

**Describe what's not working the way you expect**

The attribute name contains space causes an error. The function was not case insensitive.
Also where can I find details on what are the available member_properties that can be requested? and in what syntax to use?

**Version**
- TM1py 1.8.0
- TM1 Server Version: 11.8.4

**Additional context**
If you encounter an error, please add the error message and the stack trace
```
File "C:\Python\lib\site-packages\TM1py\Services\RestService.py", line 454, in verify_response
    raise TM1pyRestException(response.text,
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '{"error":{"code":"278","message":"Syntax error at position 53, near \"Name\" for $expand query option: Expecting ')' token."}}' - Status Code: 400 - Reason: 'Bad Request' - Headers: {'Content-Length': '130', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}
```

**Comment by MariusWirtz** [comment]
Hi @cubewise-gng,

thanks for bringing this up. I made a few changes to the `execute_mdx_set` function. 

Now spaces are removed from the attribute names before TM1py sends a request to TM1.
I improved the docstring to list the potential properties that can be retrieved on the member, parent, element level and added some tests for the function as well.

Please upgrade to the feature branch and test it:

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/feature/improve-execute-set-mdx.zip
```

**Comment by cubewise-gng** [comment]
Thanks @MariusWirtz tested the feature branch and it worked as expected.

**Comment by MariusWirtz** [comment]
Thanks! Then I will merge it.
