### ISSUE TITLE
Skip rule calculated cells when writing

### ISSUE THREAD

**Issue by cwcibo** [cubewise-code/tm1py#651]
When the TM1py script writes the data to a cube with tm1.cells.**write** but some cells are rule calculated, the scripts fails with an error.
It would be useful to have an argument to the **write** method to skip the blocked cells (like **SkipNonUpdateable=True**) and do a check similar to **CellIsUpdateable**.
If the argument is False or not provided, the script should act as of now.

**Version**
TM1 Version: 11.4.00003.8

**Comment by gbryant-dev** [comment]
Hi @cwcibo,

There's no REST API equivalent of the CellIsUpdateble TI function. You have to retrieve information about the cells and filter out the ones that aren't updateable before attempting to make updates. In addition, if one or more cells in the update fails then all of the updates in that batch fail.

I think there are a couple of things that could be done to facilitate this:

- When you execute a view or MDX statement using the `execute_view` or `execute_mdx` functions in TM1py, you can pass `skip_rule_derived_cells=True` to do this which returns a cellset dictionary in the format required for the write functions. You could then apply your updates to the dictionary and then use `write` function. Note that you would need to pass `skip_consolidated_cells=True` as well as consolidated cells can't be directly updated without using a spread function.
- As you suggested, a parameter could be added to the write functions that when set to `True`, a call is made first to get what cells are updateable and filter these out before making the updates. @MariusWirtz what do you think?

**Comment by MariusWirtz** [comment]
Hi @cwcibo,

thanks for proposing this feature. I agree it would be quite handy.

Thanks for your thoughts on this one @gbryant-dev.
The `increment: bool` argument in the `write` function works in a similar fashion, as to what you suggested.

If `use_ti` is `True`, we would have to include the `CellIsUpdateable` check in the `write_through_unbound_process function`.
If `use_ti` is `False` we would need to do what you suggested (retrieve updateable cells and apply)

I am in favor. I think we should include this feature in TM1py.

**Comment by gbryant-dev** [comment]
@MariusWirtz I'm happy to pick this one up if you or @cwcibo are not already looking at it?

**Comment by MariusWirtz** [comment]
Thanks, @gbryant-dev!
Dmitry wanted to look into this one. Maybe check with him shortly before you start developing.
