### ISSUE TITLE
Documentation is empty

### ISSUE THREAD

**Issue by yali77** [cubewise-code/tm1py#653]
Hello,

it seems, that the documentation ist empty. Does anyone know the reason? Where can I find the latest version?

https://buildmedia.readthedocs.org/media/pdf/tm1py/latest/tm1py.pdf

Many thanks!

**Comment by MariusWirtz** [comment]
Here is a link to the latest documentation that was generated successfully
https://tm1py.readthedocs.io/en/stable/

I will look into why it failed to generate on the latest release.
However, in my opinion, a good IDE (e.g., PyCharm) that offers autocompletion and shows you the docstrings on functions can substitute a classic PDF documentation.

**Comment by yali77** [comment]
Huge thanks for quick response. That link works.
And thanks for the tipp reading definitions in IDE directly.
