### ISSUE TITLE
TI processes not passing parameters to one another when triggered by Python

### ISSUE THREAD

**Issue by elcinsayin** [cubewise-code/tm1py#654]
I have a python script that triggers a process which has no parameter, and it works fine. However, when I added the lines

cProcess = GetProcessName( );
cProcessReference = cProcess |'_'| TimSt( Now, '\Y\m\d\h\i\s' );
cParameterValues = 'pClient:'|CellGetS('Google Sheet', 'Client', 'Value')|' , pYear:'|CellGetS('Google Sheet', 'Year', 'Value');
ExecuteProcess('sys.Process.Logs.Start','processname',cProcess,'ElementName',cProcessReference, 'ParameterValues', cParameterValues);

to the code, the process sys.Process.Logs.Start gave an error saying:

Error: Prolog procedure line (22): Component Element "" not found.
Error: Prolog procedure line (29): Consolidated Element "" not found.
Error: Epilog procedure line (19): Dimension element "" not found in dimension "System Process Logs". 

We realized that the processname parameter is not being passed to sys.Process.Logs.Start. Do you have any idea what might be the problem?

Thanks in advance,

Elçin

**Comment by MariusWirtz** [comment]
If you call an unbound process from TM1py, the process name of the called process is an empty string.

so that means the value for cProcess is ''
```
cProcess = GetProcessName( ) 
```
Could this be the problem?

**Comment by elcinsayin** [comment]
Exactly. That is the issue. It is a empty string. Is there a way to fix that?

**Comment by elcinsayin** [comment]
Exactly, that is the issue. Is there a way to fix it?

**Comment by elcinsayin** [comment]
Other than hardcoding the name of the process?

**Comment by MariusWirtz** [comment]
Please post the python code too. I will take a look.

**Comment by elcinsayin** [comment]
It's a very long script. Which part do you need exactly?

**Comment by MariusWirtz** [comment]
Change it to this and it should work:

```
with TM1Service(address="localhost", port=PORT, ssl=True, user="USER", password="PASSWORD") as tm1:
    success, status, error_log_file = tm1.processes.execute_with_return("Sys.GoogleSheetExport")
    if success:
        print("Process " + "Sys.GoogleSheetExport " + "executed successfully for Client" + " " +client)
    else:
        print("Process execution failed. Status: " + status + ". Path to error log file: " + error_log_file)
```

**Comment by elcinsayin** [comment]
Ok, I replaced it with the code you've sent. However I cannot check whether if it's working or not since somehow when I run the process that triggers the python script, I see that in the sessions, the ExecuteWithReturn is waiting, therefore the process never ends since that piece of code is in the beginning of the script. I think it was also a problem with ExecuteProcessWithReturn.
![wait](https://user-images.githubusercontent.com/77210293/145549506-b7730407-a153-47b2-9241-ede88f3ce8ee.PNG)

**Comment by elcinsayin** [comment]
OK, I replaced it with what you've sent, however I cannot check whether if it's working or not since when I run the process that triggers the python script, I checked the Sessions and realized that it was waiting on ExecuteWithReturn, therefore process never stops. Because ExecuteWithReturn is in the beginning of the python script. I also think that was an issue with ExecuteProcessWithReturn as well, because it happened with that one yesterday too.
![wait](https://user-images.githubusercontent.com/77210293/145550527-f6d5903a-7523-4717-9a6a-fbef71146dba.PNG)

**Comment by MariusWirtz** [comment]
As a rule of thumb, the TI process that executes python through `ExecuteCommand` shouldn't acquire any locks before calling python.

Can you make the `Sys.TimeAllocationExport.GoogleSheet` process less invasive in terms of locks?

**Comment by MariusWirtz** [comment]
Going back to your original question, if you want to use unbound processes and change:

```
cProcess = GetProcessName( );
cProcessReference = cProcess |'_'| TimSt( Now, '\Y\m\d\h\i\s' );
cParameterValues = 'pClient:'|CellGetS('Google Sheet', 'Client', 'Value')|' , pYear:'|CellGetS('Google Sheet', 'Year', 'Value');
ExecuteProcess('sys.Process.Logs.Start','processname',cProcess,'ElementName',cProcessReference, 'ParameterValues', cParameterValues);

```


to:

```
cProcess = 'Sys.GoogleSheetExport';
cProcessReference = cProcess |'_'| TimSt( Now, '\Y\m\d\h\i\s' );
cParameterValues = 'pClient:'|CellGetS('Google Sheet', 'Client', 'Value')|' , pYear:'|CellGetS('Google Sheet', 'Year', 'Value');
ExecuteProcess('sys.Process.Logs.Start','processname',cProcess,'ElementName',cProcessReference, 'ParameterValues', cParameterValues);
```

It may perhaps solve your original problem.

**Comment by elcinsayin** [comment]
Yes, I have changed it once I have changed the execute_process_with_return to execute_with_return. 

The Sys.TimeAllocationExport.GoogleSheet only includes a couple of lines that lead to ExecuteCommand. There isn't much in there either. I'm not quite sure what you mean by locks.

**Comment by elcinsayin** [comment]
Yes, I have changed it, it works fine that way.

The Sys.TimeAllocationExport.GoogleSheet only includes a couple of lines that lead to ExecuteCommand. There isn't much in there either. I'm not quite sure what you mean by locks.

**Comment by MariusWirtz** [comment]
> Yes, I have changed it, it works fine that way.

So the original problem is solved? Happy to hear that.

Locks are the reason why the two processes block each other. Both threads acquire a lock on the same object. That creates a deadlock. If the first process had never acquired a lock there would be no deadlock.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/15182131/145552500-4384d318-14fc-4243-9110-7eae5f3ab4bb.png">

**Comment by elcinsayin** [comment]
Yes, thank you so much for that. 

I will look into the locks today.
