### ISSUE TITLE
Update Hierarchy does not apply changes in attribute type

### ISSUE THREAD

**Issue by joetm1** [cubewise-code/tm1py#664]
**Describe the bug**
If the type of an attribute is changed on the hierarchy object, it isn't updated by the update method on the hierarchy service

**To Reproduce**
Change an attribute's type and then update the dimension/hierarchy.

**Expected behavior**
A change in attribute type should be recognized and applied to the model.

**Version**
1.8.0
11.8.00900.3

**Additional context**
The code in the HierarchyService.update_element_attributes appears to check for deleted attributes, newly created attributes, but not for cases where an existing attribute's type has changed.

**Comment by MariusWirtz** [comment]
Thanks for reporting this inconsistency @joetm1. I created a fix for the issue.

Please update your TM1py version to the feature branch and check if the fix resolves the issue for you:

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/feature/attribute-updates.zip
```

**Comment by joetm1** [comment]
Thanks for the lightning response!!

I’m now getting this error though:

    from TM1py.Services import TM1Service
  File "D:\Program Files\Python\lib\site-packages\TM1py\__init__.py", line 39, in <module>
    from TM1py.Services.AnnotationService import AnnotationService
  File "D:\Program Files\Python\lib\site-packages\TM1py\Services\__init__.py", line 4, in <module>
    from TM1py.Services.ChoreService import ChoreService
  File "D:\Program Files\Python\lib\site-packages\TM1py\Services\ChoreService.py", line 132
    def search_for_process_name(self, process_name: str, **kwargs) -> List[Chore]:
                                                                                  ^
IndentationError: unindent does not match any outer indentation level


Joe

**Comment by MariusWirtz** [comment]
Please retry. I just pushed another commit.

**Comment by joetm1** [comment]
Brilliant – works great!

Thanks Marius.

**Comment by MariusWirtz** [comment]
Thanks. I will merge the changes.
