### ISSUE TITLE
Create new application, add file and set alias to it

### ISSUE THREAD

**Issue by VadymS77** [cubewise-code/tm1py#669]
I need to create Folder using TM1py add to it file for example xlsx or txt and set alias to this file in Application folder 
Anyone any idea how to do it correctly, 
many thanks

**Comment by VadymS77** [comment]
I'm trying to use "update_or_create_document_from_file"
    **tm1_src.applications.update_or_create_document_from_file**(
                            path = '**Menu**',
                            name = '**Main menu**',
                            path_to_file = "D:\TM1_Models\reports\main\**Main_menu.xlsx**",
                            private=False
                        )
1. "**Menu**" doesn't create automatically. How can I create Application Folders structure using TM1py?
2. Value of parameter - "name" must include extension. Unfortunately.
Some names of my Applications structure - without extensions (for example - Application name "**Main menu**" have link to physical file - **Main_menu.xlsx**). How can I set application name without extension?

**Comment by MariusWirtz** [comment]
You can find a sample of how to create a folder here:
https://github.com/cubewise-code/tm1py/blob/4b0997d91174c625141f0007d3d7fa5a94616d97/Tests/ApplicationService_test.py#L242
Does that answer your first question?

What happens if you don't include the extension in the name?

**Comment by VadymS77** [comment]
Hi Marius
thanks you really helped me, first question closed, found my mistake
I added code for create folder, example
            app = FolderApplication("", "a_path")
            tm1.applications.create(application=app, private=False)
            
next question about extension 
If I don't include extension in the name
file in ".\DATA\}externals" will be "FileDoc_2_20220120150754.blb"
if I set extension, file will be "FileDoc_2_20220120150754.xlsx"
source file  - FileDoc_2.xlsx

**Comment by MariusWirtz** [comment]
I'm not sure I understand the problem.

Can you not do this?

``` python
with open(Path(__file__).parent.joinpath('resources', 'document.xlsx'), "rb") as file:
    app = DocumentApplication(path=folder, name='document', content=file.read())
    tm1.applications.create(application=app, private=private)
```

**Comment by VadymS77** [comment]
yes,
Of couse, I used this code. it doesn't work correctly if I put name='document' without extension.  (may by I do something wrong) otherwise with extension it work fine
My test environment:
TM1SERVER_APP_version=TM1SERVER_APP-AW64-ML-RTM-11.0.9.58-0
Name: TM1py, Version: 1.8.0


1) without extension
        with open(Path(__file__).parent.joinpath('resources', 'document.xlsx'), "rb") as file:
            app = DocumentApplication(path='a_path', name='document', content=file.read())
            tm1_src.applications.create(application=app, private=False)
2) with extension
        with open(Path(__file__).parent.joinpath('resources', 'document.xlsx'), "rb") as file:
            app = DocumentApplication(path='a_path', name='document.xlsx', content=file.read())
            tm1_src.applications.create(application=app, private=False)
            
result:
            
![rest_app_issue](https://user-images.githubusercontent.com/61417962/150812017-8a394cbb-c973-4033-8b63-e3f6a3a3b774.png)

**Comment by VadymS77** [comment]
in this case, document_timestamp.blb can be open by Excel
another one case, for example, document_timestamp.blb is opening by Word, it depend what file was added by script

**Comment by MariusWirtz** [comment]
If TM1py offered a function to rename an application, would that solve your problem?

I think if renaming an application was available you could create the application as you do in case 2 and then in a second step rename it to remove the suffix. 
Would that solve your problem?

**Comment by MariusWirtz** [comment]
OK. We will look into implementing the `rename` function.

**Comment by MariusWirtz** [comment]
Hi @VadymS77,

please upgrade to the feature branch and verify that the rename function works for you:

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/feature/rename-application.zip
```

**Comment by VadymS77** [comment]
Marius
a lot of thanks, we did it, works fine

example code:
        app = FolderApplication('', 'a_path')
        tm1_src.applications.create(application=app, private=False)
        
        with open(Path(__file__).parent.joinpath('resources', 'document.xlsx'), "rb") as file:
            app = DocumentApplication(path='a_path', name='document.xlsx', content=file.read())
            tm1_src.applications.create(application=app, private=False)

            tm1_src.applications.rename(path=app.path,
                            application_type = app.application_type,
                            application_name= app.name,
                            new_application_name= 'document',
                            private=False)
