### ISSUE TITLE
Release 1.9

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#670]
It's about time for a new release that includes all the new features from Q4 2021.

**Comment by dmillerksu** [comment]
Any idea when you're going to release 1.9?  Is there a way to download the current unreleased content?  We'd like to use the new skip_non_updateable argument for the write functions.

**Comment by MariusWirtz** [comment]
You can upgrade to the current master branch on GitHub like this:

```
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/master.zip --upgrade
```

I will try to do the release to PyPI on Friday this week.
