### ISSUE TITLE
Write attributes on hierarchies

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#676]
**Describe what did you try to do with TM1py**
I am attempting to write attributes on hierarchies using the write function.
But am getting a TI process error.

```
cell_attributes[('Calendar:' + month_name, "MMM YYYY")] = attr_value

tm1.cells.write(
    cube_name=cube_name,
    cellset_as_dict=cell_attributes,
    use_ti=True,
)
```

**Describe what's not working the way you expect**
I was expecting the unbound process to execute TI function ElementAttrPutS to write the attribute values to the hierarchy instead of CellPutS.

**Version**
- TM1py 1.8.0
- TM1 Server Version: 11.8

**Additional context**
```
  File "C:\Python\Python39\lib\site-packages\TM1py\Services\CellService.py", line 599, in write
    return self.write_through_unbound_process(
  File "C:\Python\Python39\lib\site-packages\TM1py\Utils\Utils.py", line 30, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\Python39\lib\site-packages\TM1py\Services\CellService.py", line 90, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\Python39\lib\site-packages\TM1py\Services\CellService.py", line 757, in write_through_unbound_process
    raise TM1pyWritePartialFailureException(statuses, log_files, len(successes))
TM1py.Exceptions.Exceptions.TM1pyWritePartialFailureException: 1 out of 1 write operations failed partially. Details: ['TM1ProcessError_20220127083756_66823616_.log']
```

**Comment by MariusWirtz** [comment]
@cubewise-gng

> I was expecting the unbound process to execute TI function ElementAttrPutS to write the attribute values to the hierarchy instead of CellPutS.

How would the `ElementAttrPutS` code look in your sample?

**Comment by cubewise-gng** [comment]
Hi @MariusWirtz 

The sample I am thinking is that the TI function ElementAttrPutS would be run to write attribute values against hierarchies.
```
ElementAttrPutS( 'value1', DimName, 'hierarchy1', 'element1', 'attribute1');
ElementAttrPutS( 'value2', DimName, 'hierarchy2', 'element1', 'attribute1');
```

These TI code would be generated by TM1py when it recognizes the colon syntax for hierarchies is being used
```
cells = {
   ('hierarchy1:element1', 'attribute1'): 'value1',
   ('hierarchy2:element1', 'attribute1'): 'value2'
}
```

**Comment by MariusWirtz** [comment]
I understand.
So when writing to an `}ElementAttributes` cube and the `:` syntax is used we must not use `CellPutS` but `ElementAttrPutS`.

I think we can include this check in the `write_through_unbound_process` function.

**Comment by MariusWirtz** [comment]
Hi @cubewise-gng,

I created a fix for this issue. the `write` function should now be able to write attribute values, using the colon syntax, when `use_ti` is `True`
Please upgrade to the feature branch and test if it works for you.

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/feature/write-to-other-hierarchies.zip
```

Thanks!!

**Comment by cubewise-gng** [comment]
Hi @MariusWirtz 

Thanks you. That worked. It is now able to write to the hierarchy attributes using the colon syntax.

**Comment by MariusWirtz** [comment]
Thanks for the confirmation!
