### ISSUE TITLE
execute_mdx_elements_value_dict strings with double quotes

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#696]
**Describe the bug**
The function execute_mdx_elements_value_dict() returns element names with additional double quote characters if the element name itself contains double quotes.

Example.
When querying against the }ClientGroups cube which has CAM Security Groups.

The }Group element name is
`CAMID("CognosExpressActiveDirectoryID:u:f37d2aeb2aab7c4c807a036806357318")`

but the function interprets and returns string with additional double quotes
`"CAMID(""CognosExpressActiveDirectoryID:u:f37d2aeb2aab7c4c807a036806357318"")"`

**To Reproduce**
mdx against }ClientGroups cube
`cellset = tm1.cells.execute_mdx_elements_value_dict(mdx)`

**Expected behavior**
Could the function return the element names as is without the additional double quotes used to escape the string characters?

**Version**
TM1py [1.9.1]
TM1 Server Version: [11.8.01000.6]

**Comment by MariusWirtz** [comment]
I created a fix. Please let me know if works for you:

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/issue/doubled-double-quotes-in-response-str.zip
```

**Comment by cubewise-gng** [comment]
Thanks that worked.
