### ISSUE TITLE
`execute_set_mdx` fail to show alias element type

### ISSUE THREAD

**Issue by yyzz1010** [cubewise-code/tm1py#701]
**Describe the bug**
`execute_set_mdx` fail to show alias element type, only shows "String"

**To Reproduce**
1. create an alias attribute
2. using `dimensions.hierarchies.elements.execute_set_mdx` to get data

**Expected behavior**
expect showing 'Type': 'Alias' for alias attribute

**Version**
TM1py: 1.9.0
TM1 Server Version: 11.0.00204.1032

**Screenshot**
![image](https://user-images.githubusercontent.com/45536868/159455936-b9d2ccb9-747f-4cfa-bf6f-cf2f94c559c9.png)
![image](https://user-images.githubusercontent.com/45536868/159455948-ef401a3c-82dc-4443-b90b-22462ca55d9d.png)

**Comment by jrobinsonAG** [comment]
Hi @yyzz1010

Are you looking specifically for the Alias elements, either to include or exclude them? Or handling all attributes by type?

To get a list of Alias attributes for a given dimension hierarchy
```python

tm1_source.elements.get_alias_element_attributes( dimension_name ='}zTest',  hierarchy_name = '}zTest' )
```

To get all attributes including the type for a dimension hierarchy you can use
```python
tm1_source.elements.get_element_attributes( dimension_name ='}zTest',  hierarchy_name = '}zTest' )
```

**Comment by yyzz1010** [comment]
`get_element_attributes` helps! thank you @jrobinsonAG =D
