### ISSUE TITLE
Additional elements in Leaves Hierarchy

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#702]
**Describe the bug**
If there are elements in the leaves hierarchy that aren’t in any other hierarchy TM1py needs to create them explicitly.

**To Reproduce**
Source dimension to have additional elements in the Leaves hierarchy and not in any other hierarchies.
TM1py read the dimension and create a new copy of the dimension.
The resulting dimension will be missing the additional elements in the Leaves hierarchy.

**Expected behavior**
TM1py to create all the additional elements in the Leaves hierarchy when copying from another dimension

**Version**
TM1py 1,9,0
TM1 Server Version: = 11.8

**Comment by MariusWirtz** [comment]
Nice one. Thanks for the catch! We missed this edge case.

I created a fix. Please let me know if works for you:

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/issue/create-elements-in-leaves-hierarchy.zip
```

**Comment by cubewise-gng** [comment]
Thanks that worked!
