### ISSUE TITLE
ExecuteCommand not committing data

### ISSUE THREAD

**Issue by Frank-Ruta** [cubewise-code/tm1py#705]
Hi there,

I have created a python script that creates mapping values based on some logic and then writes the data into a mapping cube in PA. Everything works perfectly when executing the script through a command line and also when running it as a batch file. I've pasted the simple batch file below. The issue is that when running through a TI via ExecuteCommand, the data does not write to the cube. I feel like I am missing something small but obvious. Hopefully somebody can help me out.

`@echo off
cd /d "D:\path_to_python_scripts"
"D:\path_to_python\python.exe" "D:\path_to_python_scripts\script.py"`

I am running it with a simple TI that uses ExecuteCommand

`ExecuteCommand('path_to_batchfile\runTI.bat',0);
`

When running the TI, I can see a spike in CPU usage by python followed with CPU usage by the tm1sd Application telling me that ExecuteCommand ran the batch file. However nothing gets written to the cube.

Below is the last line of my python script which writes a dataframe into the cube. 

`tm1.cubes.cells.write_dataframe(cube_name='Cubename', data=dataframe, dimensions=[cube_dims] )`

I am on the latest version of tm1py. And on PA 2.0.9.9

**Comment by rkvinoth** [comment]
When you run your script from command prompt or trigger it via batch script, you are running it using your credentials/ your account/ your login (what ever you wanna call it).

But when you call it via a TI process using `ExecuteCommand`, it is the account that is running the TM1 service will be calling the python script. So, does this account have the required access?

**Comment by Frank-Ruta** [comment]
Amazing, thank you! That was the issue. We switched service accounts on our dev server recently and it did not have proper access to write in PA.
