### ISSUE TITLE
Create View for Data Processing

### ISSUE THREAD

**Issue by scotthoopes** [cubewise-code/tm1py#713]
**Describe what did you try to do with TM1py**
First, I want to apologize for this newbie question! I feel like what I am trying to do is fairly basic. But I can't seem to find any documentation on what I am wanting to do. 

In a basic TI in the Prolog section you can create view that is used as the data source. 

Once the TI hits the Data section it loops through that view (all dimensions at the leaf level) and runs through the logic in the Data section. The other thing that we normally do in the TI is we create temporary subsets to help limit the data that runs. 

I feel like this is a pretty basic use case from a TI perspective when you are using Cube data as a data source. 

**Describe what's not working the way you expect**

When I am trying to do this in TM1Py I am generating the view and trying to write to a CSV. 

`with TM1Service(**config['tm1_server']) as tm1:
    data = tm1.cubes.cells.execute_view(
        cube_name="{Cube Name}",
        view_name = "{View Name}",
        private=False
    )
df = build_pandas_dataframe_from_cellset(data)`

When I am doing this the only data I am getting is the initial view that is being generated and it doesn't run through all of the possible leaf level elements based on the subsets in the view. 

I am expecting that when I write to the CSV that it will run through all of the combinations of the leaf level elements so I can get a full view of the cube data in the export. 

What is the best way to do this? 

Do I need to create an MDX statement with a variable and loop through all of the elements? 

Let me know if there is any other context needed.

**Comment by MariusWirtz** [comment]
Hi @scotthoopes,

you can use the `execute_view_dataframe` function to retrieve the content of a cube view as a dataframe. 
Once you have a dataframe you can directly create a csv or an xlsx file from it:

``` python
import pandas as pd

from TM1py import TM1Service

with TM1Service(base_url="https://localhost:12354", user="admin", password="apple") as tm1:
    df: pd.DataFrame = tm1.cells.execute_view_dataframe(
        cube_name="c1", view_name="default", private=False,
        skip_zeros=True, skip_consolidated_cells=False, skip_rule_derived_cells=False)

    df.to_excel("C:/temp/out.xlsx")
    df.to_csv("c:/temp/out.csv")
```

Does that answer your question?


You can also read the content of a cubeview as a csv directly with the `execute_view_csv` function 

``` python
from TM1py import TM1Service

with TM1Service(base_url="https://localhost:12354", user="admin", password="apple") as tm1:
    text = tm1.cells.execute_view_csv(
        cube_name="c1", view_name="default", private=False,
        skip_zeros=True, skip_consolidated_cells=False, skip_rule_derived_cells=False)

    with open("C:/temp/output.csv", "w") as file:
        file.write(text)

```

**Comment by scotthoopes** [comment]
Hi @MariusWirtz thanks for the response. I have done the Pandas dataframe and the issue that I am having is that when I am processing it is only showing me the current view rather than all of the combinations of values. 

For example, here is a screenshot of the view once it is created in our TI by `ViewCreate`:
![Screen Shot 2022-04-19 at 4 13 01 PM](https://user-images.githubusercontent.com/25986018/164113011-9ea842a3-c0e3-4e9f-88e3-d11cb6de9453.png)

As you can see the values are all zeros. But once the TI process runs it goes through all of the possible leaf level combinations in that are available in the view. This is defined in the prolog of the TI as: 

```
DataSourceType = 'VIEW' ;
DataSourceNameForServer = sSourceCube ;
DataSourceCubeView = sViewName ;
```

As an example of how I understand the TI runs when it has the cube as a source. It goes through all of the possible leaf level elements. Similar to the simple example below:

<img width="268" alt="Screen Shot 2022-04-19 at 4 48 08 PM" src="https://user-images.githubusercontent.com/25986018/164147609-96dca4f5-609b-4f73-b079-09e4f1eafbba.png">

In the current view I am running in TM1Py all I am getting is similar to the very first row value of zero. Not any of the following rows that have any values. Does that make sense? 

To further elaborate on the example if you did a text output of this view in a TI you would get something similar to this:

<img width="274" alt="Screen Shot 2022-04-19 at 10 01 59 PM" src="https://user-images.githubusercontent.com/25986018/164147858-987b7c86-5af6-4f78-9cad-2165faad9bf1.png">

In the end what I am trying to do is take a view from TM1  get all of the leaf level intersections that have values based on the subsets I have created in the view. 

I am not sure if there is a way to get the view I want but look at it from a consolidated level then in TM1Py convert it that consolidated view to all of the leaf level intersections.

In answer to your last question once I get the data into TM1Py I am going to do a few updates to the data then I am going to export the values to a CSV as an MVP. Then once I have been able to validate the value we will move from a CSV to sending the values straight to a SQL table. 

I hope that makes sense! I am happy to provide any additional details as needed.

**Comment by MariusWirtz** [comment]
Hi @scotthoopes,

it should be no problem to produce this with TM1py using the `execute_view_dataframe` function.
![image](https://user-images.githubusercontent.com/15182131/164332988-e1fb9e92-e548-4a81-aba8-a050a1f3bee5.png)

Possibly TM1py is more sensitive to the rows-columns setup of the view.
I think when you create the cube view, you would have to explicitly place Dim1, Dim2, and Dim3 on rows or columns.
Then you would get all elements from the subset/selection in the data frame.


> I am not sure if there is a way to get the view I want but look at it from a consolidated level then in TM1Py convert it that consolidated view to all of the leaf level intersections.

You could write a TM1py script that takes consolidated elements as input. So you can for instance pass `Europe`, `All Segments`, `Q1` to the script.
Then the TM1py script could send an MDX query to the cube in which it requests all leaf children underneath `Europe`, `All Segments` and `Q1`.
Is that what you have in mind?

**Comment by scotthoopes** [comment]
@MariusWirtz Thanks for the feedback. I think the answer for my main question is to suppress zeros and to build a view that will include all of the leaf level elements. 

For the example you gave at the end of sending in a consolidation then creating an MDX view for the leaf children. Is there is a good resource to learn about that? A script in the Samples perhaps?

**Comment by MariusWirtz** [comment]
Hi @scotthoopes,

this post should help you with the parametrization of the query:
https://cubewise-code.github.io/tm1py-tales/2022/dynamic-tm1-queries-with-mdxpy.html
