### ISSUE TITLE
Authentication through gateway: missing dependency requests_negotiate_sspi.HttpNegotiateAuth

### ISSUE THREAD

**Issue by grandryjn** [cubewise-code/tm1py#714]
Hi,

I need a bit of help.
I am connecting to a TM1 instance using gateway, when doing so I am facing an issue when trying to login.

I have the following error message.
RuntimeError: SSO failed due to missing dependency requests_negotiate_sspi.HttpNegotiateAuth. SSO only supported for Windows

I am on windows, I am not too sure how to get the missing dependency.
I tried to upgrade the package requests_negotiate_sspi through pip but I am still facing the issue.

any idea what I could do to overcome the issue?

Thanks,

**Comment by MariusWirtz** [comment]
Perhaps you have two versions of Python installed on the machine and you installed the package on a different one that's used to run the script.

When you run the script you can be explicit about the python interpreter:
`C:/python3/python.exe C:/py_projects/my_script.py`

To verify if the package is installed you also be explicit about the pip:
`C:/python38/scripts/pip.exe show requests_negotiate_sspi`

Please try that. If it is indeed installed and the script still fails with that error message it may be an issue in TM1py.

**Comment by grandryjn** [comment]
Unfortunately I still have the same issue when specifying the python path, and the package seems to be installed properly.

```
Name: requests-negotiate-sspi
Version: 0.5.2
Summary: This package allows for Single-Sign On HTTP Negotiate authentication using the requests library on Windows.
Home-page: https://github.com/brandond/requests-negotiate-sspi
Author: Brandon Davidson
Author-email: brad@oatmail.org
License: UNKNOWN
Location: c:\users\xxxx\appdata\roaming\python\python39\site-packages
Requires: pypiwin32, requests
Required-by: TM1py
```

**Comment by cubewise-nswan** [comment]
It looks like Python has been installed under a single-user install with the packages sitting in the roaming directory. Could you reinstall Python, installing under C:\Python38\, this will allow all users on the PC/Server to access the Python executable

**Comment by grandryjn** [comment]
My python installation folder and PATH are located into C:\Program Files\Python39 but I see that the library sits in C:\user...

Probably running my pip commands from VS code terminal is not helping. 
I'll give a go to reinstall stuff properly. 

Even though it's on my laptop (single user) I'll try to get things installed properly.

**Comment by grandryjn** [comment]
Reinstalled python (3.10) into the folder c:\python310.
Ran Pip from proper command line and check where it is insaled.

```
Name: requests-negotiate-sspi
Version: 0.5.2
Summary: This package allows for Single-Sign On HTTP Negotiate authentication using the requests library on Windows.
Home-page: https://github.com/brandond/requests-negotiate-sspi
Author: Brandon Davidson
Author-email: brad@oatmail.org
License: UNKNOWN
Location: c:\python310\lib\site-packages
Requires: pypiwin32, requests
Required-by: TM1py
```

Unfortunately I still have the same issues...
At least I have updated my python version and cleaned my installation.

**Comment by rkvinoth** [comment]
This doesn't seem to be an issue with `TM1py`. 

You can try the following steps:

1. Uninstall any previous version of python as an ADMIN
2. Make sure that all the python files are gone (deleted)
3. Reinstall python (stable version) as an ADMIN
4. Install all the required packages (`requests-negotiate-sspi` will get automatically installed when you install `TM1py`, but double check it) as an ADMIN

This is the beginners guide for `TM1py` (or any other python package).

**Comment by grandryjn** [comment]
Actually my bad, the re-install did work and updated to the following error now.
>RuntimeError: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

I guess now this is more an error with the connection details I am providing...

**Comment by rkvinoth** [comment]
Right, to help you further we will need those connection details (not the exact value but the parameters you are passing)
You can alternatively go through previously closed issues here.
