### ISSUE TITLE
'use_iterative_json' when loading a view to a data frame produces wrong output

### ISSUE THREAD

**Issue by tobiaskapser** [cubewise-code/tm1py#715]
**Describe the bug**
When using the functions `execute_mdx_dataframe()` or `execute_view_dataframe()` from the Cells-Service I get the wrong output in my DataFrame with the following parameters in the function call: `use_iterative_json=True`  and `skip_zeros=False`.
The addresses for the cells are not set properly in this case and contain the same element for each value.

**To Reproduce**
For the GO_Scorecards-Cube from the 'GO_Scorecards' sample system I define the following MDX:
```
SELECT {
  {TM1SUBSETALL( [country] )} *
  {TM1SUBSETALL( [Time] )} *
  {[gometric].[Gross profit]} *
  {[Metric Indicators].[Actual]}
  }
ON 0
FROM [GO_Scorecards]
```

and execute the view with the following function call:
```
tm1.cubes.cells.execute_mdx_dataframe(
        MDX, 
        skip_zeros=False, 
        use_iterative_json=True
        )
```
With `use_iterative_json=True`  and `skip_zeros=False` this produces:

```
0  Americas  2013     Gross profit            Status                        0
1  Americas  2013     Gross profit            Status                        1
2  Americas  2013     Gross profit            Status      211269.397241762548
3  Americas  2013     Gross profit            Status       212400.53594093115
4  Americas  2013     Gross profit            Status    0.0500000000000000028
5  Americas  2013     Gross profit            Status     -1131.13869916848489
6  Americas  2013     Gross profit            Status  -0.00532549832870033921
7  Americas  2013     Gross profit            Status    -0.106509999999999994
8  Americas  2013     Gross profit            Status     0.750589999999999979
9  Americas  2013     Gross profit            Status    -0.963869126510463192
```

**Expected behavior**

Using `use_iterative_json=False`  and `skip_zeros=False` produces the correct output:

```
0  Americas      2013  Gross profit            Actual  211269.397242
1  Americas   Q1 2013  Gross profit            Actual  131884.476436
2  Americas  Jan 2013  Gross profit            Actual   47078.169341
3  Americas  Feb 2013  Gross profit            Actual   32360.568351
4  Americas  Mar 2013  Gross profit            Actual   52445.738743
5  Americas   Q2 2013  Gross profit            Actual   46895.724790
6  Americas  Apr 2013  Gross profit            Actual   31939.519921
7  Americas  May 2013  Gross profit            Actual  -20069.551073
8  Americas  Jun 2013  Gross profit            Actual   35025.755943
9  Americas   Q3 2013  Gross profit            Actual   32489.196016
```

**Version**
TM1py: 1.9.1
TM1 Server Version: 11.8.00401.1

**Additional context**
none

**Comment by MariusWirtz** [comment]
Thanks for reporting the issue. Very much appreciated. I will look into it this week.

In the meantime, in case you are looking for a quick solution, does the script fail if you place selections on both axes?
I'm asking because currently you have all selections on the columns and this is likely the reason why this error slipped through our testing.

**Comment by MariusWirtz** [comment]
Hi @tobiaskapser,

I created a fix for the issue. Please upgrade to the latest master branch and verify that the issue is resolved.

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/master.zip
```

**Comment by tobiaskapser** [comment]
Hi @MariusWirtz,

yes, it's working fine now.  Thank you for the fast response!
