### ISSUE TITLE
new feature: ProcessDebugBreakpoint

### ISSUE THREAD

**Issue by adscheevel** [cubewise-code/tm1py#725]
I've been doing some work on a ProcessDebugBreakpoint object and additional methods in ProcessService for process debugging. It's not yet ready for a pull request to the master branch and honestly it would benefit from some community review, refactoring, and add-on development. I figured it'd be better to iterate through that in a separate branch instead of a flurry of changes on the master after an initial pull. Can you create a new branch off of master that I can submit my initial work to?

**Comment by MariusWirtz** [comment]
Hi @adscheevel,

Happy to review and contribute.

I pushed a new branch to remote: `feature/process-debug-breakpoint`. 
It is based on the current master branch. Feel free to open a PR into this branch.

**Comment by adscheevel** [comment]
Great thanks, submitted initial PR.
