### ISSUE TITLE
Retrieve attribute value unsupported token +

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#729]
**Describe the bug**
Running function execute_set_mdx() to retrieve attribute value called "Code + Description" fails because of the '+' character.

**To Reproduce**
Alias attribute name with '+' character. eg "Code + Description"

**Version**
TM1py 1.9.1
TM1 Server Version: 11.8

**Additional context**
```
Traceback (most recent call last):
  File "c:\main.py", line 112, in <module>
    elements = tm1.elements.execute_set_mdx(
  File "C:\Python\Python310\lib\site-packages\TM1py\Services\ElementService.py", line 560, in execute_set_mdx
    response = self._rest.POST(url, json.dumps(payload, ensure_ascii=False), **kwargs)
  File "C:\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 80, in wrapper
    self.verify_response(response=response)
  File "C:\Python\Python310\lib\site-packages\TM1py\Services\RestService.py", line 459, in verify_response
    raise TM1pyRestException(response.text,
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '{"error":{"code":"278","message":"Unsupported token at: +Description;$expand=Parent($select=Name,UniqueName,Attributes/Code+Description),Element($select=Type,Level)))"}}' - Status Code: 400 - Reason: 'Bad Request' - Headers: {'Content-Length': '154', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

```

**Comment by MariusWirtz** [comment]
That's unfortunately a limitation of the REST API. `+` is not allowed in attributes names
@lotsaram wrote about this a couple of years ago.

> 
> Attribute Names
> TM1 may be case and space insensitive but the OData standards and TM1’s Restful API are not. The TM1 Restful API observes the OData specification which has a limitation of only accepting alpha-numeric Ascii characters and underscore. All special characters and spaces should be avoided.
> 
> Therefore, to avoid issues querying attribute values via the Rest API we need to be even more restrictive in naming attributes than in naming elements (even though in fact attribute names are just elements). Attribute names should contain only characters:
> 
> A – Z      (characters 65 – 90)
> a – z       (characters 97 – 122)
> 0 – 9      (characters 48 – 57)
> _             (underscore, character 95)
> 


https://cubewise.com/blog/naming-convention-rules-object-element-attribute/

As a workaround, we can use MDX with DIMENSION PROPERTIES
