### ISSUE TITLE
Function to replace DimensionElementPrincipalName

### ISSUE THREAD

**Issue by MaaYuu** [cubewise-code/tm1py#730]
**Describe what did you try to do with TM1py**

I just want to replicate the use of **DimensionElementPrincipalName** function in Tm1py.
I could replicate it by fetching ElementAttributes cube values, and revert to principal name only specifying specific alias name.
This function do not need to specify any alias name, so is there any way to replicate this by not specifying any alias name?

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:

**Version**
- TM1py : 1.9.1
- TM1 Server Version: 2.0.9.1

**Comment by rkvinoth** [comment]
Use the element's `get` method. The response should give you the principal name.

In the below example - `Jan-2022` is an alias for `202201`
```python
element = tm1.elements.get(dimension_name='Period', hierarchy_name='Period', element_name='Jan-2022')
print(element.name)
```

**Comment by MariusWirtz** [comment]
Hi @MaaYuu,

Yes. I wanted to suggest the same thing as @rkvinoth.

@MaaYuu I think you could write a wrapper around the `get` function in the `ElementService` and call it something like `get_element_principal_name`. It wouldn't save people much code but it's perhaps more obvious and readable than the current approach that @rkvinoth suggested.

**Comment by MaaYuu** [comment]
Hi @rkvinoth . I will try this function.

@MariusWirtz , I made a change just copying `get` function. Please check, maybe it is not what you meant for.

**Comment by MariusWirtz** [comment]
Hi @MaaYuu,

I understood you wanted to create a new function in TM1py.
If so, feel free to open a Merge Request.

**Comment by MariusWirtz** [comment]
OK. Feel free to open a Merge Request with it.
