### ISSUE TITLE
Unauthorized response for an admin account

### ISSUE THREAD

**Issue by davidcar84** [cubewise-code/tm1py#737]
**Describe what did you try to do with TM1py**
I want to read audit logs using 'get_audit_log_entries' function. 

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. Expected result would be to have top 10 results from audit log.
2. Details: Using postman I'm able to run the query using following url pattern:
    http://server:port/api/v1/AuditLogEntries?$top=10
However, in TM1py I'm not able to run same query in spite of user is admin.
![tm1py_errors](https://user-images.githubusercontent.com/77596309/172075490-fa1c0dc1-8257-4497-aad8-3600f6898119.png)
An additional check I did was to run in Postman the `/api/v1/ActiveUser/Groups` where I'm able to see it's retrieving the admin group `{"@odata.context":"../$metadata#Groups","value":[{"Name":"ADMIN"}]}`
 
As get_audit_log_entries requires admin verification, I don't know if I'm missing something in connection parameters or if it could be a bug. Any help is appreciated.

**Version**
- TM1py [1.9.0] 
- TM1 Server Version: [11.8]

**Additional context**
If you encounter an error, please add the error message and the stack trace
`Traceback (most recent call last):
  File "C:/TM1_Connection/main.py", line 50, in <module>
    x = tm1.server.get_audit_log_entries(top=10)
  File "C:\TM1_Connection\venv\lib\site-packages\TM1py\Utils\Utils.py", line 30, in wrapper
    if not self.is_admin:
  File "C:\TM1_Connection\venv\lib\site-packages\TM1py\Services\ObjectService.py", line 57, in is_admin
    return self._rest.is_admin
  File "C:\TM1_Connection\venv\lib\site-packages\TM1py\Services\RestService.py", line 410, in is_admin
    response = self.GET("/api/v1/ActiveUser/Groups")
  File "C:\TM1_Connection\venv\lib\site-packages\TM1py\Services\RestService.py", line 80, in wrapper
    self.verify_response(response=response)
  File "C:\TM1_Connection\venv\lib\site-packages\TM1py\Services\RestService.py", line 462, in verify_response
    headers=response.headers)
TM1py.Exceptions.Exceptions.TM1pyRestException: Text: '' - Status Code: 401 - Reason: 'Unauthorized' - Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'OData-Version': '4.0', 'Set-Cookie': 'TM1SessionId=5kyNmoSA8uERTlio9ejgCmDphyA; Path=/api/; HttpOnly', 'WWW-Authenticate': 'Basic realm="TM1"'}
`

**Comment by davidcar84** [comment]
Hi @MariusWirtz, thanks for your answer. It was a silly mistake in my code as I was running the function out of the structure that creates the TM1 connection (indentation). I'm closing this comment and feel free to kick me out of here :)

**Comment by MariusWirtz** [comment]
Ha, quite the contrary! I appreciate you raising this issue. It has the positive side effect that it's findable through google and may help future TM1py users that face a similar issue. So keep 'em coming :)
