### ISSUE TITLE
Unable to ExecuteCommand using execute_ti_code

### ISSUE THREAD

**Issue by Maxpinch** [cubewise-code/tm1py#747]
**Describe the bug**
I am not able to use the ExecuteCommand() TurboIntegrator function with the execute_ti_code function.

**To Reproduce**
When I execute the following code directly from Arc, the file is successfully copied:

`ExecuteCommand('cmd /c copy /Y d:\tm1\server_dev\logs\test_copy.txt test_copy.txt', 0);`

However, when I try to execute it from TM1py, it doesn't work.

`prolog_code = "ExecuteCommand('cmd /c copy /Y d:\\tm1\\server_dev\\logs\\test_copy.txt test_copy.txt', 0);"
self.tm1.processes.execute_ti_code(prolog_code)`

I'm receiving a TM1py.Exceptions error saying the system cannot find the file specified. I'm also seeing the same error in the log file (ex: TM1ProcessError_20220610xxxx_}TM1py3217531265xz1-dsa2-.. )

**Expected behavior**
I would expect the same behavior whether the ExecuteCommand is executed from TM1py or Arc/Architect/PAW
**Version**
TM1py 1.8.0
PA 2.0.9.9
I'm an admin

**Additional context**
I'm able to use execute_ti_code to save data or RuleLoadFromFile but for some reason, I'm not able to execute a command.

**Comment by jrobinsonAG** [comment]
You may need to escape the / when passing through the python string.

**Comment by Maxpinch** [comment]
I updated my initial post. The path is good since I'm using two backslash in my path. Anyone is able to replicate this issue ?
Thanks

**Comment by jrobinsonLOR** [comment]
Hi @Maxpinch 

I was able to replicate it, the execute_ti_code method is expecting an iterable string object. So if passing a single string it is treating each character as separate line. 

If you enclose the string in a list it should work.

i.e. prolog_code = ["ExecuteCommand('cmd /c copy /Y d:\\tm1\\server_dev\\logs\\test_copy.txt test_copy.txt', 0);"]

**Comment by Maxpinch** [comment]
> Hi @Maxpinch
> 
> I was able to replicate it, the execute_ti_code method is expecting an iterable object of strings. So if passing a single string it is treating each character as separate line.
> 
> If you enclose the string in a list it should work.
> 
> i.e. prolog_code = ["ExecuteCommand('cmd /c copy /Y d:\tm1\server_dev\logs\test_copy.txt test_copy.txt', 0);"]

It works ! Thank you very much !

**Comment by Maxpinch** [comment]
If you enclose the string in a list it should work.
