### ISSUE TITLE
Update Applications

### ISSUE THREAD

**Issue by cubewise-gng** [cubewise-code/tm1py#748]
**Describe the bug**
The current function update_or_create_document_from_files(), is essentially deleting and recreating the application.
So is not really doing an update.
By uploading a new file to TM1 it is assigned a new system name so any reference to the old name will not work. eg used as menu links.

Could there also be a update() function by passing in the Application object?

**Expected behavior**
Update existing applications but retain the existing system name.

**Version**
TM1py 1.9.1

**Comment by MariusWirtz** [comment]
This issue should be addressed with #762.

@cubewise-gng please confirm that it has been resolved for you.

**Comment by cubewise-gng** [comment]
Thanks guys the update function works well.
