### ISSUE TITLE
Add Multiple Break Points

### ISSUE THREAD

**Issue by ianboltz** [cubewise-code/tm1py#764]
**Describe what did you try to do with TM1py**
I am using add break point on a process to debug, but I would like to add multiple in a single call

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. Add break point is singular, I want to be able to pass a range, or list of points to add in a single call

**Comment by adscheevel** [comment]
That should be feasible, in the meantime you can nest the add breakpoint call in a FOR loop that iterates through a list of breakpoint objects.

**Comment by MariusWirtz** [comment]
Fixed with #791 and #800
