### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by ubihw** [cubewise-code/tm1py#778]
**Describe the bug**
When accessing https://tm1py.readthedocs.io/en/latest/, only the "TM1 Services", "TM1 Objects", and "Exceptions" headers are shown. Clicking the Navigation Bar items doesn't work.

**To Reproduce**
visit https://tm1py.readthedocs.io/en/latest/, click any link.

**Expected behavior**
Documentation should be visible :-)

**Version**
tried with different browsers, computers locations, to no avail

**Comment by MariusWirtz** [comment]
Thanks for raising the issue.

I will look into this. In the meantime, I suggest you use a tool like PyCharm, that displays the docstrings and arguments of functions while you are using them. It is very helpful and substitutes a documentation to a degree.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/15182131/183875319-d2a296b4-7966-4b68-aa6a-bde1553e16be.png">

<img width="544" alt="image" src="https://user-images.githubusercontent.com/15182131/183875555-8c29ef50-bd2d-42c0-a0d0-16a1a164f083.png">

**Comment by ubihw** [comment]
Hello Marius,

Thanks for your suggestion. I use the documentation merely to get an overview oft the services/objects/functions available, I can access docstrings and synopsis in IDLE, too. But I think that if IF there is a documentation link, it should work ☺

Freundliche Grüße
Uwe Bielz

Von: Marius Wirtz ***@***.***>
Gesendet: Mittwoch, 10. August 2022 12:08
An: cubewise-code/tm1py ***@***.***>
Cc: Bielz, Uwe ***@***.***>; Author ***@***.***>
Betreff: Re: [cubewise-code/tm1py] Documentation not available (Issue #778)


Thanks for raising the issue.

I will look into this. In the meantime, I suggest you use a tool like PyCharm, that displays the docstrings and arguments of functions while you are using them. It is very helpful and substitutes a documentation to a degree.

[Das Bild wurde vom Absender entfernt. image]<https://user-images.githubusercontent.com/15182131/183875319-d2a296b4-7966-4b68-aa6a-bde1553e16be.png>

[Das Bild wurde vom Absender entfernt. image]<https://user-images.githubusercontent.com/15182131/183875555-8c29ef50-bd2d-42c0-a0d0-16a1a164f083.png>

**Comment by MariusWirtz** [comment]
Documentation is back 
https://tm1py.readthedocs.io/en/master/index.html

Let me know if you have any suggestions to improve the docs!
