### ISSUE TITLE
attempting to connect to a cam5 TM1 instance hosted on Azure

### ISSUE THREAD

**Issue by JonChrista** [cubewise-code/tm1py#788]
**Describe what did you try to do with TM1py**
Describe the script you ran and what it is supposed to do.

attempting connection with TM1service

## script
from TM1py import TM1Service

with TM1Service(address="", port=19308, ssl=True, namespace="LDAP", gateway="http://ctccrdev01.ct.hayne.cloud/ibmcognos/bi/v1/disp", verify=True) as tm1:
    print(tm1.server.get_product_version())
## End script
 

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
1. The result you expected.

Attempting to connect to a TM1 instance that is hosted on our 3rd party support provider in Azure, Expected connection to exist and Server version to be returned 

**Additional context**

## config file "
[TM1S]
AllowSeparateNandCRules=T

CAMPortalVariableFile = portal/variables_TM1.xml
ClientCAMURI = http://ctccrdev01.ct.#####.cloud/ibmcognos/bi/v1/disp
ServerCAMURI = http://ctccrdev01.ct.#####.cloud:9300/p2pd/servlet/dispatch
ClientMessagePortNumber = 19307
ClientPingCAMPassport = 43200
ClientPropertiesSyncInterval=180
IntegratedSecurityMode = 5

AdminHost=localhost
ServerName=CXMD
PortNumber = 19306
HTTPPortNumber = 19308
Protocol=tcp
UseSSL = T
Language = ENG
DistributedPlanningOutputDir = ./tunit
IdleConnectionTimeOutSeconds=9010

MaximumCubeLoadThreads= 5

DataBaseDirectory=F:\TM1DATA\CXMD\DATA
LoggingDirectory=F:\TM1DATA\CXMD\LOGS
RawstoreDirectory=F:\TM1DATA\CXMD\RAW

AuditLogMaxFileSize= 100 MB
AuditLogOn=T
AuditLogUpdateInterval=60

ParallelInteraction=T
#PerformanceMonitorOn=T
PersistentFeeders=T
ProgressMessage=True

GroupsCreationLimit=400 "
## end config file

If you encounter an error, please add the error message and the stack trace

## error code
C:\Users\Jon.Wilson\PycharmProjects\pythonProject1\venv\Scripts\python.exe C:/Users/Jon.Wilson/PycharmProjects/pythonProject1/venv/connect.py 
Traceback (most recent call last):
  File "C:\Users\Jon.Wilson\PycharmProjects\pythonProject1\venv\connect.py", line 3, in <module>
    with TM1Service(address="", port=19308, ssl=True, namespace="LDAP", gateway="http://ctccrdev01.ct.hayne.cloud/ibmcognos/bi/v1/disp", verify=True) as tm1:
  File "C:\Users\Jon.Wilson\PycharmProjects\pythonProject1\venv\lib\site-packages\TM1py\Services\TM1Service.py", line 15, in __init__
    self._tm1_rest = RestService(**kwargs)
  File "C:\Users\Jon.Wilson\PycharmProjects\pythonProject1\venv\lib\site-packages\TM1py\Services\RestService.py", line 201, in __init__
    self._start_session(
  File "C:\Users\Jon.Wilson\PycharmProjects\pythonProject1\venv\lib\site-packages\TM1py\Services\RestService.py", line 353, in _start_session
    token = self._build_authorization_token(
  File "C:\Users\Jon.Wilson\PycharmProjects\pythonProject1\venv\lib\site-packages\TM1py\Services\RestService.py", line 472, in _build_authorization_token
    return RestService._build_authorization_token_cam(user, password, namespace, gateway, verify)
  File "C:\Users\Jon.Wilson\PycharmProjects\pythonProject1\venv\lib\site-packages\TM1py\Services\RestService.py", line 493, in _build_authorization_token_cam
    raise RuntimeError(
RuntimeError: Failed to authenticate through CAM. HTTP response does not contain 'cam_passport' cookie

Process finished with exit code 1

## end error code

**Comment by MariusWirtz** [comment]
Hi @JonChrista,

this is an issue, that is been reported a few times in the past. Unfortunately, I haven't experienced the situation myself so I can not confidently say what resolves it. 

Maybe start looking into these 3 suggestions:

- @MaaYuu has suggested a solution here to change the configuration for the CAM Gateway:
https://github.com/cubewise-code/tm1py/issues/222#issuecomment-620300563

- You can access the URL manually and take the CAM passport from the browser cookies. Once you have the CAM passport, you can instantiate the `TM1Service` like this: 

``` python
with TM1Service(address=address, port=port, ssl=ssl, cam_passport=passport) as tm1:
    print(tm1.server.get_server_name())
```

- You can automate the above manual process with selenium. Python can use chrome to access the URL and grab the cookie. @AlexanderDvoynev discusses a solution here:
https://github.com/cubewise-code/tm1py/issues/124
The solution is a bit heavy, but it works.


My preferred solution would be 1. We have heard from other users that configuration on the Cognos Gateway can resolve this issue. 
Please let us know how it goes!

**Comment by MariusWirtz** [comment]
@JonChrista were you able to resolve the issue yet?

**Comment by JonChrista** [comment]
Issue resolved, using incorrect Namespace 

working code

with TM1Service(address="10.xx.xx..xx",
                port=19308, ssl=True,
                namespace="AD",
                gateway="http://###############.cloud/ibmcognos/bi/v1/disp",
                ) as tm1:

Thanks for the advice Marius

Regards Jon
