### ISSUE TITLE
Transfer data between server using tm1py

### ISSUE THREAD

**Issue by Dashon3200** [cubewise-code/tm1py#798]
Hi, I have seen a previous [question](https://github.com/cubewise-code/tm1py/issues/491) where it said that the best way to transfer data between servers is to use the to the `execute_mdx` function, so that it can return a dictionary that can be passed to the `write` function without any transformations.

I have tried to use this but I get an error in the `write` function. I am retrieving the MDX using `tm1.get_native_view (cube_name, view_name).MDX`

I feel the reason for the error is that the  order of dimension changes. Is there a way to get past this?
Also are there and better methods to transfer data using tm1py or tm1 processes?

@MariusWirtz can you please assist me with this. Thanks

**Comment by MariusWirtz** [comment]
Please post the error message and stack trace that you get when calling the `write` function with the result set from the `execute_mdx` function.

Did you pass `element_unique_names=False` as an argument to the `execute_mdx` function?

on a side note, you can simplify your code by using `execute_view` instead of reading the view and turning it into an MDX query.

**Comment by Dashon3200** [comment]
Thanks for the swift reply, I have passed `element_unique_names=False` and this solves the issue. I have also simplified the code using your suggestion to use `execute_view`. 

The code is now much simpler -
```
Data = tm1_source.cubes.cells.execute _view(source cube name, source view name, private=False, element unique names-False, skip zeros= True, skip_ consolidated cells= True, skip cell properties=True, skip_rule derived cells= True)
tm1_ target.cells.write(cube name= target cube name, cellset as dict= Data)
```
Is there anything else that can be done to make it more efficient and fast?

**Comment by MariusWirtz** [comment]
Two low-hanging fruits for performance:

- To make the writeback faster, you use the `write_async` function.
https://cubewise-code.github.io/tm1py-tales/2021/write-with-tm1py.html

- To make the reading faster you can do `skip_zeros=True` and potentially `skip_rule_derived=True` and `skip_consolidated=True`

on a side note, don't forget to clear the slice in the cube in the target instance.

**Comment by Dashon3200** [comment]
Thanks for the help, will implement this.

**Comment by MariusWirtz** [comment]
Hi @Dashon3200,

two simple solutions:

- use n smaller view / MDX queries instead of 1 large view.

- change the maximum view size parameter in the tm1.cfg. You can also do this dynamically before and after the retrieval.

``` python
config_changes = {"Performance": {"Memory": {"MaximumViewSizeMB": 5000}}}
tm1.server.update_static_configuration(config_changes)
```

**Comment by Dashon3200** [comment]
Thanks, will give this a try and share the results.
