### ISSUE TITLE
Writing a value to application from tm1py; not updating in the file in application or in Planning Analytics Workspace

### ISSUE THREAD

**Issue by tanjim2019** [cubewise-code/tm1py#799]
I have facing this issue, I am not sure if this functionality exists in tm1py or I am doing it wrong. Can you pls help me?
I have a report that is in application in tm1 architect and I have also published to planning analytics workspace. 
I am trying to update a value in a cell in the application file, which is an xlsm file uploaded in the application in tm1 architect. The same file is published in planning analytics workspace. 
I have written the below code and executed from conda environment. First, I printed the cell value from the file in the application from the python script and it is showing correctly. Then I executed the code with c1.value = "20". And after that again ran the script and put a print(c1.value), the updated value is printed that is 20 in my editor terminal but the value is not updated in the application or the planning analytics workspace. Can you pls help me with what I am doing wrong? Pls let me know if I am not clear. 

My code: 
```
from TM1py import TM1Service
from TM1py.Objects.Application import ApplicationTypes
from openpyxl import load_workbook
with TM1Service(address="XXXXX", port=8888, ssl=False, namespace = "CAM", gateway="http://xxxx:80/ibmcognos/cgi-bin/cognosisapi.dll") as tm1:
    application_entries = tm1.elements.get_element_names("}ApplicationEntries", "}ApplicationEntries")
    application_name = "xyz.xlsm" 
    application = tm1.applications.get(
        path="Admin",
        application_type=ApplicationTypes.DOCUMENT,
        name=application_name,
        private=False)
    wb = load_workbook(filename = application.name, read_only=False, keep_vba=True)
    sh = wb["Sheet1"]
    c1 = sh.cell(row = 18, column = 5)
    c1.value = "20"
    print(c1.value)
    wb.save(filename = application.name)
    tm1.applications.update(
        application = application,
        private=False)

```

**Comment by rclapp** [comment]
Based on what you are showing you are getting the file opening it, and then editing it, but doing nothing else. The edit that you are making is only happening on your machine and has never been published back to TM1. You will need to take that workbook, wb, and publish it back to the TM1 applications.

From: tanjim2019 ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Wednesday, September 7, 2022 at 2:51 PM
To: cubewise-code/tm1py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cubewise-code/tm1py] Writing a value to application from tm1py; not updating in the file in application or in Planning Analytics Workspace (Issue #799)


I have facing this issue, I am not sure if this functionality exists in tm1py or I am doing it wrong. Can you pls help me?
I have a report that is in application in tm1 architect and I have also published to planning analytics workspace.
I am trying to write a value to a cell in the application file, which is an xlsm file uploaded in the application in tm1 architect. The same file is published in planning analytics workspace.
I have written the below code and executed from conda environment. First, I printed the cell value from the file in the application from the python script and it is showing correctly. Then I executed the code with c1.value = "20". And after that again ran the script and put a print(c1.value), the updated value is printed that is 20 in my editor terminal but the value is not updated in the application or the planning analytics workspace. Can you pls help me with what I am doing wrong? Pls let me know if I am not clear.

My code:
from TM1py import TM1Service
from TM1py.Objects.Application import ApplicationTypes
from openpyxl import load_workbook
with TM1Service(address="XXXXX", port=8888, ssl=False, namespace = "CAM", gateway="http://xxxx:80/ibmcognos/cgi-bin/cognosisapi.dll") as tm1:
application_entries = tm1.elements.get_element_names("}ApplicationEntries", "}ApplicationEntries")
application_name = "xyz.xlsm"
application = tm1.applications.get(
path="Admin",
application_type=ApplicationTypes.DOCUMENT,
name=application_name,
private=False)
wb = load_workbook(filename = application.name, read_only=False, keep_vba=True)
sh = wb["Sheet1"]
c1 = sh.cell(row = 18, column = 5)
c1.value = "20"

print(c1.value)

wb.save(filename = application.name)

tm1.applications.update(

    application = application,

    private=False)

**Comment by tanjim2019** [comment]
@rclapp Thank you for your reply. I was under the impression that the below line of code updates the application after it is saved using wb.save(filename = application.name). 
    tm1.applications.update(
    application = application,
    private=False)
And also when I executed the script again with print it was giving the value I have written to ie 20. I called the file from application. So, 20 seems to be picking up from the file in the application. And do you know the script to publish a file from tm1py? I couldn't find it.

**Comment by rclapp** [comment]
Sorry I think I missed that line of code in your original post, but based on my testing I wan't able to get your code to work as written. Some small updates and this seems to work

`from TM1py import TM1Service
from openpyxl import load_workbook


with TM1Service(address='localhost', port=52670, ssl=False, user="admin", password="apple") as tm1:

    application_entries = tm1.elements.get_element_names("}ApplicationEntries", "}ApplicationEntries")
    print(application_entries)
    application_name = "24 Retail Dashboard"
    application = tm1.applications.get_document(path="Reports",
                                       name=application_name,
                                       private=False)
    application.to_xlsx(f'{application_name}.xlsx')

    wb = load_workbook(filename = f'{application_name}.xlsx', read_only=False, keep_vba=True)
    sh = wb["Dashboard"]
    c1 = sh.cell(row = 93, column = 3)
    c1.value = "20"
    print(c1.value)
    wb.save(filename = f'{application_name}.xlsx')
    tm1.applications.update_document_from_file(f'{application_name}.xlsx','Reports', application_name, private=False)`

**Comment by tanjim2019** [comment]
@rclapp thanks for your quick response. Awesome, yes that resolved it. :)
