### ISSUE TITLE
Can not skip control object when get all names in dimension service

### ISSUE THREAD

**Issue by Cubewise-Ronan** [cubewise-code/tm1py#802]
**Describe the bug**
skip_control_dims does not work, set it to True, but still seen the control objects in response.

**To Reproduce**
tm1.dimensions.get_all_names(skip_control_dims=True)

**Expected behavior**
No control object 

**Version**
TM1py [the latest]

**Additional context**
no.

**Comment by MariusWirtz** [comment]
The feature has been added in May this year f417b4b9dbd7e29d20c09f1c1239af0a0e3ddbc0 by @adscheevel 
It's not included in the PyPI release of TM1py.

You can upgrade to the current master branch for now. We will release a new version of TM1py to PyPI soon.
