### ISSUE TITLE
Impersonation issues

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/tm1py#803]
Hi all !

**Describe what did you try to do with TM1py**
Trying to use Impersonation. In this case, an IBM cloud (dev) environment.

**Describe what's not working the way you expect**
I have seen it working once in my code, afterwards it did not work anymore.

The number of model cubes and control cubes added up for an admin user ==> 92
The number of model cubes and control cubes added up for the non-admin user ==> 59
I have seen the result of 59 once in Visual Studio Code, after that, only the error message that the user in the Impersonation does not exist. But I did not change the user.

I tried a lot of things but certainly the full CAMID including CAMID, then the CAMID without CAMID( ) and this appears to work, I used the }TM1_DefaultDisplayValue alias of Planning Analytics/firstname lastname (which did not work).

Without Impersonation, I consistently get 92 as the result, so that is all good.

- TM1py: 1.9.1
- TM1 Server Version: 11.6.00004.2

I see similar behaviour (the same error message) in Postman and (Excel) VBA, all with similar coding.
My goal is to have it working in Excel VBA but also in the other tools.

![00](https://user-images.githubusercontent.com/17201709/191376125-d2786417-ee99-4afb-830d-eff24dce9ba7.PNG)

![01](https://user-images.githubusercontent.com/17201709/191376108-f2bb5704-16a3-4abb-a06a-721ea80546c5.PNG)

![02](https://user-images.githubusercontent.com/17201709/191377554-a7752a46-2ced-45e8-88fb-31171848454f.PNG)

**Comment by MariusWirtz** [comment]
Hi @wimgielis,

normally you can impersonate with the "user name".

here is a sample that works for me. Can you try this on your end?



``` python
from TM1py import TM1Service

with TM1Service(
        base_url='https://come-company.planning-analytics.ibmcloud.com/tm1/api/tm1',
        user="some_company_tm1_automation",
        namespace="LDAP",
        password="apple",
        ssl=True,
        verify=True,
        async_requests_mode=True) as tm1:
    print(f"I am '{tm1.whoami.name}' I see {tm1.cubes.get_number_of_cubes()} cubes")

    admin_users = [user.name for user in tm1.security.get_users_from_group("ADMIN")]
    users = tm1.security.get_all_user_names()

    for user in users:
        if user in admin_users:
            continue

        with TM1Service(
                base_url='https://come-company.planning-analytics.ibmcloud.com/tm1/api/tm1',
                user="some_company_tm1_automation",
                namespace="LDAP",
                password="apple",
                ssl=True,
                verify=True,
                impersonate=user,
                async_requests_mode=True) as impersonated_tm1:
            print(f"I am '{impersonated_tm1.whoami.name}' I can see {tm1.cubes.get_number_of_cubes()} cubes")

```

**Comment by wimgielis** [comment]
Many thanks Marius ! Nice testing script.

I see that all users would see 92 cubes, as if the Impersonation is not honoured (?)

![image](https://user-images.githubusercontent.com/17201709/191528106-01f16c62-a069-4c1b-8db3-8efc32b0d066.png)

Would you have any idea what is going on ? When looking in TM1 for 1 such user, I have:

This user is only part of 1 group:
![image](https://user-images.githubusercontent.com/17201709/191528978-2de3932e-c1ec-45b7-9124-766487b52fb1.png)

Cube security is limited:
![image](https://user-images.githubusercontent.com/17201709/191529324-42833be8-3a39-4e4c-8d02-9579008b55d9.png)

**Comment by MariusWirtz** [comment]
Excuse me. There was an issue in my script. please replace this line:

```
print(f"I am '{impersonated_tm1.whoami.name}' I can see {tm1.cubes.get_number_of_cubes()} cubes")
```
 with this one:

```
print(f"I am '{impersonated_tm1.whoami.name}' I can see {impersonated_tm1.cubes.get_number_of_cubes()} cubes")
```

**Comment by wimgielis** [comment]
Ah, I didn't catch that either.
Now I see 69 and 59 and 0 cubes. 0 cubes for 2 persons I know that left the company. This means that at least, this is working :-)

I will try to reverse engineer and see what might be different in Postman and Excel VBA.

Thanks for your cooperation, I will update the thread soon.

**Comment by wimgielis** [comment]
Here is the update.

I have it "working":
- In VBA, add: .setRequestHeader "TM1-Impersonate", "CAMID(""pans:u:...@... . ...."")"
- Also, any time I do such an explicit Impersonation, I need to do first a POST command of "ActiveSession/tm1.Close"

Not sure if others would do the same, but for now that will do ;-)

**Comment by wimgielis** [comment]
Ah, I didn't catch that either.
Now I see 69 and 59 and 0 cubes. 0 cubes for 2 persons I know that left
the company. This means that at least, this is working :-)

I will try to reverse engineer and see what might be different in Postman
and Excel VBA.

Thanks for your cooperation, I will update the thread soon.

------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op wo 21 sep. 2022 om 16:30 schreef Marius Wirtz ***@***.***>:
