### ISSUE TITLE
Issue with get_elements_dataframe function in Element Service

### ISSUE THREAD

**Issue by Rnvksm** [cubewise-code/tm1py#828]
Hi Marius,
As discussed earlier, these are the bugs i have found. if you can provide some solution that would be great.
**Describe the bug**
1. i have seen some error messages in the output as well in level columns
2. few cases i have seen where level elements are placed in weight columns and vice - versa .
 To be précised the issue is at  when its showing higher parents of the elements these issues are coming.

This is the screenshot highlights both the issues
![image](https://user-images.githubusercontent.com/49037021/201875058-96a8f3f7-769f-454a-ad4d-ba9635d38949.png)

**To Reproduce**
this is the syntax used to
t=tm1.dimensions.hierarchies.elements.get_elements_dataframe(dimension_name=dim, hierarchy_name=dim, skip_consolidations=False)

**Expected behavior**
i'm expecting output will without garbage and proper level elements info

**Version**
TM1py 1.10.0

**Additional context**

**Comment by MariusWirtz** [comment]
Please upgrade to the new branch and verify that the issue is resolved:

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/issue/828.zip
```

**Comment by Rnvksm** [comment]
Hi Marius ,

Now Its working .Thanks for the correction
