### ISSUE TITLE
Issue when loading tm1project from file

### ISSUE THREAD

**Issue by nicolasbisurgi** [cubewise-code/tm1py#836]
**Describe the bug**
Issue 1: when creating a tm1project from file the existing code under tm1projecttask duplicates the Processes property.
Issue 2: when adding a chore as a task we need to include the 'Chores' property as we do on the Process one.

**To Reproduce**
Issue 1: try to load a json file with the following content:
```
{
  "Version": "1.0",
  "Name": " tm1py_tm1project",
  "Tasks":
  {
    "test_bug":
    {
      "Process": "Processes('sys_initialize_new_model')"
    },
    "test_chore":
    {
      "Chore": "Chores('testingChore')"
    }
  }
}
```
Issue 2: create a task with a chore
`print(TM1ProjectTask('test_bug', chore='test_chore'))
`
you currently get {'Chore':'test_chore'} which gets you the following message:
{"error":{"code":"290","message":"Cannot find property \"test_chore\" in entity type \"EntityContainer\" while parsing entity reference test_chore."}}

**Expected behavior**
Issue 1: the tm1projecttask should evaluate if the process string has the property defined and, if not, add it.
Issue 2: the correct output for the tm1projecttask should be {'Chore': "Chores('test_chore')"}

**Version**
TM1py [e.g. 1.10.1]
TM1 Server Version: [e.g. 11.8]

**Additional context**
Created PR #835 with proposed solution

Thanks!

nico

**Comment by MariusWirtz** [comment]
Solved with #835
