### ISSUE TITLE
ram usage for using unbound TI's for writing data

### ISSUE THREAD

**Issue by ajain86** [cubewise-code/tm1py#838]
**Describe the bug**
I am running a simple python script that executes an unbound TI with 32k CELLPUTN lines (16k in prolog, 16k in epilog). The unbound TI is build and executed 20 times. After each run of the script, I am seeing RAM usage of the TM1 instance go up by 80 MB. 

I updated the TI to have 32k blank lines and executed the script. The RAM usage went up 9 MB. 

The memory does not get released and is not shown in the stats cube. It does not convert to garbage memory. 
Running a save data did not release the memory either.

**To Reproduce**
I am running this on a TM1 server with 1 cube and 6 dimensions. 

This is the script I am running. 
` 

    with TM1Service(**config['ramtest']) as server:

    x = 1
    while x < 20:
        ti_name = "testing_ram_usage_" + str(x)
        ti_process = TM1py.Process(
            name=ti_name,
            datasource_type="None"
        )

        prolog = "CELLPUTN(1, 'Cube_Test','D1','D2','D3','D4,'D5','D6');\n" * 16000
        epilog = "CELLPUTN(1, 'Cube_Test','D1','D2','D3','D4,'D5','D6');\n" * 16000

        # prolog = "   \n" * 16000
        # epilog = "   \n" * 16000

        ti_process.prolog_procedure = prolog
        ti_process.epilog_procedure = epilog

        print(f"process: {ti_name}")

        # server.processes.update_or_create(ti_process)
        server.processes.execute_process_with_return(ti_process)

        x += 1

    server.logout()
`

**Expected behavior**
I would not expect the RAM of the server to increase when executing an unbound TI. 

**Version**
TM1py [e.g. 1.3.1] - 1.9
TM1 Server Version [e.g. 11.4] - 11.8.00000.41

**Additional context**

**Comment by MariusWirtz** [comment]
Hi @ajain86,

thanks for raising the issue. I appreciate it.

At the first glance it looks like this is an issue in the TM1 Server. 
Do you have a channel with IBM to report it directly to them? Possibly as a PMR?

**Comment by ajain86** [comment]
An upgrade to 11.8.00300.34 seems to have resolved this particular issue. 

I am still gathering more data points but the crux of me testing this scenario was related to increasing RAM consumption when using **write_dataframe_async** which used an unbound TI for data load of 100k records. If I use max_workers greater than the number of cores on my machine, I see a significant amount of RAM increase. I am still tracking this on my end and will post if I find any concrete results.

**Comment by macsir** [comment]
Hi, @ajain86 
Looks like your testing code is missing one single quote for D4. Not sure if it distorted your results or not. Thanks.
```python
prolog = "CELLPUTN(1, 'Cube_Test','D1','D2','D3',**'D4**,'D5','D6');\n" * 16000
epilog = "CELLPUTN(1, 'Cube_Test','D1','D2','D3',**'D4**,'D5','D6');\n" * 16000
```

**Comment by ajain86** [comment]
Thanks @macsir. That was a typo when copying my code to github.
