### ISSUE TITLE
KeyRing

### ISSUE THREAD

**Issue by CJRothman** [cubewise-code/tm1py#839]
**Describe what did you try to do with TM1py**
I'm trying to store the admin password using KeyRing.

**Describe what's not working the way you expect**
I have a KeyRing script with 'import keyring' in line 6 but the script returns this error message even though I did an explicit 'pip install keyring' from command prompt. The pip command was successful.
**Projects\Keyring.py", line 6, in <module>
    import keyring
ModuleNotFoundError: No module named 'keyring'**

**Version**
<img width="287" alt="image" src="https://user-images.githubusercontent.com/44240381/205759294-af72f7a0-92cc-4a99-add4-4c6f016ef79c.png">

**Additional context**
If you encounter an error, please add the error message and the stack trace
**Projects\Keyring.py", line 6, in <module>
    import keyring
ModuleNotFoundError: No module named 'keyring'**

**Comment by jrobinsonAG** [comment]
Is your .py file the same same as the keyring package?

**Comment by CJRothman** [comment]
I'm also getting another error in line 6 in another script **ModuleNotFoundError: No module named 'TM1py'** that has 

L1 import configparser
L2 import logging
L3 import sys
L4 from pathlib import Path
L5from datetime import datetime
L6 from TM1py.Services import TM1Service

**Comment by jrobinsonAG** [comment]
How are you running your script, via shell on the server, via TI, or
locally?

 Can you provide the full output of the error?

**Comment by MariusWirtz** [comment]
Sounds like you have two installations of Python on the box.

When you kick off py from the cmd please be explicit about the python installation:
`E:\program files\Python\python.exe script.py`

Does that work?
