### ISSUE TITLE
Run exe using TI process

### ISSUE THREAD

**Issue by Rvee93** [cubewise-code/tm1py#843]
Hello everyone,
**I Tried to create a public view using TI process containing tm1py code in exe file**
Here is the script i used:
TI Code:
 cmd = '"\\tm1-stg.hsbc.com\TI Files\AXP_IM\Dynamic\main.exe"';
 port = '6001';
 sCode = '%cmd% %port%';
 ExecuteCommand(Expand(sCode),1);

**Here is what's not working the way I expect**
Didn't get the expected result? Describe:
1. The TI is completed successfully but view is not created.
2. Same exe when ran at my local machine directly is working fine. 

**Version**
- TM1py [1.9.1] 

**Additional context**
Does it takes admin account then only it can create the private view ?
Can someone please guide me..

**Comment by MariusWirtz** [comment]
Yes. It takes admin permissions to create public views. 
Alternatively, you could create a private view and call a bedrock process or the new PublishView to publish the private view.

https://www.ibm.com/docs/en/planning-analytics/2.0.0?topic=vmtf-publishview
https://github.com/MariusWirtz/bedrock

Please also post the actual python script

**Comment by MariusWirtz** [comment]
On a site note, when the python script fails the ExecuteCommad function will not propagate that error to TI.
You would have to propagate the error manually from python to TI, so that when python fails, you could do an ItemReject or something in TI to alert the calling user.

**Comment by Rvee93** [comment]
> Yes. It takes admin permissions to create public views. 
> Alternatively, you could create a private view and call a bedrock process or the new PublishView to publish the private view.
> 
> https://www.ibm.com/docs/en/planning-analytics/2.0.0?topic=vmtf-publishview
> https://github.com/MariusWirtz/bedrock
> 
> Please also post the actual python script

Hi @MariusWirtz,
Thanks for your quick response. I will try with bedrock one. Here is my python script below:

 import sys
 import time
 
 from TM1py import Subset
 from TM1py.Objects import NativeView
 from TM1py.Services import TM1Service
 
 start_time = time.time()
 # establish connection to TM1 Server
 ADDRESS = "htc.ppp.atom.hsbc.com"
 NAMESPACE = "HBBI"
 SSL = True
 PORT = sys.argv[1]
 GATEWAY = "https://tm1PP-dev.hsbc.com/ca/bi/v1/disp"
 # Setting up connection to IM
 
 with TM1Service(address=ADDRESS, port=PORT, namespace=NAMESPACE, ssl=SSL, gateway=GATEWAY) as tm1:
     ############### Code for Creating dynamic elements for Subsets #####################
     # For ID Dimension
     dimension_name_ID = "ID"
     ID_elements = tm1.hierarchies.elements.get_elements_filtered_by_wildcard(dimension_name=dimension_name_ID, hierarchy_name=dimension_name_ID,wildcard='USCS-3',level=0)
     # For Inv_Type Dimension
     dimension_name_Inv_Type = "Inv_Type"
     Inv_Type_elements = tm1.hierarchies.elements.get_elements_filtered_by_wildcard(dimension_name=dimension_name_Inv_Type, hierarchy_name=dimension_name_Inv_Type,wildcard='External',level=0)
     # For Version Dimension
     dimension_name_Version = "Version"
     Version_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Version, hierarchy_name=dimension_name_Version,consolidation='2022 1+11 R&O_Mgmt')
     # For View_Type Dimension
     dimension_name_View_Type = "View_Type"
     View_Type_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_View_Type, hierarchy_name=dimension_name_View_Type,consolidation='Calendarized-View')
     # For Partner Dimension
     dimension_name_Partner = "Partner"
     Partner_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Partner, hierarchy_name=dimension_name_Partner,consolidation='All Partner')
     # For Offer_Type Dimension
     dimension_name_Offer_Type = "Offer_Type"
     Offer_Type_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Offer_Type, hierarchy_name=dimension_name_Offer_Type,consolidation='All Offer Type')
     # For Target_Segment Dimension
     dimension_name_Target_Segment = "Target_Segment"
     Target_Segment_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Target_Segment, hierarchy_name=dimension_name_Target_Segment,consolidation='All Target Segment')
     # For Channel Dimension
     dimension_name_Channel = "Channel"
     Channel_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Channel, hierarchy_name=dimension_name_Channel,consolidation='All Channels')
     # For Fee_Type Dimension
     dimension_name_Fee_Type = "Fee_Type"
     Fee_Type_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Fee_Type, hierarchy_name=dimension_name_Fee_Type,consolidation='All Fees')
     # For Pre_Application_Status Dimension
     dimension_name_Pre_Application_Status = "Pre_Application_Status"
     Pre_Application_Status_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Pre_Application_Status, hierarchy_name=dimension_name_Pre_Application_Status,consolidation='All Process Path')
     # For Product Dimension
     dimension_name_Product = "Product"
     Product_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Product, hierarchy_name=dimension_name_Product,consolidation='All Product')
     # For Sub_Product Dimension
     dimension_name_Sub_Product = "Sub_Product"
     Sub_Product_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Sub_Product, hierarchy_name=dimension_name_Sub_Product,consolidation='All SubProducts')
     # For Market Dimension
     dimension_name_Market = "Market"
     Market_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_Market, hierarchy_name=dimension_name_Market,consolidation='US')
     # For BU Dimension
     dimension_name_BU = "BU"
     BU_elements = tm1.hierarchies.elements.get_leaves_under_consolidation(dimension_name=dimension_name_BU, hierarchy_name=dimension_name_BU,consolidation='USCS')
     # For Period Dimension
     dimension_name_Period = "Period"
     Period_elements = ['P1','P2','P3','P4','P5','P6','P7','P8','P9','P10','P11','P12','P13','P14','P15','P16','P17','P18','P19','P20','P21','P22','P23','P24','P25','P26','P27','P28','P29','P30','P31','P32','P33','P34','P35','P36','P37','P38','P39','P40','P41','P42','P43','P44','P45','P46','P47','P48','P49','P50','P51','P52','P53','P54','P55','P56','P57','P58','P59','P60']
     # For M_CMV Dimension
     dimension_name_M_CMV = "M_CMV"
     M_CMV_elements = tm1.hierarchies.elements.get_leaf_element_names(dimension_name=dimension_name_M_CMV, hierarchy_name=dimension_name_M_CMV)
 
 
     ############### Code for Creating subsets on the go - Static #####################
     ID_subset = 'TM1py ID'
     Inv_Type_subset = 'TM1py Inv_Type'
     Version_subset = 'TM1py Version'
     View_Type_subset = 'TM1py View_Type'
     Partner_subset = 'TM1py Partner'
     Offer_Type_subset = "TM1py Offer_Type"
     Target_Segment_subset = "TM1py Target_Segment"
     Channel_subset = "TM1py Channel"
     Fee_Type_subset = "TM1py Fee_Type"
     Pre_Application_Status_subset = "TM1py Pre_Application_Status"
     Product_subset = "TM1py Product"
     Sub_Product_subset = "TM1py Sub_Product"
     Market_subset = "TM1py Market"
     BU_subset = "TM1py BU"
     Period_subset = "TM1py Period"
     M_CMV_subset = "TM1py M_CMV"
     ############### Code for Creating subsets on the go - Dynamic #####################
     for_id = Subset(dimension_name=dimension_name_ID, subset_name=ID_subset, alias='', elements=ID_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_id, private=False)
 
     for_inv_type=Subset(dimension_name=dimension_name_Inv_Type, subset_name=Inv_Type_subset, alias='', elements=Inv_Type_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_inv_type, private=False)
 
     for_Version = Subset(dimension_name=dimension_name_Version, subset_name=Version_subset, alias='', elements=Version_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_Version, private=False)
 
     for_view_type=Subset(dimension_name=dimension_name_View_Type, subset_name=View_Type_subset, alias='', elements=View_Type_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_view_type, private=False)
 
     for_partner = Subset(dimension_name=dimension_name_Partner, subset_name=Partner_subset, alias='', elements=Partner_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_partner, private=False)
 
     for_offer_type=Subset(dimension_name=dimension_name_Offer_Type, subset_name=Offer_Type_subset, alias='', elements=Offer_Type_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_offer_type, private=False)
 
     for_target_segment = Subset(dimension_name=dimension_name_Target_Segment, subset_name=Target_Segment_subset, alias='', elements=Target_Segment_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_target_segment, private=False)
 
     for_channel=Subset(dimension_name=dimension_name_Channel, subset_name=Channel_subset, alias='', elements=Channel_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_channel, private=False)
 
     for_fee_type = Subset(dimension_name=dimension_name_Fee_Type, subset_name=Fee_Type_subset, alias='', elements=Fee_Type_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_fee_type, private=False)
 
     for_pre_application_status = Subset(dimension_name=dimension_name_Pre_Application_Status,
                                         subset_name=Pre_Application_Status_subset, alias='',
                                         elements=Pre_Application_Status_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_pre_application_status, private=False)
 
     for_product = Subset(dimension_name=dimension_name_Product, subset_name=Product_subset, alias='',
                          elements=Product_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_product, private=False)
 
     for_sub_product = Subset(dimension_name=dimension_name_Sub_Product, subset_name=Sub_Product_subset, alias='',
                              elements=Sub_Product_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_sub_product, private=False)
 
     for_market = Subset(dimension_name=dimension_name_Market, subset_name=Market_subset, alias='',
                         elements=Market_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_market, private=False)
 
     for_bu = Subset(dimension_name=dimension_name_BU, subset_name=BU_subset, alias='', elements=BU_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_bu, private=False)
 
     for_period = Subset(dimension_name=dimension_name_Period, subset_name=Period_subset, alias='',
                         elements=Period_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_period, private=False)
 
     for_m_cmv = Subset(dimension_name=dimension_name_M_CMV, subset_name=M_CMV_subset, alias='',
                         elements=M_CMV_elements)
     tm1.dimensions.subsets.update_or_create(subset=for_m_cmv, private=False)

 
 ############## Code for Creating the native views ################
     native_view = NativeView(cube_name='MC_STG_CMV_Calc',view_name='TM1py_View1',suppress_empty_columns=True,suppress_empty_rows=True)
     # set up native view - put subsets on Rows, Columns and Titles
     Subset = tm1.dimensions.subsets.get(dimension_name=for_id.dimension_name,
                                         hierarchy_name=for_id.hierarchy_name,
                                         subset_name=for_id.name,
                                         private=False)
     native_view.add_row(dimension_name=for_id.dimension_name, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=for_view_type.dimension_name,hierarchy_name=for_view_type.hierarchy_name,
                                                      subset_name=for_view_type.name,
                                                      private=False)
     native_view.add_title(dimension_name=for_view_type.dimension_name, subset=Subset,selection="Calendarized-View")
 
     Subset = tm1.dimensions.subsets.get(dimension_name=for_inv_type.dimension_name,hierarchy_name=for_inv_type.hierarchy_name,
                                         subset_name=for_inv_type.name,
                                         private=False)
     native_view.add_column(dimension_name='Inv_Type', subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name='Version',hierarchy_name='Version',
                                                    subset_name='TM1py Version',
                                                    private=False)
     native_view.add_column(dimension_name='Version', subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Partner,hierarchy_name=dimension_name_Partner,
                                                    subset_name=Partner_subset,
                                                    private=False)
     native_view.add_column(dimension_name=dimension_name_Partner, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Offer_Type,hierarchy_name=dimension_name_Offer_Type,
                                                   subset_name=Offer_Type_subset,
                                                   private=False)
     native_view.add_column(dimension_name=dimension_name_Offer_Type, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Target_Segment,hierarchy_name=dimension_name_Target_Segment,
                                                           subset_name=Target_Segment_subset,
                                                           private=False)
     native_view.add_column(dimension_name=dimension_name_Target_Segment, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Channel,hierarchy_name=dimension_name_Channel,
                                                    subset_name=Channel_subset,
                                                    private=False)
     native_view.add_column(dimension_name=dimension_name_Channel, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Fee_Type,hierarchy_name=dimension_name_Fee_Type,
                                                     subset_name=Fee_Type_subset,
                                                     private=False)
     native_view.add_column(dimension_name=dimension_name_Fee_Type, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Pre_Application_Status,hierarchy_name=dimension_name_Pre_Application_Status,
                                                     subset_name=Pre_Application_Status_subset,
                                                     private=False)
     native_view.add_column(dimension_name=dimension_name_Pre_Application_Status, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Product,hierarchy_name=dimension_name_Product,
                                                    subset_name=Product_subset,
                                                    private=False)
     native_view.add_column(dimension_name=dimension_name_Product, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Sub_Product,hierarchy_name=dimension_name_Sub_Product,
                                                        subset_name=Sub_Product_subset,
                                                        private=False)
     native_view.add_column(dimension_name=dimension_name_Sub_Product, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Market,
                                                   subset_name=Market_subset,
                                                   private=False)
     native_view.add_column(dimension_name=dimension_name_Market, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_BU,hierarchy_name=dimension_name_BU,
                                               subset_name=BU_subset,
                                               private=False)
     native_view.add_column(dimension_name=dimension_name_BU, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_Period,hierarchy_name=dimension_name_Period,
                                                   subset_name=Period_subset,
                                                   private=False)
     native_view.add_column(dimension_name=dimension_name_Period, subset=Subset)
 
     Subset = tm1.dimensions.subsets.get(dimension_name=dimension_name_M_CMV,hierarchy_name=dimension_name_M_CMV,
                                                  subset_name=M_CMV_subset,
                                                  private=False)
     native_view.add_column(dimension_name=dimension_name_M_CMV, subset=Subset)
 
     # create native view on Server
     tm1.cubes.views.update_or_create(view=native_view, private=True)
     End1 = time.time()
     Total = round(End1 - start_time, 10)
     print(str(Total) + " - time taken")

Note: I am trying to create a private view only

**Comment by MariusWirtz** [comment]
Did it work? May I close the issue?

**Comment by Rvee93** [comment]
> Did it work? May I close the issue?

Yes @MariusWirtz, 
Bedrock worked for me. Thank you ☺️
