### ISSUE TITLE
execute a TI Process (for example: Save Data) from one Instance to an another Instance

### ISSUE THREAD

**Issue by Darshan577** [cubewise-code/tm1py#845]
- TM1 Server Version: [e.g. 11.4]

Hi Marius, We are trying to execute a TI Process (for example: Save Data) from one TM1 instance (say a Source instance) to an another TM1 instance (Target instance) with the help of Python Script. The Configuration setting in the Source Instance has IntegratedSecurityMode=1 but the configuration setting in the Target Instance has IntegratedSecurityMode = 5. Due to the difference in Security Mode, we are unable to execute the Process in the Target Instance from the Source Instance. This works fine when the IntegratedSecurityMode=1 in both the instances, but not when they both are different.

Could you please help us on this issue?

The config.ini parameters in both the instances have address, port, user, password,ssl.

**Comment by MariusWirtz** [comment]
Are you using IntegratedSecurityMode5 with SSO on the target instance?

**Comment by Darshan577** [comment]
Yes, we are using IntegratedSecurityMode = 5 with SSO on the Target instance.

**Comment by MariusWirtz** [comment]
If TM1py uses CAM with SSO to authenticate then the user running the script must have access to TM1.

If you call a TM1py script from a TI process through `ExecuteCommand`, the user that is put as `Log On As` on the windows service is the user that the TM1py script runs as.

**Comment by Darshan577** [comment]
Thank you for the details Marius. This is helpful.

We will reach out if we face any issues in the future.
