### ISSUE TITLE
cells.write function lags writing to cube

### ISSUE THREAD

**Issue by HHA001** [cubewise-code/tm1py#854]
**Describe what did you try to do with TM1py**

I am trying to load a dataframe back to the cube using the cells.write function.  Code looks like this:

``` python
cellset = build_cellset_from_pandas_dataframe(d)
tm1.cubes.cells.write(cube_name = "FPA Consolidations", cellset_as_dict = cellset, 
                                    skip_non_updateable = True, 
                                    dimensions = ['Entity', 'Reporting_Standard', 'Currency', 
                                                'Scenario', 'Period_Year', 'Accounts', 
                                                'FPA_Consolidations_m'])


```

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:

It takes over 60 minutes to load 30,000 records, depending on how many zero value cells need to be over-written.  In general, the more zeros in the destination intersections, the longer it takes to load.
I have no zeros in the dataframe to be loaded, just positive/negative values.
In contrast, when it writes over the same data already sitting in the cube (meaning, no data is cleared), the process only takes about 1 minute.

Running the same dataframe as a csv load with a TI chore takes only 4 minutes and this includes processes to zero out the scenario, remove rules from the cube, load data, and reattach the rules file.  The load itself takes only a few seconds.

I feel like this is a new issue - as everything ran very smoothly only a couple of months ago.

**Version**
- TM1py 1.10.1
- Planning Analytics Local 2.0.9.13

**Comment by MariusWirtz** [comment]
You might want to consider this as well:

- it's a good practice to generally not write 0 values to TM1.
- instead, you can clear with an MDX query (`clear_with_mdx`) or call a bedrock process from TM1py to zero-out a slice.
- so when you use a TM1py function to write after you already cleared a slice in the cube, you don't need to write any 0 valus

**Comment by HHA001** [comment]
@MariusWirtz :
Thanks for your quick response!
I will give your suggestions a try.

**Comment by HHA001** [comment]
Good Evening! 
Returning to this topic, can I ask for a bit more information about the `use_ti = True` option?  I currently have "DataAdmin" security in my organization but still return the error about admin permissions when attempting `use_ti = True`.  So, is there a way to configure TM1 to allow me to run the unbound process as a DataAdmin?

**Comment by macsir** [comment]
I don’t think so as Admin is required to let API create the TI on the fly for you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
