### ISSUE TITLE
TM1Py Check py error

### ISSUE THREAD

**Issue by richenners** [cubewise-code/tm1py#857]
First attempt at running TM1Py Check from PYCharm, received the following error message "ModuleNotFoundError: No module named 'TM1py'". Python, PYCharm and TM1Py all running on local laptop. PA is Cloud version. Thanks in advance for assistance!

**Comment by rkvinoth** [comment]
The error message says that `TM1py` package has not been found. It could be because you didn't install it or could be because you installed it using one version of python and trying access it using a different version of python.

Your PA version (local or cloud) doesn't have to do anything with this error. 
Excluding the error message, connecting to a PA cloud version will require a specific way of authentication. So, please read through the [TM1py connectivity guide](https://code.cubewise.com/tm1py-help-content/connecting-to-the-ibm-cloud-remotely-with-tm1py)

**Comment by richenners** [comment]
Thank you for your response. See below for additional information:

TM1py has been installed, see below:
***@***.***
I recently installed Python311 for the first time on my laptop:
***@***.***
This is the error message:
***@***.***
We are able to connect to our TM1 model, below is the result of a test py script pulling PA version:
***@***.***

**Comment by richenners** [comment]
Adding Andrea Ludwig to thread.

From: Richard ENNERS
Sent: Friday, February 10, 2023 3:56 PM
To: cubewise-code/tm1py ***@***.***>; cubewise-code/tm1py ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [cubewise-code/tm1py] TM1Py Check py error (Issue #857)

Thank you for your response. See below for additional information:

TM1py has been installed, see below:
***@***.***
I recently installed Python311 for the first time on my laptop:
***@***.***
This is the error message:
***@***.***
We are able to connect to our TM1 model, below is the result of a test py script pulling PA version:
***@***.***

**Comment by rkvinoth** [comment]
Your comment seems encrypted or something. Make a comment directly in GitHub to make it more readable.

From the information I could gather by applying high level decryption on your comment, I believe you are able to connect with your PA server and hope we can resolve this thread.

**Comment by richenners** [comment]
I was able to resolve this issue. Our TM1 app is running on TM1 cloud which requires a different set of log-in info. I am able to connect to TM1 now. My current issue is related to pulling Dimensions from our model. I am following the instructions here https://code.cubewise.com/tm1py-help-content/getting-tm1-data-into-power-bi. However I am getting this RunTimeError: }ElementAttributes_Version cube must exist. Note: this cube does exist in our model.
![TM1py RunTimeError](https://user-images.githubusercontent.com/124631528/218207706-ae5a178c-8497-4599-a153-669039d1572b.png)
 
Should I open a new case?

**Comment by richenners** [comment]
Ok, just updated GitHub. Note: the issue I created has been resolved. I'm now chasing a new issue. See my comments in the case. Thank you.

**Comment by rkvinoth** [comment]
Are you sure your dimension name is `Version`? Could it be `Versions`? If not, try creating a new attribute to the dimension and see if the script can detect your attr cube after that.


PS: I would really appreciate if you could stop replying to the email.

**Comment by richenners** [comment]
The name is "Version". I added a new attribute, re-ran the script and received the same error message.

**Comment by rkvinoth** [comment]
Can you share the code that you are using? 
Also, let us know which version of TM1py and TM1 version you are using.

**Comment by richenners** [comment]
Here's the code:
import configparser

from TM1py import TM1Service

config = configparser.ConfigParser()
config.read('C:\\TM1py\\tm1py-samples-master\\tm1py-samples-master\\config.ini')

with TM1Service(**config["tm1srvDEV"]) as tm1:
    Version = tm1.power_bi.get_member_properties(
        dimension_name="Version",
        hierarchy_name="Version",
        skip_consolidations=False)
    Version

TM1 PA Cloud version: 11.8.01300.1

TM1py version: Not sure how to get this, please advise. But, I assume it's the latest as I downloaded it a couple of weeks ago.

Thank you.

**Comment by richenners** [comment]
Resolved this issue. The non-interactive account was not set to Admin role. Once we changed this, the py script ran fine. Thank you.
