### ISSUE TITLE
Missing function to get hierarchy by name with Dimension object

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/tm1py#86]
I think it would be nice to have a method of Dimension object to return hierarchy by name. Currently there is only a service's method to do it.

**Comment by MariusWirtz** [comment]
@pbuncik 
PR #88 introduces `__getitem__` and `__contains__` methods on the Dimension class.
you can access a hierarchy on a dimension now like this:

```
        dimension = self.tm1.dimensions.get(dimension_name="Dimension")
        hierarchy = dimension["Hierarchy3"]
```

or 
```
        dimension = self.tm1.dimensions.get(dimension_name="Dimension")
        hierarchy = dimension["Leaves"]
```

Does that work for you?
