### ISSUE TITLE
tm1.elements.get_parents() special character error. 

### ISSUE THREAD

**Issue by scotthoopes** [cubewise-code/tm1py#864]
**Describe the bug**

When using the tm1.elements.get_parents() function if a '#' is passed through through as an element it gives this error: 

TM1pyRestException: Text: '{"error":{"code":"278","message":"Quote mismatch: <End-of-Input>"}}' - Status Code: 400 - Reason: 'Bad Request' - Headers: {'Content-Length': '84', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'OData-Version': '4.0'}

**To Reproduce**

We use the '#' as a catch all for unknown values as they come into the system. 

An example of what the call looks like:

with TM1Service(**config['server01']) as tm1:
    get_parents('Market Area', 'Market Area', '#')

**Expected behavior**

I am expecting this to return the parent of this element. 

**Version**
TM1py   1.10.2
TM1 Server Version: 2.0.9.13

**Additional context**
I have tested this in a variety of different ways. I tried to escape the '#' character and that didn't work. I also tested these elements in other element functions and they work. It seems like this issue is specific to the get_parents() functions.

**Comment by MariusWirtz** [comment]
Thank you. You identified an issue in TM1py. There was a bug that we weren't escaping the element names for the URL in the function.

Please upgrade to the latest master branch. It should be fixed now!

**Comment by scotthoopes** [comment]
@MariusWirtz thanks so much for the quick turnaround. I tested it already and everything is working as expected!
