### ISSUE TITLE
Unauthorized Response in call to tm1.dimensions.create(dimension)

### ISSUE THREAD

**Issue by cwolfe-lpa** [cubewise-code/tm1py#870]
All,

Trying to create a new dimension in TM1py.  Using config.ini (IntegratedSecurityMode=1, Client=Admin) to instantiate the server.  This is successful (code from Check TM1py.py used).   I'm sure there is an issue with the code below but I just can't see it!

The dimension should be
All Cars
  -- 8
     --- 87
     --- 52
  -- 1
    --- 37

I create the elements from a dictionary that is created from JSON.   I create the edges similar to the examples.  
Elements:
{"Name": "87", "Type": "Numeric"}
{"Name": "52", "Type": "Numeric"}
{"Name": "37", "Type": "Numeric"}
{"Name": "All Cars", "Type": "Consolidated"}
{"Name": "8", "Type": "Consolidated"}
{"Name": "1", "Type": "Consolidated"}
Edges:
('All Cars', '8')
('All Cars', '1')
('8', '87')
('8', '52')
('1', '37')

When executing in Jupyter Notebooks, the response is:
**ERROR:
	Text: '' - Status Code: 401 - Reason: 'Unauthorized' - Headers: {'Content-Type': 'text/plain', 'Content-Length': '0', 'Connection': 'keep-alive', 'OData-Version': '4.0', 'Set-Cookie': 'TM1SessionId=MCICvhNjh2ql6h6rxvgylhVpITQ; Path=/api/; HttpOnly; Secure', 'WWW-Authenticate': 'Basic realm="TM1"'}**

Can anyone spot the flaw in the code?  Since I am logging into the server as Admin, the user should be authorized to create a dimension.  If I use the same config file for various create dimension samples, it works flawlessly.  My code, however, does not!  The code is:
```
import json
import configparser
from TM1py.Services import TM1Service
from TM1py.Objects import Dimension, Hierarchy, Element
from TM1py.Utils import Utils

with open('c:/temp/cars.json', 'r') as f:
  data = json.load(f)
  
  cars = data['data']['cars']['nodes']

config.read(r'.\Config.ini')

dimName = 'Cars'
superconsol = 'All Cars'

try:
    with TM1Service(**config['tm1srv01']) as tm1:
        server_name = tm1.server.get_server_name()
        print("Connection to TM1 established!! your Servername is: {}".format(server_name))

edges = Utils.CaseAndSpaceInsensitiveTuplesDict()
    elements = [Element('{}'.format(car['brand']['id']), 'Numeric') for car in cars]       
    elements.append(Element(superconsol, 'Consolidated'))          
     
         
    for i in cars:  
       car_parent_id = str(i['brand']['parent']['id'])
       car_id = str(i['brand']['id'])
       print(car_parent_id, car_id)
       edges[parent_child] = 1    
       parent_child = (car_parent_id, car_id)
       print('PC2', parent_child)
       edges[parent_child] = 1      
    
    print('Elements:')       
    for j in elements:
       print(j)

    print('Edges:')
    for k in edges:
       print(k)
    
    hierarchy = Hierarchy(name=dimName, dimension_name=dimName, elements=elements, edges=edges)
    dimension = Dimension(name=dimName, hierarchies=[hierarchy])

    # Send everything to TM1
    tm1.dimensions.create(dimension)
except Exception as e:
    print("\nERROR:")
    print("\t" + str(e))
```

**Comment by ubihw** [comment]
Hi.

You connect with an context manager ("with TM1Service..."). The variable tm1 is only valid for the following two properly indented lines.
Right after the print statement, you continue dedented ("edges = Utils..."), so the connection ist lost.

**Comment by cwolfe-lpa** [comment]
Oy!  Thank you for that observation!  That was the problem.  The code is working perfectly now.
Thanks again!
Chris
