### ISSUE TITLE
Error on Command run

### ISSUE THREAD

**Issue by pdvanderberg** [cubewise-code/tm1py#871]
I am running RushTI, my TI creates my text file for my tasks as expected, manually executing the same command used in sCommand in CMD and executes without any issues. Once I have my TI running the scommand keep getting an error that it can't find a file. And there is no record on which one of the 2 files are not found. Python resides on the same server as the TM1 instance, so I am running everything on the local server using the local Architect to kick off the process. 

I don't have any issues with TM1 process connecting to any of the files on the server on the different drives. The Python folder is on the same drive as TM1 instance, Python is installed on the same drive as the TM1 software.  Currently all instances are being run as local host.

![image](https://user-images.githubusercontent.com/47628384/223590385-a2380c39-7541-4fbf-ac81-6a2a11d36008.png)

Questions, should RushTI and the tasks text be on the same drive on the machine

**Describe what's not working the way you expect**
TM1 is not able to find a file when running the scommand script for RushTI.

**Version**
- TM1py 1.9
- TM1 Server Version:11.8.013

**Additional context**
sCommand line code 

"sCommand = 'python F:\Python\rushti-master\RushTI.py E:\Integration\Import\Temp\tasks.txt 10';

ExecuteCommand(sCommand,1);"

**Comment by rkvinoth** [comment]
`ExecuteCommand` function will not throw any error.

1. Check if the TI uses a data source.
2. Check if the TI completes successfully when the ExecuteCommand is commented out.


What do you have in line 143?

**Comment by pdvanderberg** [comment]
> `ExecuteCommand` function will not throw any error.
> 
> 1. Check if the TI uses a data source.
> 2. Check if the TI completes successfully when the ExecuteCommand is commented out.
> 
> What do you have in line 143?

It doesn't have a data source, we are using bedrock to extract the data, RushTI scripts calls it. The Execute command is in line 143, so when it is commented out it executes successfully.

Based on a 2nd test done, it is not able to find the python script file being called, we don't have service accounts on the server, question is to do we need a service account, everything is ran as localhost, with all processes not needing it to pick up any of the csv files used from these exact folders, I don't see why it can be an issue to call the python script?

**Comment by rkvinoth** [comment]
Normally in a production environment we use service accounts to run the TM1 service for various reasons. 

Other checks that you could do:

1. If python has been installed for all users within the server?
2. Have you added the python executable to the PATH?
3. Try placing the python script in a different drive.

> This is not a TM1py specific issue.

**Comment by pdvanderberg** [comment]
Issue was using the scripts in the command as per the RushTI website, using just python to call it, using the full path has resolved the issue.

Python was added to the PATH, can see it in the Environment variables. Is also available to all users, both those were set as part of the installation process.
