### ISSUE TITLE
Simple question, how to create a view

### ISSUE THREAD

**Issue by CRoyNortera** [cubewise-code/tm1py#877]
**Describe what did you try to do with TM1py**
Sorry this is a simple question, a bit new here... I am trying to assign subsets to a view. The subsets exists in the dimensions ok, I can create them with TM1py. 
I am at a loss as to create the view on the cube and attache these subsets. 
tm1.cubes.views.create(view=subset_or_view_name) does not mention the cube so I am probably missing a lot of code here.

**Version**
- TM1py: 1.10.2
- TM1 Server Version: 11.x

**Comment by rkvinoth** [comment]
Hi Roy

Did you get a chance to check out the [tm1py-samples](https://github.com/cubewise-code/tm1py-samples) package? It has loads of examples in it for variety of use cases. That is the best place to start learning/exploring TM1py.
Here is a [script](https://github.com/cubewise-code/tm1py-samples/blob/master/Metadata/cube_view_create.py) from the same with guidance on how to create a cube view using TM1py.

Thanks,
Vinoth

**Comment by MariusWirtz** [comment]
Hi @CRoyNortera

If you don't mind reading through the test classes, you can also find a LOT of examples of how to work with views in TM1py.
https://github.com/cubewise-code/tm1py/blob/master/Tests/ViewService_test.py

**Comment by CRoyNortera** [comment]
@rkvinoth I will give this a try. Thanks. 
@MariusWirtz Yes, I do need to go through that.

**Comment by MariusWirtz** [comment]
OK. Will close this issue. Feel free to post a sample, once you get it to work, for future reference.
