### ISSUE TITLE
Support for TM1 v12

### ISSUE THREAD

**Issue by rclapp** [cubewise-code/tm1py#889]
Version 12 introduces a number new concepts that are important for managing both cloud and cp4d installations. v12 changes the base URL for accessing TM1 and adds new authentication requirements. Overall the patterns for accessing and managing v12 instances will require considerable work to support in TM1py

**New manage endpoint requires root credentials to interact**
`domain/manage/v1/Instances`

Instances contain databases
`domain/manage/v1/Instances('Instance Name')/Databases`

Databases are what we normally understand as a TM1 instances, CRUD operations are available from the manage API
`POST domain/manage/v1/Instances('instance')/Databases
{
    "Name": "{{databaseName}}",
    "Replicas": 2,
    "ProductVersion": "12.0.0-alpha.1",
    "Resources": {
        "Replica": {
            "CPU": {
                "Requests": "1000m",
                "Limits": "2000m"
            },
            "Memory": {
                "Requests": "1G",
                "Limits": "2G"
            }
        },
        "Storage": {
            "Size": "20Gi"
        }
    }
}`
Applications are unique pools of users that can connect to a TM1 database (maybe instances?). From the manage endpoint you need to create and application. Upon creation a client secret is returned for storage and reuse

**Connecting to TM1 Databases**
To connect to a TM1 database the application credentials created above are required to connect. Use the new Auth endpoint to create a session

`domain/instance/auth/v1/session`

capture the TM1SessionID and using that session you can query the database root as normal

`domain/instance/api/v1/Databases('Database Name')/`

**Comment by rclapp** [comment]
[tm1-v12.http.txt](https://github.com/cubewise-code/tm1py/files/11172656/tm1-v12.http.txt)

**Comment by MariusWirtz** [comment]
Thanks for opening the issue and providing context and samples. 
I think we can aim for the next release (version 1.12 in roughly 3 months) with this feature.

**Comment by rclapp** [comment]
Status Update for v12 Support


**Changes Complete for Alpha Release Support**

* Changes to all service URL definitions
* New methods to define the service root url
* Support for service-to-service auth model
* Expanded support for new endpoints like setting default members
* Updates to all unit tests to ensure backwards compatibility
* Added error checking for poorly configured OpenShift Networking domains which can lead to mal formed cookies and an invalid session
* Updates to the FileService to support new resource path standards, new methods to get lists of items
* New ManagerService to wrap the control plane API
* New Util functions to test for version support in tests and services
* New Exceptions for version deprecations
* New Methods to update server logging levels
* Fixed testing instantiation and tear-down issues


**Changes Complete for GA Release Support**

* Small changes to URL construction to prevent trailing &
* Significant changes to correct support for get_elements_datafram function
    * Level naming conflicts
    * Attribute property references
* Changes to MDX construction to ensure the use of PROPERTIES
* Fixed issues with ELISANC method to check for missing elements before execution
* New method to extract session ID to bypass issues with domain definitions in CP4D
* Fixed issue with getting servers from admin host
* Updated the methods to used to turn version numbers into integers and related tests
* Fixed problems introduced by new Compact JSON format
* Fixed trace and check tests to use the new odata tag
* Fixed issues with clear via MDX methods
* Changed NativeViews to use MDXpy in tests. 



**Open Items for All Releases**

* Blob based interactions fail due to TS013587321
* Search string tests and methods fail due to TS013610286
* Execute MDX dataframe with attributes fails due to TS013764899 
* Views stored in applications return as Null, IBM aware
* ServerService and MonitorService still need alot of work, many of the enpoints used have been deprecated. We may want to introduce new versions of these with ServerService12 and MonitorService12 or something similar


**Tickets with IBM**

* TS013611120 -  TM1 Rest API returns incorrect cell cardinality when mdx query only has 1 axis - Closed No Issue

According to the OData standard, the response should contain the key property and/or the id control information. In v11 we choose to inject the id control information (the relative canonical URL to the entity) if the key (ordinal) property was not requested. In v12 we switched to including the key property instead (which makes the response less verbose).

* TS013764899 - MDX query returning more properties than expected

It looks like this problem has been resolved in version 12.3.1 of the server. I've ran the testcase and the output is below. Please take a look and confirm the same to ensure I'm not missing something.


* TS013610286 - [TM1-740] TM1 REST API, odata based string searches fails to find processes

this problem has been confirmed as a defect and has been logged accordingly. We will let you know of any meaningful updates, otherwise we will keep you informed about targets/fix expectations when we know more.


* TS013587321 - TI NVALUE/SVALUE variable values set incorrectly during [MDX] view extract

Confirmed defect

**Comment by janus-t** [comment]
We have PA version 12 environment, where we would like to use tm1py. This v12 feature is not yet in master branch, but is there development branch that we could use? I didn't find what I was looking for based on branch names, since best matching branch feature/tm1-12 was closed.

We could help with testing and further development, since we would anyway need these functionalities.

**Comment by rclapp** [comment]
Hi @janus-t you can certainly test with my fork where I am doing the development. All of our work and testing so far has been focused on v12 On-Premises (aka Cloud Pak for Data). I have not tested it with v12 on Cloud. 
https://github.com/rclapp/TM1py/tree/tm1-v12-ga-release-testing

**Comment by janus-t** [comment]
Thank you for this. It seems that authentication differs a little bit for Cloud Pak for Data local compared to both Cloud Pak for Data on IBM Cloud and PAaaS on AWS. There is differences in both authentication url and payload contents. It could be that I have missed something with these two environments, but I have gotten rest api work on these with different approach.

This means I might have to modify whole authentication part on RestService to get this working with PAaaS on AWS for example. Then I can use everything else.

**Comment by rclapp** [comment]
We likely need cloud specific methods as the SaaS version uses CloudPak as the authN provider. I imagine that over the long term we may need to offer a way to bring your own authN support.

From: janus-t ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Wednesday, November 15, 2023 at 7:00 AM
To: cubewise-code/tm1py ***@***.***>
Cc: "Clapp, Ryan" ***@***.***>, Author ***@***.***>
Subject: Re: [cubewise-code/tm1py] Support for TM1 v12 (Issue #889)


Thank you for this. It seems that authentication differs a little bit for Cloud Pak for Data local compared to both Cloud Pak for Data on IBM Cloud and PAaaS on AWS. There is differences in both authentication url and payload contents. It could be that I have missed something with these two environments, but I have gotten rest api work on these with different approach.

This means I might have to modify whole authentication part on RestService to get this working with PAaaS on AWS for example. Then I can use everything else.

**Comment by Wuzardor** [comment]
Hello all,
I don't know if  its the right place to  talk about it but I'm using PA as a Service hosted on AWS for a client and I did some work with postman  to update the data base and authenticate me to PA. The way to authenticate has changed with the V12 as said before. It use IAM with API keys and bearer token. With it, you can retrieve an access token in the response body. Does the futur version of TM1py will suppport it. If it's needed I could help to implement it.

**Comment by MariusWirtz** [comment]
Yes. The future version of TM1py must support this.

Your contribution would be very much appreciated. Please feel free to open a PR.

**Comment by rclapp** [comment]
We can use all the help we can get. My hope is to have a public pull request for v12 support by the end of the year. Once that is done adding more auth methods will be much easier.

From: Wuzardor ***@***.***>
Reply-To: cubewise-code/tm1py ***@***.***>
Date: Friday, November 24, 2023 at 4:23 AM
To: cubewise-code/tm1py ***@***.***>
Cc: "Clapp, Ryan" ***@***.***>, Author ***@***.***>
Subject: Re: [cubewise-code/tm1py] Support for TM1 v12 (Issue #889)


Hello all,
I don't know if its the right place to talk about it but I'm using PA as a Service hosted on AWS for a client and I did some work with postman to update the data base and authenticate me to PA. The way to authenticate has changed with the V12 as said before. It use IAM with API keys and bearer token. With it, you can retrieve an access token in the response body. Does the futur version of TM1py will suppport it. If it's needed I could help to implement it.

**Comment by MariusWirtz** [comment]
Solved with #1000
