### ISSUE TITLE
support for optional timeout argument in all TM1py functions

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/tm1py#89]
All methods in TM1py should support an optional argument: `timeout`:

`data = tm1.cubes.cells.execute_mdx(mdx=mdx, timeout=120)`

If the TM1 Server does not respond in a timely manner, TM1py will throw a TimeoutException.
This allows to circumvent hanging situations on the client side, when the request may be locked or working for a long time in the Server.

**Comment by csjean** [comment]
+1

Here is the patch file.

Timeout was added with the **TM1Service** logon and so is the same for the length of the session (until logout).
[tm1py_timeout.zip](https://github.com/cubewise-code/tm1py/files/2968122/tm1py_timeout.zip)

I've tested it with GET, POST, DELETE and it works with or without _timeout_ argument.

**Comment by cubewise-tryan** [comment]
Hi @csjean,

It is great that you have provided a patch, welcome as a contributor!

The appropriate way to contribute is to fork TM1Py and then create a pull request with your changes. That makes it transparent who has made changes and also reduces the security risk of zip files of unknown origin. 

Instructions are below:

1. https://help.github.com/en/articles/fork-a-repo
1. https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by csjean** [comment]
Thanks @cubewise-tryan .

I have created a pull request.

Cheers!

**Comment by cubewise-tryan** [comment]
@csjean, excellent! We really appreciate it.

**Comment by MariusWirtz** [comment]
solved with #115
