### ISSUE TITLE
Proxy support for TM1py

### ISSUE THREAD

**Issue by Cubewise-gtejeda** [cubewise-code/tm1py#910]
**Description**
TM1py currently does not work when using a proxy.

**To Reproduce**
When requests to Planning Analytics are only allowed through a proxy, TM1py shows an error that there was no response from Planning Analytics.

**Expected behavior**
Proxy configuration should be made available in TM1py, so that requests can be tunneled through a proxy.

**Version**
TM1py [any]
TM1 Server Version: [any]

**Additional context**
The requests library supports the configuration of a proxy described in this article:  
https://www.scrapingbee.com/blog/python-requests-proxy/  
  
Proxy authentication should be supported, but could be implemented in a later release.

**Comment by MariusWirtz** [comment]
Solved with #911
