### ISSUE TITLE
urllib3 v2.0.2 causing issue if async_requests_mode set to True

### ISSUE THREAD

**Issue by headmann** [cubewise-code/tm1py#914]
**Describe the bug**
After upgrading ***urllib3*** package to **v2.0.2** TM1Py throws folowing error on connect:
```
AttributeError: type object 'HTTPResponse' has no attribute 'from_httplib'
``` 

**To Reproduce**
Update urllib3 to 2.0.2 and run  TM1Py TM1Service(). 

**Expected behavior**
No errors on parsing the request

**Version**
TM1py 10x, 11x.
TM1 Server Version: 11.8.01700.1

**Additional context**
I don't believe this is a TM1Py issue but TM1Py is affected. The latest urllib3 package to run ok was 1.26.15

**Comment by sbethea-cw** [comment]
@headmann I had the same issue.  I downgraded urllib3 to 1.26.15 and it resolved it.
