### ISSUE TITLE
How to use a different servername on TM1

### ISSUE THREAD

**Issue by Amy-Li-X** [cubewise-code/tm1py#916]
**Describe what did you try to do with TM1py**
I'm using TM1py to generate MDX query from cube view.

**Describe what's not working the way you expect**
Didn't get the expected result? Describe:
My TM1 server has more than one Servernames, default Servername is bbb. I need to connect to the one other than bbb, how can I write the TM1Service address? 

Below screenshot is the example. By default TM1Service connected to server bbb. But I need to connect to server eee. How can I do it?
![TM1servernames](https://github.com/cubewise-code/tm1py/assets/30788601/88d333dd-8bac-44a1-acd6-caff6e5ecf79)

**Version**
- TM1py [e.g. 1.3.1] 
- TM1 Server Version: [e.g. 11.4]

**Additional context**
If you encounter an error, please add the error message and the stack trace

**Comment by MariusWirtz** [comment]
Hi @Amy-Li-X,

I am assuming you are using TM1 on-premise and not in the cloud.
Depending on the integrated security mode of the TM1 instance (=server), you need to pass different arguments to instantiate the TM1Service.

Here you can find examples:
https://code.cubewise.com/tm1py-help-content/how-to-authenticate-to-tm1-with-tm1py

Most likely will need to pass a different port to the TM1Service to connect to the other TM1 Server.
That port number you can find the tm1s.cfg of the server. It is called `HttpPortNumber`
