### ISSUE TITLE
TM1Service exception handling flaw

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/tm1py#92]
Hello,
We are attempting to handle a situation when invalid credentials are used during TM1Service connection allocation by using exception handler that catches TM1pyException and subsequently by checking for status_code attribute of the exception. However when this attempt is made with invalid credentials, we won't catch TM1pyException, because generic Exception is raised. To check for the issue, I made following simple test:
```python
from TM1py.Exceptions.Exceptions import TM1pyException
from TM1py.Services import TM1Service

try:
    tm1 = TM1Service(
            base_url="http://10.77.19.10:5455",
            user="admin",
            password="invalid_password",
            ssl=False)
except TM1pyException as e:
    if e.status_code == 401:
        print("Credentials Failure")
    else:
        print("Other TM1py Failure")
except Exception as e:
    print("General Failure")
```
Result:
![image](https://user-images.githubusercontent.com/43746968/52216431-7be01800-2896-11e9-8b2f-2b96d829f56f.png)

To assess the exception fully I have removed the exception handler:
```python
tm1 = TM1Service(
        base_url="http://10.77.19.10:5455",
        user="admin",
        password="invalid_password",
        ssl=False)
```
Result:
![image](https://user-images.githubusercontent.com/43746968/52217207-450b0180-2898-11e9-801f-849fdd9f02e6.png)

As can be seen from the exception itself, TM1pyException was properly raised, but another exception occurred - I suspect that I'm getting the second one in the handler.
BR
Petr

**Comment by MariusWirtz** [comment]
Hi @pbuncik ,

thanks for the catch.

when I run your sample code against the branch [issue/87-b64-password
](https://github.com/MariusWirtz/TM1py/tree/issue/87-b64-password) it prints `Credentials Failure`

It seems we fixed this bug unintentionally in the latest version

**Comment by MariusWirtz** [comment]
@pbuncik 
Does the fix work for you? May I close this issue?

**Comment by pbuncik** [comment]
Hi,
I can confirm the fix works perfectly and you can close the issue.
Thank you,
Petr
