### ISSUE TITLE
keep_existing_attributes issue

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#922]
**Describe the bug**

I'm using TM1py 1.11.3

https://github.com/cubewise-code/tm1py/issues/853 introduces "keep_existing_attributes"

I called it like this, but I noticed that i does not work:
tm1_TAR.dimensions.update(dimension=dim, keep_existing_attributes=True)

Looks to me that the boolean is not passed to HierarchyService.
In DimensionService, on line 80 it says:
`self.hierarchies.update(hierarchy, **kwargs)`

I think it should be:
`self.hierarchies.update(hierarchy, keep_existing_attributes=keep_existing_attributes, **kwargs)`

**Comment by MariusWirtz** [comment]
Thanks for the catch @hermie64!

Could you please open a PR with the fix?

**Comment by hermie64** [comment]
Done

**Comment by MariusWirtz** [comment]
Resolved with #924 
Thanks @hermie64!
