### ISSUE TITLE
TM1py installation issues re. setuptools

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/tm1py#926]
I wanted to upgrade TM1py, but I get errors on setuptools, see screenshot:

![2023-06-06_153551](https://github.com/cubewise-code/tm1py/assets/5301621/6d49f80d-aa35-4225-9938-cdec863b22ae)

running Python 3.8.6
setuptools installed 67.8.0
requirements.txt says setuptools>=49.2.1

Never had this issue before. I can install other Python packages. Any clues?

Best, Herman

**Comment by MariusWirtz** [comment]
Hi @hermie64,

I'm not sure about this one.
Can you try installing a more recent Python version (like python 3.11) on the same box and retry?

Maybe upgrade pip as well:
`python -m pip install --upgrade pip`

**Comment by hermie64** [comment]
Hi @MariusWirtz,

I already tried and upgraded pip.

I'm getting older, apparently I had the exact same issue with xlwings quite some time ago, see https://github.com/xlwings/xlwings/issues/1853

The solution then was to add to pip: --no-build-isolation --no-use-pep517

I tried this now with: pip install TM1py --upgrade --proxy="xxxxxxxxxxx" --no-build-isolation --no-use-pep517
I then get an error as in screenshot:
![2023-06-07_071713](https://github.com/cubewise-code/tm1py/assets/5301621/f4410d22-daed-45af-a5de-0cb9e66077c1)

xlwings' fzumstein wrote "I should have uploaded wheels ages ago. Will fix this with hopefully the next release."

**Comment by MariusWirtz** [comment]
In 2021 we published tm1py as wheels.Later we changed to `.tar.gz`.

Can you try to install an older version of TM1py that was published as wheels:
`pip install tm1py==1.7.0`

If this works, perhaps we can publish the release in both shapes as we did in 1.8.
https://pypi.org/project/TM1py/1.8.0/#files

**Comment by hermie64** [comment]
Re. "Can you try to install an older version of TM1py that was published as wheels".

That worked, it installed without any issues
![2023-06-07_125005](https://github.com/cubewise-code/tm1py/assets/5301621/09505fd5-b20a-475a-8587-0ed1096e605c)

So this means I must wait until latest version is published as wheels before I can upgrade, right?

How does this work then?
Apparently the .tar.gz has issues behind company firewall etc., but when also published as wheel, it uses that distribution first?

Thanks.

**Comment by MariusWirtz** [comment]
Hi @hermie64,

Sorry for the late reply. were you able to resolve it on your end already?

I will make sure to provide a wheel with the next minor release.

**Comment by hermie64** [comment]
Dear @MariusWirtz,

It would be great if you could provide TM1py as a wheel going forward.

For now I used a workaround to install/upgrade TM1py offline on our servers.

1. Installed wheel on server
2. Since the test to install older of TM1py that was published as wheels worked, I assumed this would also work on server: 
**pip wheel --wheel-dir=C:/tmp/wheelhouse tm1py --proxy="xxxx.xxx.xxx:81"**. 
It did not (also timeout on dependencies) , but I could run it successfully on my own workstation.
3. Copied C:/tmp/wheelhouse from workstation to server.
4. Executed on server: **pip install --no-index --find-links=C:/tmp/wheelhouse tm1py**
