### ISSUE TITLE
cells.execute_mdx_dataframe retrieves emtpy string attribute as nan

### ISSUE THREAD

**Issue by Kevin-Dekker** [cubewise-code/tm1py#938]
**Describe the bug**
cells.execute_mdx_dataframe retrieves emtpy string attribute as nan whereas it may be more logical when it retrieves and empty string. 

**To Reproduce**
describe a setup or post a script that reproduces the bug.
Create any cube with two dimensions. Give one dimension a string attribute. Query with one dim on rows on on columns and add DIMENSION PROPERTIES [dim].[dim].[string_attribute] ON 1

**Expected behavior**
It may be more logical when it retrieves and empty string. 

**Version**
TM1py 1.11.2

**Additional context**
Discussed in today's tm1py call with Marius.

**Comment by MariusWirtz** [comment]
Solved with #1045
