### ISSUE TITLE
Server Memory Leakage Retrieving Views on Latest TM1PY

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/tm1py#945]
I am seeing some very strange behavior in the latest TM1PY. We were previously on a forked version we created a couple of years ago with the stream_decode parameter (https://github.com/raeldor/tm1py@feature/stream-decode#egg=TM1py).  We are seeing huge memory leakage ON THE SERVER when retrieving views. We pull large views into a data mart and using this method were losing about 20GB of RAM every 12 hours. I've attached a screenshot. The 'X' shows where we restart instances and the arrows show the memory leakage. On the final restart we switched out code back to our old fork and the memory leakage stops.

The fact that the switching of code back to an old forked version of TM1PY solves the server memory leakage is a sign something fishy is going on. I'll try and run some tests later on the forked version without using the stream_decode parameter.

EDIT: Even removing the stream_decode flag it continues in a straight line. So something in the latest TM1PY appears to be causing memory leakage on the server compared to when we originally forked.

![image](https://github.com/cubewise-code/tm1py/assets/1768444/4dfbba21-3bac-4d86-ac94-25fc8216294d)

**Comment by MariusWirtz** [comment]
Thanks for reporting this.
I will try to replicate the issue on my side. 

What version of TM1 are you on?

**Comment by raeldor** [comment]
Appreciate you looking into it.  We are on 11.8.00900.3.  Thanks!

**Comment by raeldor** [comment]
Looks like it's Windows Server 2016.

**Comment by raeldor** [comment]
Correct.  Whether I use either one, both, or neither it still leaks.  The call looks like this...

`df_cube_data = tm1.cubes.cells.execute_view_dataframe(cube_name=cube_name, view_name=export_view_name, skip_zeros=True, skip_consolidated_cells=True, skip_rule_derived_cells=False, dtype=dtypes_list)`

**Comment by MariusWirtz** [comment]
When `use_blob` is passed as `True,` TM1py actually leverages unbound processes and blob file transfer _(through REST)_ instead of standard REST API requests to read data from a view.

The fact that this read mode also causes memory leaks in TM1 indicates that the issue doesn't actually lie with TM1py but with TM1 itself or how rules are implemented within the cubes.
This could also explain why the issue hasn't occurred at other users.

The only inconsistent thing about this hypothesis is that your old (streaming) branch doesn't seem to trigger the memory leaks.

Could you perhaps verify if the behavior only occurs for some cubes? Possibly the ones with complex rules?

**Comment by raeldor** [comment]
Yeah, the fact that changing the branch causes this to consistently trigger the leaks is odd.  The process actually pulls from about 10 different cubes, over 2 instances.  I suspect the bigger the cube, the more leakage.

The only other thing I thought it that I can maybe pull branches since our fork and see at what point the memory leak starts happening.  We might be able to pin down to a particular branch that way.

**Comment by MariusWirtz** [comment]
It would be great if you could do this research.

You could start with the major releases we did in the last 2-3 years.

```
pip install tm1py==1.11
pip install tm1py==1.10.2
pip install tm1py==1.9.1
pip install tm1py==1.8.0
pip install tm1py==1.7.0
pip install tm1py==1.6.2
pip install tm1py==1.5
```

**Comment by raeldor** [comment]
So, now I can only get it to occur with either the use_iterative_json or use_blob setting on 1.9.1 and later.  Which is weird, because I'm sure it was leaking before without that flag, but now it doesn't appear to be doing so.  Either way, I'm assuming big memory leaks are not expected with either of those flags?

**Comment by MariusWirtz** [comment]
Yes. These kinds of memory leaks are unexpected. In my experience, this is also unusual.

Thanks for narrowing it down to a specific version.
I will take a closer look at the changes between 1.8 and 1.9.1

**Comment by raeldor** [comment]
Sorry, I don’t want to lead you on a wild goose chase.  I don’t think it’s due to code changes between these versions.  This is just when the iterative_json flag became available.  That’s the only reason it starts happening then.  I think the use_blob may have become available later.  I think if you get the MDX for a view with around 15M records and then execute the MDX using the iterative_json flag in a loop, you should be able to reproduce the memory loss on the server.  Just to be clear the memory loss is on the server, not the client.

**Comment by rclapp** [comment]
@raeldor can you clarify a bit, your last comment confused me a bit. The memory leak is happening on python.exe or tm1sd.exe?

**Comment by raeldor** [comment]
The memory leak is happening on the Tm1 Server, but is related to the use of enabling either of the two flags. Turn both off and the server memory leaks stop.

**Comment by rclapp** [comment]
Okay. This will likely need to be an IBM ticket as well. If you can replicate it, then IBM will have a set of logs and steps that they will want to review. What version of TM1 are you running?

**Comment by raeldor** [comment]
We are on 11.8.00900.3.

**Comment by MariusWirtz** [comment]
Closed since it can't be reproduced.

Please re-open if IBM wasn't able to support and it still impacts your TM1py experience-
