### ISSUE TITLE
Get default element of a hierarchy without need to allocate hierarchy in memory

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/tm1py#95]
Hi,
It would be a great feature to add a function to return name of a default member in a hierarchy without actually allocating that hierarchy in memory as python representation of the whole hierarchy is not necessary for such request. The reason is that default member might be queried straight by `HierarchyService` to save resources and time for such query.
I'm currently using following code to get default member of a dimension hierarchy:
```python
dim_hier = tm1_source.dimensions.hierarchies.get(dim_name_simple, dim_name_simple)
value = dim_hier.default_member
```
However memory is allocated not only for default member, but also for all elements in that hierarchy - this means to spend memory and time especially in cases when hierarchy contains thousands of elements.

**Comment by MariusWirtz** [comment]
Hi @pbuncik,

makes sense! I will add two new functions to the `HierarchyService`: 

```
get_default_member(dimension_name, hierarchy_name, member_name)
```
and
```
update_default_member(dimension_name, hierarchy_name, member_name)
```
