### ISSUE TITLE
Feature Request: get_values similar to write_values

### ISSUE THREAD

**Issue by raeldor** [cubewise-code/tm1py#951]
Hi,

We have a use-case where it would be great to be able to get multiple specific values back at a time. Is it possible to have a 'get_values' function that is like 'write_values', but takes a list of data point tuples and returns a list similar to what is passed INTO write_values?

I actually wrote a draft version of this already, though it's based on an older version of get_value().  Maybe it's still useful as a starting point.  I tried pasting it, but the code pasting is a bit weird with quotes, so I attached a file.

[get_values.txt](https://github.com/cubewise-code/tm1py/files/12256927/get_values.txt)

I also updated the code here...

https://github.com/raeldor/tm1py/tree/feature/add-get_values

**Comment by MariusWirtz** [comment]
Please open a PR with this function. It makes sense to include it in TM1py IMO.

**Comment by raeldor** [comment]
Done.

https://github.com/cubewise-code/tm1py/pull/954

**Comment by MariusWirtz** [comment]
Solved with #1020
