### ISSUE TITLE
Cubes.cells.execute_mdx with list of cell_properties returns invalid value for RuleDerived properties when Updateable is not supplied within cell properties

### ISSUE THREAD

**Issue by pbuncik** [cubewise-code/tm1py#96]
Hello,
I have experienced following behavior when querying for cell properties of a target slice - I wish to update target cells with values while avoiding cells that are consolidated or rule derived in order to avoid exceptions.
When I'm querying cell properties by mdx query and asking for `Consolidated` and `RuleDerived` properties, I will get following result for a chosen target cell:
The code:
```python
mdx_query_tgt = """
     SELECT
         {{[}}APQ UX Settings Service Dimensions Measure].[Default_Member]}} ON COLUMNS,
         {{TM1SUBSETALL([}}APQ UX Dimension])}} ON ROWS 
      FROM [}}APQ UX Settings Service Dimensions]
          WHERE ( [}}APQ UX Instance].[{}] )
""".format(cs_instance)
c=tm1_dest.cubes.cells.execute_mdx(mdx=mdx_query_tgt, cell_properties=["RuleDerived", "Consolidated"])
```
![image](https://user-images.githubusercontent.com/43746968/52329150-39cbe900-29f2-11e9-82c8-617ae73bf55e.png)

The above result is __incorrect__, because target cell is not rule derived (checked in the cube).

However if I run the same mdx query and asking for `Consolidated`, `RuleDerived` and `Updateable`, I will receive following result, which is __correct__:
The code:
```python
mdx_query_tgt = """
     SELECT
         {{[}}APQ UX Settings Service Dimensions Measure].[Default_Member]}} ON COLUMNS,
         {{TM1SUBSETALL([}}APQ UX Dimension])}} ON ROWS 
      FROM [}}APQ UX Settings Service Dimensions]
          WHERE ( [}}APQ UX Instance].[{}] )
""".format(cs_instance)
c=tm1_dest.cubes.cells.execute_mdx(mdx=mdx_query_tgt, cell_properties=["RuleDerived", "Consolidated", "Updateable"])
```
![image](https://user-images.githubusercontent.com/43746968/52329481-2b320180-29f3-11e9-9357-0406b67b18cf.png)

I have tried to run the same mdx query again, this time asking for `Consolidated`, `RuleDerived` and `Value` and I got __incorrect__ results again:
![image](https://user-images.githubusercontent.com/43746968/52329606-89f77b00-29f3-11e9-9fd8-e5c1250916eb.png)

I suspect this is an error in TM1 REST API, rather than in TM1py...
I'm using interim branch issue/87-b64-password.

**Comment by MariusWirtz** [comment]
Hi,

was able to replicate it in Postman.

This:
http://10.77.19.10:6545/api/v1/ExecuteMDX?$expand=Cells($select=RuleDerived,Consolidated;$top=2)

produces a different result than this:
http://10.77.19.10:6545/api/v1/ExecuteMDX?$expand=Cells($select=RuleDerived,Consolidated,Updateable;$top=2)

Seems to be an issue in the TM1 REST API.
