### ISSUE TITLE
TM1Py - Python script in Jupyter Notebook.

### ISSUE THREAD

**Issue by Mickaelp26** [cubewise-code/tm1py#970]
Hello,

I have installed TM1Py and I am using it to get data and metadata in PowerBI.
I directly copy/paste python script in PowerBI.

As Cubewise mentioned, it's possible to use Jupyter Notebook to test some python scripts.
When I did it, my script seems to work because I didn't get any error message BUT I also didn't get any response/output.

Do someone know what can I do ?
Is it normal ?

**Version**
- Python 3.11
- Jupyter Notebook 6.5.4
- IBM Planning Analytics 2.0
- TM1Py 1.11.3

Thanks a lot.

Regards,

Mickaël

**Comment by MariusWirtz** [comment]
Please include the script, that doesn't behave as you expect, with your post

**Comment by Mickaelp26** [comment]
Of course.
Sorry for that.

Here we are : 

import configparser

from TM1py import TM1Service

config = configparser.ConfigParser()
config.read('C:/Apps/tm1py-samples-master/tm1py-samples-master/config.ini')

with TM1Service(**config["MPPOWERBI"]) as tm1:
    ActualityMonthly_FAP = tm1.power_bi.get_member_properties(
        dimension_name="ActualityMonthly_FAP",
        hierarchy_name="ActualityMonthly_FAP",
        skip_consolidations=True)
    ActualityMonthly_FAP



And here is a screen shot of what happened:  

![Jupyter Notebook Issue](https://github.com/cubewise-code/tm1py/assets/138594359/11ea11de-26fe-4a2f-83c9-8f66776d0f90)


Thanks a lot.

**Comment by MariusWirtz** [comment]
Just unindent the `ActualityMonthy_FAP` line and it should print out the data frame

**Comment by Mickaelp26** [comment]
Whouahou ! 

What a quick resolution.
Thanks a lot Marius.

A really appreciate.

Regards,

Mickaël
