### ISSUE TITLE
Dimension Function: update_or_create   does not respect source element order

### ISSUE THREAD

**Issue by fat4tony** [cubewise-code/tm1py#986]
**Describe the bug**
When using dimension.update_or_create() function, the result dimension does not respect source element order.

**To Reproduce**
Choose a dimension in one instance, clone it to another instance

**Expected behavior**
The result dimension copies source element order.

**Version**
TM1py Version: 1.11.3
TM1 Server Version: 11.8.00300.34

**Comment by MariusWirtz** [comment]
I just checked. 
When a dimension is moved across for the first time, the order is kept.

TBH, I'm not sure it's reasonable to assume that TM1py synchronizes the element order when TM1py is updating existing structures in the target instance.

I think you might want to assure the element order explicitly by calling a TI function like [hierarchysortorder](https://www.ibm.com/docs/en/planning-analytics/2.0.0?topic=hmtf-hierarchysortorder).

It would be nice if IBM offered a REST endpoint for us to update the element order in a hierarchy explicitly. 
Something that would allow us to send a list of all element names and then register that as the new order.
If that endpoint existed, TM1py could assure the element order is kept. 
Should we perhaps raise a request for enhancement with IBM?
