### ISSUE TITLE
PowerBI using TM1py connection and PA data - Change the TM1 user already connected, possible?

### ISSUE THREAD

**Issue by Mickaelp26** [cubewise-code/tm1py#990]
Hello the community!

I am running some python scripts in PowerBI to retrieve data from a PA server and it is working well.
To do that, I followed the CubeWise.code website and used the check.py script : 

https://code.cubewise.com/tm1py-help-content/check-connectivity-with-tm1

I was using an admin TM1 profile but now, I wonder how I can change from this user to another one ?
What is the best way to secure the connection to PA ?

- Is there a script that disconnect the first connection made with my admin user?
- Is there a script that can change the user ?

**Version :**
Python 3.11
Jupyter Notebook 6.5.4
IBM Planning Analytics 2.0
TM1Py 1.11.3

Thanks a lot.
Regards,

Mickaël

**Comment by MariusWirtz** [comment]
Hi @Mickaelp26,

The best and most secure approach is to use TM1 with integrated login. 
If your TM1 Server is setup to use CAM Authentication with SSO, your TM1py/python code would be like this:

``` python
with TM1Service(address="", port=12354, ssl=True, namespace="LDAP", gateway="http://web-host:80/ibmcognos/bi/v1/disp") as tm1:
    print(tm1.server.get_product_version())
```

*please note that there are no password or credentials in the code*

If you want to keep using the admin account to log into TM1, but want to impersonate users to retrieve data with their security, you can use the impersonate argument.

``` python
from TM1py import TM1Service

tm1 = TM1Service(address="", port=12297, ssl=True, user="admin", password="", impersonate="Joe")
```

In the above example, tm1py would perceive your TM1 model as if it were Joe. So, it would see only data and metadata Joe can see.



To close your session, you can either call the `logout()` function or initiate the `TM1Service` using the `with` context manager
