### ISSUE TITLE
Function power_bi.execute_view returns too many values on zero suppressed string measure with stacked dimensions on rows

### ISSUE THREAD

**Issue by Cubewise-gtejeda** [cubewise-code/tm1py#997]
When having stacked dimensions on rows on a view and only a string measure as the column, despite zero suppression applied, the function power_bi.execute_view returns nan values, whereas Architect and Arc display the view correctly.

**To Reproduce**
1.  Create two dimensions with some elements
1.  Create a measures dimension with only one element, which is set to String
1.  Create a three-dimensional cube with the dimensions from the above steps
1.  Open the cube and create a view with the first two dimensions stacked and the measure dimension on the column
1.  Turn off zero suppression (if turned on)
1.  Enter some data into some of the cells
1.  Turn zero suppression on
1.  Save the view
1.  Run the view in TM1py using the power_bi.execute_view function

**Expected behavior**
The dataframe should contain the same data as displayed in Architect or Arc

**Current behavior**
The dataframe contains nan values

**Version**
TM1py 1.11.3
TM1 Server Version: 11.8.01900.10

**Screenshots**
Arc with zero suppression:
![image](https://github.com/cubewise-code/tm1py/assets/44591391/59d3675e-939d-4537-a429-f49226764906)

Pandas dataframe:
![image](https://github.com/cubewise-code/tm1py/assets/44591391/610aec36-ecb3-49b2-8266-1f7f57a8c6f3)

Please let me know if you need further details.

**Comment by Cubewise-gtejeda** [comment]
Further testing shows that setting use_iterative_json to False produces the correct result.

**Comment by MariusWirtz** [comment]
solved with https://github.com/cubewise-code/tm1py/pull/1008
