### ISSUE TITLE
'tuple' object has no attribute 'suffix' when get application type Document

### ISSUE THREAD

**Issue by farevian** [cubewise-code/tm1py#998]
**Describe the bug**
Trying to get a application document return 'tuple' object has no attribute 'suffix'

**To Reproduce**
_Juste use this code_ 
           xapplication_type=ApplicationTypes.DOCUMENT
           print(type(xapplication_type))
           print(xapplication_type.value)
           print(xapplication_type.suffix)

_In ApplicationService function get_document we have this code_ 
       application_type=ApplicationTypes.DOCUMENT
        if not name.endswith(application_type.suffix):
            name += application_type.suffix    
That this part wich generate the error

**Expected behavior**
Get the document

**Version**
TM1py 1.11.3
TM1 Server Version: 11.8

**Additional context**

**Comment by farevian** [comment]
Hello,
I found a workaround to be able to access Excel sheets. My level in Python does not guarantee that it is the best but with the line added in ApplicationService.py, I no longer have errors and I access the files well. 

def get_document(self, path: str, name: str, private: bool = False, **kwargs) -> DocumentApplication:
        """ Get Excel Application from TM1 Server in binary format. Can be dumped to file.

        :param path: path through folder structure to application. For instance: "Finance/P&L.xlsx"
        :param name: name of the application
        :param private: boolean
        :return: Return DocumentApplication
        """
        The ligne added :
        _application_type=ApplicationType(*ApplicationTypes.DOCUMENT.value)_
        
        if not name.endswith(application_type.suffix):
            name += application_type.suffix

**Comment by MariusWirtz** [comment]
I'm not sure I understand your proposed change.
The `_application_type` variable you create at the beginning of the function is not used later on.

Please open a Pull Request with your proposed change. Ideally, you also add a test case [here ](https://github.com/cubewise-code/tm1py/blob/master/Tests/ApplicationService_test.py) that reproduces the issue in the current master branch.

**Comment by farevian** [comment]
Hi Marius, 
Not sure my Python is at the level to propose change. Juste find that the code in [tm1py-samples][Metadata]/application_get.py
send me an error : 'tuple' object has no attribute 'suffix'

The change I maid just cast application_type to  ApplicationTypes.DOCUMENT to access the properties suffix.

The error
![Sans titre](https://github.com/cubewise-code/tm1py/assets/58982767/9fb
[testfonc.txt](https://github.com/cubewise-code/tm1py/files/13744764/testfonc.txt)
54834-4d3c-4d3f-837e-ae2464cb59a8)
The test code (the sample, with anly change on the connexion)

**Comment by MariusWirtz** [comment]
The issue seems to be resolved on the current master branch.

Please upgrade to current master branch and try below code snippet and confirm that it works on your side.

<img width="156" alt="image" src="https://github.com/cubewise-code/tm1py/assets/15182131/9b75c7bb-3586-4f92-a8bb-ebfcfa465180">


``` python
with TM1Service(**tm1params) as tm1:
    # get the application
    application = tm1.applications.get(
        path="Reporting",
        application_type=ApplicationTypes.DOCUMENT,
        name="pnl.xlsx",
        private=False)

    # write it to xlsx file
    application.to_file("out.xlsx")

```

**Comment by farevian** [comment]
Hello, upgrade to 2.02 and get the same issue. Change the code of class ApplicationTypes by class ApplicationTypes(Enum) and it look working :
    CHORE = ApplicationType(1, ".chore", "tm1.ChoreReference")
    CUBE = ApplicationType(2, ".cube", "tm1.CubeReference")
    DIMENSION = ApplicationType(3, ".dimension", "tm1.DimensionReference")
    DOCUMENT = ApplicationType(4, ".blob", "#ibm.tm1.api.v1.Document")
    FOLDER = ApplicationType(5, "", "#ibm.tm1.api.v1.Folder")
    LINK = ApplicationType(6, ".extr", "#ibm.tm1.api.v1.Link")
    PROCESS = ApplicationType(7, ".process", "tm1.ProcessReference")
    SUBSET = ApplicationType(8, ".subset", "tm1.SubsetReference")
    VIEW = ApplicationType(9, ".view", "tm1.ViewReference")

    @classmethod
    def _missing_(cls, value: str) -> ApplicationType:
        for member in cls:
            if member.name.lower() == value.lower():
                print(type(member))
                #return ApplicationType(member)
                return cls(member.value)

    
    @property
    def suffix(self) -> str:
        #return self.value.suffix
        return ApplicationType(*self.value).suffix
    @property
    def odata_type(self) -> str:
        return ApplicationType(*self.value).odata_type
        #return self.value.odata_type

(in comment old code). 

Will be please to join the projet to help if I can, but dont know how to get a environnement from github.
Regards
