### ISSUE TITLE
Empty alias values

### ISSUE THREAD

**Issue by Cubewise-gtejeda** [cubewise-code/tm1py#999]
When requesting alias values in TM1py, empty values are being returned in case there is no value in the }ElementAttributes cube.  
  
Example:

**Subset Editor (Arc):**
![image](https://github.com/cubewise-code/tm1py/assets/44591391/343a76bd-5e0d-46f7-ba40-645a013b719e)
  
**Cubeviewer (Arc):**
![image](https://github.com/cubewise-code/tm1py/assets/44591391/4797720b-6e22-4fd3-b602-acf6c74debbb)

**TM1py dataframe:**
![image](https://github.com/cubewise-code/tm1py/assets/44591391/a8507d02-d1f4-4dc6-917e-d28caa3b75fc)

Code:
```
from TM1py import TM1Service
import pandas as pd

with TM1Service(
    address="localhost",
    port=12354,
    user="admin",
    password="apple",
    ) as conn:
    print(conn.server.get_server_name())
    print(conn.server.version)
    dim = "dim1"
    sub = "Default"
    setexpression = "{TM1SubsetToSet([" + dim + "].[" + dim + "],'" + sub + "')}"
    df = conn.power_bi.get_member_properties(
        dimension_name=dim,
        hierarchy_name=dim,
        member_selection=setexpression,
        skip_weights=False,
        skip_consolidations=False)

    with pd.option_context('display.max_rows', None, 'display.max_columns',
                           None):  # more options can be specified also
        print(df.to_markdown())

```

**Expected behavior:**
Alias values by definition should never be empty.

**Comment by rkvinoth** [comment]
Even `CellGetS` function wouldn't return a value in TI. I don't think this is a bug.

**Comment by MariusWirtz** [comment]
Agree. Not a bug.

We can treat this as an enhancement request in the `get_member_properties`, `get_elements_dataframe` functions we could offer an additional argument like `blank_alias_values` which is True by default. If passed as False, the function could fill the empty alias attributes with the element name in a kind of post-processing step once the data has been retrieved to py.

**Comment by Cubewise-gtejeda** [comment]
It is a bug...
There is some inconsistency in TM1 when looking at aliases:
When using attribute functions, you get the correct result. When looking at cube values in the attributes cube you will get empty values, in case the alias has not been set.
This is also reflected when using the REST API.

When using attribute specific functions in TM1py, it should behave the same as the REST API.

**Comment by Cubewise-gtejeda** [comment]
This works, however, there is a warning when running the updated code:
```
C:\Python311\Lib\site-packages\TM1py\Services\ElementService.py:347: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_data[cols_to_format] = df_data[cols_to_format].applymap(lambda x: '{:.6f}'.for
```
